<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 5 Inferencia de las medias | Curso de R básico</title>
  <meta name="description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 5 Inferencia de las medias | Curso de R básico" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 5 Inferencia de las medias | Curso de R básico" />
  
  <meta name="twitter:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

<meta name="author" content="Alejandro Ruiz-García" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probabilidad.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de R básico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Requisitos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#descarga-de-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Descarga de R y RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introducción-a-r.html"><a href="introducción-a-r.html"><i class="fa fa-check"></i><b>2</b> Introducción a R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introducción-a-r.html"><a href="introducción-a-r.html#interfaz"><i class="fa fa-check"></i><b>2.1</b> Interfaz</a></li>
<li class="chapter" data-level="2.2" data-path="introducción-a-r.html"><a href="introducción-a-r.html#creando-nuestro-primer-proyecto"><i class="fa fa-check"></i><b>2.2</b> Creando nuestro primer proyecto</a></li>
<li class="chapter" data-level="2.3" data-path="introducción-a-r.html"><a href="introducción-a-r.html#objetos-y-variables"><i class="fa fa-check"></i><b>2.3</b> Objetos y variables</a></li>
<li class="chapter" data-level="2.4" data-path="introducción-a-r.html"><a href="introducción-a-r.html#instalar-paquetes"><i class="fa fa-check"></i><b>2.4</b> Instalar paquetes</a></li>
<li class="chapter" data-level="2.5" data-path="introducción-a-r.html"><a href="introducción-a-r.html#importar-datos-a-r"><i class="fa fa-check"></i><b>2.5</b> Importar datos a R</a></li>
<li class="chapter" data-level="2.6" data-path="introducción-a-r.html"><a href="introducción-a-r.html#comentarios"><i class="fa fa-check"></i><b>2.6</b> Comentarios</a></li>
<li class="chapter" data-level="2.7" data-path="introducción-a-r.html"><a href="introducción-a-r.html#exportar-datos"><i class="fa fa-check"></i><b>2.7</b> Exportar datos</a></li>
<li class="chapter" data-level="2.8" data-path="introducción-a-r.html"><a href="introducción-a-r.html#pedir-ayuda"><i class="fa fa-check"></i><b>2.8</b> Pedir ayuda</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html"><i class="fa fa-check"></i><b>3</b> Estadística descriptiva</a>
<ul>
<li class="chapter" data-level="3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>3.1</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#media"><i class="fa fa-check"></i><b>3.1.1</b> Media</a></li>
<li class="chapter" data-level="3.1.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mediana"><i class="fa fa-check"></i><b>3.1.2</b> Mediana</a></li>
<li class="chapter" data-level="3.1.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#moda"><i class="fa fa-check"></i><b>3.1.3</b> Moda</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>3.2</b> Medidas de dispersión</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#rango"><i class="fa fa-check"></i><b>3.2.1</b> Rango</a></li>
<li class="chapter" data-level="3.2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#desviación-estándar"><i class="fa fa-check"></i><b>3.2.2</b> Desviación estándar</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-posición-relativa"><i class="fa fa-check"></i><b>3.3</b> Medidas de posición relativa</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#valores-z"><i class="fa fa-check"></i><b>3.3.1</b> Valores Z</a></li>
<li class="chapter" data-level="3.3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-absoluta"><i class="fa fa-check"></i><b>3.3.2</b> Frecuencia absoluta</a></li>
<li class="chapter" data-level="3.3.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-relativa"><i class="fa fa-check"></i><b>3.3.3</b> Frecuencia relativa</a></li>
<li class="chapter" data-level="3.3.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#cuartiles"><i class="fa fa-check"></i><b>3.3.4</b> Cuartiles</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#el-uso-de-la-librería-dplyr"><i class="fa fa-check"></i><b>3.4</b> El uso de la librería <code>dplyr</code></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probabilidad.html"><a href="probabilidad.html"><i class="fa fa-check"></i><b>4</b> Probabilidad</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probabilidad.html"><a href="probabilidad.html#probabilidad-frecuentista"><i class="fa fa-check"></i><b>4.1</b> Probabilidad frecuentista</a></li>
<li class="chapter" data-level="4.2" data-path="probabilidad.html"><a href="probabilidad.html#reglas-de-probabilidad"><i class="fa fa-check"></i><b>4.2</b> Reglas de probabilidad</a></li>
<li class="chapter" data-level="4.3" data-path="probabilidad.html"><a href="probabilidad.html#curvas-de-densidad"><i class="fa fa-check"></i><b>4.3</b> Curvas de densidad</a></li>
<li class="chapter" data-level="4.4" data-path="probabilidad.html"><a href="probabilidad.html#distribución-binomial"><i class="fa fa-check"></i><b>4.4</b> Distribución binomial</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="probabilidad.html"><a href="probabilidad.html#media-y-desviación-estándar-de-la-distribución-binomial"><i class="fa fa-check"></i><b>4.4.1</b> Media y desviación estándar de la distribución binomial</a></li>
<li class="chapter" data-level="4.4.2" data-path="probabilidad.html"><a href="probabilidad.html#distribución-binomial-en-r"><i class="fa fa-check"></i><b>4.4.2</b> Distribución binomial en R</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="probabilidad.html"><a href="probabilidad.html#distribución-normal"><i class="fa fa-check"></i><b>4.5</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="probabilidad.html"><a href="probabilidad.html#distribución-normal-en-r"><i class="fa fa-check"></i><b>4.5.1</b> Distribución normal en R</a></li>
<li class="chapter" data-level="4.5.2" data-path="probabilidad.html"><a href="probabilidad.html#pruebas-de-normalidad-en-r"><i class="fa fa-check"></i><b>4.5.2</b> Pruebas de normalidad en R</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="probabilidad.html"><a href="probabilidad.html#distribución-muestral"><i class="fa fa-check"></i><b>4.6</b> Distribución muestral</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="probabilidad.html"><a href="probabilidad.html#poblaciones-muestras-y-distribuciones-muestrales"><i class="fa fa-check"></i><b>4.6.1</b> Poblaciones, muestras y distribuciones muestrales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html"><i class="fa fa-check"></i><b>5</b> Inferencia de las medias</a>
<ul>
<li class="chapter" data-level="5.1" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#error-estándar-de-la-media"><i class="fa fa-check"></i><b>5.1</b> Error estándar de la media</a></li>
<li class="chapter" data-level="5.2" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>5.2</b> Intervalo de confianza para <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#distribución-t-de-student"><i class="fa fa-check"></i><b>5.2.1</b> Distribución <span class="math inline">\(t\)</span> de Student</a></li>
<li class="chapter" data-level="5.2.2" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#construcción-de-un-intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>5.2.2</b> Construcción de un intervalo de confianza para <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="5.2.3" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#intervalos-de-confianza-unilaterales"><i class="fa fa-check"></i><b>5.2.3</b> Intervalos de confianza unilaterales</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#comparación-de-dos-medias"><i class="fa fa-check"></i><b>5.3</b> Comparación de dos medias</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#intervalo-de-confianza-para-mu_1---mu_2"><i class="fa fa-check"></i><b>5.3.1</b> Intervalo de confianza para <span class="math inline">\(\mu_1 - \mu_2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#pruebas-de-hipótesis"><i class="fa fa-check"></i><b>5.4</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#t-test"><i class="fa fa-check"></i><b>5.4.1</b> <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="5.4.2" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#t-test-de-una-cola"><i class="fa fa-check"></i><b>5.4.2</b> <span class="math inline">\(t\)</span> test de una cola</a></li>
<li class="chapter" data-level="5.4.3" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#tamaño-de-efecto"><i class="fa fa-check"></i><b>5.4.3</b> Tamaño de efecto</a></li>
<li class="chapter" data-level="5.4.4" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#prueba-de-wilcoxon-mann-whitney"><i class="fa fa-check"></i><b>5.4.4</b> Prueba de Wilcoxon-Mann-Whitney</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#comparación-de-muestras-pareadas"><i class="fa fa-check"></i><b>5.5</b> Comparación de muestras pareadas</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#prueba-de-t-pareada"><i class="fa fa-check"></i><b>5.5.1</b> Prueba de <span class="math inline">\(t\)</span> pareada</a></li>
<li class="chapter" data-level="5.5.2" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#prueba-de-signos"><i class="fa fa-check"></i><b>5.5.2</b> Prueba de signos</a></li>
<li class="chapter" data-level="5.5.3" data-path="inferencia-de-las-medias.html"><a href="inferencia-de-las-medias.html#prueba-de-rangos-con-signos-de-wilcoxon"><i class="fa fa-check"></i><b>5.5.3</b> Prueba de rangos con signos de Wilcoxon</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="6" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html"><i class="fa fa-check"></i><b>6</b> Análisis de Varianza (ANOVA)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#prueba-de-normalidad"><i class="fa fa-check"></i><b>6.1</b> Prueba de normalidad</a></li>
<li class="chapter" data-level="6.2" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#prueba-de-homocedasticidad"><i class="fa fa-check"></i><b>6.2</b> Prueba de homocedasticidad</a></li>
<li class="chapter" data-level="6.3" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#análisis-de-varianza-anova-de-una-vía"><i class="fa fa-check"></i><b>6.3</b> Análisis de varianza (ANOVA de una vía)</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#anova-en-r"><i class="fa fa-check"></i><b>6.3.1</b> ANOVA en R</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#pruebas-post-hoc"><i class="fa fa-check"></i><b>6.4</b> Pruebas <em>post hoc</em></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso de R básico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inferencia-de-las-medias" class="section level1" number="5">
<h1><span class="header-section-number">Lección 5</span> Inferencia de las medias</h1>
<p>En esta lección aprenderemos a hacer <strong>inferencias</strong>, basadas en un modelo de muestreo aleatorio. Usaremos información proveniente de nuestras muestras aleatorias para <em>inferir</em> hechos acerca de la población de la que fueron tomadas. Utilizamos datos para determinar alguna característica de la población original o para medir la precisión de nuestras estimaciones.</p>
<p>Sabemos que al tomar muestras de una población, nuestros datos son susceptibles a un error de muestreo. Cabe aclarar que este error no solamente tiene que ver con la precisión de medición, si no que este error surge por el hecho de que no estamos tomando en cuenta los datos de toda la población.</p>
<div id="error-estándar-de-la-media" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Error estándar de la media</h2>
<p>El <strong>error estándar</strong> mide la magnitud del error de muestreo, es decir, la discrepancia entre <span class="math inline">\(\overline{x}\)</span> y <span class="math inline">\(\mu\)</span> utilizando la distribución muestral de <span class="math inline">\(\overline{X}\)</span>. La fórmula del error estándar es la siguiente:</p>
<p><span class="math display" id="eq:stderror">\[\begin{equation}
SE_\overline{X} = \frac{s}{\sqrt{n}}
\tag{5.1}
\end{equation}\]</span></p>
<p>Como podemos ver, esta fórmula es bastante similar a la fórmula de la desviación estándar de la muestra <span class="math inline">\(\sigma_{\overline{X}} = \frac{\sigma}{\sqrt{n}}\)</span>.</p>
<p>Normalmente, la diferencia entre <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\overline{x}\)</span> es unos cuantos errores estándar. De hecho, encontramos a <span class="math inline">\(\overline{x}\)</span> a un error estándar de <span class="math inline">\(\mu\)</span> bastante seguido. Hay que destacar que el error estándar dependen de la desviación estándar muestral <span class="math inline">\(s\)</span> y del tamaño de muestra <span class="math inline">\(n\)</span>.</p>
<p>Es importante destacar la diferencia entre el error estándar y la desviación estándar. La desviación estándar describe la <strong>dispersión</strong> de los datos de una muestra, mientras que el error estándar describe la <strong>falta de fidelidad</strong> en la media de una muestra como estimación de la media poblacional, debido al error de muestreo. Una forma de disminuir el error estándar es incrementando el tamaño de muestra <span class="math inline">\(n\)</span>.</p>
<p>En las gráficas podemos ver el error estándar o la desviación estándar representadas como intervalos en nuestros puntos. Por ejemplo, las siguientes gráficas representan la desviación estándar en la figura <a href="inferencia-de-las-medias.html#fig:sd-bar">5.1</a> y el error estándar en la figura <a href="inferencia-de-las-medias.html#fig:se-bar">5.2</a>. Como podemos ver, la dispersión de los datos es mayor al error estándar.</p>
<div class="figure" style="text-align: center"><span id="fig:sd-bar"></span>
<img src="Curso_R_basico_files/figure-html/sd-bar-1.png" alt="Gráfico con la desviación estándar representada en forma de intervalo." width="672" />
<p class="caption">
Figura 5.1: Gráfico con la desviación estándar representada en forma de intervalo.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:se-bar"></span>
<img src="Curso_R_basico_files/figure-html/se-bar-1.png" alt="Gráfico con el error estándar representado en forma de intervalo." width="672" />
<p class="caption">
Figura 5.2: Gráfico con el error estándar representado en forma de intervalo.
</p>
</div>
</div>
<div id="intervalo-de-confianza-para-mu" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Intervalo de confianza para <span class="math inline">\(\mu\)</span></h2>
<p>Un <strong>intervalo de confianza</strong> nos sirve para determinar qué tan cerca está de <span class="math inline">\(\mu\)</span> nuestra media muestral <span class="math inline">\(\overline{x}\)</span>. Ya que no podemos medir de manera directa <span class="math inline">\(\mu\)</span>, utilizamos <span class="math inline">\(\overline{x}\)</span> adicional al error estándar <span class="math inline">\(SE_\overline{X}\)</span> como se indica en la fórmula <a href="inferencia-de-las-medias.html#eq:IC">(5.2)</a>.</p>
<p><span class="math display" id="eq:IC">\[\begin{equation}
\overline{x} \pm {2}*{SE_\overline{X}}
\tag{5.2}
\end{equation}\]</span></p>
<p>¿Por qué utilizar dos veces <span class="math inline">\(SE_\overline{X}\)</span>? Porque al utilizarlo sabemos que el 95% de las veces <span class="math inline">\(\mu\)</span> se encontrará en este intervalo. Si utilizáramos solamente un <span class="math inline">\(SE_\overline{X}\)</span> solamente estaríamos seguros de que <span class="math inline">\(\mu\)</span> se encuentra en este intervalo el 68% de las veces. Esta idea está basada en la distribución muestral de <span class="math inline">\(X\)</span> que vimos en la lección anterior. Al estandarizar nuestra variable <span class="math inline">\(X\)</span> y transformarla en valores <span class="math inline">\(Z\)</span>, lo que buscamos es un área de 0.95. Estos valores Z corresponden a -1.96 como límite inferior y 1.96 como limite superior.</p>
<p><span class="math display">\[\begin{equation}
P({-1.96}&lt;{Z}&lt;1.96) = 0.95 \\

P({-1.96}&lt;{\frac{\overline{X}-\mu}{\sigma/\sqrt{n}}}&lt;1.96) = 0.95 \\

P({-1.96\times{\sigma/\sqrt{n}}}&lt;{{\overline{X}-\mu}}&lt;1.96\times{\sigma/\sqrt{n}}) = 0.95 \\

P({-\overline{X}-1.96\times{\sigma/\sqrt{n}}}&lt;{-\mu}&lt;-\overline{X}1.96\times{\sigma/\sqrt{n}}) = 0.95 \\

P({\overline{X}-1.96\times{\sigma/\sqrt{n}}}&lt;{\mu}&lt;\overline{X}1.96\times{\sigma/\sqrt{n}}) = 0.95 \\

\end{equation}\]</span></p>
<p>A partir de este despeje obtenemos la fórmula para un intervalo de confianza que contendrá a <span class="math inline">\(\mu\)</span> el 95% de las veces.</p>
<p><span class="math display" id="eq:IC2">\[\begin{equation}
\overline{X} \pm 1.96\frac{\sigma}{\sqrt{n}}
\tag{5.3}
\end{equation}\]</span></p>
<p>Si en este caso, cambiamos <span class="math inline">\(\sigma\)</span> por <span class="math inline">\(s\)</span>, podemos calcular el intervalo de confianza para nuestra muestra. William Sealy Gosset, quién publicó sus hallazgos bajo el seudónimo de <em>Student</em>, descubrió un método para preservar la interpretación del 95% y desde entonces este método lleva su seudónimo. Básicamente, si la muestra proviene de una población normal, y si remplazamos <span class="math inline">\(\sigma\)</span> del intervalo por <span class="math inline">\(s\)</span>, la interpretación del 95% se puede preservar utilizando la nueva cantidad denotada como <span class="math inline">\(t_{0.025}\)</span> y que está relacionada con una distribución conocida como <strong>distribución <span class="math inline">\(t\)</span> de Student</strong>.</p>
<div id="distribución-t-de-student" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Distribución <span class="math inline">\(t\)</span> de Student</h3>
<p>La distribución <span class="math inline">\(t\)</span> de Student es una distribución teórica continua, usada para distintos propósitos en estadística, por ejemplo, para la construcción de intervalos de confianza. La distribución depende de una cantidad conocida como <strong>grados de libertad</strong> o <strong>df</strong>. La forma de una distribución <span class="math inline">\(t\)</span> de Student es de campana, similar a la distribución normal, pero con una desviación estándar mayor. Conforme los grados de libertad aumentan, la curva de una distribución <span class="math inline">\(t\)</span> de Student se asemeja más a una curva normal (podría decirse que una curva normal es una curva <span class="math inline">\(t\)</span> de Student con <span class="math inline">\(df = \infty\)</span>). En la figura <a href="inferencia-de-las-medias.html#fig:df-graph">5.3</a> podemos ver como la forma de una distribución <span class="math inline">\(t\)</span> de Student cambia conforme los <span class="math inline">\(df\)</span> aumentan. La línea punteada es una curva con distribución normal.</p>
<div class="figure" style="text-align: center"><span id="fig:df-graph"></span>
<img src="Curso_R_basico_files/figure-html/df-graph-1.png" alt="Curvas con distribución *t* de Student y cómo cambian dependiendo de los *df*." width="672" />
<p class="caption">
Figura 5.3: Curvas con distribución <em>t</em> de Student y cómo cambian dependiendo de los <em>df</em>.
</p>
</div>
<p>La cantidad <span class="math inline">\(t_{0.025}\)</span> se conoce como <strong>valor crítico al 5% de dos colas</strong> de una distribución <span class="math inline">\(t\)</span> de Student. El área entre <span class="math inline">\(-t_{0.025}\)</span> y <span class="math inline">\(t_{0.025}\)</span> contiene el 95% del área de la curva. Es decir el área debajo de <span class="math inline">\(-t_{0.025}\)</span> y encima de <span class="math inline">\(t_{0.025}\)</span> suman en total 5% como se ve en la figura <a href="inferencia-de-las-medias.html#fig:t-crit">5.4</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:t-crit"></span>
<img src="Curso_R_basico_files/figure-html/t-crit-1.png" alt="Valores críticos de una distribución *t* de Student" width="672" />
<p class="caption">
Figura 5.4: Valores críticos de una distribución <em>t</em> de Student
</p>
</div>
<p>Existen <strong>tablas de distribución <span class="math inline">\(t\)</span> de Student</strong> que se utilizan para encontrar los valores críticos acorde con nuestros grados de libertad. Al igual que la distribución binomial y normal, <code>R</code> viene con funciones para la distribución <span class="math inline">\(t\)</span> de Student.</p>
<p>Estos son los siguientes:</p>
<p>-<code>dt()</code> nos da un valor de densidad en determinado punto de la distribución de <span class="math inline">\(t\)</span> (valor puntual de la función de densidad).</p>
<p>-<code>pt()</code> nos da un valor de densidad acumulado hasta cierto punto en la distribución de <span class="math inline">\(t\)</span> (área debajo de la curva).</p>
<p>-<code>qt()</code> toma el valor de densidad que le ponemos como primer argumento y nos da como regreso un número cuya densidad acumulada empate con el valor de densidad ingresado.</p>
<p>-<code>rt()</code> genera cierta cantidad de número aleatorios de acuerdo al valor de densidad.</p>
<p>Sin embargo en este caso, en lugar de contar con el argumento <code>n</code> para el tamaño de muestra, contamos con otro argumento <code>df</code> para los grados de libertad.</p>
<p>Para poder utilizar el método <span class="math inline">\(t\)</span> de Student, se necesitan cumplir ciertas condiciones:</p>
<ul>
<li><p>Las muestras deben de ser <strong>aleatorias</strong>.</p></li>
<li><p>Las observaciones de la muestra deben ser independientes unas de otras.</p></li>
<li><p>Si <span class="math inline">\(n\)</span> es pequeña, la distribución de la población debe ser aproximadamente normal.</p></li>
<li><p>Si <span class="math inline">\(n\)</span> es grande, la distribución de la población no necesita ser normal.</p></li>
</ul>
</div>
<div id="construcción-de-un-intervalo-de-confianza-para-mu" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Construcción de un intervalo de confianza para <span class="math inline">\(\mu\)</span></h3>
<p>El primer paso para construir nuestro intervalo de confianza es elegir nuestro nivel de confianza (generalmente es 95% pero esto no quiere decir que siempre tenga que ser así). Si quisiéramos un nivel de confianza de 90% utilizamos un valor crítico de <span class="math inline">\(t_{0.05}\)</span>.</p>
<p>Después tenemos que establecer los límites de nuestro intervalo utilizando la siguiente fórmula (para intervalos con 95% de confianza):</p>
<p><span class="math display" id="eq:IC3">\[\begin{equation}
\overline{x} \pm t_{0.025}\frac{s}{\sqrt{n}}
\tag{5.4}
\end{equation}\]</span></p>
<p>Como vimos, el valor crítico de <span class="math inline">\(t\)</span> es determinado por los grados de libertad. Estos se calculan utilizando las siguiente fórmula:</p>
<p><span class="math display" id="eq:df">\[\begin{equation}
df = n - 1
\tag{5.5}
\end{equation}\]</span></p>
<p>¿Por qué se calculan así los grados de libertad? Bueno, las desviaciones (<span class="math inline">\(x_i - \overline{x}\)</span>) deben de sumar 0 en total, por lo que solamente una (<span class="math inline">\(n - 1\)</span>) de estas desviaciones puede variar <em>libremente</em>.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Una muestra del área de las alas obtenida de una población de la Mariposa Monarca (<em>Danaus plexippus</em>) de 14 ejemplares tiene una media <span class="math inline">\(\overline{x} = 32.8143cm^2\)</span> y una desviación estándar <span class="math inline">\(s = 2.4757 cm^2\)</span>. Sabemos que los datos provienen de una población con distribución normal. ¿Cuál sería el intervalo de confianza al 95% para esta muestra?</p>
</blockquote>
<p>El primer paso es calcular los grados de libertad.</p>
<p><span class="math display">\[\begin{equation}
df = n - 1 = 14 - 1 = 13
\end{equation}\]</span></p>
<p>Como queremos un intervalo de confianza al 95%, utilizamos el valor crítico de <span class="math inline">\(t_{0.025}\)</span>. Para encontrar este valor podemos buscarlo en una tabla de <span class="math inline">\(t\)</span> o utilizar las funciones de <code>R</code>.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="inferencia-de-las-medias.html#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="dv">13</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 2.160369</code></pre>
<p>Por lo tanto el intervalo de confianza al 95% para nuestra muestra es</p>
<p><span class="math display">\[\begin{equation}
32.8143 \pm {2.16}{\frac{2.4757}{\sqrt{14}}} \\
32.8143 \pm {2.16}*{0.6617} \\
32.8143 \pm 1.4293
\end{equation}\]</span></p>
<p>De nuevo, esto se puede calcular en <code>R</code> de manera sencilla.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="inferencia-de-las-medias.html#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fl">32.8143</span> <span class="sc">+</span> <span class="fl">2.160</span><span class="sc">*</span>(<span class="fl">2.4757</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">14</span>))</span></code></pre></div>
<pre><code>## [1] 34.24348</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="inferencia-de-las-medias.html#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fl">32.8143</span> <span class="sc">-</span> <span class="fl">2.160</span><span class="sc">*</span>(<span class="fl">2.4757</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">14</span>))</span></code></pre></div>
<pre><code>## [1] 31.38512</code></pre>
<p>Una forma compacta de escribir el intervalo de confianza es con el límite inferior y superior separados por una coma y entre paréntesis (<span class="math inline">\(31.4, 34.2\)</span>). Con esta información sabemos entonces que <span class="math inline">\(31.4cm^2 &gt; \mu &gt; 34.2cm^2\)</span>.</p>
<p>Una cosa importante a destacar es que es el propio intervalo de confianza el que es <strong>aleatorio</strong>. Si consideramos intervalos de confianza al 95%, entonces:</p>
<p><span class="math display">\[\begin{equation}
P(La\space siguiente\space muestra\space nos\space dará\space un\space intervalo\space de\space confianza\space que\space contenga\space a\space \mu) = 0.95
\end{equation}\]</span></p>
<p>Véanoslo de la siguiente manera. Si hiciéramos un meta-estudio y construyéramos un intervalo de confianza a 95% para cada una de las muestras, entonces el 95% de los intervalos de confianza contendrán a <span class="math inline">\(\mu\)</span>. El nivel de confianza (90%, 95%, 99%) es una propiedad del método más que de un intervalo particular.</p>
</div>
<div id="intervalos-de-confianza-unilaterales" class="section level3" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Intervalos de confianza unilaterales</h3>
<p>Este tipo de intervalos de confianza se obtienen cuando solamente nos interesa el límite inferior o superior. Supongamos que queremos construir un intervalo de confianza con un límite inferior al 95%. Mientras que un intervalo de confianza bilateral está basado en usar el valor <span class="math inline">\(\pm t_0.025\)</span>, un intervalo de confianza al 95% de un solo lado (en este caso inferior) solamente se preocupa por el área bajo la curva del lado correspondiente. Ya que <span class="math inline">\(P(-t_{0.05} &gt; t &gt; \infty) = 0.95\)</span>, para un intervalo de confianza unilateral al 95% utilizamos un valor de <span class="math inline">\(-t_{0.05}\)</span> y establecemos el límite con la siguientes operaciones:</p>
<p><span class="math display">\[\begin{equation}
\overline{x} - t_{0.05}{SE_{\overline{X}}} \\
\overline{x} + t_{0.05}{SE_{\overline{X}}}
\end{equation}\]</span></p>
<p>Estas serían las operaciones a realizar para un intervalo de confianza con límite inferior y superior, respectivamente.</p>
</div>
</div>
<div id="comparación-de-dos-medias" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Comparación de dos medias</h2>
<p>Cuando queremos comparar dos muestras que provienen de supuestamente poblaciones distintas, podemos realizar las comparaciones utilizando (1) las medias de las muestras; (2) sus desviaciones estándar o; (3) la forma de su distribución.</p>
<p>Para comprar la media de dos muestras, es natural considerar la diferencia entre ellas.</p>
<p><span class="math display">\[\begin{equation}
\overline{X}_1 - \overline{X}_2
\end{equation}\]</span></p>
<p>Esta cantidad es un estimado de la diferencia entre las poblaciones (<span class="math inline">\(\mu_1 - \mu_2\)</span>). Para caracterizar el error de muestreo de esta estimación, debemos conocer el error estándar entre la diferencia de (<span class="math inline">\(\overline{X}_1 - \overline{X}_2\)</span>).</p>
<p>La fórmula para el <strong>error estándar</strong> de (<span class="math inline">\(\overline{X}_1 - \overline{X}_2\)</span>) es la siguiente:</p>
<p><span class="math display" id="eq:stderror2">\[\begin{equation}
SE_{(\overline{X}_1 - \overline{X}_2)} = \sqrt{\frac{s^2_1}{n_1} + \frac{s^2_2}{n_2}}
\tag{5.6}
\end{equation}\]</span></p>
<p>Otra forma de representar la fórmula es de la siguiente manera</p>
<p><span class="math display" id="eq:stderror3">\[\begin{equation}
SE_{(\overline{X}_1 - \overline{X}_2)} = \sqrt{SE^2_1 + SE^2_2}
\tag{5.7}
\end{equation}\]</span></p>
<p>En donde <span class="math inline">\(SE_1 = SE_{\overline{X}_1} = \frac{s_1}{\sqrt{n_1}}\)</span> y <span class="math inline">\(SE_2 = SE_{\overline{X}_2} = \frac{s_2}{\sqrt{n_2}}\)</span>.</p>
<div id="intervalo-de-confianza-para-mu_1---mu_2" class="section level3" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Intervalo de confianza para <span class="math inline">\(\mu_1 - \mu_2\)</span></h3>
<p>Podemos comprar las medias de dos muestras construyendo un intervalo de confianza para la diferencia de las medias. La fórmula para un intervalo de confianza de la diferencia de las medias es bastante similar a la usada para construir uno para una muestra.</p>
<p><span class="math display" id="eq:IC4">\[\begin{equation}
(\overline{X}_1 - \overline{X}_2) \pm t_{0.025} SE_{(\overline{X}_1 - \overline{X}_2)}
\tag{5.8}
\end{equation}\]</span></p>
<p>El valor crítico de <span class="math inline">\(t_{0.025}\)</span> es determinado a partir de la distribución <span class="math inline">\(t\)</span> de Student utilizando los grados de libertad que en este caso se calculan de la siguiente manera:</p>
<p><span class="math display" id="eq:df2">\[\begin{equation}
df = \frac{(SE^2_1 + SE^2_2)^2}{SE^4_1/(n_1 - 1) + SE^4_2/(n_2 -1)}
\tag{5.9}
\end{equation}\]</span></p>
<p>Otros métodos se basan en obtener los grados de libertad utilizando el número más pequeño entre (<span class="math inline">\(n_1 - 1\)</span>) y (<span class="math inline">\(n_2 - 1\)</span>) o <span class="math inline">\(n_1 + n_2 - 2\)</span>.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Varios biólogos creen que el tórax de las mariposas monarca macho es mayor que el de las hembras. Una muestra de 7 machos y 8 hembras dan los resultados de la tabla <a href="inferencia-de-las-medias.html#tab:ej1">5.1</a> y la figura <a href="inferencia-de-las-medias.html#fig:a">5.5</a>.</p>
</blockquote>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ej1">Tabla 5.1: </span>Peso del torax (mg)
</caption>
<thead>
<tr>
<th style="text-align:center;">
Machos
</th>
<th style="text-align:center;">
Hembras
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
67
</td>
<td style="text-align:center;min-width: 3cm; ">
73
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
73
</td>
<td style="text-align:center;min-width: 3cm; ">
54
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
85
</td>
<td style="text-align:center;min-width: 3cm; ">
61
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
84
</td>
<td style="text-align:center;min-width: 3cm; ">
63
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
78
</td>
<td style="text-align:center;min-width: 3cm; ">
66
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
63
</td>
<td style="text-align:center;min-width: 3cm; ">
57
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
80
</td>
<td style="text-align:center;min-width: 3cm; ">
75
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
</td>
<td style="text-align:center;min-width: 3cm; ">
58
</td>
</tr>
</tbody>
</table>
<p>En la siguiente figura se puede observar la distribución de los datos para los machos y las hembras. A simple vista parece ser que el tórax de los machos pesa ligeramente más que el de las hebras.</p>
<p>Ahora tendremos que calcular ciertos valores para estos datos, como las medias y desviaciones estándar de cada grupo. Recuerden que para esto podemos usar la librería <code>dplyr</code>. Anteriormente creé una variable llamada <code>Sample2</code> que contiene los datos que vamos a necesitar.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="inferencia-de-las-medias.html#cb146-1" aria-hidden="true" tabindex="-1"></a>Sample2</span></code></pre></div>
<pre><code>##      Grupo Peso
## 1   Machos   67
## 2   Machos   73
## 3   Machos   85
## 4   Machos   84
## 5   Machos   78
## 6   Machos   63
## 7   Machos   80
## 9  Hembras   73
## 10 Hembras   54
## 11 Hembras   61
## 12 Hembras   63
## 13 Hembras   66
## 14 Hembras   57
## 15 Hembras   75
## 16 Hembras   58</code></pre>
<p>En este caso yo he redondeado los valores a solamente 1 dígito. Ahora para obtener el intervalo de confianza no hace falta que hagamos todas las fórmulas para obtener los grados de libertad, el error estándar, etc. Basta con usar la función <code>t.test()</code> para obtener nuestro intervalo de confianza.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="inferencia-de-las-medias.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Peso <span class="sc">~</span> Grupo,Sample2)<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] -21.353087  -3.325484
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>Como podemos ver nuestro intervalo se encuentra entre (<span class="math inline">\(3.3, 21.4\)</span>) para un nivel de significancia del 95%. ¿Cómo se interpreta esto? Bueno, de la siguiente manera: de acuerdo a nuestro intervalo de confianza, podemos estar 95% seguros de que la media poblacional del tórax de los machos de Mariposa Monarca (<span class="math inline">\(\mu_1\)</span>) es más grande que la de las hembras (<span class="math inline">\(\mu_2\)</span>) por una cantidad tan pequeña como 3.3 mg o tan grande como 21.4 mg.</p>
<p>Si quisiéramos ajustar el nivel de confianza de nuestro intervalo, también podemos hacerlo.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="inferencia-de-las-medias.html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Peso <span class="sc">~</span> Grupo,Sample2, <span class="at">conf.level =</span> <span class="fl">0.9</span>)<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] -19.716479  -4.962093
## attr(,&quot;conf.level&quot;)
## [1] 0.9</code></pre>
<p>Un intervalo de confianza al 90% se encuentra entre (<span class="math inline">\(5.0, 19.7\)</span>).</p>
<div class="figure" style="text-align: center"><span id="fig:a"></span>
<img src="Curso_R_basico_files/figure-html/a-1.png" alt="Peso del torax de Mariposas Monarca macho y hembra (mg)" width="672" />
<p class="caption">
Figura 5.5: Peso del torax de Mariposas Monarca macho y hembra (mg)
</p>
</div>
</div>
</div>
<div id="pruebas-de-hipótesis" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Pruebas de hipótesis</h2>
<p>¿Qué tan diferentes tienen que ser dos muestras para concluir que las poblaciones de las que vienen son distintas? Una aproximación que podemos hacer es comparar las medias de las dos muestras y ver qué tanto difieren comparándolo con la diferencia que esperaríamos si fuese azar.</p>
<div id="t-test" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> <span class="math inline">\(t\)</span>-test</h3>
<p>La idea general es formular una hipótesis para ver si <span class="math inline">\(\mu_1\)</span> y <span class="math inline">\(\mu_2\)</span> difieren, y ver la información que tenemos de nuestras muestras para ver si se apoya esta hipótesis. La hipótesis de que <span class="math inline">\(\mu_1\)</span> y <span class="math inline">\(\mu_2\)</span> no son iguales es, de manera general, nuestra <strong>hipótesis alternativa</strong> y se abrevia como <span class="math inline">\(H_A\)</span>.</p>
<p><span class="math display" id="eq:HA">\[\begin{equation}
H_A: \mu_1 \neq \mu_2
\tag{5.10}
\end{equation}\]</span></p>
<p>La antítesis de esta hipótesis se conoce como <strong>hipótesis nula</strong> y se abrevia como <span class="math inline">\(H_0\)</span>.</p>
<p><span class="math display" id="eq:H0">\[\begin{equation}
H_0: \mu_1 = \mu_2
\tag{5.11}
\end{equation}\]</span></p>
<p>Una <strong>estadístico de prueba de hipótesis</strong> o <strong>estadístico de prueba</strong> nos ayuda a corroborar la fuerza de la evidencia presentada en los datos en favor de la <span class="math inline">\(H_A\)</span>.</p>
<p>Ya que la <span class="math inline">\(H_0\)</span> dice que las medias de las poblaciones son iguales, esperaríamos que esa diferencia fuese 0.</p>
<p><span class="math display">\[\begin{equation}
H_0: \mu_1 = \mu_2 \longleftrightarrow H_0: \mu_1 - \mu_2 = 0
\end{equation}\]</span></p>
<p>La <span class="math inline">\(H_A\)</span> dice que la diferencia entre las medias no es igual a 0.</p>
<p><span class="math display">\[\begin{equation}
H_0: \mu_1 \neq \mu_2 \longleftrightarrow H_0: \mu_1 - \mu_2 \neq 0
\end{equation}\]</span></p>
<p>La <strong>prueba de <span class="math inline">\(t\)</span></strong> es un método que nos ayuda a elegir entre ambas hipótesis. Para hacer un análisis como este, primero necesitamos computar el <strong>estadístico de <span class="math inline">\(t\)</span></strong>.</p>
<p><span class="math display" id="eq:tstat">\[\begin{equation}
t_s = \frac{(\overline{x}_1 - \overline{x}_2) - 0}{SE_{(\overline{X}_1 - \overline{X}_2)}}
\tag{5.12}
\end{equation}\]</span></p>
<p>Este estadístico mide que tan larga es la diferencia de las medias de la diferencia que esperaríamos si la <span class="math inline">\(H_0\)</span> fuese verdad <span class="math inline">\((\overline{x}_1 - \overline{x}_2) - 0\)</span>, expresada en relación con el error estándar de la diferencia <span class="math inline">\(SE_{(\overline{X}_1 - \overline{X}_2)}\)</span> (la cantidad de variación que esperaríamos ver en la diferencias de muestras aleatorias). Veamos un ejemplo.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Investigadores están interesados en los efectos que produce el tolueno. Para esto, midieron las concentraciones de varios químicos en el cerebro de ratas que habían sido expuestas a tolueno y ratas que no habían sido expuestas (control). En la siguiente tabla se muestran las concentraciones de norepinefrina (NE) de la región de la médula del cerebro. La <span class="math inline">\(H_0\)</span> de los investigadores es que el tolueno no tiene efecto en la concentración de NE en la médula de las ratas. Por ende, la <span class="math inline">\(H_A\)</span> es que el tolueno tiene un efecto en la médlua de las ratas.</p>
</blockquote>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="inferencia-de-las-medias.html#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb152-2"><a href="inferencia-de-las-medias.html#cb152-2" aria-hidden="true" tabindex="-1"></a>Tolueno <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="fl">540.8</span>, <span class="fl">66.1</span>), <span class="dv">1</span>)</span>
<span id="cb152-3"><a href="inferencia-de-las-medias.html#cb152-3" aria-hidden="true" tabindex="-1"></a>Control <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="fl">444.2</span>, <span class="fl">69.6</span>), <span class="dv">1</span>)</span>
<span id="cb152-4"><a href="inferencia-de-las-medias.html#cb152-4" aria-hidden="true" tabindex="-1"></a>ex1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Control, Tolueno)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-101">Tabla 5.2: </span>Concentración de NE en cerebro de ratas (ng/gm)
</caption>
<thead>
<tr>
<th style="text-align:center;">
Control
</th>
<th style="text-align:center;">
Tolueno
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
529.4
</td>
<td style="text-align:center;min-width: 3cm; ">
503.8
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
469.2
</td>
<td style="text-align:center;min-width: 3cm; ">
525.6
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
472.1
</td>
<td style="text-align:center;min-width: 3cm; ">
643.8
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
451.9
</td>
<td style="text-align:center;min-width: 3cm; ">
545.5
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
405.5
</td>
<td style="text-align:center;min-width: 3cm; ">
549.3
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
568.6
</td>
<td style="text-align:center;min-width: 3cm; ">
654.2
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
478.9
</td>
<td style="text-align:center;min-width: 3cm; ">
571.3
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
307.3
</td>
<td style="text-align:center;min-width: 3cm; ">
457.2
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
493.0
</td>
<td style="text-align:center;min-width: 3cm; ">
495.4
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
411.3
</td>
<td style="text-align:center;min-width: 3cm; ">
511.3
</td>
</tr>
</tbody>
</table>
<p><img src="Curso_R_basico_files/figure-html/ex2-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>En este caso tenemos que conocer la desviación estándar y la media de nuestros datos. Para esto podemos usar la librería de <code>dplyr</code>.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="inferencia-de-las-medias.html#cb153-1" aria-hidden="true" tabindex="-1"></a>ex2 <span class="ot">&lt;-</span> <span class="fu">gather</span>(ex1, Grupo, Conc)</span>
<span id="cb153-2"><a href="inferencia-de-las-medias.html#cb153-2" aria-hidden="true" tabindex="-1"></a>ex3 <span class="ot">&lt;-</span> ex2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Grupo) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">Media =</span> <span class="fu">mean</span>(Conc), <span class="at">SD =</span> <span class="fu">sd</span>(Conc), <span class="at">SE =</span> SD<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb153-3"><a href="inferencia-de-las-medias.html#cb153-3" aria-hidden="true" tabindex="-1"></a>ex3</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   Grupo       n Media    SD    SE
##   &lt;chr&gt;   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Control    10  459.  72.3  22.9
## 2 Tolueno    10  546.  63.0  19.9</code></pre>
<p>Listo, tenemos nuestra media <span class="math inline">\(\overline{x}\)</span>, desviación estándar <span class="math inline">\(s\)</span> y error estándar <span class="math inline">\(SE\)</span> para el grupo control y el grupo tratado con tolueno. Ahora procedemos a aplicar la fórmula para encontrar nuestro estadístico <span class="math inline">\(t\)</span>. Primero debemos calcular el error estándar de (<span class="math inline">\(\overline{X}_1 - \overline{X}_2\)</span>).</p>
<p><span class="math display">\[\begin{equation}
SE_{(\overline{X}_1 - \overline{X}_2)} = \sqrt{\frac{63.04^2}{10} + \frac{72.26^2}{10}} 
\end{equation}\]</span></p>
<p>Posteriormente aplicaríamos la fórmula para encontrar el estadístico <span class="math inline">\(t\)</span>.</p>
<p><span class="math display">\[\begin{equation}
t_s = \frac{(545.74 - 458.72) - 0}{SE_{(\overline{X}_1 - \overline{X}_2)}}
\end{equation}\]</span></p>
<p>Sin embargo, gracias a la función <code>t.test</code> no es necesario que hagamos este procedimiento paso a paso. Por ejemplo, si queremos obtener el estadístico <span class="math inline">\(t\)</span> simplemente escribimos lo siguiente.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="inferencia-de-las-medias.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Conc <span class="sc">~</span> Grupo, ex2)<span class="sc">$</span>statistic</span></code></pre></div>
<pre><code>##         t 
## -2.869561</code></pre>
<p>Si agregamos <code>$statistic</code> al final de nuestra función obtenemos el estadístico de <span class="math inline">\(t\)</span> que en este caso es 2.87. Pero, ¿cómo sabemos que tenemos suficiente evidencia para aceptar o rechazar la <span class="math inline">\(H_A\)</span>? Bueno, si la <span class="math inline">\(H_0\)</span> es verdadera, la distribución muestral de <span class="math inline">\(t_s\)</span> se aproximará a una distribución <span class="math inline">\(t\)</span> de Student con los grados de libertad dados por la fórmula <a href="inferencia-de-las-medias.html#eq:df2">(5.9)</a>.</p>
<p>La esencia de de la prueba de <span class="math inline">\(t\)</span> es ver en qué parte de la distribución <span class="math inline">\(t\)</span> de Student cae el estadístico <span class="math inline">\(t_s\)</span>. Si cae cercano al centro, entonces la evidencia de los datos es compatible con la <span class="math inline">\(H_0\)</span>. Sin embargo, si <span class="math inline">\(t_s\)</span> cae en alguna de las colas, entonces, la evidencia de los datos es compatible con la <span class="math inline">\(H_A\)</span> y una observación como la obtenida no puede explicarse meramente por azar.</p>
<p>Para juzgar si nuestro valor <span class="math inline">\(t_s\)</span> cae en la cola de la distribución <span class="math inline">\(t\)</span> de Student, usamos un valor conocido como <strong>valor-p</strong>. El valor-<em>p</em> puede definirse como el área bajo la curva de una distribución <span class="math inline">\(t\)</span> de Student en cualquiera de las colas que se encuentra más allá de <span class="math inline">\(-t_s\)</span> o <span class="math inline">\(t_s\)</span> como se muestra en la figura <a href="inferencia-de-las-medias.html#fig:pvalue">5.6</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:pvalue"></span>
<img src="Curso_R_basico_files/figure-html/pvalue-1.png" alt="Valor-*p* para un valor de $t_s$." width="672" />
<p class="caption">
Figura 5.6: Valor-<em>p</em> para un valor de <span class="math inline">\(t_s\)</span>.
</p>
</div>
<p>Otra forma de definir el valor-<em>p</em> es como la probabilidad de obtener un valor tan extremo como el observado si la <span class="math inline">\(H_0\)</span> fuera verdadera. Para calcular el valor-<em>p</em> necesitamos encontrar el área bajo la distribución <span class="math inline">\(t\)</span> de Student que se encuentre más allá de <span class="math inline">\(\pm SE_{\overline{X}_1 - \overline{X}_2}\)</span>. Afortunadamente, la función <code>t.test()</code> también nos da el valor-<em>p</em>. Podemos corroborar esto a mano.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="inferencia-de-las-medias.html#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Conc <span class="sc">~</span> Grupo, ex2)<span class="sc">$</span>parameter</span></code></pre></div>
<pre><code>##      df 
## 17.6748</code></pre>
<p>Como podemos ver, para nuestros datos tenemos 17.67 grados de libertad. Entonces simplemente en la distribución <span class="math inline">\(t\)</span> de Student buscamos el área correspondiente para un valor <span class="math inline">\(t_s = -2.87\)</span> con <span class="math inline">\(df = 17.67\)</span>.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="inferencia-de-las-medias.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="fl">2.87</span>, <span class="fl">17.67</span>, <span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 0.005160011</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="inferencia-de-las-medias.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.87</span>, <span class="fl">17.67</span>, <span class="at">lower.tail =</span> T)</span></code></pre></div>
<pre><code>## [1] 0.005160011</code></pre>
<p>Como en este caso se trata de un valor-<em>p</em> de dos colas, tenemos que sumar el área que obtenemos de la cola inferior y superior, que dan como resultado cerca de 0.0103. Por ende, nuestro <span class="math inline">\(valor-p = 0.0103\)</span>. Afortunadamente no tenemos que hacer esto cada vez que realizamos una prueba de <span class="math inline">\(t\)</span> en <code>R</code>. Simplemente escribimos <code>$p.value</code> al final de nuestro comando y este nos debería dar nuestro valor-<em>p</em>.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="inferencia-de-las-medias.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Conc <span class="sc">~</span> Grupo, ex2)<span class="sc">$</span>p.value</span></code></pre></div>
<pre><code>## [1] 0.0103277</code></pre>
<p>Como podemos ver el valor es aproximadamente igual (puede diferir debido a los decimales). Un valor-<em>p</em> cercano a 1 indica que el valor <span class="math inline">\(t_s\)</span> se encuentra cercano al centro de la distribución <span class="math inline">\(t\)</span>, que resultaría en una falta de evidencia para la <span class="math inline">\(H_A\)</span>. Un valor-<em>p</em> cercano a 0 indica que el valor <span class="math inline">\(t_s\)</span> se encuentra en una de las colas de la distribución <span class="math inline">\(t\)</span>, lo que daría evidencia para la <span class="math inline">\(H_A\)</span>.</p>
<p>¿Cómo decidimos qué valores-<em>p</em> muestran evidencia para la <span class="math inline">\(H_A\)</span>? Para esto necesitamos elegir un <strong>nivel de significancia</strong> o <span class="math inline">\(\alpha\)</span>. Este valor lo elige, generalmente, quién realiza la decisión acerca del estudio. Valores <span class="math inline">\(\alpha\)</span> comunes son <span class="math inline">\(\alpha = 0.1, \space 0.05, \space 0.01\)</span>. Si nuestro valor-<em>p</em> es menor o igual a nuestro alfa (<span class="math inline">\(valor-p \leq \alpha\)</span>) nuestros datos muestran evidencia de una diferencia <strong>estadísticamente significativa</strong> a favor de <span class="math inline">\(H_A\)</span>. Decimos que la <span class="math inline">\(H_0\)</span> se rechaza. Si por el contrario el valor-<em>p</em> es mayor que nuestro alfa (<span class="math inline">\(valor-p \geq \alpha\)</span>), decimos que hay insuficiente evidencia para decir que <span class="math inline">\(H_A\)</span> es verdad, por lo tanto no se rechaza la <span class="math inline">\(H_0\)</span>.</p>
<p>¿Cómo podemos ver toda está información? Bueno, si no agregamos ningún valor al final de nuestro comando <code>t.test()</code>, obtenemos toda la información condensada.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="inferencia-de-las-medias.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Conc <span class="sc">~</span> Grupo, ex2)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Conc by Grupo
## t = -2.8696, df = 17.675, p-value = 0.01033
## alternative hypothesis: true difference in means between group Control and group Tolueno is not equal to 0
## 95 percent confidence interval:
##  -150.81499  -23.22501
## sample estimates:
## mean in group Control mean in group Tolueno 
##                458.72                545.74</code></pre>
<p>¿Dónde ponemos o indicamos el <span class="math inline">\(\alpha\)</span>? La función <code>t.test()</code> no especifica un nivel de significancia y lo deja a manos de quién está realizando el experimento para decidir qué <span class="math inline">\(\alpha\)</span> utilizar.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-108"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-108-1.png" alt="Gráfico con el valor-*p* (área sombreada) correspondiente a los datos del ejercicio anterior." width="672" />
<p class="caption">
Figura 5.7: Gráfico con el valor-<em>p</em> (área sombreada) correspondiente a los datos del ejercicio anterior.
</p>
</div>
<p>Algo importante a tener en consideración es que, incluso cuando nuestro valor-<em>p</em> no muestra diferencias significativas no quiere decir esto que la <span class="math inline">\(H_A\)</span> no sea verdadera. Esto nos lleva a los tipos de errores que podemos cometer cuando hacemos pruebas de hipótesis.</p>
<ul>
<li><p><strong>Tipo de error I:</strong> Cuando decimos que los datos proveen evidencia significativa a favor de la <span class="math inline">\(H_A\)</span>, cuando en realidad <span class="math inline">\(H_0\)</span> es verdad. Este tipo de error se contrarresta cuando elegimos nuestro <span class="math inline">\(\alpha\)</span>.</p></li>
<li><p><strong>Tipo de error II:</strong> cuando la <span class="math inline">\(H_A\)</span> es verdadera, pero no obtenemos suficiente información que demuestre esto. Las muestras con tamaños de muestra pequeños son particularmente vulnerables a este tipo de error. La probabilidad de cometer este tipo de error se conoce como <span class="math inline">\(\beta\)</span>.</p></li>
</ul>
<p>La posibilidad de no cometer un error tipo II cuando la <span class="math inline">\(H_A\)</span> es verdadera se conoce como <strong>poder</strong>.</p>
<p><span class="math display" id="eq:power">\[\begin{equation}
Poder = 1 - \beta =  P(evidencia \space significativa \space para \space H_{A}) \space si \space H_{A} \space es \space verdad
\tag{5.13}
\end{equation}\]</span></p>
</div>
<div id="t-test-de-una-cola" class="section level3" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> <span class="math inline">\(t\)</span> test de una cola</h3>
<p>En caso de que tengamos una <strong>hipótesis direccional</strong> en la que nos interese solamente una de las dos colas de la distribución de <span class="math inline">\(t\)</span>, realizamos un <span class="math inline">\(t\)</span> test de una cola.</p>
<p>Las <span class="math inline">\(H_A\)</span> podrían ser <span class="math inline">\(H_{A}: \mu_1 &gt; \mu_2\)</span> o <span class="math inline">\(H_{A}: \mu_1 &lt; \mu_2\)</span>. Para este tipo de pruebas lo primero es checar la direccionalidad: ¿Nos interesa la parte inferior o superior de la distribución de <span class="math inline">\(t\)</span>? Después de eso, ver hacia que lado se desvían los datos. Si nuestros datos se desvían en dirección de la <span class="math inline">\(H_A\)</span> entonces podemos seguir con el procedimiento.</p>
<p>En este caso, el valor-<em>p</em> de una prueba de <span class="math inline">\(t\)</span> de una cola será el área que se encuentre más allá de <span class="math inline">\(t_s\)</span>.</p>
<p>Para hacer una prueba de una cola en R simplemente necesitamos cambiar un argumento en <code>t.test(alternative = "greater")</code> o <code>t.test(alternative = "less")</code>.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="inferencia-de-las-medias.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Conc <span class="sc">~</span> Grupo, ex2, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Conc by Grupo
## t = -2.8696, df = 17.675, p-value = 0.005164
## alternative hypothesis: true difference in means between group Control and group Tolueno is less than 0
## 95 percent confidence interval:
##       -Inf -34.38172
## sample estimates:
## mean in group Control mean in group Tolueno 
##                458.72                545.74</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="inferencia-de-las-medias.html#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Conc <span class="sc">~</span> Grupo, ex2, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Conc by Grupo
## t = -2.8696, df = 17.675, p-value = 0.9948
## alternative hypothesis: true difference in means between group Control and group Tolueno is greater than 0
## 95 percent confidence interval:
##  -139.6583       Inf
## sample estimates:
## mean in group Control mean in group Tolueno 
##                458.72                545.74</code></pre>
<p>Ahora bien, algo importante a recalcar es que existan <strong>diferencia significativas</strong> no quiere decir que el efecto sea realmente <strong>importante</strong>. Una prueba de hipótesis solamente responde a la pregunta <em>¿Hay suficiente diferencia entre ambas muestras como para inferir que vinieron de dos poblaciones distintas?</em> sin embargo no nos dice qué tan grande o importante es la diferencia.</p>
</div>
<div id="tamaño-de-efecto" class="section level3" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Tamaño de efecto</h3>
<p>Para medir la importancia de una diferencia uno debe de considerar la magnitud de la diferencia. El <strong>tamaño de efecto</strong> de un estudio es la diferencia entre <span class="math inline">\(\mu_{1}\)</span> y <span class="math inline">\(\mu_{2}\)</span>, en relación con la desviación estándar de una de las poblaciones.</p>
<p><span class="math display" id="eq:es">\[\begin{equation}
Tamaño \space de \space efecto = \frac{|{\overline{x}_1-\overline{x}_2}|}{\sigma}
\tag{5.14}
\end{equation}\]</span></p>
<p>Los resultados están dados en desviaciones estándar y el valor se conoce como <strong>d de Cohen</strong>. Para calcular la d de Cohen en <code>R</code> necesitamos un paquete estadístico llamado <code>effsize</code> y la función <code>cohen.d()</code>.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="inferencia-de-las-medias.html#cb171-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb171-2"><a href="inferencia-de-las-medias.html#cb171-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohen.d</span>(Conc <span class="sc">~</span> Grupo, <span class="at">data =</span> ex2, <span class="at">pooled_sd =</span> F)</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: -1.283307 (large)
## 95 percent confidence interval:
##      lower      upper 
## -2.3150540 -0.2515596</code></pre>
<p>La ventaja de esta función es que nos dice si nuestro tamaño de efecto es grande o pequeño.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-111"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-111-1.png" alt="Diferencias entre las medias de ambas muestras utilizadas en el ejercicio anterior." width="672" />
<p class="caption">
Figura 5.8: Diferencias entre las medias de ambas muestras utilizadas en el ejercicio anterior.
</p>
</div>
</div>
<div id="prueba-de-wilcoxon-mann-whitney" class="section level3" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> Prueba de Wilcoxon-Mann-Whitney</h3>
<p>También es utilizada para comprar dos muestras. A diferencia de la prueba de <span class="math inline">\(t\)</span>, incluso cuando las distribuciones de las poblaciones no son normales. Este tipo de pruebas no se enfocan en un parámetro particular como la media o la mediana, por esta razón se conocen como pruebas <strong>no paramétricas</strong>.</p>
<p>En el caso de esta prueba, una <span class="math inline">\(H_0\)</span> generalmente empleada es que las distribuciones de <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span> son iguales, y la <span class="math inline">\(H_A\)</span> es que la distribución de <span class="math inline">\(X_1\)</span> es distinta a la distribución de la población <span class="math inline">\(X_2\)</span>.</p>
<p>Esta prueba es recomendable aplicarla cuando tenemos datos que no se pueden transformar a una distribución normal aunque realicemos transformaciones (como logaritmos u otra transformación). El estadístico de esta prueba se denota como <span class="math inline">\(U_s\)</span> y mide el grado de separación entra ambas muestras.</p>
<ol style="list-style-type: decimal">
<li><p>Lo primero es acomodar los datos en orden, de menor a mayor para ambas muestras.</p></li>
<li><p>Posteriormente determinamos <span class="math inline">\(K_1\)</span> y <span class="math inline">\(K_2\)</span>. Para <span class="math inline">\(K_1\)</span>, contamos el número de observaciones en la muestra 2 que son más pequeñas que la muestra 1. Si hay observaciones que sean iguales para ambas muestras, se cuenta como 1/2 punto. Luego contamos para <span class="math inline">\(K_2\)</span> el número de observaciones en la muestra 1 que son menores que la muestra 2 y de igual forma, 1/2 si hay alguna observación con valor igual.</p></li>
<li><p>Para corroborar si nuestros cálculos son correctos la suma de <span class="math inline">\(K_1\)</span> y <span class="math inline">\(K_2\)</span> debe ser igual al producto de <span class="math inline">\(n_1 * n_2\)</span>.</p></li>
<li><p>El estadístico <span class="math inline">\(U_s\)</span> va a ser el más grande de los dos <span class="math inline">\(K_1\)</span> o <span class="math inline">\(K_2\)</span>.</p></li>
<li><p>Para encontrar el valor-<em>p</em> se utilizan tablas de U. Aunque en <code>R</code> es más sencillo, utilizando la función <code>wilcox.text()</code>.</p></li>
</ol>
<blockquote>
<p><strong>Ejemplo:</strong> En un estudio farmacéutico, investigadores midieron la concentración de dopamina en el cerebro de seis ratas expuestas a tolueno y seis ratas que funcionaron como control. Las concentraciones se muestran en la tabla <a href="inferencia-de-las-medias.html#tab:uex">5.3</a>.</p>
</blockquote>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="inferencia-de-las-medias.html#cb173-1" aria-hidden="true" tabindex="-1"></a>Tolueno1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3420</span>, <span class="dv">2314</span>, <span class="dv">1911</span>, <span class="dv">2464</span>, <span class="dv">2781</span>, <span class="dv">2803</span>)</span>
<span id="cb173-2"><a href="inferencia-de-las-medias.html#cb173-2" aria-hidden="true" tabindex="-1"></a>Control1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1820</span>, <span class="dv">1843</span>, <span class="dv">1397</span>, <span class="dv">1803</span>, <span class="dv">2539</span>, <span class="dv">1990</span>)</span>
<span id="cb173-3"><a href="inferencia-de-las-medias.html#cb173-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-4"><a href="inferencia-de-las-medias.html#cb173-4" aria-hidden="true" tabindex="-1"></a>Dopamina <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Tolueno1, Control1)</span></code></pre></div>
<table class="kable_wrapper">
<caption>
<span id="tab:uex">Tabla 5.3: </span>Concentración de dopamina (ng/mg) y sus estadísticos descriptivos.
</caption>
<tbody>
<tr>
<td>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Tolueno
</th>
<th style="text-align:center;">
Control
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 1.5cm; ">
3420
</td>
<td style="text-align:center;min-width: 1.5cm; ">
1820
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 1.5cm; ">
2314
</td>
<td style="text-align:center;min-width: 1.5cm; ">
1843
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 1.5cm; ">
1911
</td>
<td style="text-align:center;min-width: 1.5cm; ">
1397
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 1.5cm; ">
2464
</td>
<td style="text-align:center;min-width: 1.5cm; ">
1803
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 1.5cm; ">
2781
</td>
<td style="text-align:center;min-width: 1.5cm; ">
2539
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 1.5cm; ">
2803
</td>
<td style="text-align:center;min-width: 1.5cm; ">
1990
</td>
</tr>
</tbody>
</table>
</td>
<td>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Grupo
</th>
<th style="text-align:center;">
n
</th>
<th style="text-align:center;">
Media
</th>
<th style="text-align:center;">
SD
</th>
<th style="text-align:center;">
SE
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
Control1
</td>
<td style="text-align:center;min-width: 3cm; ">
6
</td>
<td style="text-align:center;min-width: 3cm; ">
1898.667
</td>
<td style="text-align:center;min-width: 3cm; ">
371.073
</td>
<td style="text-align:center;min-width: 3cm; ">
151.490
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
Tolueno1
</td>
<td style="text-align:center;min-width: 3cm; ">
6
</td>
<td style="text-align:center;min-width: 3cm; ">
2615.500
</td>
<td style="text-align:center;min-width: 3cm; ">
513.798
</td>
<td style="text-align:center;min-width: 3cm; ">
209.757
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="inferencia-de-las-medias.html#cb174-1" aria-hidden="true" tabindex="-1"></a>Dopamina <span class="ot">&lt;-</span> <span class="fu">gather</span>(Dopamina, Tratamiento, Concentracion) <span class="co">#Organizamos los datos de manera que se puedan trabajar.</span></span>
<span id="cb174-2"><a href="inferencia-de-las-medias.html#cb174-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb174-3"><a href="inferencia-de-las-medias.html#cb174-3" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Concentracion <span class="sc">~</span> Tratamiento, <span class="at">data =</span> Dopamina)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum exact test
## 
## data:  Concentracion by Tratamiento
## W = 4, p-value = 0.02597
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>El valor <span class="math inline">\(W\)</span> es equivalente al estadístico <span class="math inline">\(U_s\)</span>. En este caso vemos que en nuestro ejemplo tenemos diferencias significativas entre ambos tratamientos ya que el <span class="math inline">\(valor-p &lt; 0.05\)</span>. Eso claro, siempre que elijamos un <span class="math inline">\(\alpha = 0.05\)</span>.</p>
</div>
</div>
<div id="comparación-de-muestras-pareadas" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Comparación de muestras pareadas</h2>
<p>En esta ocasión vamos a considerar dos muestras que no son independientes entre sí, si no que se encuentran <strong>pareadas</strong>. En un diseño pareado, las observaciones de (<span class="math inline">\(X_1, X_2\)</span>) ocurren en pares. Esto quiere decir que las observaciones tienen más en común entre sí que con otros pares.</p>
<div id="prueba-de-t-pareada" class="section level3" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Prueba de <span class="math inline">\(t\)</span> pareada</h3>
<p>Cuando tenemos datos pareados, cambiamos un poco el enfoque. En lugar de considerar a <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2\)</span> por separado, consideramos su diferencia <span class="math inline">\(D\)</span>.</p>
<p><span class="math display" id="eq:diff">\[\begin{equation}
D = X_1 - X_2
\tag{5.15}
\end{equation}\]</span></p>
<p>Cuando tenemos datos pareados, son las diferencias en sí lo que queremos registrar. La media de <span class="math inline">\(D\)</span> es <span class="math inline">\(\overline{D}\)</span> y de igual manera se obtiene como una diferencia entre las medias de ambas muestras.</p>
<p><span class="math display" id="eq:diffmean">\[\begin{equation}
\overline{D} = \overline{X}_1 - \overline{X}_2
\tag{5.16}
\end{equation}\]</span></p>
<p>Lo mismo con la diferencia entre las medias de la población.</p>
<p><span class="math display" id="eq:diffmeanpop">\[\begin{equation}
\overline{D_\mu} = \mu_1 - \mu_2
\tag{5.17}
\end{equation}\]</span></p>
<p>Debido a esto podemos decir que la media de la diferencia es igual a la diferencia de las medias. Debido a esto podemos concentrarnos exclusivamente en <span class="math inline">\(D\)</span>. Ya que <span class="math inline">\(\overline{D}\)</span> es la media de una sola muestra, para obtener el error estándar simplemente aplicamos la fórmula <a href="inferencia-de-las-medias.html#eq:stderror">(5.1)</a>.</p>
<p><span class="math display" id="eq:stderrord">\[\begin{equation}
SE_\overline{D} = \frac{s_D}{\sqrt{n_D}}
\tag{5.18}
\end{equation}\]</span></p>
<p>Donde <span class="math inline">\(s_{D}\)</span> y <span class="math inline">\(n_D\)</span> son la desviación estándar y el tamaño de muestra de <span class="math inline">\(D\)</span>, respectivamente.</p>
<p>Veamos esto con un ejemplo.</p>
<blockquote>
<p><strong>Ejemplo:</strong> El adenosin monofosfato cíclico (cAMP) es una sustancia que regula la respuesta celular a las hormonas. En un estudio de maduración de ovarios en la rana <em>Xenopus laevis</em>, los oocitos de cada una de las 4 hembras fueron divdidos en dos grupos: un grupo fue expuesto a progesterona y el otro no. Después de 2 minutos, cada grupo fue analizado para encontrar el contenido de cAMP. Los datos se muestran en la siguiente tabla <a href="inferencia-de-las-medias.html#tab:camp">5.4</a>.</p>
</blockquote>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="inferencia-de-las-medias.html#cb176-1" aria-hidden="true" tabindex="-1"></a>Control <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">6.01</span>, <span class="fl">2.28</span>, <span class="fl">1.51</span>, <span class="fl">2.12</span>)</span>
<span id="cb176-2"><a href="inferencia-de-las-medias.html#cb176-2" aria-hidden="true" tabindex="-1"></a>Progesterona <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">5.23</span>, <span class="fl">1.21</span>, <span class="fl">1.40</span>, <span class="fl">1.38</span>)</span>
<span id="cb176-3"><a href="inferencia-de-las-medias.html#cb176-3" aria-hidden="true" tabindex="-1"></a>Datos1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Control, Progesterona)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:camp">Tabla 5.4: </span>Concentración de cAMP (pmol/oocito)
</caption>
<thead>
<tr>
<th style="text-align:center;">
Control
</th>
<th style="text-align:center;">
Progesterona
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
6.01
</td>
<td style="text-align:center;min-width: 3cm; ">
5.23
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
2.28
</td>
<td style="text-align:center;min-width: 3cm; ">
1.21
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
1.51
</td>
<td style="text-align:center;min-width: 3cm; ">
1.40
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
2.12
</td>
<td style="text-align:center;min-width: 3cm; ">
1.38
</td>
</tr>
</tbody>
</table>
<p>Ahora que tenemos nuestros datos, lo primero es encontrar las diferencias, <span class="math inline">\(d\)</span> entre los datos. Esto lo hacemos muy sencillo agregando una nueva columna <code>$d</code> a nuestra tabla.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="inferencia-de-las-medias.html#cb177-1" aria-hidden="true" tabindex="-1"></a>Datos1<span class="sc">$</span>d <span class="ot">&lt;-</span> Control <span class="sc">-</span> Progesterona <span class="co">#Encontramos d sacando la diferencia entre nuestros datos.</span></span></code></pre></div>
<p>Bien, ahora para poder encontrar la media y la desviación estándar de nuestras muestras de la diferencia <span class="math inline">\(d\)</span> necesitamos transformar la tabla en un formato que nos permita hacer estos análisis. Afortunadamente la función <code>gather()</code> nos ayuda con eso, que es parte del paquete <code>tidyr</code>.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="inferencia-de-las-medias.html#cb178-1" aria-hidden="true" tabindex="-1"></a>Datos2 <span class="ot">&lt;-</span> <span class="fu">gather</span>(Datos1, Grupo, Concentracion)</span></code></pre></div>
<p>La función <code>gather()</code> nos ayuda a reorganizar los datos para tenerlos de manera en que podamos trabajar con ellos. Ahora con la propia librería de <code>dplyr</code> deberíamos poder encontrar la media, tanto para los tratamientos como para <span class="math inline">\(d\)</span>.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="inferencia-de-las-medias.html#cb179-1" aria-hidden="true" tabindex="-1"></a>Datos3 <span class="ot">&lt;-</span> Datos2 <span class="sc">%&gt;%</span> </span>
<span id="cb179-2"><a href="inferencia-de-las-medias.html#cb179-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Grupo) <span class="sc">%&gt;%</span> </span>
<span id="cb179-3"><a href="inferencia-de-las-medias.html#cb179-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">Media =</span> <span class="fu">mean</span>(Concentracion), <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Concentracion), <span class="dv">3</span>))</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-118">Tabla 5.5: </span>Estadísticos descriptivos de cAMP
</caption>
<thead>
<tr>
<th style="text-align:center;">
Grupo
</th>
<th style="text-align:center;">
n
</th>
<th style="text-align:center;">
Media
</th>
<th style="text-align:center;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
Control
</td>
<td style="text-align:center;min-width: 3cm; ">
4
</td>
<td style="text-align:center;min-width: 3cm; ">
2.980
</td>
<td style="text-align:center;min-width: 3cm; ">
2.047
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
d
</td>
<td style="text-align:center;min-width: 3cm; ">
4
</td>
<td style="text-align:center;min-width: 3cm; ">
0.675
</td>
<td style="text-align:center;min-width: 3cm; ">
0.404
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
Progesterona
</td>
<td style="text-align:center;min-width: 3cm; ">
4
</td>
<td style="text-align:center;min-width: 3cm; ">
2.305
</td>
<td style="text-align:center;min-width: 3cm; ">
1.952
</td>
</tr>
</tbody>
</table>
<p>En este caso tenemos ya la media de la diferencia <span class="math inline">\(\overline{d}\)</span> y la desviación estándar de la diferencia <span class="math inline">\(s_D\)</span> así como el tamaño de muestra de la diferencia, en este caso <span class="math inline">\(n_D\)</span>. Nos quedaría calcular el error estándar de la diferencia <span class="math inline">\(SE_{\overline{D}}\)</span>, que en este caso sería.</p>
<p><span class="math display">\[\begin{equation}
SE_\overline{D} = \frac{0.404}{\sqrt{4}} = 0.202
\end{equation}\]</span></p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="inferencia-de-las-medias.html#cb180-1" aria-hidden="true" tabindex="-1"></a>Datos3 <span class="ot">&lt;-</span> Datos2 <span class="sc">%&gt;%</span></span>
<span id="cb180-2"><a href="inferencia-de-las-medias.html#cb180-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Grupo) <span class="sc">%&gt;%</span></span>
<span id="cb180-3"><a href="inferencia-de-las-medias.html#cb180-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">Media =</span> <span class="fu">mean</span>(Concentracion), <span class="at">SD =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Concentracion), <span class="dv">3</span>), <span class="at">SE =</span> SD<span class="sc">/</span><span class="fu">sqrt</span>(n))</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-120">Tabla 5.6: </span>Estadísticos descriptivos incluyendo el error estándar
</caption>
<thead>
<tr>
<th style="text-align:center;">
Grupo
</th>
<th style="text-align:center;">
n
</th>
<th style="text-align:center;">
Media
</th>
<th style="text-align:center;">
SD
</th>
<th style="text-align:center;">
SE
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
Control
</td>
<td style="text-align:center;min-width: 3cm; ">
4
</td>
<td style="text-align:center;min-width: 3cm; ">
2.980
</td>
<td style="text-align:center;min-width: 3cm; ">
2.047
</td>
<td style="text-align:center;">
1.0235
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
d
</td>
<td style="text-align:center;min-width: 3cm; ">
4
</td>
<td style="text-align:center;min-width: 3cm; ">
0.675
</td>
<td style="text-align:center;min-width: 3cm; ">
0.404
</td>
<td style="text-align:center;">
0.2020
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
Progesterona
</td>
<td style="text-align:center;min-width: 3cm; ">
4
</td>
<td style="text-align:center;min-width: 3cm; ">
2.305
</td>
<td style="text-align:center;min-width: 3cm; ">
1.952
</td>
<td style="text-align:center;">
0.9760
</td>
</tr>
</tbody>
</table>
<p>A partir de aquí podemos construir un intervalo de confianza para <span class="math inline">\(D\)</span>. La forma de hacerlo es igual a la que vimos anteriormente.</p>
<p><span class="math display" id="eq:ICpair">\[\begin{equation}
\overline{d} \pm t_{n_{D}-1, 0.025}SE_\overline{D}
\tag{5.19}
\end{equation}\]</span></p>
<p>En donde <span class="math inline">\(t_{n_{D}-1, 0.025}\)</span> es una constante determinada a partir de la distribución <span class="math inline">\(t\)</span> de Student, utilizando como grados de libertad la fórmula <span class="math inline">\(df = n_D - 1\)</span>. Intervalos de confianza con otros coeficientes se construyen de la misma manera.</p>
<p>Construir el intervalo de confianza correspondiente es relativamente sencillo. Vamos a utilizar la función <code>t.test()</code> pero con el argumento <code>paired = TRUE</code>.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="inferencia-de-las-medias.html#cb181-1" aria-hidden="true" tabindex="-1"></a>Datos4 <span class="ot">&lt;-</span>  <span class="fu">data.frame</span>(Control, Progesterona)</span>
<span id="cb181-2"><a href="inferencia-de-las-medias.html#cb181-2" aria-hidden="true" tabindex="-1"></a>Datos4 <span class="ot">&lt;-</span> <span class="fu">gather</span>(Datos4, Grupo, Concentracion)</span>
<span id="cb181-3"><a href="inferencia-de-las-medias.html#cb181-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb181-4"><a href="inferencia-de-las-medias.html#cb181-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Concentracion <span class="sc">~</span> Grupo, Datos4, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  Concentracion by Grupo
## t = 3.3387, df = 3, p-value = 0.04443
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.0315868 1.3184132
## sample estimates:
## mean of the differences 
##                   0.675</code></pre>
<p>De hecho, de esta manera obtenemos el intervalo de confianza, el valor crítico de <span class="math inline">\(t\)</span>, los grados de libertad, el valor-<em>p</em>, la media de las diferencias <span class="math inline">\(\overline{D}\)</span>. Hay que tener en cuenta que en este caso nuestra hipótesis nula <span class="math inline">\(H_0\)</span> tiene una connotación distinta. En este caso:</p>
<p><span class="math display">\[\begin{equation}
H_0 : \mu_{d} = 0 \\
H_A : \mu_{d} \neq 0
\end{equation}\]</span></p>
<p>Para nuestro ejemplo, nuestras hipótesis pueden ser las siguientes:</p>
<ul>
<li><p><strong><span class="math inline">\(H_0\)</span>:</strong> La media de la concentración de cAMP de los oocitos es la misma tanto con exposición o sin exposición a progesterona.</p></li>
<li><p><strong><span class="math inline">\(H_A\)</span>:</strong> La media de la concentración de cAMP de los oocitos es distinta tras exponerse a progesterona a los que no fueron expuestos.</p></li>
</ul>
<p>En este caso nuestro <span class="math inline">\(valor-p &lt; 0.05\)</span> por lo tanto tenemos suficiente evidencia para rechazar la <span class="math inline">\(H_0\)</span>.</p>
<p>Si quisiéramos hacer el cálculo de manera manual, encontrar el valor crítico <span class="math inline">\(t_s\)</span> se realiza con la siguiente fórmula:</p>
<p><span class="math display" id="eq:tpair">\[\begin{equation}
t_s = \frac{\overline{d}-0}{SE_\overline{D}}
\tag{5.20}
\end{equation}\]</span></p>
</div>
<div id="prueba-de-signos" class="section level3" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> Prueba de signos</h3>
<p>El <strong>sign test</strong> o <strong>prueba de signos</strong> es un método no paramétrico para comparar dos muestras pareadas. También se basa en las diferencias <span class="math inline">\(D = X_1 - X_2\)</span>. La única información que se utiliza en esta prueba es el <strong>signo</strong> (positivo o negativo) de cada diferencia.</p>
<ol style="list-style-type: decimal">
<li><p>El primer paso es contar el número de signos positivos <span class="math inline">\(N_+\)</span> y negativos <span class="math inline">\(N_-\)</span>. El estadístico de la prueba de signos se conoce como <span class="math inline">\(B_s\)</span> y dependiendo de nuestra hipótesis, <span class="math inline">\(B_s = N_+\)</span> o <span class="math inline">\(B_s = N_-\)</span>.</p></li>
<li><p>Posteriormente calculamos el valor-<em>p</em>. Como el estadístico <span class="math inline">\(B_s\)</span> sigue una distribución binomial, podemos decir que <span class="math inline">\(p\)</span> representa la probabilidad de que la diferencia sea positiva o negativa. La distribución nula de <span class="math inline">\(B_s\)</span> es una distribución binomial con <span class="math inline">\(n\)</span> = número de muestras y <span class="math inline">\(p = 0.5\)</span>.</p></li>
<li><p>Entonces el valor-<em>p</em> para la prueba consiste en la probabilidad de obtener <span class="math inline">\(B_s\)</span> o más diferencias, positivas o negativas.</p></li>
</ol>
<p>Esta prueba es aplicable en situaciones en las que la <span class="math inline">\(H_0 : P(D \space es \space positiva) = 0.5\)</span> en los que se puede aplicar una distribución binomial. En esta prueba la forma de la distribución no es un factor importante. Para hacer una prueba de signos en <code>R</code> simplemente utilizamos la distribución binomial que vimos anteriormente.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Un investigador estudia la interacción entre dos subespecies de aves, el Junco de Carolina y el Junco Norteño. Puso a ambos en un aviario y observó el comportamiento durante 45 minutos. Este proceso fue repetido en varios días con distintos pares de individuos. Los resultados se muestran en la tabla <a href="inferencia-de-las-medias.html#tab:signex">5.7</a>.</p>
</blockquote>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="inferencia-de-las-medias.html#cb183-1" aria-hidden="true" tabindex="-1"></a>Norteno <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb183-2"><a href="inferencia-de-las-medias.html#cb183-2" aria-hidden="true" tabindex="-1"></a>Carolina <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">6</span>, <span class="dv">22</span>, <span class="dv">16</span>, <span class="dv">17</span>, <span class="dv">33</span>, <span class="dv">24</span>, <span class="dv">40</span>)</span>
<span id="cb183-3"><a href="inferencia-de-las-medias.html#cb183-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-4"><a href="inferencia-de-las-medias.html#cb183-4" aria-hidden="true" tabindex="-1"></a>Aves <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Norteno, Carolina)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style='font-family: "Arial Narrow", "Source Sans Pro", sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<caption>
<span id="tab:signex">Tabla 5.7: </span>Número de veces que fue dominante un ave
</caption>
<thead>
<tr>
<th style="text-align:center;">
Norteno
</th>
<th style="text-align:center;">
Carolina
</th>
<th style="text-align:center;">
Signo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
0
</td>
<td style="text-align:center;min-width: 3cm; ">
9
</td>
<td style="text-align:center;min-width: 3cm; ">
<ul>
<li></td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
0
</td>
<td style="text-align:center;min-width: 3cm; ">
6
</td>
<td style="text-align:center;min-width: 3cm; ">
<ul>
<li></td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
0
</td>
<td style="text-align:center;min-width: 3cm; ">
22
</td>
<td style="text-align:center;min-width: 3cm; ">
<ul>
<li></td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
2
</td>
<td style="text-align:center;min-width: 3cm; ">
16
</td>
<td style="text-align:center;min-width: 3cm; ">
<ul>
<li></td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
0
</td>
<td style="text-align:center;min-width: 3cm; ">
17
</td>
<td style="text-align:center;min-width: 3cm; ">
<ul>
<li></td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
2
</td>
<td style="text-align:center;min-width: 3cm; ">
33
</td>
<td style="text-align:center;min-width: 3cm; ">
<ul>
<li></td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
1
</td>
<td style="text-align:center;min-width: 3cm; ">
24
</td>
<td style="text-align:center;min-width: 3cm; ">
<ul>
<li></td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
0
</td>
<td style="text-align:center;min-width: 3cm; ">
40
</td>
<td style="text-align:center;min-width: 3cm; ">
<ul>
<li></td>
</tr>
</tbody>
</table>
Para este ejemplo, <span class="math inline">\(N_+ = 0\)</span> y <span class="math inline">\(N_- = 8\)</span>, por lo tanto <span class="math inline">\(B_s = 8\)</span>. Nuestro valor-<em>p</em> es la probabilidad de obtener 8 valores con signo -, en un experimento binomial con <span class="math inline">\(n = 8\)</span>. Para encontrar el valor-<em>p</em> podemos usar alguna tabla o la función <code>dbinom()</code>.</li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="inferencia-de-las-medias.html#cb184-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">dbinom</span>(<span class="dv">8</span>, <span class="dv">8</span>, <span class="fl">0.5</span>) <span class="co">#Multiplicamos por dos, ya que hacemos una prueba de signos de dos colas.</span></span></code></pre></div>
<pre><code>## [1] 0.0078125</code></pre>
<p>Como podemos ver, el <span class="math inline">\(valor-p = 0.008\)</span>, por lo tanto el <span class="math inline">\(valor-p &lt; 0.05\)</span> y aceptamos la <span class="math inline">\(H_A\)</span> y vemos que hay diferencias significativas entre las dos subespecies en cuanto a la dominancia. También podemos hacer uso del paquete <code>BSDA</code>, `<code>DescTools</code> o <code>signmedia.test</code> con sus funciones correspondientes, como veremos en todos los casos obtenemos un resultado similar.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="inferencia-de-las-medias.html#cb186-1" aria-hidden="true" tabindex="-1"></a>Diferencia <span class="ot">&lt;-</span> Norteno <span class="sc">-</span> Carolina <span class="co">#Obtenemos la diferencia de nuestros datos</span></span>
<span id="cb186-2"><a href="inferencia-de-las-medias.html#cb186-2" aria-hidden="true" tabindex="-1"></a>Diferencia</span></code></pre></div>
<pre><code>## [1]  -9  -6 -22 -14 -17 -31 -23 -40</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="inferencia-de-las-medias.html#cb188-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BSDA)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;BSDA&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:datasets&#39;:
## 
##     Orange</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="inferencia-de-las-medias.html#cb191-1" aria-hidden="true" tabindex="-1"></a><span class="fu">SIGN.test</span>(Diferencia, <span class="at">md =</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## 
##  One-sample Sign-Test
## 
## data:  Diferencia
## s = 0, p-value = 0.007813
## alternative hypothesis: true median is not equal to 8
## 95 percent confidence interval:
##  -33.925  -8.025
## sample estimates:
## median of x 
##       -19.5 
## 
## Achieved and Interpolated Confidence Intervals: 
## 
##                   Conf.Level  L.E.pt U.E.pt
## Lower Achieved CI     0.9297 -31.000 -9.000
## Interpolated CI       0.9500 -33.925 -8.025
## Upper Achieved CI     0.9922 -40.000 -6.000</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="inferencia-de-las-medias.html#cb193-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb193-2"><a href="inferencia-de-las-medias.html#cb193-2" aria-hidden="true" tabindex="-1"></a><span class="fu">SignTest</span>(Diferencia, <span class="at">mu =</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## 
##  One-sample Sign-Test
## 
## data:  Diferencia
## S = 0, number of differences = 8, p-value = 0.007812
## alternative hypothesis: true median is not equal to 8
## 99.2 percent confidence interval:
##  -40  -6
## sample estimates:
## median of the differences 
##                     -19.5</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="inferencia-de-las-medias.html#cb195-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(signmedian.test)</span>
<span id="cb195-2"><a href="inferencia-de-las-medias.html#cb195-2" aria-hidden="true" tabindex="-1"></a><span class="fu">signmedian.test</span>(Diferencia, <span class="at">mu =</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## 
##  Exact sign test
## 
## data:  Diferencia
## #(x!=8) = 8, mu = 8, p-value = 0.007812
## alternative hypothesis: the median of x is not equal to mu
## 92.96875 percent confidence interval:
##  -31  -9
## sample estimates:
## point estimator 
##           -19.5</code></pre>
<p>Como podemos ver obtenemos el mismo valor que en nuestro código con la distribución binomial.</p>
</div>
<div id="prueba-de-rangos-con-signos-de-wilcoxon" class="section level3" number="5.5.3">
<h3><span class="header-section-number">5.5.3</span> Prueba de rangos con signos de Wilcoxon</h3>
<p>Esta es una prueba para datos pareados que no siguen una distribución normal. También esta basado en las diferencias de <span class="math inline">\(D = X_1 - X_2\)</span> y combina las ideas de “mirar a los signos de las diferencias” con “mirar las magnitudes de las diferencias.”</p>
<ol style="list-style-type: decimal">
<li><p>El primer paso para una prueba de rangos con signos de Wilcoxon es calcular las diferencia <span class="math inline">\(d\)</span> entre los datos pareados. Después de esto, buscamos el valor absoluto de las diferencias <span class="math inline">\(|d|\)</span>.</p></li>
<li><p>Después de organizan estas diferencias de las menores a las mayores.</p></li>
<li><p>Después de esto regresamos los signos que tenían previamente a los valores absolutos y sumamos los valores con símbolos positivos para formar <span class="math inline">\(W_+\)</span> y los valores absolutos de los valores con símbolos negativos para formar <span class="math inline">\(W_-\)</span>. El estadístico <span class="math inline">\(W_s\)</span> es el valor que sea más grande entre <span class="math inline">\(W_+\)</span> y <span class="math inline">\(W_-\)</span>.</p></li>
<li><p>Para encontrar el valor-<em>p</em> se pueden utilizar tablas. En este caso, basta con cambiar un argumento al comando <code>wilcox.test(paired = TRUE)</code>.</p></li>
</ol>
<p>Esta prueba se puede llevar a cabo incluso cuando hay información incompleta. La hipótesis es similar al test del Wilcoxon para datos no pareados, <span class="math inline">\(H_0 : \mu_{D} = 0\)</span>.</p>
<blockquote>
<p><strong>Ejemplo:</strong> En una investigación acerca de posible daño cerebral debido al alcoholísmo, un procedimo de rayos-X conocido como tomografía computarizada (TC) fue utilizado para medir la densidad del cerebro en 11 bebedores de alcohol crónicos. Para cada alcohólico, se selecciono una persona no alcohólica para empatar en edad, sexo, educación, etc.</p>
</blockquote>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="inferencia-de-las-medias.html#cb197-1" aria-hidden="true" tabindex="-1"></a>Alcoholico <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">40.1</span>, <span class="fl">38.5</span>, <span class="fl">36.9</span>, <span class="fl">41.4</span>, <span class="fl">40.6</span>, <span class="fl">42.3</span>, <span class="fl">37.2</span>, <span class="fl">38.6</span>, <span class="fl">38.5</span>, <span class="fl">38.4</span>, <span class="fl">38.1</span>)</span>
<span id="cb197-2"><a href="inferencia-de-las-medias.html#cb197-2" aria-hidden="true" tabindex="-1"></a>NoAlcoholico <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">41.3</span>, <span class="fl">40.2</span>, <span class="fl">37.4</span>, <span class="fl">46.1</span>, <span class="fl">43.9</span>, <span class="fl">41.9</span>, <span class="fl">39.9</span>, <span class="fl">40.4</span>, <span class="fl">38.6</span>, <span class="fl">38.1</span>, <span class="fl">39.5</span>)</span>
<span id="cb197-3"><a href="inferencia-de-las-medias.html#cb197-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb197-4"><a href="inferencia-de-las-medias.html#cb197-4" aria-hidden="true" tabindex="-1"></a>Densidad <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Alcoholico, NoAlcoholico)</span>
<span id="cb197-5"><a href="inferencia-de-las-medias.html#cb197-5" aria-hidden="true" tabindex="-1"></a>Densidad2 <span class="ot">&lt;-</span> <span class="fu">gather</span>(Densidad, Grupo, Densidad)</span></code></pre></div>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="inferencia-de-las-medias.html#cb198-1" aria-hidden="true" tabindex="-1"></a>DiferenciaDensidad <span class="ot">&lt;-</span> Alcoholico <span class="sc">-</span> NoAlcoholico</span>
<span id="cb198-2"><a href="inferencia-de-las-medias.html#cb198-2" aria-hidden="true" tabindex="-1"></a>Densidad3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Alcoholico, NoAlcoholico, DiferenciaDensidad)</span>
<span id="cb198-3"><a href="inferencia-de-las-medias.html#cb198-3" aria-hidden="true" tabindex="-1"></a>Densidad3 <span class="sc">%&gt;%</span> </span>
<span id="cb198-4"><a href="inferencia-de-las-medias.html#cb198-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="st">&quot;html&quot;</span>, <span class="at">align =</span> <span class="fu">c</span>(<span class="st">&quot;c&quot;</span>, <span class="st">&quot;c&quot;</span>), <span class="at">caption =</span> <span class="st">&quot;Diferencia de densidad entre personas alcohólicas y no alcohólicas&quot;</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;Alcohólico&quot;</span>, <span class="st">&quot;No Alcohólico&quot;</span>, <span class="st">&quot;Diferencia&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb198-5"><a href="inferencia-de-las-medias.html#cb198-5" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_classic</span>(<span class="at">lightable_options =</span> <span class="st">&quot;striped&quot;</span>, <span class="at">full_width =</span> F) <span class="sc">%&gt;%</span> </span>
<span id="cb198-6"><a href="inferencia-de-las-medias.html#cb198-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">width_min =</span> <span class="st">&quot;4cm&quot;</span>)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-126">Tabla 5.8: </span>Diferencia de densidad entre personas alcohólicas y no alcohólicas
</caption>
<thead>
<tr>
<th style="text-align:center;">
Alcohólico
</th>
<th style="text-align:center;">
No Alcohólico
</th>
<th style="text-align:center;">
Diferencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 4cm; ">
40.1
</td>
<td style="text-align:center;min-width: 4cm; ">
41.3
</td>
<td style="text-align:center;min-width: 4cm; ">
-1.2
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
38.5
</td>
<td style="text-align:center;min-width: 4cm; ">
40.2
</td>
<td style="text-align:center;min-width: 4cm; ">
-1.7
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
36.9
</td>
<td style="text-align:center;min-width: 4cm; ">
37.4
</td>
<td style="text-align:center;min-width: 4cm; ">
-0.5
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
41.4
</td>
<td style="text-align:center;min-width: 4cm; ">
46.1
</td>
<td style="text-align:center;min-width: 4cm; ">
-4.7
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
40.6
</td>
<td style="text-align:center;min-width: 4cm; ">
43.9
</td>
<td style="text-align:center;min-width: 4cm; ">
-3.3
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
42.3
</td>
<td style="text-align:center;min-width: 4cm; ">
41.9
</td>
<td style="text-align:center;min-width: 4cm; ">
0.4
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
37.2
</td>
<td style="text-align:center;min-width: 4cm; ">
39.9
</td>
<td style="text-align:center;min-width: 4cm; ">
-2.7
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
38.6
</td>
<td style="text-align:center;min-width: 4cm; ">
40.4
</td>
<td style="text-align:center;min-width: 4cm; ">
-1.8
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
38.5
</td>
<td style="text-align:center;min-width: 4cm; ">
38.6
</td>
<td style="text-align:center;min-width: 4cm; ">
-0.1
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
38.4
</td>
<td style="text-align:center;min-width: 4cm; ">
38.1
</td>
<td style="text-align:center;min-width: 4cm; ">
0.3
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
38.1
</td>
<td style="text-align:center;min-width: 4cm; ">
39.5
</td>
<td style="text-align:center;min-width: 4cm; ">
-1.4
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="inferencia-de-las-medias.html#cb199-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Densidad <span class="sc">~</span> Grupo, Densidad2, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  Densidad by Grupo
## V = 5, p-value = 0.009766
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Como podemos ver, nuestro valor-<em>p</em> quiere decir que hay diferencias significativas ya que <span class="math inline">\(valor-p &lt; 0.05\)</span>. Si quisiéramos usar una hipótesis unidireccional, podríamos escribir como argumento <code>alternative = "less"</code> para ver si el alcoholismo reduce la densidad del cerebro.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="inferencia-de-las-medias.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Densidad <span class="sc">~</span> Grupo, Densidad2, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  Densidad by Grupo
## V = 5, p-value = 0.004883
## alternative hypothesis: true location shift is less than 0</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probabilidad.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
