<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 7 Correlación y regresión lineal | Curso de R básico</title>
  <meta name="description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 7 Correlación y regresión lineal | Curso de R básico" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 7 Correlación y regresión lineal | Curso de R básico" />
  
  <meta name="twitter:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="modelado-de-relaciones.html"/>
<link rel="next" href="bibliografia.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de R básico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Requisitos</a>
<ul>
<li><a href="index.html#descarga-de-r-y-rstudio">Descarga de <code>R</code> y RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introducción-a-r.html"><a href="introducción-a-r.html"><i class="fa fa-check"></i><b>1</b> Introducción a R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introducción-a-r.html"><a href="introducción-a-r.html#interfaz"><i class="fa fa-check"></i><b>1.1</b> Interfaz</a></li>
<li class="chapter" data-level="1.2" data-path="introducción-a-r.html"><a href="introducción-a-r.html#creando-nuestro-primer-proyecto"><i class="fa fa-check"></i><b>1.2</b> Creando nuestro primer proyecto</a></li>
<li class="chapter" data-level="1.3" data-path="introducción-a-r.html"><a href="introducción-a-r.html#objetos-y-variables"><i class="fa fa-check"></i><b>1.3</b> Objetos y variables</a></li>
<li class="chapter" data-level="1.4" data-path="introducción-a-r.html"><a href="introducción-a-r.html#instalar-paquetes"><i class="fa fa-check"></i><b>1.4</b> Instalar paquetes</a></li>
<li class="chapter" data-level="1.5" data-path="introducción-a-r.html"><a href="introducción-a-r.html#importar-datos-a-r"><i class="fa fa-check"></i><b>1.5</b> Importar datos a R</a></li>
<li class="chapter" data-level="1.6" data-path="introducción-a-r.html"><a href="introducción-a-r.html#comentarios"><i class="fa fa-check"></i><b>1.6</b> Comentarios</a></li>
<li class="chapter" data-level="1.7" data-path="introducción-a-r.html"><a href="introducción-a-r.html#exportar-datos"><i class="fa fa-check"></i><b>1.7</b> Exportar datos</a></li>
<li class="chapter" data-level="1.8" data-path="introducción-a-r.html"><a href="introducción-a-r.html#pedir-ayuda"><i class="fa fa-check"></i><b>1.8</b> Pedir ayuda</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html"><i class="fa fa-check"></i><b>2</b> Estadística descriptiva</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#datos-y-estudios"><i class="fa fa-check"></i><b>2.1</b> Datos y estudios</a></li>
<li class="chapter" data-level="2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>2.2</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#media"><i class="fa fa-check"></i><b>2.2.1</b> Media</a></li>
<li class="chapter" data-level="2.2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mediana"><i class="fa fa-check"></i><b>2.2.2</b> Mediana</a></li>
<li class="chapter" data-level="2.2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#moda"><i class="fa fa-check"></i><b>2.2.3</b> Moda</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>2.3</b> Medidas de dispersión</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#rango"><i class="fa fa-check"></i><b>2.3.1</b> Rango</a></li>
<li class="chapter" data-level="2.3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#desviación-estándar"><i class="fa fa-check"></i><b>2.3.2</b> Desviación estándar</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-posición-relativa"><i class="fa fa-check"></i><b>2.4</b> Medidas de posición relativa</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#valores-z"><i class="fa fa-check"></i><b>2.4.1</b> Valores <span class="math inline">\(Z\)</span></a></li>
<li class="chapter" data-level="2.4.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-absoluta"><i class="fa fa-check"></i><b>2.4.2</b> Frecuencia absoluta</a></li>
<li class="chapter" data-level="2.4.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-relativa"><i class="fa fa-check"></i><b>2.4.3</b> Frecuencia relativa</a></li>
<li class="chapter" data-level="2.4.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#cuartiles"><i class="fa fa-check"></i><b>2.4.4</b> Cuartiles</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#el-uso-de-la-librería-dplyr"><i class="fa fa-check"></i><b>2.5</b> El uso de la librería <code>dplyr</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probabilidad.html"><a href="probabilidad.html"><i class="fa fa-check"></i><b>3</b> Probabilidad</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probabilidad.html"><a href="probabilidad.html#probabilidad-frecuentista"><i class="fa fa-check"></i><b>3.1</b> Probabilidad frecuentista</a></li>
<li class="chapter" data-level="3.2" data-path="probabilidad.html"><a href="probabilidad.html#reglas-de-probabilidad"><i class="fa fa-check"></i><b>3.2</b> Reglas de probabilidad</a></li>
<li class="chapter" data-level="3.3" data-path="probabilidad.html"><a href="probabilidad.html#curvas-de-densidad"><i class="fa fa-check"></i><b>3.3</b> Curvas de densidad</a></li>
<li class="chapter" data-level="3.4" data-path="probabilidad.html"><a href="probabilidad.html#distribución-binomial"><i class="fa fa-check"></i><b>3.4</b> Distribución binomial</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="probabilidad.html"><a href="probabilidad.html#media-y-desviación-estándar-de-la-distribución-binomial"><i class="fa fa-check"></i><b>3.4.1</b> Media y desviación estándar de la distribución binomial</a></li>
<li class="chapter" data-level="3.4.2" data-path="probabilidad.html"><a href="probabilidad.html#distribución-binomial-en-r"><i class="fa fa-check"></i><b>3.4.2</b> Distribución binomial en R</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="probabilidad.html"><a href="probabilidad.html#distribución-normal"><i class="fa fa-check"></i><b>3.5</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="probabilidad.html"><a href="probabilidad.html#distribución-normal-en-r"><i class="fa fa-check"></i><b>3.5.1</b> Distribución normal en R</a></li>
<li class="chapter" data-level="3.5.2" data-path="probabilidad.html"><a href="probabilidad.html#pruebas-de-normalidad-en-r"><i class="fa fa-check"></i><b>3.5.2</b> Pruebas de normalidad en R</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="probabilidad.html"><a href="probabilidad.html#distribución-muestral"><i class="fa fa-check"></i><b>3.6</b> Distribución muestral</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="probabilidad.html"><a href="probabilidad.html#poblaciones-muestras-y-distribuciones-muestrales"><i class="fa fa-check"></i><b>3.6.1</b> Poblaciones, muestras y distribuciones muestrales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html"><i class="fa fa-check"></i><b>4</b> Estadística inferencial</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#error-estándar-de-la-media"><i class="fa fa-check"></i><b>4.1</b> Error estándar de la media</a></li>
<li class="chapter" data-level="4.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>4.2</b> Intervalo de confianza para <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#distribución-t-de-student"><i class="fa fa-check"></i><b>4.2.1</b> Distribución <span class="math inline">\(t\)</span> de Student</a></li>
<li class="chapter" data-level="4.2.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#construcción-de-un-intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>4.2.2</b> Construcción de un intervalo de confianza para <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="4.2.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalos-de-confianza-unilaterales"><i class="fa fa-check"></i><b>4.2.3</b> Intervalos de confianza unilaterales</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-de-dos-medias"><i class="fa fa-check"></i><b>4.3</b> Comparación de dos medias</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalo-de-confianza-para-mu_1---mu_2"><i class="fa fa-check"></i><b>4.3.1</b> Intervalo de confianza para <span class="math inline">\(\mu_1 - \mu_2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#pruebas-de-hipótesis"><i class="fa fa-check"></i><b>4.4</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#t-test"><i class="fa fa-check"></i><b>4.4.1</b> <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="4.4.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#t-test-de-una-cola"><i class="fa fa-check"></i><b>4.4.2</b> <span class="math inline">\(t\)</span> test de una cola</a></li>
<li class="chapter" data-level="4.4.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#tamaño-de-efecto"><i class="fa fa-check"></i><b>4.4.3</b> Tamaño de efecto</a></li>
<li class="chapter" data-level="4.4.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-wilcoxon-mann-whitney"><i class="fa fa-check"></i><b>4.4.4</b> Prueba de Wilcoxon-Mann-Whitney</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-de-muestras-pareadas"><i class="fa fa-check"></i><b>4.5</b> Comparación de muestras pareadas</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-t-pareada"><i class="fa fa-check"></i><b>4.5.1</b> Prueba de <span class="math inline">\(t\)</span> pareada</a></li>
<li class="chapter" data-level="4.5.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-signos"><i class="fa fa-check"></i><b>4.5.2</b> Prueba de signos</a></li>
<li class="chapter" data-level="4.5.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-rangos-con-signos-de-wilcoxon"><i class="fa fa-check"></i><b>4.5.3</b> Prueba de rangos con signos de Wilcoxon</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html"><i class="fa fa-check"></i><b>5</b> Inferencia de datos categóricos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#distribuciones-de-una-muestra"><i class="fa fa-check"></i><b>5.1</b> Distribuciones de una muestra</a></li>
<li class="chapter" data-level="5.2" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-de-chi-cuadrada"><i class="fa fa-check"></i><b>5.2</b> Prueba de Chi-cuadrada</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#hipótesis-compuestas-y-direccionales"><i class="fa fa-check"></i><b>5.2.1</b> Hipótesis compuestas y direccionales</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-de-chi-cuadrada-para-tablas-de-contingencia"><i class="fa fa-check"></i><b>5.3</b> Prueba de Chi-cuadrada para tablas de contingencia</a></li>
<li class="chapter" data-level="5.4" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#interpretación-de-las-tablas-de-contingencia"><i class="fa fa-check"></i><b>5.4</b> Interpretación de las tablas de contingencia</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#cuestiones-acerca-de-las-columnas-y-filas"><i class="fa fa-check"></i><b>5.4.1</b> Cuestiones acerca de las columnas y filas</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-exacta-de-fisher"><i class="fa fa-check"></i><b>5.5</b> Prueba exacta de Fisher</a></li>
<li class="chapter" data-level="5.6" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#tablas-de-contingencia-r-times-k"><i class="fa fa-check"></i><b>5.6</b> Tablas de contingencia <span class="math inline">\(r \times k\)</span></a></li>
<li class="chapter" data-level="5.7" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#intervalos-de-confianza-para-la-diferencia-entre-probabilidades"><i class="fa fa-check"></i><b>5.7</b> Intervalos de confianza para la diferencia entre probabilidades</a></li>
<li class="chapter" data-level="5.8" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#datos-pareados-en-tablas-2x2"><i class="fa fa-check"></i><b>5.8</b> Datos pareados en tablas 2x2</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html"><i class="fa fa-check"></i><b>6</b> Modelado de relaciones</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#análisis-de-varianza-anova"><i class="fa fa-check"></i><b>6.1</b> Análisis de Varianza (ANOVA)</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#variación-dentro-de-los-grupos"><i class="fa fa-check"></i><b>6.1.1</b> Variación dentro de los grupos</a></li>
<li class="chapter" data-level="6.1.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#variación-entre-los-grupos"><i class="fa fa-check"></i><b>6.1.2</b> Variación entre los grupos</a></li>
<li class="chapter" data-level="6.1.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#una-relación-importante-en-el-anova"><i class="fa fa-check"></i><b>6.1.3</b> Una relación importante en el ANOVA</a></li>
<li class="chapter" data-level="6.1.4" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#tabla-de-anova"><i class="fa fa-check"></i><b>6.1.4</b> Tabla de ANOVA</a></li>
<li class="chapter" data-level="6.1.5" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#modelo-del-anova"><i class="fa fa-check"></i><b>6.1.5</b> Modelo del ANOVA</a></li>
<li class="chapter" data-level="6.1.6" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#distribución-de-f"><i class="fa fa-check"></i><b>6.1.6</b> Distribución de <span class="math inline">\(F\)</span></a></li>
<li class="chapter" data-level="6.1.7" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#prueba-de-f"><i class="fa fa-check"></i><b>6.1.7</b> Prueba de <span class="math inline">\(F\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diseño-por-bloques-aleatorizados"><i class="fa fa-check"></i><b>6.2</b> Diseño por bloques aleatorizados</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#creando-los-bloques"><i class="fa fa-check"></i><b>6.2.1</b> Creando los bloques</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#anova-de-dos-vías"><i class="fa fa-check"></i><b>6.3</b> ANOVA de dos vías</a></li>
<li class="chapter" data-level="6.4" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#combinaciones-lineales-de-las-medias"><i class="fa fa-check"></i><b>6.4</b> Combinaciones lineales de las medias</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#contrastes"><i class="fa fa-check"></i><b>6.4.1</b> Contrastes</a></li>
<li class="chapter" data-level="6.4.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>6.4.2</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="6.4.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#prueba-de-t"><i class="fa fa-check"></i><b>6.4.3</b> Prueba de <span class="math inline">\(t\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#pruebas-post-hoc"><i class="fa fa-check"></i><b>6.5</b> Pruebas post hoc</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diferencia-menos-significativa-de-fisher-lsd"><i class="fa fa-check"></i><b>6.5.1</b> Diferencia menos significativa de Fisher (LSD)</a></li>
<li class="chapter" data-level="6.5.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diferencia-significativa-honesta-de-tukey-hsd"><i class="fa fa-check"></i><b>6.5.2</b> Diferencia significativa honesta de Tukey (HSD)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html"><i class="fa fa-check"></i><b>7</b> Correlación y regresión lineal</a>
<ul>
<li class="chapter" data-level="7.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-coeficiente-de-correlación-r"><i class="fa fa-check"></i><b>7.1</b> El coeficiente de correlación <span class="math inline">\(r\)</span></a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#midiendo-la-fuerza-de-la-asociación"><i class="fa fa-check"></i><b>7.1.1</b> Midiendo la fuerza de la asociación</a></li>
<li class="chapter" data-level="7.1.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#inferencia-acerca-de-la-correlación"><i class="fa fa-check"></i><b>7.1.2</b> Inferencia acerca de la correlación</a></li>
<li class="chapter" data-level="7.1.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalo-de-confianza-para-rho"><i class="fa fa-check"></i><b>7.1.3</b> Intervalo de confianza para <span class="math inline">\(\rho\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#regresión-lineal"><i class="fa fa-check"></i><b>7.2</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#la-línea-sd"><i class="fa fa-check"></i><b>7.2.1</b> La línea SD</a></li>
<li class="chapter" data-level="7.2.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#ecuación-de-la-regresión-lineal"><i class="fa fa-check"></i><b>7.2.2</b> Ecuación de la regresión lineal</a></li>
<li class="chapter" data-level="7.2.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#gráfica-de-promedios"><i class="fa fa-check"></i><b>7.2.3</b> Gráfica de promedios</a></li>
<li class="chapter" data-level="7.2.4" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#la-suma-de-cuadrados-de-los-residuales"><i class="fa fa-check"></i><b>7.2.4</b> La suma de cuadrados de los residuales</a></li>
<li class="chapter" data-level="7.2.5" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#desviación-estándar-de-los-residuales"><i class="fa fa-check"></i><b>7.2.5</b> Desviación estándar de los residuales</a></li>
<li class="chapter" data-level="7.2.6" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-coeficiente-de-determinación"><i class="fa fa-check"></i><b>7.2.6</b> El coeficiente de determinación</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-model-lineal"><i class="fa fa-check"></i><b>7.3</b> El model lineal</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#estmiaciones-del-modelo-lineal"><i class="fa fa-check"></i><b>7.3.1</b> Estmiaciones del modelo lineal</a></li>
<li class="chapter" data-level="7.3.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#interpolación-en-el-modelo-lineal"><i class="fa fa-check"></i><b>7.3.2</b> Interpolación en el modelo lineal</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#inferencia-estadística-respecto-de-beta_1"><i class="fa fa-check"></i><b>7.4</b> Inferencia estadística respecto de <span class="math inline">\(\beta_1\)</span></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-error-estándar-de-b_1"><i class="fa fa-check"></i><b>7.4.1</b> El error estándar de <span class="math inline">\(b_1\)</span></a></li>
<li class="chapter" data-level="7.4.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalo-de-confianza-para-beta_1"><i class="fa fa-check"></i><b>7.4.2</b> Intervalo de confianza para <span class="math inline">\(\beta_1\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#prueba-de-hipótesis-para-h_0-beta_1-0"><i class="fa fa-check"></i><b>7.5</b> Prueba de hipótesis para <span class="math inline">\(H_0: \beta_1 = 0\)</span></a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#gráficos-de-residuales"><i class="fa fa-check"></i><b>7.5.1</b> Gráficos de residuales</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalos-de-confianza-y-de-predicción"><i class="fa fa-check"></i><b>7.6</b> Intervalos de confianza y de predicción</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#computando-los-intervalos"><i class="fa fa-check"></i><b>7.6.1</b> Computando los intervalos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografia</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso de R básico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="correlación-y-regresión-lineal" class="section level1" number="7">
<h1><span class="header-section-number">Lección 7</span> Correlación y regresión lineal</h1>
<p>La <strong>correlación lineal</strong> y <strong>regresión lineal</strong> son técnicas basadas en ajustar una línea recta a nuestros datos. Estos análisis usualmente consisten de un par de observaciones (<span class="math inline">\(X, Y\)</span>).</p>
<blockquote>
<p><strong>Ejemplo:</strong> La anfetamina es una droga que suprime el apetito. En un estudio, investigadores alocaron aleatoriamente a 24 ratas a tres distintos grupos de tratamientos para recibir una inyección de anfetamina a distintas dosis y una inyección con solución salina. Se midió la cantidad de comida consumida por cada animal 3 horas después de la inyección. Los resultados (g de comida consumidos por kg de peso) se muestran en la siguiente tabla.</p>
</blockquote>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:anf1">Tabla 7.1: </span>Consumo de comida (Y) de las ratas (g/kg). X = Dosis de anfetamina (mg/kg)
</caption>
<thead>
<tr>
<th style="text-align:center;">
X = 0
</th>
<th style="text-align:center;">
X = 2.5
</th>
<th style="text-align:center;">
X = 5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 5cm; ">
112.6
</td>
<td style="text-align:center;min-width: 5cm; ">
73.3
</td>
<td style="text-align:center;min-width: 5cm; ">
38.5
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5cm; ">
102.1
</td>
<td style="text-align:center;min-width: 5cm; ">
84.8
</td>
<td style="text-align:center;min-width: 5cm; ">
81.3
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5cm; ">
90.2
</td>
<td style="text-align:center;min-width: 5cm; ">
67.3
</td>
<td style="text-align:center;min-width: 5cm; ">
57.1
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5cm; ">
81.5
</td>
<td style="text-align:center;min-width: 5cm; ">
55.3
</td>
<td style="text-align:center;min-width: 5cm; ">
62.3
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5cm; ">
105.6
</td>
<td style="text-align:center;min-width: 5cm; ">
80.7
</td>
<td style="text-align:center;min-width: 5cm; ">
51.5
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5cm; ">
93.0
</td>
<td style="text-align:center;min-width: 5cm; ">
90.0
</td>
<td style="text-align:center;min-width: 5cm; ">
48.3
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5cm; ">
106.6
</td>
<td style="text-align:center;min-width: 5cm; ">
75.5
</td>
<td style="text-align:center;min-width: 5cm; ">
42.7
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5cm; ">
108.3
</td>
<td style="text-align:center;min-width: 5cm; ">
77.1
</td>
<td style="text-align:center;min-width: 5cm; ">
57.9
</td>
</tr>
</tbody>
</table>
<p>A continuación tenemos una <strong>gráfica de dispersión</strong> con los valores de la tabla <a href="correlación-y-regresión-lineal.html#tab:anf1">7.1</a>.</p>
<p><img src="Curso_R_basico_files/figure-html/anf2-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Este es un ejemplo de dos variables que se encuentran en pares (Consumo de comida y dosis de anfetamina).</p>
<div id="el-coeficiente-de-correlación-r" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> El coeficiente de correlación <span class="math inline">\(r\)</span></h2>
<p>Supongamos que tenemos <span class="math inline">\(n\)</span> número de par de observaciones, con cada par representado por dos variables, <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span>. Si realizamos un gráfico de dispersión y vemos una tendencia lineal general, es natural intentar describir la fuerza de la asociación. Para realizar esto utilizamos el <strong>coeficiente de correlación.</strong></p>
<blockquote>
<p><strong>Ejemplo:</strong> En un estudio de una población silvestre de la serpiente <em>Vipera bertis</em>, investigadores capturaron y midieron nueve hembras adultas. Se midió su peso así como su longitud. Estos valores se muestran en la tabla <a href="correlación-y-regresión-lineal.html#tab:snake1">7.2</a> y en el gráfico de dispersión de la figura <a href="correlación-y-regresión-lineal.html#fig:snake2">7.1</a>.</p>
</blockquote>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:snake1">Tabla 7.2: </span>Longitud (X, en cm) y peso (Y, en g) de serpientes hembra
</caption>
<thead>
<tr>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
Longitud (cm)
</th>
<th style="text-align:center;">
Peso (g)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
60.0
</td>
<td style="text-align:center;min-width: 4cm; ">
136.0
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
69.0
</td>
<td style="text-align:center;min-width: 4cm; ">
198.0
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
66.0
</td>
<td style="text-align:center;min-width: 4cm; ">
194.0
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
64.0
</td>
<td style="text-align:center;min-width: 4cm; ">
140.0
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
54.0
</td>
<td style="text-align:center;min-width: 4cm; ">
93.0
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
67.0
</td>
<td style="text-align:center;min-width: 4cm; ">
172.0
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
59.0
</td>
<td style="text-align:center;min-width: 4cm; ">
116.0
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
65.0
</td>
<td style="text-align:center;min-width: 4cm; ">
174.0
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;min-width: 4cm; ">
63.0
</td>
<td style="text-align:center;min-width: 4cm; ">
145.0
</td>
</tr>
<tr>
<td style="text-align:center;">
Media
</td>
<td style="text-align:center;min-width: 4cm; ">
63.0
</td>
<td style="text-align:center;min-width: 4cm; ">
152.0
</td>
</tr>
<tr>
<td style="text-align:center;">
SD
</td>
<td style="text-align:center;min-width: 4cm; ">
4.6
</td>
<td style="text-align:center;min-width: 4cm; ">
35.3
</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span id="fig:snake2"></span>
<img src="Curso_R_basico_files/figure-html/snake2-1.png" alt="Regresión lineal del peso y longitud de 9 serpientes hembra." width="480" />
<p class="caption">
Figura 7.1: Regresión lineal del peso y longitud de 9 serpientes hembra.
</p>
</div>
<p>Como podemos ver, parece ser que existe una <strong>asociación positiva</strong> entre la longitud y el peso de las serpientes. Por lo tanto, si una serpiente es más larga que el promedio <span class="math inline">\(\overline{x} = 63\)</span> también tenderá a ser más pesada que el promedio <span class="math inline">\(\overline{y} = 152\)</span>. La línea que tenemos en el gráfico se conoce como <strong>línea de cuadrados mínimos</strong> o <strong>regresión lineal ajustada</strong> de <span class="math inline">\(Y\)</span> en <span class="math inline">\(X\)</span>.</p>
<div id="midiendo-la-fuerza-de-la-asociación" class="section level3" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Midiendo la fuerza de la asociación</h3>
<p>Para medir la fuerza de nuestra asociación utilizamos el <strong>coeficiente de correlación</strong>, <span class="math inline">\(r\)</span>. Carece de escala por lo que no es afectado por cambios en las unidades de medición. Para entender su funcionamiento, consideremos los datos de las serpientes transformados en valores <span class="math inline">\(Z\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:snake3"></span>
<img src="Curso_R_basico_files/figure-html/snake3-1.png" alt="Gráfico de dispersión de la longitud estandarizada contra el peso estandarizado." width="576" />
<p class="caption">
Figura 7.2: Gráfico de dispersión de la longitud estandarizada contra el peso estandarizado.
</p>
</div>
<p>Como podemos ver en la gráfica, la mayoría de nuestros puntos caen en el cuadrante superior derecho y el inferior izquierdo. Los puntos que caigan en estos cuadrantes tendrán valores <span class="math inline">\(Z\)</span> cuyos productos (<span class="math inline">\(z_x z_y\)</span>) son positivos. De igual manera, cualquier punto que caiga en el cuadrante superior izquierdo e inferior derecho tendrá valores <span class="math inline">\(Z\)</span> cuyos productos serán negativos.</p>
<p>En nuestro caso, existe una <strong>asociación positiva</strong> entre la longitud y el peso de las serpientes, ya que la mayoría de nuestros puntos caen en cuadrantes con productos positivos, por ende, la suma de los productos estandarizados dará un valor positivo. Si no existiera una relación lineal en nuestros datos, los puntos estarían distribuidos de manera aleatoria en los cuadrantes y la suma de los productos sería 0.</p>
<p>De hecho, el coeficiente de correlación está basado en esta suma. Se computa como el promedio de los productos de los valores estandarizados y se obtiene de la siguiente manera:</p>
<p><span class="math display" id="eq:corr">\[\begin{equation}
r = \frac{1}{n - 1}\sum_{i=1}^n (\frac{x_i - \overline{x}}{s_x})(\frac{y_i - \overline{y}}{s_y})
\tag{7.1}
\end{equation}\]</span></p>
<p>Afortunadamente en <code>R</code> podemos obtener este coeficiente sin necesidad de hacer todas las transformaciones y operaciones correspondientes, simplemente utilizamos la función <code>cor()</code> en nuestros datos.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="correlación-y-regresión-lineal.html#cb279-1" aria-hidden="true" tabindex="-1"></a>Longitud <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">69</span>, <span class="dv">66</span>, <span class="dv">64</span>, <span class="dv">54</span>, <span class="dv">67</span>, <span class="dv">59</span>, <span class="dv">65</span>, <span class="dv">63</span>)</span>
<span id="cb279-2"><a href="correlación-y-regresión-lineal.html#cb279-2" aria-hidden="true" tabindex="-1"></a>Peso <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">136</span>, <span class="dv">198</span>, <span class="dv">194</span>, <span class="dv">140</span>, <span class="dv">93</span>, <span class="dv">172</span>, <span class="dv">116</span>, <span class="dv">174</span>, <span class="dv">145</span>)</span>
<span id="cb279-3"><a href="correlación-y-regresión-lineal.html#cb279-3" aria-hidden="true" tabindex="-1"></a>Serpientes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Longitud, Peso)</span>
<span id="cb279-4"><a href="correlación-y-regresión-lineal.html#cb279-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb279-5"><a href="correlación-y-regresión-lineal.html#cb279-5" aria-hidden="true" tabindex="-1"></a>Serpientes</span></code></pre></div>
<pre><code>##   Longitud Peso
## 1       60  136
## 2       69  198
## 3       66  194
## 4       64  140
## 5       54   93
## 6       67  172
## 7       59  116
## 8       65  174
## 9       63  145</code></pre>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="correlación-y-regresión-lineal.html#cb281-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Serpientes<span class="sc">$</span>Longitud, Serpientes<span class="sc">$</span>Peso)</span></code></pre></div>
<pre><code>## [1] 0.9436756</code></pre>
<p>Es importante que tengamos los datos arreglados en dos columnas, una con la variable <span class="math inline">\(x\)</span> (por ejemplo, longitud) y la otra con la variable <span class="math inline">\(y\)</span> (por ejemplo, peso). Como podemos ver, nuestro coeficiente <span class="math inline">\(r = 0.9437\)</span> lo que indica una fuerte correlación lineal. Normalmente, el valor de <span class="math inline">\(r\)</span> se sitúa entre -1 y 1. Valores cercanos a 1 indican una correlación positiva, como en el caso de las serpientes, mientras que valores cercanos a -1 indican una correlación negativa. Valores cercanos a 0 indican ausencia de correlación lineal (los datos pueden estar correlacionados de otras maneras).</p>
<p>En caso de nuestra muestra, nos referimos a este coeficiente como la <strong>correlación muestral,</strong> ya que las medidas tomadas de estas 9 serpientes componen una muestra de una población más grande. Es decir nosotros estamos estimando la <strong>correlación poblacional,</strong> normalmente denotada con el símbolo <span class="math inline">\(\rho\)</span> (léase rho). Debe considerarse que, para que nuestro coeficiente <span class="math inline">\(r\)</span> pueda ser utilizado como una estimación de <span class="math inline">\(\rho\)</span>, tanto los valores de <span class="math inline">\(X\)</span> como <span class="math inline">\(Y\)</span> deben de ser seleccionados de manera aleatoria siguiendo el <strong>modelo de muestreo aleatorio bivariado,</strong> donde cada par de observaciones (<span class="math inline">\(x_i, y_i\)</span>) se considera una muestra aleatoria tomada a partir de una población (<span class="math inline">\(x, y\)</span>) de pares.</p>
<p>En este modelo, los valores observados de <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span> se toman como muestras aleatorias, así que los valores <span class="math inline">\(\overline{x}, \overline{y}, s_x\)</span> y <span class="math inline">\(s_y\)</span> son estimados de los valores poblacionales correspondientes, <span class="math inline">\(\mu_x, \mu_y, \sigma_x\)</span> y <span class="math inline">\(\sigma_y\)</span>. Aunque este modelo es razonable para muchos investigadores, quienes no lo consideran así, especialmente cuando cuando los valores de <span class="math inline">\(X\)</span> son especificados por el investigador, como en el caso de las ratas y las anfetaminas. Este modelo se conoce como <strong>modelo de submuestreo aleatorio.</strong></p>
</div>
<div id="inferencia-acerca-de-la-correlación" class="section level3" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Inferencia acerca de la correlación</h3>
<p>Ya hemos visto como el coeficiente de correlación nos sirve para describir un conjunto de datos. Ahora consideraremos la estadística inferencial basada en <span class="math inline">\(r\)</span> para los datos de este modelo.</p>
<p>Consideremos que cualquier patrón o tendencia aparente en nuestros datos es meramente ilusoria y que solamente refleja la variabilidad de nuestros datos. Para estos casos, <span class="math inline">\(H_0: X \space y \space Y no \space están \space correlacionadas\ space en \space la \space población\)</span> o de manera alterna, <span class="math inline">\(H_0: no \space existe \space correlación \space linear \space entre \space X \space y \space Y\)</span>. ¿Cómo podemos probar esto?</p>
<p>Podemos realizar una prueba de <span class="math inline">\(t\)</span>. En este caso la fórmula para calcular nuestro estadístico es la siguiente:</p>
<p><span class="math display" id="eq:corrt">\[\begin{equation}
t_s = r\sqrt{\frac{n-2}{1-r^2}}
\tag{7.2}
\end{equation}\]</span></p>
<p>Para este caso los grados de libertad <span class="math inline">\(df\)</span> se obtienen así:</p>
<p><span class="math display" id="eq:corrdf">\[\begin{equation}
df = n - 2
\tag{7.3}
\end{equation}\]</span></p>
<p>¿Por qué <span class="math inline">\(n-2\)</span>? Bueno, dos puntos cualesquiera determinan una linea recta, sin embargo, con esa cantidad de datos, <span class="math inline">\(n=2\)</span>, no obtenemos información acerca de la variabilidad inherente de los datos. Es hasta que observamos un tercer punto que podemos comenzar a estimar la fuerza de la correlación.</p>
<p>Para nuestros datos de las serpientes:</p>
<p><span class="math display">\[\begin{equation}
t_s = 0.9437 \sqrt{\frac{9 - 2}{1 - 0.9437^2}} = 7.549
\end{equation}\]</span></p>
<p>Ahora tendríamos que checar el valor crítico en nuestro valor de tablas o con la función de <span class="math inline">\(t\)</span>. Sin embargo, en <code>R</code> basta con utilizar la función <code>cor.test()</code> con los argumentos de nuestra correlación y obtenemos nuestro resultado, junto con nuestro valor-<em>p</em>.</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="correlación-y-regresión-lineal.html#cb283-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(Serpientes<span class="sc">$</span>Longitud, Serpientes<span class="sc">$</span>Peso)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Serpientes$Longitud and Serpientes$Peso
## t = 7.5459, df = 7, p-value = 0.0001321
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7489030 0.9883703
## sample estimates:
##       cor 
## 0.9436756</code></pre>
<p>Como podemos ver, hay una clara evidencia a favor de la correlación que estamos viendo pues nuestro <span class="math inline">\(valor-p &lt; 0.05\)</span> por lo que rechazaríamos la <span class="math inline">\(H_0\)</span> y diríamos que sí existe correlación lineal entre nuestras dos variables <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span>.</p>
</div>
<div id="intervalo-de-confianza-para-rho" class="section level3" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Intervalo de confianza para <span class="math inline">\(\rho\)</span></h3>
<p>Como vimos la función <code>cor.test()</code> nos construye el intervalo de confianza al 95% de nuestro valor para <span class="math inline">\(r\)</span>, es decir, podemos estar 95% seguros de que <span class="math inline">\(\rho\)</span> se encuentra entre <span class="math inline">\((0.749, 0.988)\)</span>. Sin embargo, veamos cómo se calcula esto de manera tradicional.</p>
<p>Si nuestro tamaño de muestra es suficientemente grande, podemos realizar la construcción del intervalo. Ya que la distribución muestral del coeficiente de correlación muestral, <span class="math inline">\(r\)</span>, se encuentra sesgada, aplicamos una transformación conocida como <strong>la transformación de Fisher:</strong></p>
<p><span class="math display">\[\begin{equation}
z_r = \frac{1}{2}\ln \left[{\frac{1+r}{1-r}}\right]
\end{equation}\]</span></p>
<p>Donde <span class="math inline">\(\ln\)</span> es un logaritmo natural base <span class="math inline">\(e\)</span>. Podemos construir el intervalo de confianza al 95% para este valor transformado <span class="math inline">\(\frac{1}{2}\ln \left[{\frac{1+\rho}{1-\rho}}\right]\)</span> de la siguiente manera:</p>
<p><span class="math display">\[\begin{equation}
z_r \pm 1.96 \frac{1}{\sqrt{n-3}}
\end{equation}\]</span></p>
<p>Debido a la transformación que hicimos, tenemos que convertir los limites de nuestro intervalo de confianza para <span class="math inline">\(\frac{1}{2}\ln \left[{\frac{1+r}{1-r}}\right]\)</span> a un intervalo de confianza para <span class="math inline">\(\rho\)</span>. Para hacer esto, resolvemos para <span class="math inline">\(\rho\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\frac{1}{2}\ln \left[{\frac{1+\rho}{1-\rho}}\right] = z_r \pm 1.96 \frac{1}{\sqrt{n-3}}
\end{equation}\]</span></p>
<p>En donde <span class="math inline">\(\rho\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\rho = \frac{e^{2(z_r - 1.96 \frac{1}{\sqrt{n-3}})}-1}{e^{2(z_r - 1.96 \frac{1}{\sqrt{n-3}})}+1} \\
\rho = \frac{e^{2(z_r + 1.96 \frac{1}{\sqrt{n-3}})}-1}{e^{2(z_r + 1.96 \frac{1}{\sqrt{n-3}})}+1}
\end{equation}\]</span></p>
<p>Intentemos hacer el cálculo para nuestros datos:</p>
<p><span class="math display">\[\begin{equation}
z_r = \frac{1}{2} \ln \left[ {\frac{1+0.9437}{1-0.9437}} \right] = \frac{1}{2} \ln \left[ {\frac{1.9437}{0.0563}} \right] = 1.77085
\end{equation}\]</span></p>
<p>Bien ya sabemos que nuestro valor <span class="math inline">\(z_r = 1.77085\)</span>, ahora debemos calcular el intervalo:</p>
<p><span class="math display">\[\begin{equation}
1.77085 \pm 1.96 \frac{1}{\sqrt{9-3}} \\
1.77085 \pm 0.8
\end{equation}\]</span></p>
<p>Entonces nuestros límites de nuestro intervalo para <span class="math inline">\(\frac{1}{2}\ln \left[{\frac{1+r}{1-r}}\right]\)</span> son <span class="math inline">\((0.971, 2.571)\)</span>, aproximadamente (tomando en cuenta los múltiples redondeos). Ahora simplemente transformamos el intervalo para <span class="math inline">\(\frac{1}{2}\ln \left[{\frac{1+r}{1-r}}\right]\)</span> en un intervalo para <span class="math inline">\(\rho\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\rho = \frac{e^{2(0.971)}-1}{e^{2(0.971)}+1} = 0.988 \\
\rho = \frac{e^{2(2.571)}-1}{e^{2(2.571)}+1} = 0.75
\end{equation}\]</span></p>
<p>Más o menos el valor estimado que obtuvimos con la función de <code>R</code> y como pudimos ver es más sencillo obtener el intervalo de confianza para <span class="math inline">\(\rho\)</span> utilizando el comando <code>cor.test()</code>, que corresponde a <span class="math inline">\((0.749, 0.988)\)</span>.</p>
</div>
</div>
<div id="regresión-lineal" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Regresión lineal</h2>
<p>En esta sección aprenderemos a encontrar e interpretar la línea que mejor se ajuste a nuestros datos.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Consideremos un conjunto de datos que tienen una relación linear perfecta entre <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span>, por ejemplo, la temperatura medida en <span class="math inline">\(X\)</span> = Celsius y <span class="math inline">\(Y\)</span> = Fahrenheit. Sabemos que la fórmula para transformar de grados Celsius a Fahrenheit es <span class="math inline">\(y = 32 + \frac{9}{5}x\)</span>, por lo que esta es la línea que describe esta relación.</p>
</blockquote>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="correlación-y-regresión-lineal.html#cb285-1" aria-hidden="true" tabindex="-1"></a>Celsius <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">12.3</span>, <span class="fl">12.8</span>, <span class="fl">13.2</span>, <span class="fl">13.8</span>, <span class="fl">14.5</span>, <span class="fl">14.9</span>, <span class="dv">15</span>, <span class="fl">15.1</span>, <span class="fl">15.2</span>, <span class="fl">15.25</span>, <span class="fl">15.6</span>, <span class="fl">15.7</span>, <span class="fl">16.1</span>, <span class="fl">16.3</span>, <span class="fl">16.5</span>, <span class="dv">17</span>, <span class="fl">17.1</span>, <span class="fl">17.7</span>, <span class="fl">17.8</span>, <span class="fl">17.85</span>)</span>
<span id="cb285-2"><a href="correlación-y-regresión-lineal.html#cb285-2" aria-hidden="true" tabindex="-1"></a>Fahrenheit <span class="ot">&lt;-</span> Celsius<span class="sc">*</span>(<span class="dv">9</span><span class="sc">/</span><span class="dv">5</span>) <span class="sc">+</span> <span class="dv">32</span></span>
<span id="cb285-3"><a href="correlación-y-regresión-lineal.html#cb285-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb285-4"><a href="correlación-y-regresión-lineal.html#cb285-4" aria-hidden="true" tabindex="-1"></a>Temperatura <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Celsius, Fahrenheit)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-188">Tabla 7.3: </span>Grados Celsius °C contra grados Fahrenheit °F
</caption>
<thead>
<tr>
<th style="text-align:center;">
°C
</th>
<th style="text-align:center;">
°F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 4cm; ">
12.30
</td>
<td style="text-align:center;min-width: 4cm; ">
54.14
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
12.80
</td>
<td style="text-align:center;min-width: 4cm; ">
55.04
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
13.20
</td>
<td style="text-align:center;min-width: 4cm; ">
55.76
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
13.80
</td>
<td style="text-align:center;min-width: 4cm; ">
56.84
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
14.50
</td>
<td style="text-align:center;min-width: 4cm; ">
58.10
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
14.90
</td>
<td style="text-align:center;min-width: 4cm; ">
58.82
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
15.00
</td>
<td style="text-align:center;min-width: 4cm; ">
59.00
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
15.10
</td>
<td style="text-align:center;min-width: 4cm; ">
59.18
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
15.20
</td>
<td style="text-align:center;min-width: 4cm; ">
59.36
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
15.25
</td>
<td style="text-align:center;min-width: 4cm; ">
59.45
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
15.60
</td>
<td style="text-align:center;min-width: 4cm; ">
60.08
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
15.70
</td>
<td style="text-align:center;min-width: 4cm; ">
60.26
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
16.10
</td>
<td style="text-align:center;min-width: 4cm; ">
60.98
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
16.30
</td>
<td style="text-align:center;min-width: 4cm; ">
61.34
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
16.50
</td>
<td style="text-align:center;min-width: 4cm; ">
61.70
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
17.00
</td>
<td style="text-align:center;min-width: 4cm; ">
62.60
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
17.10
</td>
<td style="text-align:center;min-width: 4cm; ">
62.78
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
17.70
</td>
<td style="text-align:center;min-width: 4cm; ">
63.86
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
17.80
</td>
<td style="text-align:center;min-width: 4cm; ">
64.04
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
17.85
</td>
<td style="text-align:center;min-width: 4cm; ">
64.13
</td>
</tr>
</tbody>
</table>
<p>La siguiente tabla muestra la relación entre las dos variables.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-189"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-189-1.png" alt="Gráfico de temperatura en °C contra °F" width="672" />
<p class="caption">
Figura 7.3: Gráfico de temperatura en °C contra °F
</p>
</div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-190">Tabla 7.4: </span>Media y desviación estándar de los datos de temperatura
</caption>
<thead>
<tr>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
°C
</th>
<th style="text-align:center;">
°F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
Media
</td>
<td style="text-align:center;min-width: 3cm; ">
15.48
</td>
<td style="text-align:center;min-width: 3cm; ">
59.87
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
SD
</td>
<td style="text-align:center;min-width: 3cm; ">
1.62
</td>
<td style="text-align:center;min-width: 3cm; ">
2.92
</td>
</tr>
</tbody>
</table>
<p>Como ambas variables están midiendo lo mismo, cuando el valor <span class="math inline">\(X\)</span> aumente en una desviación estándar (<span class="math inline">\(s_x = 1.62\)</span>), es lógico pensar que también el valor <span class="math inline">\(y\)</span> aumentará una desviación estándar (<span class="math inline">\(s_y = 2.92\)</span>). Combinados estos dos valores, se puede describir la pendiente que se ajusta perfectamente a los datos:</p>
<p><span class="math display">\[\begin{equation}
\frac{s_y}{s_x} = \frac{2.92}{1.62} = 1.80
\end{equation}\]</span></p>
<p>Ya conocíamos este valor antes, que equivale a la pendiente de <span class="math inline">\(\frac{9}{5} = 1.80\)</span> que vimos en la fórmula para convertir °C a °F.</p>
<div id="la-línea-sd" class="section level3" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> La línea SD</h3>
<p>Cuando existe una relación linear perfecta (<span class="math inline">\(r = \pm1\)</span>) la línea que se ajusta exactamente a los datos será <span class="math inline">\(\pm s_y/s_x\)</span>, con el signo de la pendiente correspondiendo al signo de la correlación y pasa a través del punto, (<span class="math inline">\(\overline{x}, \overline{y}\)</span>). Esta línea se le conoce como <strong>línea SD.</strong> Cuando no tenemos una correlación perfecta, la línea SD tiende a sobrestimar o infraestimar algunos valores.</p>
<p>Se puede demostrar, de manera matemática, que la línea que mejor se ajusta para predecir <span class="math inline">\(Y\)</span> es la llamada <strong>línea de cuadrados mínimos</strong> o <strong>regresión lineal ajustada,</strong> que tiene una pendiente igual a <span class="math inline">\(r(s_y/s_x)\)</span> y pasa por el punto (<span class="math inline">\(\overline{x},\overline{y}\)</span>). Es decir, por cada valor de <span class="math inline">\(X\)</span> que se encuentra a una desviación estándar por encima del promedio, el valor de la media de <span class="math inline">\(Y\)</span> solo estará <span class="math inline">\(r\)</span> desviaciones estándar encima del promedio (asumiendo que <span class="math inline">\(r\)</span> es positivo, si es negativo, entonces por cada valor <span class="math inline">\(X\)</span> una desviación estándar encima del promedio, el valor de la media <span class="math inline">\(Y\)</span> estará <span class="math inline">\(r\)</span> desviaciones estándar debajo del promedio).</p>
</div>
<div id="ecuación-de-la-regresión-lineal" class="section level3" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Ecuación de la regresión lineal</h3>
<p>La ecuación para una recta se puede escribir de la siguiente manera:</p>
<p><span class="math display" id="eq:recta">\[\begin{equation}
Y = b_0 + b_1X
\tag{7.4}
\end{equation}\]</span></p>
<p>Donde <span class="math inline">\(b_0\)</span> es el intercepto de <span class="math inline">\(y\)</span> y <span class="math inline">\(b_1\)</span> es la pendiente de la línea. <span class="math inline">\(b_1\)</span> también es la razón de cambio de <span class="math inline">\(Y\)</span> con respecto de <span class="math inline">\(X\)</span>. La regresión lineal ajustada de <span class="math inline">\(Y\)</span> en <span class="math inline">\(X\)</span> se escribe <span class="math inline">\(\hat{y} = b_0 + b_1x\)</span>. Escribimos <span class="math inline">\(\hat{y}\)</span> para recordar que la línea nos está dando solamente un estimado o predicción de los valores de <span class="math inline">\(Y\)</span>. La pendiente y el intercepto de la linea de regresión de los cuadrados mínimos se calcula a partir de los datos de la siguiente manera:</p>
<p><span class="math display" id="eq:slope">\[\begin{equation}
Pendiente: b_1 = r(\frac{s_y}{s_x})
\tag{7.5}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:incercept">\[\begin{equation}
Intercepto: b_0 = \overline{y} - b_1\overline{x}
\tag{7.6}
\end{equation}\]</span></p>
<p>Por ejemplo, para nuestros datos de las serpientes, podemos encontrar la pendiente con nuestro coeficiente de correlación <span class="math inline">\(r\)</span> multiplicado por las desviaciones estándar de los datos de peso y longitud (4.6 y 35.3 respectivamente).</p>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-191">Tabla 7.5: </span>Media y desviación estándar de la longitud y peso de serpientes
</caption>
<thead>
<tr>
<th style="text-align:center;">
</th>
<th style="text-align:center;">
Longitud (cm)
</th>
<th style="text-align:center;">
Peso (g)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3.5cm; ">
Media
</td>
<td style="text-align:center;min-width: 3.5cm; ">
63.0
</td>
<td style="text-align:center;min-width: 3.5cm; ">
152.0
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3.5cm; ">
SD
</td>
<td style="text-align:center;min-width: 3.5cm; ">
4.6
</td>
<td style="text-align:center;min-width: 3.5cm; ">
35.3
</td>
</tr>
</tbody>
</table>
<p>Por ende, <span class="math inline">\(s_x = 4.6\)</span> y <span class="math inline">\(s_y = 35.3\)</span>. Además sabíamos que para estos datos, <span class="math inline">\(r = 0.9437\)</span>. Tenemos todos los elementos para encontrar nuestra pendiente <span class="math inline">\(b_1\)</span> y nuestro intercepto <span class="math inline">\(b_0\)</span>.</p>
<p><span class="math display">\[\begin{equation}
r(s_y/s_x) = 0.9437 \times (35.337/4.637) = 7.1916
\end{equation}\]</span></p>
<p>Lo que equivale a un cambio de 7.1916 g/cm. Es decir que un incremento en la longitud de una serpiente de 1 cm trae consigo un aumento en su peso de cerca de 7.1916 g. Usando estos valores podemos encontrar el intercepto de <span class="math inline">\(Y\)</span>.</p>
<p><span class="math display">\[\begin{equation}
b_0 = 152 - 7.7976 \times 63 = -301.08
\end{equation}\]</span></p>
<p>Por ende, nuestra línea de regresión ajustada es <span class="math inline">\(\hat{y} = -301.08 + 7.1916x\)</span>.</p>
</div>
<div id="gráfica-de-promedios" class="section level3" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Gráfica de promedios</h3>
<p>Si tenemos varias observaciones de <span class="math inline">\(Y\)</span> en un nivel dado de <span class="math inline">\(X\)</span>, como el caso del ejemplo de las anfetaminas y ratas, podemos estimar la media de la población <span class="math inline">\(Y\)</span> para un valor dado de <span class="math inline">\(X\)</span> (<span class="math inline">\(\mu_{Y|X}\)</span>) simplemente usando la media muestral de <span class="math inline">\(Y\)</span>, <span class="math inline">\(\overline{y}\)</span>, para ese valor dado de <span class="math inline">\(X\)</span>. Podemos denotar esta media muestral como <span class="math inline">\(\overline{y}|X\)</span>. Una gráfica de <span class="math inline">\(\overline{y}|X\)</span> se conoce como una <strong>gráfica de promedios,</strong> ya que muestra la media observada de <span class="math inline">\(Y\)</span> para distintos valores de <span class="math inline">\(X\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-192"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-192-1.png" alt="Gráfica de promedios con los promedios de cada observación de X marcados por una línea horizontal." width="672" />
<p class="caption">
Figura 7.4: Gráfica de promedios con los promedios de cada observación de X marcados por una línea horizontal.
</p>
</div>
<p>Donde las líneas horizontales en los distintos niveles de <span class="math inline">\(X\)</span> representan la media para este conjunto de datos. Si los valores de <span class="math inline">\(\overline{y}\)</span> en la gráfica de promedios encaja exactamente como una línea, entonces esa línea es la regresión linear y <span class="math inline">\(\mu_{Y|X}\)</span> es estimado a partir de <span class="math inline">\(\overline{y}|X\)</span>. Sin embargo, usualmente los valores de <span class="math inline">\(\overline{y}\)</span> no son colineares. En este caso, la regresión es una versión <em>suavizada</em> de la gráfica de promedios, resultado en un modelo de ajuste en el cual todos los estimados de <span class="math inline">\(\mu_{Y|X}\)</span> caen en una línea. La ventaja de este proceso es que utilizamos toda la información disponible de todas las observaciones para estimar <span class="math inline">\(\mu_{Y|X}\)</span> en cualquier nivel de <span class="math inline">\(X\)</span>.</p>
<p>Si aplicamos las fórmulas de regresión a nuestros datos de las ratas y las anfetaminas obtenemos que <span class="math inline">\(b_0 = 99.3\)</span> y <span class="math inline">\(b_1 = -9.01\)</span>. Entonces el estimado de <span class="math inline">\(\mu_{Y|X=0}\)</span> es <span class="math inline">\(99.3 \space g/kg\)</span>. Este valor es ligeramente distinto a <span class="math inline">\(\overline{y}|X = 0\)</span> de <span class="math inline">\(100 \space g/kg\)</span>. Este nuevo valor hace uso de los 8 datos obtenidos cuando <span class="math inline">\(X = 0\)</span> pero también de la tendencia lineal establecida por los otros 16 valores. De igual manera, <span class="math inline">\(\mu_{Y|X=2.5}\)</span> es <span class="math inline">\(99.3 - 9.01 \times 2.5 = 76.78 \space g/kg\)</span>, que difiere ligeramente del valor <span class="math inline">\(\overline{y}|X=2.5\)</span> de <span class="math inline">\(75.5 \space g/kg\)</span> y <span class="math inline">\(\mu_{Y|X=5}\)</span> que es <span class="math inline">\(99.3-9.01 \times 5 = 54.25 \space g/kg\)</span>, que difiere ligeramente de <span class="math inline">\(\overline{y}|X=5\)</span> que tiene un valor de <span class="math inline">\(55.0 \space g/kg\)</span>. Este es, a grandes rasgos, el procedimiento por el cuál <em>suavizamos</em> una línea recta sobre un gráfico de promedios.</p>
</div>
<div id="la-suma-de-cuadrados-de-los-residuales" class="section level3" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> La suma de cuadrados de los residuales</h3>
<p>Ahora consideraremos un estadístico que describe la dispersión de los puntos respecto de la línea ajustada. Por cada valor <span class="math inline">\(x_i\)</span> de nuestros datos, existe una predicción del valor de <span class="math inline">\(Y\)</span> dado por <span class="math inline">\(\hat{y} = b_0 + b_1x_i\)</span>. Para encontrar nuestro valor predicho, simplemente utilizamos la fórmula de nuestra regresión:</p>
<p><span class="math display" id="eq:valpred">\[\begin{equation}
\hat{y}_i = b_0 + b_1x_i
\tag{7.7}
\end{equation}\]</span></p>
<p>Además, asociado a cada observación, existe una cantidad llamada <strong>residual,</strong> definida como:</p>
<p><span class="math display" id="eq:residual">\[\begin{equation}
e_i = y_i - \hat{y}_i
\tag{7.8}
\end{equation}\]</span></p>
<div class="figure" style="text-align: center"><span id="fig:resid"></span>
<img src="Curso_R_basico_files/figure-html/resid-1.png" alt="Residuales para los datos de longitud y peso de serpientes." width="480" />
<p class="caption">
Figura 7.5: Residuales para los datos de longitud y peso de serpientes.
</p>
</div>
<p>En este gráfico con los residuales de nuestros datos de las serpientes vemos que las líneas punteadas van desde nuestro valor observado hasta la línea de la regresión. La magnitud del residual corresponde al valor absoluto de la línea vertical. Los valores predichos <span class="math inline">\(\hat{y}_i\)</span> se encuentran en color azul en nuestra figura <a href="correlación-y-regresión-lineal.html#fig:resid">7.5</a>.</p>
<p>Lo que nos importa principalmente es qué tan cerca está el valor observado, <span class="math inline">\(y_i\)</span>, de su valor predicho, <span class="math inline">\(\hat{y}_i\)</span>. Por esto medimos la distancia vertical de cada punto hasta la línea ajustada. Una medida que engloba a estos valores es la <strong>suma de cuadrados de los residuales</strong> o <span class="math inline">\(SS(residuales)\)</span>, que se obtiene de la siguiente manera:</p>
<p><span class="math display" id="eq:residual2">\[\begin{equation}
SS(residuales) = \sum_{i=1}^n(y_i - \hat{y}_i)^2 = \sum_{i=1}^n e_i^2
\tag{7.9}
\end{equation}\]</span></p>
<p>La suma de cuadrados de los residuales será entonces más pequeña conforme mejor se ajuste la línea a nuestros datos. Veamos estos cálculos realizados con los datos de nuestras serpientes.</p>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-193">Tabla 7.6: </span>Residuales y valores predichos para los datos de serpientes
</caption>
<thead>
<tr>
<th style="text-align:center;">
<span class="math inline">\(x\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(y\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(\hat{y}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(y-\hat{y}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\((y-\hat{y})^2\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3cm; ">
60
</td>
<td style="text-align:center;min-width: 3cm; ">
136
</td>
<td style="text-align:center;min-width: 3cm; ">
130.42442
</td>
<td style="text-align:center;min-width: 3cm; ">
5.575581
</td>
<td style="text-align:center;min-width: 3cm; ">
31.087108
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
69
</td>
<td style="text-align:center;min-width: 3cm; ">
198
</td>
<td style="text-align:center;min-width: 3cm; ">
195.15116
</td>
<td style="text-align:center;min-width: 3cm; ">
2.848837
</td>
<td style="text-align:center;min-width: 3cm; ">
8.115873
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
66
</td>
<td style="text-align:center;min-width: 3cm; ">
194
</td>
<td style="text-align:center;min-width: 3cm; ">
173.57558
</td>
<td style="text-align:center;min-width: 3cm; ">
20.424419
</td>
<td style="text-align:center;min-width: 3cm; ">
417.156875
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
64
</td>
<td style="text-align:center;min-width: 3cm; ">
140
</td>
<td style="text-align:center;min-width: 3cm; ">
159.19186
</td>
<td style="text-align:center;min-width: 3cm; ">
-19.191861
</td>
<td style="text-align:center;min-width: 3cm; ">
368.327508
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
54
</td>
<td style="text-align:center;min-width: 3cm; ">
93
</td>
<td style="text-align:center;min-width: 3cm; ">
87.27326
</td>
<td style="text-align:center;min-width: 3cm; ">
5.726744
</td>
<td style="text-align:center;min-width: 3cm; ">
32.795599
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
67
</td>
<td style="text-align:center;min-width: 3cm; ">
172
</td>
<td style="text-align:center;min-width: 3cm; ">
180.76744
</td>
<td style="text-align:center;min-width: 3cm; ">
-8.767442
</td>
<td style="text-align:center;min-width: 3cm; ">
76.868037
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
59
</td>
<td style="text-align:center;min-width: 3cm; ">
116
</td>
<td style="text-align:center;min-width: 3cm; ">
123.23256
</td>
<td style="text-align:center;min-width: 3cm; ">
-7.232558
</td>
<td style="text-align:center;min-width: 3cm; ">
52.309897
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
65
</td>
<td style="text-align:center;min-width: 3cm; ">
174
</td>
<td style="text-align:center;min-width: 3cm; ">
166.38372
</td>
<td style="text-align:center;min-width: 3cm; ">
7.616279
</td>
<td style="text-align:center;min-width: 3cm; ">
58.007707
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3cm; ">
63
</td>
<td style="text-align:center;min-width: 3cm; ">
145
</td>
<td style="text-align:center;min-width: 3cm; ">
152.00000
</td>
<td style="text-align:center;min-width: 3cm; ">
-7.000000
</td>
<td style="text-align:center;min-width: 3cm; ">
49.000000
</td>
</tr>
</tbody>
</table>
<pre><code>## [1] 1093.669</code></pre>
<p>Donde <span class="math inline">\(x\)</span> es la longitud, <span class="math inline">\(y\)</span> el peso, <span class="math inline">\(\hat{y}\)</span> es el valor predicho de <span class="math inline">\(y\)</span> para un punto dado por <span class="math inline">\(x\)</span>, <span class="math inline">\(y-\hat{y}\)</span> son los residuales y <span class="math inline">\((y-\hat{y})^2\)</span> son los cuadrados de los residuales. Por lo tanto para nuestros datos <span class="math inline">\(SS(residuales) = 1093.669\)</span>.</p>
<p>El <strong>criterio de mínimos cuadrados</strong> se basa en que la mejor línea recta es aquella que minimiza la suma de cuadrados de los residuales al mínimo. Debido a esto, la línea de regresión lineal ajustada también es conocida como <strong>la línea de mínimos cuadrados.</strong></p>
</div>
<div id="desviación-estándar-de-los-residuales" class="section level3" number="7.2.5">
<h3><span class="header-section-number">7.2.5</span> Desviación estándar de los residuales</h3>
<p>Esta es una medida derivada de la <span class="math inline">\(SS(residuales)\)</span>, es más fácil de interpretar y se representa como <span class="math inline">\(s_e\)</span>.</p>
<p><span class="math display" id="eq:se">\[\begin{equation}
s_e = \sqrt{\frac{\sum_{i=1}^n(y_i - \hat{y}_i)^2}{n-2}} = \sqrt{\frac{\sum_{i=1}^ne_i^2}{n-2}} = \sqrt{\frac{SS(residuales)}{n-2}}
\tag{7.10}
\end{equation}\]</span></p>
<p>Esta <strong>desviación estándar de los residuales</strong> nos dice que tan arriba o debajo de la línea de regresión tienden a estar. Para nuestros datos de las serpientes tenemos la siguiente <span class="math inline">\(s_e\)</span>:</p>
<p><span class="math display">\[\begin{equation}
s_e = \sqrt{1093.669}{n-2} = 12.5
\end{equation}\]</span></p>
<p>Por lo tanto, la desviación estándar de los residuales (también conocido como error estándar de los residuales) nos da como resultado 12.5 g/cm. De nuestros datos, esperamos que el 68% de ellos se encuentren a <span class="math inline">\(\pm1 s _e\)</span> de la línea de regresión (de manera similar, el 95% de ellos se encontrará a <span class="math inline">\(\pm2s_e\)</span>).</p>
<p>¿Cómo podemos hacer estos cálculos con <code>R</code>? Bueno, recordemos nuestra variable <code>Serpientes</code> que habíamos creado anteriormente.</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="correlación-y-regresión-lineal.html#cb287-1" aria-hidden="true" tabindex="-1"></a>Serpientes</span></code></pre></div>
<pre><code>##   Longitud Peso
## 1       60  136
## 2       69  198
## 3       66  194
## 4       64  140
## 5       54   93
## 6       67  172
## 7       59  116
## 8       65  174
## 9       63  145</code></pre>
<p>A partir de esta variable podemos construir un modelo lineal utilizando la función <code>lm()</code>.</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="correlación-y-regresión-lineal.html#cb289-1" aria-hidden="true" tabindex="-1"></a>Regresion <span class="ot">&lt;-</span> <span class="fu">lm</span>(Peso <span class="sc">~</span> Longitud, Serpientes) <span class="co">#Crea el modelo lineal</span></span>
<span id="cb289-2"><a href="correlación-y-regresión-lineal.html#cb289-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Regresion)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Peso ~ Longitud, data = Serpientes)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -19.192  -7.233   2.849   5.727  20.424 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -301.0872    60.1885  -5.002 0.001561 ** 
## Longitud       7.1919     0.9531   7.546 0.000132 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.5 on 7 degrees of freedom
## Multiple R-squared:  0.8905, Adjusted R-squared:  0.8749 
## F-statistic: 56.94 on 1 and 7 DF,  p-value: 0.0001321</code></pre>
<p>Como podemos ver, nos da el valor de la desviación estándar residual, pero, ¿Cómo hacemos para ver los valores predichos? ¿O para ver los residuales? Para esto vamos a agregar dos columnas a nuestra variable con los datos de las serpientes. Utilizamos <code>predict()</code> para extraer los valores de <span class="math inline">\(\hat{y}\)</span> y <code>residuals()</code> para extraer los residuales.</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="correlación-y-regresión-lineal.html#cb291-1" aria-hidden="true" tabindex="-1"></a>Serpientes<span class="sc">$</span>Predicho <span class="ot">&lt;-</span> <span class="fu">predict</span>(Regresion) <span class="co">#Guarda los valores predichos</span></span>
<span id="cb291-2"><a href="correlación-y-regresión-lineal.html#cb291-2" aria-hidden="true" tabindex="-1"></a>Serpientes<span class="sc">$</span>Residuales <span class="ot">&lt;-</span> <span class="fu">residuals</span>(Regresion) <span class="co">#Guarda los residuales</span></span>
<span id="cb291-3"><a href="correlación-y-regresión-lineal.html#cb291-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb291-4"><a href="correlación-y-regresión-lineal.html#cb291-4" aria-hidden="true" tabindex="-1"></a>Serpientes</span></code></pre></div>
<pre><code>##   Longitud Peso  Predicho Residuales
## 1       60  136 130.42442   5.575581
## 2       69  198 195.15116   2.848837
## 3       66  194 173.57558  20.424419
## 4       64  140 159.19186 -19.191860
## 5       54   93  87.27326   5.726744
## 6       67  172 180.76744  -8.767442
## 7       59  116 123.23256  -7.232558
## 8       65  174 166.38372   7.616279
## 9       63  145 152.00000  -7.000000</code></pre>
</div>
<div id="el-coeficiente-de-determinación" class="section level3" number="7.2.6">
<h3><span class="header-section-number">7.2.6</span> El coeficiente de determinación</h3>
<p>Cuando elevamos <span class="math inline">\(r\)</span> al cuadrado, obtenemos información adicional de la regresión. El coeficiente de determinación, <span class="math inline">\(r^2\)</span>, describe la proporción de la varianza en <span class="math inline">\(Y\)</span> que es explicada por la relación lineal entre <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span>. El coeficiente de correlación <span class="math inline">\(r\)</span> obedece la siguiente aproximación:</p>
<p><span class="math display">\[\begin{equation}
r^2 \approx \frac{s_y^2-s_e^2}{s_y^2} = 1 - \frac{s_e^2}{s_y^2}
\end{equation}\]</span></p>
<p>El numerador <span class="math inline">\(s_y^2 - s_e^2\)</span> puede ser interpretado como la varianza total en <span class="math inline">\(Y\)</span> explicada por la línea de regresión. Si la línea de regresión se ajusta bien a los datos, entonces <span class="math inline">\(s_e^2\)</span> será cercano a 0, por lo que el numerador será cercano a <span class="math inline">\(s_y^2\)</span> y <span class="math inline">\(r^2\)</span> será cercano a 1. Nuestro valor de <span class="math inline">\(r^2\)</span> adquiere valores que van desde 0 a 1. Para nuestros datos de las serpientes, <span class="math inline">\(r = 0.9437\)</span>, por lo que <span class="math inline">\(r^2 = 0.8906\)</span>. Esto quiere decir que 89.06% de la varianza en el peso de las serpientes es explicada por esta relación.</p>
</div>
</div>
<div id="el-model-lineal" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> El model lineal</h2>
<p>Podemos considerar realizar inferencia a partir de los datos sobre una población más grande. Una <strong>población condicional</strong> de <span class="math inline">\(Y\)</span> es una población en la cual los valores de <span class="math inline">\(Y\)</span> están asociados o fijos, dados un valor de <span class="math inline">\(X\)</span>. Dentro de una población condicional, podemos hablar de una <strong>distribución condicional</strong> de <span class="math inline">\(Y\)</span>. <span class="math inline">\(\mu_{Y|X}\)</span> corresponde a la media poblacional de <span class="math inline">\(Y\)</span> para un valor dado de <span class="math inline">\(X\)</span>. <span class="math inline">\(\sigma_{Y|X}\)</span> corresponde a la desviación estándar poblacional para un valor dado de <span class="math inline">\(X\)</span>.</p>
<p>Por ejemplo, en el caso de las ratas y las anfetaminas, <span class="math inline">\(\mu_{Y|X}\)</span> y <span class="math inline">\(\sigma_{Y|X}\)</span> representan la media y la desviación estándar de los valores de consumo de comida para las ratas dada la dosis <span class="math inline">\(X\)</span> de anfetamina. Cabe aclarar que en estudios observacionales, las distribuciones condicionales corresponden a subpoblaciones más que a unidades experimentales.</p>
<p>Para el modelo lineal, se le puede dar una interpretación paramétrica si se cumplen dos condiciones:</p>
<p><strong>- Linearidad:</strong> <span class="math inline">\(Y = \mu_{Y|X} + \epsilon\)</span> donde <span class="math inline">\(\mu_{Y|X}\)</span> es la función lineal de <span class="math inline">\(X\)</span>, es decir, <span class="math inline">\(\mu_{Y|X} = \beta_0 + \beta_1X\)</span>. Por ende <span class="math inline">\(Y = \beta_0 + \beta_1X + \epsilon\)</span>.</p>
<p><strong>- Constancia en la desviación estándar:</strong> o sea, que <span class="math inline">\(\sigma_{Y|X}\)</span> no dependa de <span class="math inline">\(X\)</span>. Denotamos este valor constante como <span class="math inline">\(\sigma_\epsilon\)</span>.</p>
<p>Por lo tanto, la fórmula general para el modelo lineal es:</p>
<p><span class="math display" id="eq:lm">\[\begin{equation}
Y = \beta_0 + \beta_1X + \epsilon
\tag{7.11}
\end{equation}\]</span></p>
<p>Como en el caso del ANOVA, el término <span class="math inline">\(\epsilon\)</span> representa el error aleatorio. La desviación estándar condicional es la que determina la variabilidad de <span class="math inline">\(Y\)</span> en un valor dado de <span class="math inline">\(X\)</span>, sin embargo, ya que el modelo lineal determina que la desviación estándar es la misma para todos los valores de <span class="math inline">\(X\)</span>, entonces la representamos como <span class="math inline">\(\sigma_\epsilon\)</span> y nos referimos a ella como la desviación estándar del error aleatorio.</p>
<div id="estmiaciones-del-modelo-lineal" class="section level3" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Estmiaciones del modelo lineal</h3>
<p>Al aplicar el modelo lineal estamos dispuestos a asumir que también aceptamos el <strong>modelo de submuestreo aleatorio,</strong> el cuál dice que para cada par de observaciones (<span class="math inline">\(x, y\)</span>), consideramos al valor de <span class="math inline">\(y\)</span> como si hubiese sido muestreado de manera aleatoria de la población condicional de los valores de <span class="math inline">\(Y\)</span> asociados al valor <span class="math inline">\(x\)</span> de <span class="math inline">\(X\)</span>.</p>
<p>Bajo este modelo, los valores <span class="math inline">\(b_0, b_1\)</span> y <span class="math inline">\(s_e\)</span> calculados en la regresión lineal se interpretan como estimadores de los parámetros poblacionales:</p>
<p>-<span class="math inline">\(b_0\)</span> es un estimado de <span class="math inline">\(\beta_0\)</span></p>
<p>-<span class="math inline">\(b_1\)</span> es un estimado de <span class="math inline">\(\beta_1\)</span></p>
<p>-<span class="math inline">\(s_e\)</span> es un estimado de <span class="math inline">\(\sigma_\epsilon\)</span></p>
<p>Gracias a la función <code>summary(Regresion)</code> y a los cálculos realizados anteriormente, sabemos que <span class="math inline">\(b_0 = -301.08\)</span>, <span class="math inline">\(b_1 = 7.1916\)</span> y que <span class="math inline">\(s_e = 12.5\)</span> para los datos de nuestras serpientes.</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="correlación-y-regresión-lineal.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Regresion)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Peso ~ Longitud, data = Serpientes)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -19.192  -7.233   2.849   5.727  20.424 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -301.0872    60.1885  -5.002 0.001561 ** 
## Longitud       7.1919     0.9531   7.546 0.000132 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.5 on 7 degrees of freedom
## Multiple R-squared:  0.8905, Adjusted R-squared:  0.8749 
## F-statistic: 56.94 on 1 and 7 DF,  p-value: 0.0001321</code></pre>
<p>La pendiente de la línea de regresión <span class="math inline">\(b_0 = 7.1916\)</span> g/cm es un estimado de un parámetro morfológico (cambios en unidades de peso por cada unidad de longitud). Además, encontramos una variabilidad estimada de 12.5 g en el peso de las serpientes para un valor fijo de <span class="math inline">\(X\)</span>.</p>
</div>
<div id="interpolación-en-el-modelo-lineal" class="section level3" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> Interpolación en el modelo lineal</h3>
<p>Imaginemos que quisiéramos saber el peso de una hipotética serpiente que midiese 63.5 cm. Ya que en nuestros datos no tenemos ningún valor que nos de un estimado, tenemos que realizar una <strong>interpolación</strong> a partir de nuestra fórmula de regresión lineal. Para el caso de las serpientes, <span class="math inline">\(\hat{y} = (-301.08) + 7.1916 \times 63.5 = 155.59\)</span>, lo que corresponde a un promedio estimado de 155.9 g con una desviación estándar <span class="math inline">\(s_e = 12.5\)</span> g (esto no quiere decir que el valor de <span class="math inline">\(y\)</span> será 155.59 g, pero si obtenemos múltiples observaciones de este valor cuando <span class="math inline">\(X = 63.5\)</span> en promedio, obtendremos 155.59 g).</p>
<p>Cabe aclarar que lo que hicimos fue una interpolación porque, el dato estimado que queríamos saber se encuentra dentro del rango de nuestros datos. Cuando estimamos valores fuera del rango de nuestros datos, se le conoce como <strong>extrapolación.</strong> Aunque esto se recomienda evitar siempre que sea posible, ya que no hay garantía de que la linearidad se mantendrá fuera del conjunto de datos observados.</p>
<p>La ventaja de realizar predicciones utilizando el modelo de la regresión lineal es que, este hace uso de <strong>todo</strong> el conjunto de datos que tenemos.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Supongamos que capturamos una hembra de la serpiente <em>V. bertis</em> y queremos saber cuál es su peso. No hemos medido a la serpiente aún, así que no conocemos su longitud.</p>
</blockquote>
<p>Para este caso, nuestro mejor estimado sería utilizar la media para el peso, <span class="math inline">\(\overline{y} = 152\)</span> g.</p>
<blockquote>
<p><strong>Ejemplo:</strong> tras realizar la medición correspondiente, sabemos que la hembra de <em>V. bertis</em> mide 63 cm Tomando en cuenta esta información, ¿cuál es el mejor estimado de su peso?</p>
</blockquote>
<p>Sabemos por el grupo que capturamos anteriormente que el promedio del peso de las serpientes que miden 63 cm es, <span class="math inline">\(\overline{y}|x = 145\)</span> (ya que solamente capturamos una serpiente que midiera 63 cm).</p>
<blockquote>
<p><strong>Ejemplo:</strong> los investigadores ajustan una línea para el conjunto de datos de <em>V. bertis</em> capturadas anteriormente, por lo que sabemos que la lína de regresión lineal de mínimos cuadrados es <span class="math inline">\(Y = -301.08 - 7.1916X\)</span>.</p>
</blockquote>
<p>Ahora que sabemos esto, podemos dar un estimado mucho mejor sobre cuál será el promedio del peso de las serpientes cuando miden 63 cm. <span class="math inline">\(\hat{y} = -301.08 + 7.1916 \times 63 = 151.9905\)</span> cm.</p>
<p>Esperamos que la última predicción sea la mejor, siempre y cuando creamos que existen una relación lineal entre las variables <span class="math inline">\(Y\)</span> y <span class="math inline">\(X\)</span>. Además nos da resultados para valores que no se encuentren dentro del conjunto de datos. Es importante saber que esto será verdad siempre y cuando se mantenga la relación lineal de las variables.</p>
</div>
</div>
<div id="inferencia-estadística-respecto-de-beta_1" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Inferencia estadística respecto de <span class="math inline">\(\beta_1\)</span></h2>
<p>En esta parte consideraremos la inferencia acerca de la verdadera pendiente de <span class="math inline">\(\beta_1\)</span> de la regresión lineal. Basado en que la condición de que la distribución condicional de la población <span class="math inline">\(Y\)</span> para cada valor de <span class="math inline">\(X\)</span> tiene una distribución normal. Esto quiere decir que en el modelo lineal <span class="math inline">\(Y = \beta_0 + \beta_1X + \epsilon\)</span>, el valor de <span class="math inline">\(\epsilon\)</span> tiene una distribución normal.</p>
<div id="el-error-estándar-de-b_1" class="section level3" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> El error estándar de <span class="math inline">\(b_1\)</span></h3>
<p>En el contexto del modelo lineal, <span class="math inline">\(b_1\)</span> es un estimado de <span class="math inline">\(\beta_1\)</span> y como todo valor estimado, está sujeto a error de muestreo. La fórmula para calcularlo es la siguiente:</p>
<p><span class="math display" id="eq:b1se">\[\begin{equation}
SE_{b_1} = \frac{s_e}{s_x\sqrt{n-1}}
\tag{7.12}
\end{equation}\]</span></p>
<p>Para los datos de las serpientes, tenemos que <span class="math inline">\(n = 9\)</span>, <span class="math inline">\(s_x = 4.637\)</span>, y que <span class="math inline">\(s_e = 12.5\)</span>. Entonces el error estándar de <span class="math inline">\(b_0\)</span> sería:</p>
<p><span class="math display">\[\begin{equation}
SE_{b_1} = \frac{12.5}{4.637 \sqrt{9-1}} = 0.9531
\end{equation}\]</span></p>
<p>Entonces, el error estándar de nuestra pendiente <span class="math inline">\(b_1 = 0.9531\)</span>. El valor de <span class="math inline">\(b_1\)</span> depende de varios aspectos de los datos. <span class="math inline">\(SE_{b_1}\)</span> depende de la dispersión de los datos sobre la regresión lineal (<span class="math inline">\(s_e\)</span>) y en el tamaño de muestreo <span class="math inline">\(n\)</span>. Datos con menor dispersión sobre la regresión lineal (una <span class="math inline">\(s_e\)</span> más pequeña) y tamaños de muestra más grandes, producen mejores estimadores de <span class="math inline">\(\beta_1\)</span>. Además de esto, existe un tercer factor que afecta al <span class="math inline">\(SE_{b_1}\)</span> y es la variabilidad de <span class="math inline">\(X\)</span>. Entre más dispresos estén los valores de <span class="math inline">\(X\)</span> (mayor <span class="math inline">\(s_x\)</span>), mayor será la precisión de nuestra estimación.</p>
<p>Esto tiene implicaciones en el diseño experimental, ya que si podemos controlar la dispresión de los valores de <span class="math inline">\(X\)</span> preferiríamos datos que minimicen el valor del <span class="math inline">\(SE_{b_1}\)</span>.</p>
</div>
<div id="intervalo-de-confianza-para-beta_1" class="section level3" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Intervalo de confianza para <span class="math inline">\(\beta_1\)</span></h3>
<p>Un intervalo de confianza para <span class="math inline">\(\beta_1\)</span> se puede construir basándose en la distribución <span class="math inline">\(t\)</span> de Student. Entonces, un intervalo de confianza al 95% sería:</p>
<p><span class="math display">\[\begin{equation}
b_1 \pm t_{0.025}SE_{b_1}
\end{equation}\]</span></p>
<p>En dónde el valor crítico de <span class="math inline">\(t\)</span> se determina por la distribución <span class="math inline">\(t\)</span> de Student con los grados de libertad:</p>
<p><span class="math display">\[\begin{equation}
df = n -2
\end{equation}\]</span></p>
<p>Para el caso de las serpientes, nuestro intervalo de confianza sería:</p>
<p><span class="math display">\[\begin{equation}
7.1916 \pm 2.365 \times 0.9531
\end{equation}\]</span></p>
<p>Por lo que nuestro intervalo sería <span class="math inline">\((4.94, 9.45)\)</span> g/cm. Podemos calcular el intervalo de confianza en <code>R</code> con la función `<code>confint()</code>.</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="correlación-y-regresión-lineal.html#cb295-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(Regresion)</span></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) -443.410309 -158.764110
## Longitud       4.938183    9.445538</code></pre>
<p>Donde obtenemos el intervalo de confianza tanto para <span class="math inline">\(b_0\)</span> como para <span class="math inline">\(b_1\)</span>. En este caso nos interesa el de nuestra pendiente <span class="math inline">\(b_1\)</span>.</p>
</div>
</div>
<div id="prueba-de-hipótesis-para-h_0-beta_1-0" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> Prueba de hipótesis para <span class="math inline">\(H_0: \beta_1 = 0\)</span></h2>
<p>En algunas investigaciones, no es una conclusión inevitable que exista una relación lineal entre <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span>. Puede ser entonces importante considerar qu cualquier tendencia aparente surgió por azar, que sea ilusora y que solo refleje la variabilidad del muestreo. Entonces:</p>
<p><span class="math display">\[\begin{equation}
H_0: \mu_{Y|X} \space no \space depende \space de \space X
\end{equation}\]</span></p>
<p>Lo que se puede traducir a <span class="math inline">\(H_0: \beta_1 = 0\)</span>. Entonces nuestro estadístico de prueba sería:</p>
<p><span class="math display" id="eq:b1test">\[\begin{equation}
t_s = \frac{b_1 - 0}{SE_{b_1}}
\tag{7.13}
\end{equation}\]</span></p>
<p>Y de nuevo, los valores críticos se calculan con los grados de libertad, <span class="math inline">\(df = n - 2\)</span>. En <code>R</code> este proceso ya lo hemos realizado con la función <code>summary()</code> aplicada a nuestro modelo. El valor <span class="math inline">\(0\)</span> en la fórmula <a href="correlación-y-regresión-lineal.html#eq:b1test">(7.13)</a> nos recuerda que estamos comparando el valor esperado bajo la <span class="math inline">\(H_0\)</span> con el valor obtenido.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="correlación-y-regresión-lineal.html#cb297-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Regresion)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Peso ~ Longitud, data = Serpientes)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -19.192  -7.233   2.849   5.727  20.424 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -301.0872    60.1885  -5.002 0.001561 ** 
## Longitud       7.1919     0.9531   7.546 0.000132 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.5 on 7 degrees of freedom
## Multiple R-squared:  0.8905, Adjusted R-squared:  0.8749 
## F-statistic: 56.94 on 1 and 7 DF,  p-value: 0.0001321</code></pre>
<p>En este caso podemos ver que el valor <span class="math inline">\(t\)</span> ya está dado en el apartado de los coeficientes (<span class="math inline">\(t_s = 7.546\)</span>), junto con nuestro valor-<em>p</em> denotado por el título <code>Pr(&gt;|t|)</code>, que en este caso corresponde a <span class="math inline">\(valor-p = 0.000132\)</span>, por lo tanto rechazamos la <span class="math inline">\(H_0\)</span> ya que <span class="math inline">\(valor-p &lt; 0.05\)</span>.</p>
<p>Hay que interpretar esta prueba con cuidado. La prueba de hipótesis para <span class="math inline">\(\beta_1\)</span> no nos dice si existen una relación lineal entre <span class="math inline">\(\mu_{Y|X}\)</span> y <span class="math inline">\(X\)</span>, más bien, asume que el modelo linea es verdadero y nos dice si podemos concluir que la pendiente no es 0.</p>
<div id="gráficos-de-residuales" class="section level3" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> Gráficos de residuales</h3>
<p>Son bastante útiles para detectar anomalías en los datos (como algún patrón distinto al patrón lineal). Estos gráficos, conocidos como <strong>gráficos de residuales</strong> es lo que queda después de que removemos la tendencia lineal, por lo que esperamos que sean gráficos sin un patrón conciso. Por ejemplo, la figura <a href="correlación-y-regresión-lineal.html#fig:resplot">7.6</a></p>
<div class="figure" style="text-align: center"><span id="fig:resplot"></span>
<img src="Curso_R_basico_files/figure-html/resplot-1.png" alt="Gráfico de residuales mostrando la ausencia de curvatura o patrón para los datos de serpientes." width="480" />
<p class="caption">
Figura 7.6: Gráfico de residuales mostrando la ausencia de curvatura o patrón para los datos de serpientes.
</p>
</div>
<p>De igual manera si las condiciones de normalidad se cumplen, deberíamos ver esto en un gráfico en el que se comparan los valores de los residuales con los valores <span class="math inline">\(Z\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:resplot2"></span>
<img src="Curso_R_basico_files/figure-html/resplot2-1.png" alt="Gráfico de residuales comparados con la valores Z teóricos para mostrar la normalidad." width="480" />
<p class="caption">
Figura 7.7: Gráfico de residuales comparados con la valores Z teóricos para mostrar la normalidad.
</p>
</div>
<p>Como podemos ver también se sigue una distribución más o menos lineal cuando se compara con los valores <span class="math inline">\(Z\)</span> teóricos.</p>
</div>
</div>
<div id="intervalos-de-confianza-y-de-predicción" class="section level2" number="7.6">
<h2><span class="header-section-number">7.6</span> Intervalos de confianza y de predicción</h2>
<p>En esta parte veremos la diferencia entre la predicción de la media del valor de <span class="math inline">\(Y\)</span> para un valor <span class="math inline">\(X\)</span> dado con obtener un valor específico de <span class="math inline">\(Y\)</span> para un valor de <span class="math inline">\(X\)</span> dado.</p>
<p>Por ejemplo, ya sabemos que si queremos predecir la media del peso de una de las serpientes con una longitud de 63.5 cm la media de nuestras observaciones será 155.59 g. Sin embargo, ¿qué valor obtendríamos si quisieramos calcular un valor puntual? Pues la respuesta es que obtendríamos el mismo valor de 155.59 g. Utilizamos la regresión lineal de la misma manera, sin embargo, la precisión de nuestras predicciones son distinas.</p>
<div id="computando-los-intervalos" class="section level3" number="7.6.1">
<h3><span class="header-section-number">7.6.1</span> Computando los intervalos</h3>
<p>Supongamos que queremos predecir <span class="math inline">\(\mu_{Y|X=x^*}\)</span> o <span class="math inline">\(Y|X=x^*\)</span>. Es decir, predicr la media o el valor actual de <span class="math inline">\(Y\)</span> cuando el valor de <span class="math inline">\(X = x^*\)</span>.
Las fórmulas para el intevalo de confianza (Fórmula @eq:ICreg) y el intervalo de la predicción (Fórmula @eq:ICreg) son:</p>
<p><span class="math display" id="eq:ICreg">\[\begin{equation}
\hat{y} \pm t_{0.025}s_e\sqrt{\frac{1}{n} + \frac{(x^*-\overline{x})^2}{(n-1)s_x^2}}
\tag{7.14}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:ICreg2">\[\begin{equation}
\hat{y} \pm t_{0.025}s_e\sqrt{1 + \frac{1}{n} + \frac{(x^*-\overline{x})^2}{(n-1)s_x^2}}
\tag{7.15}
\end{equation}\]</span></p>
<p>Con el valor de <span class="math inline">\(t_{0.025}\)</span> determinado por la distribución de <span class="math inline">\(t\)</span> y los <span class="math inline">\(df = n - 2\)</span>. Aunque las fórmulas son muy parecidas, el <span class="math inline">\(1\)</span> agregado debajo de la raíz cuadrada factoriza la variabilidad asociada cuando intentamos hacer una predicción individual.</p>
<div class="figure" style="text-align: center"><span id="fig:confypred"></span>
<img src="Curso_R_basico_files/figure-html/confypred-1.png" alt="Intervalo de confianza al 95% (gris) e intervalo de la predicción al 95% (línea azul punteada) para los datos de serpientes." width="480" />
<p class="caption">
Figura 7.8: Intervalo de confianza al 95% (gris) e intervalo de la predicción al 95% (línea azul punteada) para los datos de serpientes.
</p>
</div>
<p>Como podemos ver en la figura <a href="correlación-y-regresión-lineal.html#fig:confypred">7.8</a>, el intervalo de confianza es muchísimo más preciso que el intervalo de predicción, como se mencionó anteriormente. Para obtener los intervalos de confianza y de predicción en <code>R</code> podemos utilizar las siguientes funciones basadas en nuestro modelo lineal.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="correlación-y-regresión-lineal.html#cb299-1" aria-hidden="true" tabindex="-1"></a>Conf.int <span class="ot">&lt;-</span> <span class="fu">predict</span>(Regresion, <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span>
<span id="cb299-2"><a href="correlación-y-regresión-lineal.html#cb299-2" aria-hidden="true" tabindex="-1"></a>Conf.int</span></code></pre></div>
<pre><code>##         fit       lwr      upr
## 1 130.42442 118.47544 142.3734
## 2 195.15116 178.42057 211.8818
## 3 173.57558 161.62660 185.5246
## 4 159.19186 149.08515 169.2986
## 5  87.27326  64.72396 109.8225
## 6 180.76744 167.41336 194.1215
## 7 123.23256 109.87848 136.5866
## 8 166.38372 155.54939 177.2181
## 9 152.00000 142.14777 161.8522</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="correlación-y-regresión-lineal.html#cb301-1" aria-hidden="true" tabindex="-1"></a>Pred.int <span class="ot">&lt;-</span> <span class="fu">predict</span>(Regresion, <span class="at">interval=</span> <span class="st">&quot;prediction&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in predict.lm(Regresion, interval = &quot;prediction&quot;): predictions on current data refer to _future_ responses</code></pre>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="correlación-y-regresión-lineal.html#cb303-1" aria-hidden="true" tabindex="-1"></a>Pred.int</span></code></pre></div>
<pre><code>##         fit       lwr      upr
## 1 130.42442  98.54375 162.3051
## 2 195.15116 161.18778 229.1145
## 3 173.57558 141.69492 205.4562
## 4 159.19186 127.95495 190.4288
## 5  87.27326  50.09706 124.4494
## 6 180.76744 148.33397 213.2009
## 7 123.23256  90.79908 155.6660
## 8 166.38372 134.90386 197.8636
## 9 152.00000 120.84450 183.1555</code></pre>
<p>Si vemos los resultados, los valores del intervalo de confianza son más estrechos que los del intervalo de predicción. El apartado <code>fit</code> corresponde al valor predicho para cierto valor de <span class="math inline">\(X\)</span>. Con el argumento <code>level</code> podemos cambiar el nivel de % para nuestros intervalos.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modelado-de-relaciones.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bibliografia.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
