<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 2 Estadística descriptiva | Curso de R básico</title>
  <meta name="description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 2 Estadística descriptiva | Curso de R básico" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 2 Estadística descriptiva | Curso de R básico" />
  
  <meta name="twitter:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

<meta name="author" content="Alejandro Ruiz-García" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introducción-a-r.html"/>
<link rel="next" href="análisis-de-varianza-anova.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de R básico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Requisitos</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#descarga-de-r-y-rstudio"><i class="fa fa-check"></i><b>0.1</b> Descarga de R y RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introducción-a-r.html"><a href="introducción-a-r.html"><i class="fa fa-check"></i><b>1</b> Introducción a R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introducción-a-r.html"><a href="introducción-a-r.html#interfaz"><i class="fa fa-check"></i><b>1.1</b> Interfaz</a></li>
<li class="chapter" data-level="1.2" data-path="introducción-a-r.html"><a href="introducción-a-r.html#creando-nuestro-primer-proyecto"><i class="fa fa-check"></i><b>1.2</b> Creando nuestro primer proyecto</a></li>
<li class="chapter" data-level="1.3" data-path="introducción-a-r.html"><a href="introducción-a-r.html#objetos-y-variables"><i class="fa fa-check"></i><b>1.3</b> Objetos y variables</a></li>
<li class="chapter" data-level="1.4" data-path="introducción-a-r.html"><a href="introducción-a-r.html#instalar-paquetes"><i class="fa fa-check"></i><b>1.4</b> Instalar paquetes</a></li>
<li class="chapter" data-level="1.5" data-path="introducción-a-r.html"><a href="introducción-a-r.html#importar-datos-a-r"><i class="fa fa-check"></i><b>1.5</b> Importar datos a R</a></li>
<li class="chapter" data-level="1.6" data-path="introducción-a-r.html"><a href="introducción-a-r.html#comentarios"><i class="fa fa-check"></i><b>1.6</b> Comentarios</a></li>
<li class="chapter" data-level="1.7" data-path="introducción-a-r.html"><a href="introducción-a-r.html#exportar-datos"><i class="fa fa-check"></i><b>1.7</b> Exportar datos</a></li>
<li class="chapter" data-level="1.8" data-path="introducción-a-r.html"><a href="introducción-a-r.html#pedir-ayuda"><i class="fa fa-check"></i><b>1.8</b> Pedir ayuda</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html"><i class="fa fa-check"></i><b>2</b> Estadística descriptiva</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>2.1</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#media-en-r"><i class="fa fa-check"></i><b>2.1.1</b> Media en R</a></li>
<li class="chapter" data-level="2.1.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mediana-en-r"><i class="fa fa-check"></i><b>2.1.2</b> Mediana en R</a></li>
<li class="chapter" data-level="2.1.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#la-función-summary"><i class="fa fa-check"></i><b>2.1.3</b> La función <code>summary</code></a></li>
<li class="chapter" data-level="2.1.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#visualización-básica-de-datos"><i class="fa fa-check"></i><b>2.1.4</b> Visualización básica de datos</a></li>
<li class="chapter" data-level="2.1.5" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#valores-atípicos"><i class="fa fa-check"></i><b>2.1.5</b> Valores atípicos</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>2.2</b> Medidas de dispersión</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#rango-en-r"><i class="fa fa-check"></i><b>2.2.1</b> Rango en R</a></li>
<li class="chapter" data-level="2.2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#desviación-estándar-en-r"><i class="fa fa-check"></i><b>2.2.2</b> Desviación estándar en R</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-posición"><i class="fa fa-check"></i><b>2.3</b> Medidas de posición</a></li>
<li class="chapter" data-level="2.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#el-uso-de-la-librería-dplyr"><i class="fa fa-check"></i><b>2.4</b> El uso de la librería <code>dplyr</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html"><i class="fa fa-check"></i><b>3</b> Análisis de Varianza (ANOVA)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#prueba-de-normalidad"><i class="fa fa-check"></i><b>3.1</b> Prueba de normalidad</a></li>
<li class="chapter" data-level="3.2" data-path="análisis-de-varianza-anova.html"><a href="análisis-de-varianza-anova.html#prueba-de-homocedasticidad"><i class="fa fa-check"></i><b>3.2</b> Prueba de homocedasticidad</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso de R básico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estadística-descriptiva" class="section level1" number="2">
<h1><span class="header-section-number">Lección 2</span> Estadística descriptiva</h1>
<p>En esta lección veremos las nociones básicas de estadística descriptiva haciendo uso de R y RStudio. Veremos medidas de tendencia central como la media, mediana y moda y medidas de dispersión como varianza, desviación estándar e intervalos de confianza.</p>
<div id="medidas-de-tendencia-central" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Medidas de tendencia central</h2>
<p>Los estadísticos descriptivos sirven para describir parte de la información de nuestros datos. Las tres medidas de tendencia central más utilizadas son:</p>
<ul>
<li><p><strong>Moda:</strong> Es el valor que más se repite en un conjunto de datos. Sin embargo, casi no se utiliza en estadística y por lo mismo no hablaremos más de ella.</p></li>
<li><p><strong>Media:</strong> Mide el promedio del valor de nuestros datos. Se calcula como la suma de las observaciones dividida entre el número de observaciones. Para obtener la media utilizamos la ecuación <a href="estadística-descriptiva.html#eq:mean">(2.1)</a>.</p></li>
</ul>
<p><span class="math display" id="eq:mean">\[\begin{equation}
  \overline{x} = \frac{\sum_{i = 1}^{n}{x_i}}{n}
  \tag{2.1}
\end{equation}\]</span>
Donde <span class="math inline">\(\sum_{i=1}^{n}{x_i}\)</span> representa la sumatoria de los valores de todas nuestras observaciones y <span class="math inline">\(n\)</span> es el número de observaciones.</p>
<ul>
<li><strong>Mediana:</strong> Es el valor que se encuentra justo por la mitad de la distribución de nuestros datos.
<span class="math display">\[
1, 2, 3, 4, 5
\]</span></li>
</ul>
<p>En este caso, la mediana es igual al número <strong>3</strong> que se encuentra justo por la mitad de los datos. En caso de tener un número par de observaciones, la mediana se puede calcular como un promedio de los dos valores centrales.
<span class="math display">\[
5, 6, 7, 8, 9, 10
\]</span></p>
<p>En este caso nuestros valores centrales son 7 y 8. Estos simplemente se promedian.
<span class="math display">\[
\tilde{x} = \frac{7 + 8}{2} = 7.5
\]</span></p>
<div id="media-en-r" class="section level3" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Media en R</h3>
<p>El cálculo de la media en R para un conjunto de datos es relativamente sencillo. Para ello implementamos la función <code>mean()</code>. Podemos ver un resumen de los primeros 10 datos con la función <code>head()</code>.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="estadística-descriptiva.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb46-2"><a href="estadística-descriptiva.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;iris&quot;</span>)</span>
<span id="cb46-3"><a href="estadística-descriptiva.html#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="estadística-descriptiva.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length)</span></code></pre></div>
<pre><code>## [1] 5.843333</code></pre>
<p>Hemos calculado la media o el promedio para la longitud del sepalo del grupo de datos <code>iris</code> que viene incluida en el paquete <code>vegan</code>. Como en esta base de datos tenemos numerosas variables, nos referimos a una variable específica utilizando el símbolo $ seguido del nombre de la variable de interés.</p>
<p>Si quisiéramos podemos almacenar el promedio de la longitud y el ancho de los sépalos en una variable nueva.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="estadística-descriptiva.html#cb50-1" aria-hidden="true" tabindex="-1"></a>Long.Prom <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length)</span>
<span id="cb50-2"><a href="estadística-descriptiva.html#cb50-2" aria-hidden="true" tabindex="-1"></a>Long.Prom</span></code></pre></div>
<pre><code>## [1] 5.843333</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="estadística-descriptiva.html#cb52-1" aria-hidden="true" tabindex="-1"></a>Ancho.Prom <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Width)</span>
<span id="cb52-2"><a href="estadística-descriptiva.html#cb52-2" aria-hidden="true" tabindex="-1"></a>Ancho.Prom</span></code></pre></div>
<pre><code>## [1] 3.057333</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="estadística-descriptiva.html#cb54-1" aria-hidden="true" tabindex="-1"></a>Sepalos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Long.Prom, Ancho.Prom)</span>
<span id="cb54-2"><a href="estadística-descriptiva.html#cb54-2" aria-hidden="true" tabindex="-1"></a>Sepalos</span></code></pre></div>
<pre><code>##   Long.Prom Ancho.Prom
## 1  5.843333   3.057333</code></pre>
<p>De esta manera obtenemos nuestra matriz con los promedios del largo y ancho de los sépalos. Si tuviéramos muestras de distintas poblaciones, podríamos generar una tabla con la media de cada población.</p>
<p>Es importante que especifiquemos de qué variable queremos estimar el promedio con el símbolo <code>$</code>, de lo contrario podemos obtener errores.</p>
</div>
<div id="mediana-en-r" class="section level3" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Mediana en R</h3>
<p>La mediana sigue una lógica muy similar a la media. Simplemente utilizamos la función <code>median()</code> para obtener nuestro valor de interés.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="estadística-descriptiva.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(iris<span class="sc">$</span>Sepal.Length)</span></code></pre></div>
<pre><code>## [1] 5.8</code></pre>
<p>De nuevo, podemos hacer una matriz de datos con las medianas de nuestras observaciones.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="estadística-descriptiva.html#cb58-1" aria-hidden="true" tabindex="-1"></a>Long.Median <span class="ot">&lt;-</span> <span class="fu">median</span>(iris<span class="sc">$</span>Sepal.Length)</span>
<span id="cb58-2"><a href="estadística-descriptiva.html#cb58-2" aria-hidden="true" tabindex="-1"></a>Long.Median</span></code></pre></div>
<pre><code>## [1] 5.8</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="estadística-descriptiva.html#cb60-1" aria-hidden="true" tabindex="-1"></a>Ancho.Median <span class="ot">&lt;-</span> <span class="fu">median</span>(iris<span class="sc">$</span>Sepal.Width)</span>
<span id="cb60-2"><a href="estadística-descriptiva.html#cb60-2" aria-hidden="true" tabindex="-1"></a>Ancho.Median</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="estadística-descriptiva.html#cb62-1" aria-hidden="true" tabindex="-1"></a>Sepalos2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Long.Median, Ancho.Median)</span>
<span id="cb62-2"><a href="estadística-descriptiva.html#cb62-2" aria-hidden="true" tabindex="-1"></a>Sepalos2</span></code></pre></div>
<pre><code>##   Long.Median Ancho.Median
## 1         5.8            3</code></pre>
<p>Incluso podríamos combinar ambas matrices (promedio y mediana) en una sola.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="estadística-descriptiva.html#cb64-1" aria-hidden="true" tabindex="-1"></a>Sepalos.Resumen <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Sepalos, Sepalos2)</span>
<span id="cb64-2"><a href="estadística-descriptiva.html#cb64-2" aria-hidden="true" tabindex="-1"></a>Sepalos.Resumen</span></code></pre></div>
<pre><code>##   Long.Prom Ancho.Prom Long.Median Ancho.Median
## 1  5.843333   3.057333         5.8            3</code></pre>
<p>También podríamos optar por escribir directamente las nuevas variables de la mediana sobre la matriz de datos que ya habíamos generado para las medias.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="estadística-descriptiva.html#cb66-1" aria-hidden="true" tabindex="-1"></a>Sepalos<span class="sc">$</span>Long.Median <span class="ot">&lt;-</span> <span class="fu">median</span>(iris<span class="sc">$</span>Sepal.Length)</span>
<span id="cb66-2"><a href="estadística-descriptiva.html#cb66-2" aria-hidden="true" tabindex="-1"></a>Sepalos<span class="sc">$</span>Ancho.Median <span class="ot">&lt;-</span> <span class="fu">median</span>(iris<span class="sc">$</span>Sepal.Width)</span>
<span id="cb66-3"><a href="estadística-descriptiva.html#cb66-3" aria-hidden="true" tabindex="-1"></a>Sepalos</span></code></pre></div>
<pre><code>##   Long.Prom Ancho.Prom Long.Median Ancho.Median
## 1  5.843333   3.057333         5.8            3</code></pre>
<p>Como podemos ver, el resultado es el mismo. Al nosotros escribir Sépalos$Long.Median y asignarle una función, estamos generando una nueva variable en la matriz de datos preexistente aunque en dicha matriz no existía previamente la variable Long.Median. Ambas son técnicas distintas de llegar al mismo resultado y ambas son perfectamente válidas.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="estadística-descriptiva.html#cb68-1" aria-hidden="true" tabindex="-1"></a>Sepalos</span></code></pre></div>
<pre><code>##   Long.Prom Ancho.Prom Long.Median Ancho.Median
## 1  5.843333   3.057333         5.8            3</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="estadística-descriptiva.html#cb70-1" aria-hidden="true" tabindex="-1"></a>Sepalos.Resumen</span></code></pre></div>
<pre><code>##   Long.Prom Ancho.Prom Long.Median Ancho.Median
## 1  5.843333   3.057333         5.8            3</code></pre>
<p>Incluso podemos calcular la media y la mediana para los valores de los pétalos y resumir todo en una sola matriz.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="estadística-descriptiva.html#cb72-1" aria-hidden="true" tabindex="-1"></a>Pet.Long.Mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Petal.Length)</span>
<span id="cb72-2"><a href="estadística-descriptiva.html#cb72-2" aria-hidden="true" tabindex="-1"></a>Pet.Ancho.Mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Petal.Width)</span>
<span id="cb72-3"><a href="estadística-descriptiva.html#cb72-3" aria-hidden="true" tabindex="-1"></a>Pet.Long.Median <span class="ot">&lt;-</span> <span class="fu">median</span>(iris<span class="sc">$</span>Petal.Length)</span>
<span id="cb72-4"><a href="estadística-descriptiva.html#cb72-4" aria-hidden="true" tabindex="-1"></a>Pet.Ancho.Median <span class="ot">&lt;-</span> <span class="fu">median</span>(iris<span class="sc">$</span>Petal.Width)</span>
<span id="cb72-5"><a href="estadística-descriptiva.html#cb72-5" aria-hidden="true" tabindex="-1"></a>Resumen.iris <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Sepalos, Pet.Long.Mean, Pet.Ancho.Mean, Pet.Long.Median, Pet.Ancho.Median)</span>
<span id="cb72-6"><a href="estadística-descriptiva.html#cb72-6" aria-hidden="true" tabindex="-1"></a>Resumen.iris</span></code></pre></div>
<pre><code>##   Long.Prom Ancho.Prom Long.Median Ancho.Median Pet.Long.Mean Pet.Ancho.Mean
## 1  5.843333   3.057333         5.8            3         3.758       1.199333
##   Pet.Long.Median Pet.Ancho.Median
## 1            4.35              1.3</code></pre>
<p>Lo ideal sería cambiar el nombre a las primeras 4 columnas para indicar que se trata de sépalos. También podemos hacer esto.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="estadística-descriptiva.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(Resumen.iris)[<span class="fu">colnames</span>(Resumen.iris) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Long.Prom&quot;</span>, <span class="st">&quot;Ancho.Prom&quot;</span>, <span class="st">&quot;Long.Median&quot;</span>, <span class="st">&quot;Ancho.Median&quot;</span>)] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Sep.Long.Prom&quot;</span>, <span class="st">&quot;Sep.Ancho.Prom&quot;</span>, <span class="st">&quot;Sep.Long.Median&quot;</span>, <span class="st">&quot;Sep.Ancho.Median&quot;</span>)</span>
<span id="cb74-2"><a href="estadística-descriptiva.html#cb74-2" aria-hidden="true" tabindex="-1"></a>Resumen.iris</span></code></pre></div>
<pre><code>##   Sep.Long.Prom Sep.Ancho.Prom Sep.Long.Median Sep.Ancho.Median Pet.Long.Mean
## 1      5.843333       3.057333             5.8                3         3.758
##   Pet.Ancho.Mean Pet.Long.Median Pet.Ancho.Median
## 1       1.199333            4.35              1.3</code></pre>
<p>El operador %in% sirve para subsetear datos. En este caso, le indicamos que queremos que a las variables con nombre “Long.Prom,” “Ancho.Prom,” “Long.Median,” “Ancho.Median” les asigne un nuevo nombre, indicado con &lt;- y la función de concatenar <code>c</code>.</p>
</div>
<div id="la-función-summary" class="section level3" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> La función <code>summary</code></h3>
<p>Como pudimos observar, hacer todos estos cálculos uno por uno harían que nuestro script sea demasiado largo. Debido a esto, podemos utilizar una función llamada <code>summary()</code> que nos da estos mismos estadísticos y otros adicionales que serán de mucha ayuda.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="estadística-descriptiva.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
<p>Esta función además de darnos la media y la mediana, nos da los valores mínimos y máximos, además del primer y tercer cuartil (utilizados para generar gráficos de boxplot) y nos dice cuántas observaciones tenemos de cada una de las especies.</p>
<p>Podríamos guardar este resumen en una variable.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="estadística-descriptiva.html#cb78-1" aria-hidden="true" tabindex="-1"></a>summ.iris <span class="ot">&lt;-</span> <span class="fu">summary</span>(iris)</span>
<span id="cb78-2"><a href="estadística-descriptiva.html#cb78-2" aria-hidden="true" tabindex="-1"></a>summ.iris</span></code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
</div>
<div id="visualización-básica-de-datos" class="section level3" number="2.1.4">
<h3><span class="header-section-number">2.1.4</span> Visualización básica de datos</h3>
<p>Podemos graficar, por ejemplo, la base de datos iris.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="estadística-descriptiva.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(iris)</span></code></pre></div>
<p><img src="Curso_R_basico_files/figure-html/unnamed-chunk-49-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Como podemos ver, tenemos una gráfica compleja donde no se pueden apreciar del todo bien los datos. Para hacer una gráfica de, por ejemplo, la longitud de los sépalos de cada una de las especies, tenemos que agregar ciertos argumentos a la función <code>plot()</code>.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="estadística-descriptiva.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(iris, <span class="at">x =</span> iris<span class="sc">$</span>Species, <span class="at">y =</span> iris<span class="sc">$</span>Sepal.Length)</span></code></pre></div>
<p><img src="Curso_R_basico_files/figure-html/unnamed-chunk-50-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>También podemos graficar la relación entre dos variables para observar como estas van cambiando.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="estadística-descriptiva.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> iris<span class="sc">$</span>Petal.Length, <span class="at">y =</span> iris<span class="sc">$</span>Petal.Width)</span></code></pre></div>
<p><img src="Curso_R_basico_files/figure-html/unnamed-chunk-51-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Por ejemplo, graficamos la relación que existe entre la longitud del petal y su ancho. A primera vista parece existir una correlación positiva entre ambos.</p>
<p>Podemos agregar más argumentos a nuestro gráfico para hacerlo más presentable.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="estadística-descriptiva.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> iris<span class="sc">$</span>Petal.Length, <span class="at">y =</span> iris<span class="sc">$</span>Petal.Width, <span class="at">main =</span> <span class="st">&quot;Gráfico de relación entre la longitud y el ancho del petalo&quot;</span>,</span>
<span id="cb83-2"><a href="estadística-descriptiva.html#cb83-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="st">&quot;Datos obtenidos de la base de datos iris&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Longitud del petalo&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Ancho del petalo&quot;</span>)</span></code></pre></div>
<p><img src="Curso_R_basico_files/figure-html/unnamed-chunk-52-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Los argumentos <code>main</code> y <code>sub</code> sirven para darle un título y un subtítulo a nuestro gráfico, respectivamente. Los argumentos <code>xlab</code> y <code>ylab</code> sirven para nombrar los ejes x y y.</p>
<p>Otros argumentos con los que podemos modificar la forma, color y contorno de los puntos son <em>pch</em>, <em>bg</em> y <em>col</em>, respectivamente. Con el argumento <code>cex</code> podemos modificar el tamaño de los puntos.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="estadística-descriptiva.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> iris<span class="sc">$</span>Petal.Length, <span class="at">y =</span> iris<span class="sc">$</span>Petal.Width, <span class="at">main =</span> <span class="st">&quot;Gráfico de relación entre la longitud y el ancho del petalo&quot;</span>,</span>
<span id="cb84-2"><a href="estadística-descriptiva.html#cb84-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="st">&quot;Datos obtenidos de la base de datos iris&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Longitud del petalo&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Ancho del petalo&quot;</span>, <span class="at">cex =</span> <span class="fl">0.8</span>,</span>
<span id="cb84-3"><a href="estadística-descriptiva.html#cb84-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> iris<span class="sc">$</span>Species, <span class="at">pch =</span> <span class="dv">20</span>)</span></code></pre></div>
<p><img src="Curso_R_basico_files/figure-html/unnamed-chunk-53-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Es necesario que para que el relleno (argumento <code>bg</code>) sea visible, se necesitan <code>pch = 21:25</code>, en este caso utilizamos <code>pch = 20</code>. Al no poner ningún valor para <code>col</code> el contorno de los puntos es negro.</p>
<p>Las leyendas con los comandos R de base no son muy bonitas y son poco intuitivas. Para esto utilizaremos una librería más adelante llamada <code>ggplot2</code>.</p>
</div>
<div id="valores-atípicos" class="section level3" number="2.1.5">
<h3><span class="header-section-number">2.1.5</span> Valores atípicos</h3>
<p><img src="Curso_R_basico_files/figure-html/unnamed-chunk-54-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Como podemos ver en el gráfico anterior, en el eje de las ordenadas tenemos a las tres especies: <em>Iris setosa, I. versicolor e I. virginica</em>. Esta es una gráfica llamada boxplot y se construye a partir de los datos que tenemos en nuestro resumen. La parte inferior de la caja corresponde al primer cuartil, la línea negra central corresponde a la mediana y la parte superior de la caja corresponde al tercer cuartil. Las líneas que salen de la caja corresponden a los valores máximos y mínimos que no son valores atípicos o <em>outliers</em>. Un valor atípico es aquel que se sale de la cerca superior e inferior, pero, ¿cómo se definen estos límites?</p>
<p>Para el calculo de estas cercas se implementan las siguientes ecuaciones <a href="estadística-descriptiva.html#eq:fence">(2.2)</a>.</p>
<p><span class="math display" id="eq:fence">\[\begin{equation}
\begin{split}
  Cerca_i = Q_1 - 1.5 * IQR \\
  Cerca_s = Q_3 + 1.5 * IQR
\end{split}
\tag{2.2}
\end{equation}\]</span></p>
<p>Donde <span class="math inline">\(Cerca_i\)</span> y <span class="math inline">\(Cerca_s\)</span> corresponden a la cerca inferior y superior, respectivamente, y el valor de <span class="math inline">\(IQR\)</span> corresponde al rango intercuartil (diferencia entre el primer y tercer cuartil <span class="math inline">\(IQR = Q_3 - Q_1\)</span>). Por ejemplo, para la especies <em>I. virginica</em> el <span class="math inline">\(IQR\)</span> de la longitud del sepalo es el siguiente:
<span class="math display">\[
IQR = 6.9 - 6.225 = 0.675
\]</span></p>
<p>Y las cercas correspondientes son:
<span class="math display">\[
Cerca_i = 6.225 - 1.5*0.675 = 5.2125 \\
Cerca_s = 6.9 + 1.5*0.675 = 7.9125
\]</span></p>
<p>Aunque no están incluidas en el boxplot, nuestras cercas inferior y superior son 5.2125 y 7.9125, respectivamente. Cualquier valor por encima o por debajo de este límite será considerado un valor atípico o <em>outlier</em>. Aunque las cercas no se incluyen en el boxplot, este sí gráfica los puntos cuando estos son considerados como valores atípicos, como en el caso del punto que podemos observar en <em>I. virginica</em>, que tiene un valor menor a 5.2125, específicamente, tiene un valor de 4.9. Incluso nosotros podríamos buscar este valor utilizando una serie de filtros.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="estadística-descriptiva.html#cb85-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(Sepal.Length <span class="sc">&lt;=</span> <span class="fl">5.2125</span>)</span></code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
## 1           5.1         3.5          1.4         0.2     setosa
## 2           4.9         3.0          1.4         0.2     setosa
## 3           4.7         3.2          1.3         0.2     setosa
## 4           4.6         3.1          1.5         0.2     setosa
## 5           5.0         3.6          1.4         0.2     setosa
## 6           4.6         3.4          1.4         0.3     setosa
## 7           5.0         3.4          1.5         0.2     setosa
## 8           4.4         2.9          1.4         0.2     setosa
## 9           4.9         3.1          1.5         0.1     setosa
## 10          4.8         3.4          1.6         0.2     setosa
## 11          4.8         3.0          1.4         0.1     setosa
## 12          4.3         3.0          1.1         0.1     setosa
## 13          5.1         3.5          1.4         0.3     setosa
## 14          5.1         3.8          1.5         0.3     setosa
## 15          5.1         3.7          1.5         0.4     setosa
## 16          4.6         3.6          1.0         0.2     setosa
## 17          5.1         3.3          1.7         0.5     setosa
## 18          4.8         3.4          1.9         0.2     setosa
## 19          5.0         3.0          1.6         0.2     setosa
## 20          5.0         3.4          1.6         0.4     setosa
## 21          5.2         3.5          1.5         0.2     setosa
## 22          5.2         3.4          1.4         0.2     setosa
## 23          4.7         3.2          1.6         0.2     setosa
## 24          4.8         3.1          1.6         0.2     setosa
## 25          5.2         4.1          1.5         0.1     setosa
## 26          4.9         3.1          1.5         0.2     setosa
## 27          5.0         3.2          1.2         0.2     setosa
## 28          4.9         3.6          1.4         0.1     setosa
## 29          4.4         3.0          1.3         0.2     setosa
## 30          5.1         3.4          1.5         0.2     setosa
## 31          5.0         3.5          1.3         0.3     setosa
## 32          4.5         2.3          1.3         0.3     setosa
## 33          4.4         3.2          1.3         0.2     setosa
## 34          5.0         3.5          1.6         0.6     setosa
## 35          5.1         3.8          1.9         0.4     setosa
## 36          4.8         3.0          1.4         0.3     setosa
## 37          5.1         3.8          1.6         0.2     setosa
## 38          4.6         3.2          1.4         0.2     setosa
## 39          5.0         3.3          1.4         0.2     setosa
## 40          4.9         2.4          3.3         1.0 versicolor
## 41          5.2         2.7          3.9         1.4 versicolor
## 42          5.0         2.0          3.5         1.0 versicolor
## 43          5.0         2.3          3.3         1.0 versicolor
## 44          5.1         2.5          3.0         1.1 versicolor
## 45          4.9         2.5          4.5         1.7  virginica</code></pre>
<p>Como podemos ver, la mayoría de las especies con valores inferiores a 5.2125 corresponden a otras especies, sin embargo, tenemos una única observación de la especies <em>I. virginica</em> con estas características. Los valores atípicos nos pueden indicar errores en la medición, en nuestra instrumentación, entre otras</p>
</div>
</div>
<div id="medidas-de-dispersión" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Medidas de dispersión</h2>
<p>A diferencia de los estadísticos de tendencia central, los estadísticos de dispersión se basan en cómo se distribuyen los datos y qué tan esparcidos están. Algunas medidas de dispersión son:</p>
<ul>
<li><strong>Rango:</strong> La diferencia entre el valor máximo y el valor mínimo de un conjunto de datos. Para obtener el valor del rango utilizamos la ecuación <a href="estadística-descriptiva.html#eq:range">(2.3)</a>.</li>
</ul>
<p><span class="math display" id="eq:range">\[\begin{equation}
  rango = x_{max} - x_{max}
\tag{2.3}
\end{equation}\]</span></p>
<ul>
<li><strong>Desviación estándar:</strong> Indica qué tan dispersos están los datos respecto a la media. Es la medida de dispersión más usada. Para obtener la desviación estándar utilizamos la ecuación <a href="estadística-descriptiva.html#eq:sd">(2.4)</a>.</li>
</ul>
<p><span class="math display" id="eq:sd">\[\begin{equation}
  s = \sqrt{\frac{\sum_{i = 1}^{n}( {x_i-\overline{x} ) ^2}}{n-1}}
\tag{2.4}
\end{equation}\]</span></p>
<p>Donde <span class="math inline">\(\sum_{i = 1}^{n}({x_i-\overline{x})^2}\)</span> es igual al valor cada observación menos la media, elevado al cuadrado y el apartado <span class="math inline">\({n-1}\)</span> corresponde a los grados de libertad que tenemos para el cálculo de la desviación estándar.</p>
<p>Una medida derivad de la desviación estándar es la varianza. Se obtiene de forma sencilla como lo indica la ecuación <a href="estadística-descriptiva.html#eq:var">(2.5)</a>.</p>
<p><span class="math display" id="eq:var">\[\begin{equation}
  Varianza = {s}^2
  \tag{2.5}
\end{equation}\]</span></p>
<div id="rango-en-r" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Rango en R</h3>
<p>El rango es simplemente la diferencia entre el valor más grande y el más chico. Su calculo en R se puede hacer con la función <code>range()</code>.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="estadística-descriptiva.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(iris<span class="sc">$</span>Petal.Length)</span></code></pre></div>
<pre><code>## [1] 1.0 6.9</code></pre>
<p>A partir del output de está función podemos hacer el cálculo del rango.
<span class="math display">\[
Rango = 6.9 - 1 = 5.9
\]</span></p>
<p>Otra forma de hacer el cálculo de manera directa es con las funciones <code>min()</code> y <code>max()</code>.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="estadística-descriptiva.html#cb89-1" aria-hidden="true" tabindex="-1"></a>Rango <span class="ot">&lt;-</span> <span class="fu">max</span>(iris<span class="sc">$</span>Petal.Length) <span class="sc">-</span> <span class="fu">min</span>(iris<span class="sc">$</span>Petal.Length)</span>
<span id="cb89-2"><a href="estadística-descriptiva.html#cb89-2" aria-hidden="true" tabindex="-1"></a>Rango</span></code></pre></div>
<pre><code>## [1] 5.9</code></pre>
</div>
<div id="desviación-estándar-en-r" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Desviación estándar en R</h3>
<p>Para obtener la desviación estándar en R lo único que necesitamos es utilizar la función <code>sd()</code>.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="estadística-descriptiva.html#cb91-1" aria-hidden="true" tabindex="-1"></a>SD <span class="ot">&lt;-</span> <span class="fu">sd</span>(iris<span class="sc">$</span>Petal.Length)</span>
<span id="cb91-2"><a href="estadística-descriptiva.html#cb91-2" aria-hidden="true" tabindex="-1"></a>SD</span></code></pre></div>
<pre><code>## [1] 1.765298</code></pre>
<p>En caso de querer obtener la varianza, simplemente elevamos nuestro valor al cuadrado.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="estadística-descriptiva.html#cb93-1" aria-hidden="true" tabindex="-1"></a>Var <span class="ot">&lt;-</span> SD<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb93-2"><a href="estadística-descriptiva.html#cb93-2" aria-hidden="true" tabindex="-1"></a>Var</span></code></pre></div>
<pre><code>## [1] 3.116278</code></pre>
</div>
</div>
<div id="medidas-de-posición" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Medidas de posición</h2>
<p>Podemos hacer también el calculo de medidas de posición como las siguientes:</p>
<ul>
<li><p><strong>Frecuencia absoluta:</strong> Es el valor total de los datos que observamos.</p></li>
<li><p><strong>Frecuencia relativa:</strong> Es el valor relativo de cada dato respecto del total como se observa en la ecuación <a href="estadística-descriptiva.html#eq:frecr">(2.6)</a>. Si se le multiplica por 100% se obtiene su valor en porcentaje.</p></li>
</ul>
<p><span class="math display" id="eq:frecr">\[\begin{equation}
  f_i = \frac{n_i}{N}
\tag{2.6}
\end{equation}\]</span></p>
<p>En este caso, utilizaremos la base de datos de aves que vimos en la lección anterior.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="estadística-descriptiva.html#cb95-1" aria-hidden="true" tabindex="-1"></a>Aves <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;Aves.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Para obtener la frecuencia absoluta utilizamos al función <code>table()</code> y el argumento <code>Aves$ambiente</code> para obtener la frecuencia de aves del bosque y aves de arbustales.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="estadística-descriptiva.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Aves<span class="sc">$</span>ambiente)</span></code></pre></div>
<pre><code>## 
## arbustal   bosque 
##       20       16</code></pre>
<p>En caso de querer las frecuencias relativas, podemos usar la función <code>prop.table()</code> y el mismo argumento de <code>Aves$ambiente</code>. Para esto debemos tener las frecuencias absolutas guardadas en una variable.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="estadística-descriptiva.html#cb98-1" aria-hidden="true" tabindex="-1"></a>Frecab <span class="ot">&lt;-</span> <span class="fu">table</span>(Aves<span class="sc">$</span>ambiente)</span>
<span id="cb98-2"><a href="estadística-descriptiva.html#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(Frecab)</span></code></pre></div>
<pre><code>## 
##  arbustal    bosque 
## 0.5555556 0.4444444</code></pre>
<p>Para facilitar la lectura vamos a transformar las frecuencias relativas a porcentajes multiplicando por 100 y utilizando la función <code>round()</code> para redondear los valores a 2 dígitos.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="estadística-descriptiva.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>((<span class="fu">prop.table</span>(Frecab) <span class="sc">*</span> <span class="dv">100</span>), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## 
## arbustal   bosque 
##    55.56    44.44</code></pre>
<p>Podemos ver que el 55.56% de las aves son de hábitos arbustivos mientras que el 44.44% prefieren los bosques.</p>
</div>
<div id="el-uso-de-la-librería-dplyr" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> El uso de la librería <code>dplyr</code></h2>
<p>Para facilitar aún más las cosas podemos utilizar las herramientas de la librería <code>dplyr</code> que vienen incluidas en el paquete de <code>tidyverse</code>.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="estadística-descriptiva.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>Las funciones más importantes de este paquete son:</p>
<ul>
<li><p><code>group_by:</code> agrupa datos.</p></li>
<li><p><code>summarize</code> o <code>summarise:</code> resumen de datos agrupados.</p></li>
<li><p><code>filter:</code> encuentra filas con ciertas condiciones.</p></li>
<li><p><code>select:</code> junto a ‘starts_with,’ ‘ends_with’ o ‘contains’</p></li>
<li><p><code>mutate:</code> genera nuevas variables.</p></li>
<li><p><code>%&gt;%:</code> pipeline.</p></li>
<li><p><code>arrange:</code> ordena.</p></li>
</ul>
<p>Con <code>dplyr</code> la extracción de la media y la mediana es a través de la función <code>summarise</code> y sería así:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="estadística-descriptiva.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;iris&quot;</span>)</span>
<span id="cb103-2"><a href="estadística-descriptiva.html#cb103-2" aria-hidden="true" tabindex="-1"></a>resum.iris <span class="ot">&lt;-</span> <span class="fu">summarise</span>(iris, <span class="at">Petal.Length.Mean =</span> <span class="fu">mean</span>(Petal.Length), <span class="at">Petal.Length.Median =</span> <span class="fu">median</span>(Petal.Length))</span>
<span id="cb103-3"><a href="estadística-descriptiva.html#cb103-3" aria-hidden="true" tabindex="-1"></a>resum.iris</span></code></pre></div>
<pre><code>##   Petal.Length.Mean Petal.Length.Median
## 1             3.758                4.35</code></pre>
<p>Pero supongamos que quiero extraer estos valores de cada una de las especies. Para esto utilizamos la función <code>group_by</code>:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="estadística-descriptiva.html#cb105-1" aria-hidden="true" tabindex="-1"></a>iris.especies <span class="ot">&lt;-</span> <span class="fu">group_by</span>(iris, Species) <span class="co">#Aparentemente esta función no cambia la matriz de datos, sin embargo si hacemos un summarise estos se ordenarán por la forma en que los agrupamos.</span></span>
<span id="cb105-2"><a href="estadística-descriptiva.html#cb105-2" aria-hidden="true" tabindex="-1"></a>resum.iris.especies <span class="ot">&lt;-</span> <span class="fu">summarise</span>(iris.especies, <span class="at">Petal.Length.Mean =</span> <span class="fu">mean</span>(Petal.Length), <span class="at">Petal.Length.Median =</span> <span class="fu">median</span>(Petal.Length))</span>
<span id="cb105-3"><a href="estadística-descriptiva.html#cb105-3" aria-hidden="true" tabindex="-1"></a>resum.iris.especies</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   Species    Petal.Length.Mean Petal.Length.Median
##   &lt;fct&gt;                  &lt;dbl&gt;               &lt;dbl&gt;
## 1 setosa                  1.46                1.5 
## 2 versicolor              4.26                4.35
## 3 virginica               5.55                5.55</code></pre>
<p>Con la función <code>mutate</code> nosotros podemos crear nuevas variables. Por ejemplo, la relación entre longitud del pétalo-ancho del pétalo.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="estadística-descriptiva.html#cb107-1" aria-hidden="true" tabindex="-1"></a>iris <span class="ot">&lt;-</span> <span class="fu">mutate</span>(iris, <span class="at">Petal.Leng.Wid.Ratio =</span> Petal.Length<span class="sc">/</span>Petal.Width)</span>
<span id="cb107-2"><a href="estadística-descriptiva.html#cb107-2" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">$</span>Petal.Leng.Wid.Ratio</span></code></pre></div>
<pre><code>##   [1]  7.000000  7.000000  6.500000  7.500000  7.000000  4.250000  4.666667
##   [8]  7.500000  7.000000 15.000000  7.500000  8.000000 14.000000 11.000000
##  [15]  6.000000  3.750000  3.250000  4.666667  5.666667  5.000000  8.500000
##  [22]  3.750000  5.000000  3.400000  9.500000  8.000000  4.000000  7.500000
##  [29]  7.000000  8.000000  8.000000  3.750000 15.000000  7.000000  7.500000
##  [36]  6.000000  6.500000 14.000000  6.500000  7.500000  4.333333  4.333333
##  [43]  6.500000  2.666667  4.750000  4.666667  8.000000  7.000000  7.500000
##  [50]  7.000000  3.357143  3.000000  3.266667  3.076923  3.066667  3.461538
##  [57]  2.937500  3.300000  3.538462  2.785714  3.500000  2.800000  4.000000
##  [64]  3.357143  2.769231  3.142857  3.000000  4.100000  3.000000  3.545455
##  [71]  2.666667  3.076923  3.266667  3.916667  3.307692  3.142857  3.428571
##  [78]  2.941176  3.000000  3.500000  3.454545  3.700000  3.250000  3.187500
##  [85]  3.000000  2.812500  3.133333  3.384615  3.153846  3.076923  3.666667
##  [92]  3.285714  3.333333  3.300000  3.230769  3.500000  3.230769  3.307692
##  [99]  2.727273  3.153846  2.400000  2.684211  2.809524  3.111111  2.636364
## [106]  3.142857  2.647059  3.500000  3.222222  2.440000  2.550000  2.789474
## [113]  2.619048  2.500000  2.125000  2.304348  3.055556  3.045455  3.000000
## [120]  3.333333  2.478261  2.450000  3.350000  2.722222  2.714286  3.333333
## [127]  2.666667  2.722222  2.666667  3.625000  3.210526  3.200000  2.545455
## [134]  3.400000  4.000000  2.652174  2.333333  3.055556  2.666667  2.571429
## [141]  2.333333  2.217391  2.684211  2.565217  2.280000  2.260870  2.631579
## [148]  2.600000  2.347826  2.833333</code></pre>
<p>Para realizar operaciones de manera secuencial utilizamos el <code>pipeline %&gt;%</code>. En lugar de escribir el siguiente código y asignar dos variables, podemos hacer todo de una.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="estadística-descriptiva.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#iris.especies &lt;- group_by(iris, Species)</span></span>
<span id="cb109-2"><a href="estadística-descriptiva.html#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="co">#resum.iris.especies &lt;- summarise(iris.especies, Petal.Length.Mean = mean(Petal.Length), Petal.Length.Median = median(Petal.Length)) </span></span>
<span id="cb109-3"><a href="estadística-descriptiva.html#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="estadística-descriptiva.html#cb109-4" aria-hidden="true" tabindex="-1"></a>resum.iris.especies2 <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span></span>
<span id="cb109-5"><a href="estadística-descriptiva.html#cb109-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span> </span>
<span id="cb109-6"><a href="estadística-descriptiva.html#cb109-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Petal.Length.Mean =</span> <span class="fu">mean</span>(Petal.Length), <span class="at">Petal.Length.Median =</span> <span class="fu">median</span>(Petal.Length))</span>
<span id="cb109-7"><a href="estadística-descriptiva.html#cb109-7" aria-hidden="true" tabindex="-1"></a>resum.iris.especies2</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   Species    Petal.Length.Mean Petal.Length.Median
##   &lt;fct&gt;                  &lt;dbl&gt;               &lt;dbl&gt;
## 1 setosa                  1.46                1.5 
## 2 versicolor              4.26                4.35
## 3 virginica               5.55                5.55</code></pre>
<p>Trabajar de esta forma es más cómodo y más claro.</p>
<p>Para hacer filtros utilizamos la función <code>filter</code>. Sin embargo, como posiblemente hay otros paquetes que han nombrado una función igual, para evitar conflictos agregamos <code>dplyr::</code> antes de la función <code>filter</code> para especificar que queremos trabajar con el <code>filter</code> del paquete de <code>dplyr</code>. Hagamos un ejemplo de filtrado de la matriz de datos <code>iris</code> para obtener solamente las especies de <em>I. versicolor</em>.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="estadística-descriptiva.html#cb111-1" aria-hidden="true" tabindex="-1"></a>iris.versicolor <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">&quot;versicolor&quot;</span>)</span>
<span id="cb111-2"><a href="estadística-descriptiva.html#cb111-2" aria-hidden="true" tabindex="-1"></a>iris.versicolor</span></code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
## 1           7.0         3.2          4.7         1.4 versicolor
## 2           6.4         3.2          4.5         1.5 versicolor
## 3           6.9         3.1          4.9         1.5 versicolor
## 4           5.5         2.3          4.0         1.3 versicolor
## 5           6.5         2.8          4.6         1.5 versicolor
## 6           5.7         2.8          4.5         1.3 versicolor
## 7           6.3         3.3          4.7         1.6 versicolor
## 8           4.9         2.4          3.3         1.0 versicolor
## 9           6.6         2.9          4.6         1.3 versicolor
## 10          5.2         2.7          3.9         1.4 versicolor
## 11          5.0         2.0          3.5         1.0 versicolor
## 12          5.9         3.0          4.2         1.5 versicolor
## 13          6.0         2.2          4.0         1.0 versicolor
## 14          6.1         2.9          4.7         1.4 versicolor
## 15          5.6         2.9          3.6         1.3 versicolor
## 16          6.7         3.1          4.4         1.4 versicolor
## 17          5.6         3.0          4.5         1.5 versicolor
## 18          5.8         2.7          4.1         1.0 versicolor
## 19          6.2         2.2          4.5         1.5 versicolor
## 20          5.6         2.5          3.9         1.1 versicolor
## 21          5.9         3.2          4.8         1.8 versicolor
## 22          6.1         2.8          4.0         1.3 versicolor
## 23          6.3         2.5          4.9         1.5 versicolor
## 24          6.1         2.8          4.7         1.2 versicolor
## 25          6.4         2.9          4.3         1.3 versicolor
## 26          6.6         3.0          4.4         1.4 versicolor
## 27          6.8         2.8          4.8         1.4 versicolor
## 28          6.7         3.0          5.0         1.7 versicolor
## 29          6.0         2.9          4.5         1.5 versicolor
## 30          5.7         2.6          3.5         1.0 versicolor
## 31          5.5         2.4          3.8         1.1 versicolor
## 32          5.5         2.4          3.7         1.0 versicolor
## 33          5.8         2.7          3.9         1.2 versicolor
## 34          6.0         2.7          5.1         1.6 versicolor
## 35          5.4         3.0          4.5         1.5 versicolor
## 36          6.0         3.4          4.5         1.6 versicolor
## 37          6.7         3.1          4.7         1.5 versicolor
## 38          6.3         2.3          4.4         1.3 versicolor
## 39          5.6         3.0          4.1         1.3 versicolor
## 40          5.5         2.5          4.0         1.3 versicolor
## 41          5.5         2.6          4.4         1.2 versicolor
## 42          6.1         3.0          4.6         1.4 versicolor
## 43          5.8         2.6          4.0         1.2 versicolor
## 44          5.0         2.3          3.3         1.0 versicolor
## 45          5.6         2.7          4.2         1.3 versicolor
## 46          5.7         3.0          4.2         1.2 versicolor
## 47          5.7         2.9          4.2         1.3 versicolor
## 48          6.2         2.9          4.3         1.3 versicolor
## 49          5.1         2.5          3.0         1.1 versicolor
## 50          5.7         2.8          4.1         1.3 versicolor
##    Petal.Leng.Wid.Ratio
## 1              3.357143
## 2              3.000000
## 3              3.266667
## 4              3.076923
## 5              3.066667
## 6              3.461538
## 7              2.937500
## 8              3.300000
## 9              3.538462
## 10             2.785714
## 11             3.500000
## 12             2.800000
## 13             4.000000
## 14             3.357143
## 15             2.769231
## 16             3.142857
## 17             3.000000
## 18             4.100000
## 19             3.000000
## 20             3.545455
## 21             2.666667
## 22             3.076923
## 23             3.266667
## 24             3.916667
## 25             3.307692
## 26             3.142857
## 27             3.428571
## 28             2.941176
## 29             3.000000
## 30             3.500000
## 31             3.454545
## 32             3.700000
## 33             3.250000
## 34             3.187500
## 35             3.000000
## 36             2.812500
## 37             3.133333
## 38             3.384615
## 39             3.153846
## 40             3.076923
## 41             3.666667
## 42             3.285714
## 43             3.333333
## 44             3.300000
## 45             3.230769
## 46             3.500000
## 47             3.230769
## 48             3.307692
## 49             2.727273
## 50             3.153846</code></pre>
<p>Como podemos ver, hemos filtrado a todas las especies pertenecientes a <em>I. versicolor</em>.</p>
<table class="table table-striped table-bordered table-hover" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-71">Tabla 2.1: </span>Símbolos utilizados con la función filter
</caption>
<thead>
<tr>
<th style="text-align:left;">
Símbolo
</th>
<th style="text-align:left;">
Significado
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
&gt;
</td>
<td style="text-align:left;">
Mayor que
</td>
</tr>
<tr>
<td style="text-align:left;">
&lt;
</td>
<td style="text-align:left;">
Menor que
</td>
</tr>
<tr>
<td style="text-align:left;">
==
</td>
<td style="text-align:left;">
Igual a
</td>
</tr>
<tr>
<td style="text-align:left;">
&gt;=
</td>
<td style="text-align:left;">
Mayor o igual a
</td>
</tr>
<tr>
<td style="text-align:left;">
&lt;=
</td>
<td style="text-align:left;">
Menor o igual a
</td>
</tr>
<tr>
<td style="text-align:left;">
!=
</td>
<td style="text-align:left;">
Distinto a
</td>
</tr>
<tr>
<td style="text-align:left;">
%in%
</td>
<td style="text-align:left;">
Dentro del grupo
</td>
</tr>
<tr>
<td style="text-align:left;">
is.na
</td>
<td style="text-align:left;">
Es NA
</td>
</tr>
<tr>
<td style="text-align:left;">
!is.na
</td>
<td style="text-align:left;">
No es NA
</td>
</tr>
<tr>
<td style="text-align:left;">
|, &amp;
</td>
<td style="text-align:left;">
O, Y
</td>
</tr>
</tbody>
</table>
<p>Habíamos visto un individuo de la especie de <em>I. virginica</em> que tenía un valor en la longitud del sépalo menor a la cerca inferior de 5.2125 por lo que se le consideraba un valor atípico. Podemos encontrar este valor utilizando la función <code>dplyr::filter()</code>.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="estadística-descriptiva.html#cb113-1" aria-hidden="true" tabindex="-1"></a>outlier <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">&quot;virginica&quot;</span>, Sepal.Length <span class="sc">&lt;=</span> <span class="fl">5.2125</span>)</span>
<span id="cb113-2"><a href="estadística-descriptiva.html#cb113-2" aria-hidden="true" tabindex="-1"></a>outlier</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 1          4.9         2.5          4.5         1.7 virginica
##   Petal.Leng.Wid.Ratio
## 1             2.647059</code></pre>
<p>Así podemos corroborar las otras medidas que este valor presenta, para verificar que no sean atípica en sus correspondientes cuartiles.</p>
<p>Podemos utilizar otra función llamada <code>n()</code> junto con <code>summarise()</code> para obtener las frecuencias absolutas de nuestros datos.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="estadística-descriptiva.html#cb115-1" aria-hidden="true" tabindex="-1"></a>Frecuencias <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span></span>
<span id="cb115-2"><a href="estadística-descriptiva.html#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span> </span>
<span id="cb115-3"><a href="estadística-descriptiva.html#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Frecuencia_absoluta =</span> <span class="fu">n</span>())</span>
<span id="cb115-4"><a href="estadística-descriptiva.html#cb115-4" aria-hidden="true" tabindex="-1"></a>Frecuencias</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   Species    Frecuencia_absoluta
##   &lt;fct&gt;                    &lt;int&gt;
## 1 setosa                      50
## 2 versicolor                  50
## 3 virginica                   50</code></pre>
<p>Para obtener la frecuencia relativa utilizamos la función <code>mutate</code> para agregar una nueva variable llamada <code>Frecuencia_relativa</code> junto con la función <code>sum</code> para obtener el número total de observaciones <span class="math inline">\(N\)</span> de la ecuación <a href="estadística-descriptiva.html#eq:frecr">(2.6)</a> para nuestros datos.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="estadística-descriptiva.html#cb117-1" aria-hidden="true" tabindex="-1"></a>Frecuencias <span class="ot">&lt;-</span> Frecuencias <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Frecuencia_relativa =</span> Frecuencia_absoluta <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia_absoluta))</span>
<span id="cb117-2"><a href="estadística-descriptiva.html#cb117-2" aria-hidden="true" tabindex="-1"></a>Frecuencias</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   Species    Frecuencia_absoluta Frecuencia_relativa
##   &lt;fct&gt;                    &lt;int&gt;               &lt;dbl&gt;
## 1 setosa                      50               0.333
## 2 versicolor                  50               0.333
## 3 virginica                   50               0.333</code></pre>
<p>Y si quisiéramos obtener el porcentaje, de nuevo podemos utilizar la función <code>mutate</code> y multiplicando la variable <code>Frecuencia_relativa</code> por 100%.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="estadística-descriptiva.html#cb119-1" aria-hidden="true" tabindex="-1"></a>Frecuencias <span class="ot">&lt;-</span> Frecuencias <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> Frecuencia_relativa<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb119-2"><a href="estadística-descriptiva.html#cb119-2" aria-hidden="true" tabindex="-1"></a>Frecuencias</span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   Species    Frecuencia_absoluta Frecuencia_relativa Porcentaje
##   &lt;fct&gt;                    &lt;int&gt;               &lt;dbl&gt;      &lt;dbl&gt;
## 1 setosa                      50               0.333       33.3
## 2 versicolor                  50               0.333       33.3
## 3 virginica                   50               0.333       33.3</code></pre>
<p>Con la función <code>select</code> podemos elegir unas cuantas variables para trabajar. Esto es útil para bases de datos con muchas variables como matrices de abundancias.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="estadística-descriptiva.html#cb121-1" aria-hidden="true" tabindex="-1"></a>Petals <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(Petal.Length, Petal.Width, Species)</span>
<span id="cb121-2"><a href="estadística-descriptiva.html#cb121-2" aria-hidden="true" tabindex="-1"></a>Petals</span></code></pre></div>
<pre><code>##     Petal.Length Petal.Width    Species
## 1            1.4         0.2     setosa
## 2            1.4         0.2     setosa
## 3            1.3         0.2     setosa
## 4            1.5         0.2     setosa
## 5            1.4         0.2     setosa
## 6            1.7         0.4     setosa
## 7            1.4         0.3     setosa
## 8            1.5         0.2     setosa
## 9            1.4         0.2     setosa
## 10           1.5         0.1     setosa
## 11           1.5         0.2     setosa
## 12           1.6         0.2     setosa
## 13           1.4         0.1     setosa
## 14           1.1         0.1     setosa
## 15           1.2         0.2     setosa
## 16           1.5         0.4     setosa
## 17           1.3         0.4     setosa
## 18           1.4         0.3     setosa
## 19           1.7         0.3     setosa
## 20           1.5         0.3     setosa
## 21           1.7         0.2     setosa
## 22           1.5         0.4     setosa
## 23           1.0         0.2     setosa
## 24           1.7         0.5     setosa
## 25           1.9         0.2     setosa
## 26           1.6         0.2     setosa
## 27           1.6         0.4     setosa
## 28           1.5         0.2     setosa
## 29           1.4         0.2     setosa
## 30           1.6         0.2     setosa
## 31           1.6         0.2     setosa
## 32           1.5         0.4     setosa
## 33           1.5         0.1     setosa
## 34           1.4         0.2     setosa
## 35           1.5         0.2     setosa
## 36           1.2         0.2     setosa
## 37           1.3         0.2     setosa
## 38           1.4         0.1     setosa
## 39           1.3         0.2     setosa
## 40           1.5         0.2     setosa
## 41           1.3         0.3     setosa
## 42           1.3         0.3     setosa
## 43           1.3         0.2     setosa
## 44           1.6         0.6     setosa
## 45           1.9         0.4     setosa
## 46           1.4         0.3     setosa
## 47           1.6         0.2     setosa
## 48           1.4         0.2     setosa
## 49           1.5         0.2     setosa
## 50           1.4         0.2     setosa
## 51           4.7         1.4 versicolor
## 52           4.5         1.5 versicolor
## 53           4.9         1.5 versicolor
## 54           4.0         1.3 versicolor
## 55           4.6         1.5 versicolor
## 56           4.5         1.3 versicolor
## 57           4.7         1.6 versicolor
## 58           3.3         1.0 versicolor
## 59           4.6         1.3 versicolor
## 60           3.9         1.4 versicolor
## 61           3.5         1.0 versicolor
## 62           4.2         1.5 versicolor
## 63           4.0         1.0 versicolor
## 64           4.7         1.4 versicolor
## 65           3.6         1.3 versicolor
## 66           4.4         1.4 versicolor
## 67           4.5         1.5 versicolor
## 68           4.1         1.0 versicolor
## 69           4.5         1.5 versicolor
## 70           3.9         1.1 versicolor
## 71           4.8         1.8 versicolor
## 72           4.0         1.3 versicolor
## 73           4.9         1.5 versicolor
## 74           4.7         1.2 versicolor
## 75           4.3         1.3 versicolor
## 76           4.4         1.4 versicolor
## 77           4.8         1.4 versicolor
## 78           5.0         1.7 versicolor
## 79           4.5         1.5 versicolor
## 80           3.5         1.0 versicolor
## 81           3.8         1.1 versicolor
## 82           3.7         1.0 versicolor
## 83           3.9         1.2 versicolor
## 84           5.1         1.6 versicolor
## 85           4.5         1.5 versicolor
## 86           4.5         1.6 versicolor
## 87           4.7         1.5 versicolor
## 88           4.4         1.3 versicolor
## 89           4.1         1.3 versicolor
## 90           4.0         1.3 versicolor
## 91           4.4         1.2 versicolor
## 92           4.6         1.4 versicolor
## 93           4.0         1.2 versicolor
## 94           3.3         1.0 versicolor
## 95           4.2         1.3 versicolor
## 96           4.2         1.2 versicolor
## 97           4.2         1.3 versicolor
## 98           4.3         1.3 versicolor
## 99           3.0         1.1 versicolor
## 100          4.1         1.3 versicolor
## 101          6.0         2.5  virginica
## 102          5.1         1.9  virginica
## 103          5.9         2.1  virginica
## 104          5.6         1.8  virginica
## 105          5.8         2.2  virginica
## 106          6.6         2.1  virginica
## 107          4.5         1.7  virginica
## 108          6.3         1.8  virginica
## 109          5.8         1.8  virginica
## 110          6.1         2.5  virginica
## 111          5.1         2.0  virginica
## 112          5.3         1.9  virginica
## 113          5.5         2.1  virginica
## 114          5.0         2.0  virginica
## 115          5.1         2.4  virginica
## 116          5.3         2.3  virginica
## 117          5.5         1.8  virginica
## 118          6.7         2.2  virginica
## 119          6.9         2.3  virginica
## 120          5.0         1.5  virginica
## 121          5.7         2.3  virginica
## 122          4.9         2.0  virginica
## 123          6.7         2.0  virginica
## 124          4.9         1.8  virginica
## 125          5.7         2.1  virginica
## 126          6.0         1.8  virginica
## 127          4.8         1.8  virginica
## 128          4.9         1.8  virginica
## 129          5.6         2.1  virginica
## 130          5.8         1.6  virginica
## 131          6.1         1.9  virginica
## 132          6.4         2.0  virginica
## 133          5.6         2.2  virginica
## 134          5.1         1.5  virginica
## 135          5.6         1.4  virginica
## 136          6.1         2.3  virginica
## 137          5.6         2.4  virginica
## 138          5.5         1.8  virginica
## 139          4.8         1.8  virginica
## 140          5.4         2.1  virginica
## 141          5.6         2.4  virginica
## 142          5.1         2.3  virginica
## 143          5.1         1.9  virginica
## 144          5.9         2.3  virginica
## 145          5.7         2.5  virginica
## 146          5.2         2.3  virginica
## 147          5.0         1.9  virginica
## 148          5.2         2.0  virginica
## 149          5.4         2.3  virginica
## 150          5.1         1.8  virginica</code></pre>
<p>En este caso, eliminamos los datos de los sépalos y nos quedamos con los datos solamente de los pétalos. Otra forma de seleccionar las variables es con el argumento <code>starts_with()</code>, por ejemplo, para seleccionar solamente las variables que empiecen con la palabra “Petal.”</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="estadística-descriptiva.html#cb123-1" aria-hidden="true" tabindex="-1"></a>Petals2 <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;Petal&quot;</span>), Species)</span>
<span id="cb123-2"><a href="estadística-descriptiva.html#cb123-2" aria-hidden="true" tabindex="-1"></a>Petals2</span></code></pre></div>
<pre><code>##     Petal.Length Petal.Width Petal.Leng.Wid.Ratio    Species
## 1            1.4         0.2             7.000000     setosa
## 2            1.4         0.2             7.000000     setosa
## 3            1.3         0.2             6.500000     setosa
## 4            1.5         0.2             7.500000     setosa
## 5            1.4         0.2             7.000000     setosa
## 6            1.7         0.4             4.250000     setosa
## 7            1.4         0.3             4.666667     setosa
## 8            1.5         0.2             7.500000     setosa
## 9            1.4         0.2             7.000000     setosa
## 10           1.5         0.1            15.000000     setosa
## 11           1.5         0.2             7.500000     setosa
## 12           1.6         0.2             8.000000     setosa
## 13           1.4         0.1            14.000000     setosa
## 14           1.1         0.1            11.000000     setosa
## 15           1.2         0.2             6.000000     setosa
## 16           1.5         0.4             3.750000     setosa
## 17           1.3         0.4             3.250000     setosa
## 18           1.4         0.3             4.666667     setosa
## 19           1.7         0.3             5.666667     setosa
## 20           1.5         0.3             5.000000     setosa
## 21           1.7         0.2             8.500000     setosa
## 22           1.5         0.4             3.750000     setosa
## 23           1.0         0.2             5.000000     setosa
## 24           1.7         0.5             3.400000     setosa
## 25           1.9         0.2             9.500000     setosa
## 26           1.6         0.2             8.000000     setosa
## 27           1.6         0.4             4.000000     setosa
## 28           1.5         0.2             7.500000     setosa
## 29           1.4         0.2             7.000000     setosa
## 30           1.6         0.2             8.000000     setosa
## 31           1.6         0.2             8.000000     setosa
## 32           1.5         0.4             3.750000     setosa
## 33           1.5         0.1            15.000000     setosa
## 34           1.4         0.2             7.000000     setosa
## 35           1.5         0.2             7.500000     setosa
## 36           1.2         0.2             6.000000     setosa
## 37           1.3         0.2             6.500000     setosa
## 38           1.4         0.1            14.000000     setosa
## 39           1.3         0.2             6.500000     setosa
## 40           1.5         0.2             7.500000     setosa
## 41           1.3         0.3             4.333333     setosa
## 42           1.3         0.3             4.333333     setosa
## 43           1.3         0.2             6.500000     setosa
## 44           1.6         0.6             2.666667     setosa
## 45           1.9         0.4             4.750000     setosa
## 46           1.4         0.3             4.666667     setosa
## 47           1.6         0.2             8.000000     setosa
## 48           1.4         0.2             7.000000     setosa
## 49           1.5         0.2             7.500000     setosa
## 50           1.4         0.2             7.000000     setosa
## 51           4.7         1.4             3.357143 versicolor
## 52           4.5         1.5             3.000000 versicolor
## 53           4.9         1.5             3.266667 versicolor
## 54           4.0         1.3             3.076923 versicolor
## 55           4.6         1.5             3.066667 versicolor
## 56           4.5         1.3             3.461538 versicolor
## 57           4.7         1.6             2.937500 versicolor
## 58           3.3         1.0             3.300000 versicolor
## 59           4.6         1.3             3.538462 versicolor
## 60           3.9         1.4             2.785714 versicolor
## 61           3.5         1.0             3.500000 versicolor
## 62           4.2         1.5             2.800000 versicolor
## 63           4.0         1.0             4.000000 versicolor
## 64           4.7         1.4             3.357143 versicolor
## 65           3.6         1.3             2.769231 versicolor
## 66           4.4         1.4             3.142857 versicolor
## 67           4.5         1.5             3.000000 versicolor
## 68           4.1         1.0             4.100000 versicolor
## 69           4.5         1.5             3.000000 versicolor
## 70           3.9         1.1             3.545455 versicolor
## 71           4.8         1.8             2.666667 versicolor
## 72           4.0         1.3             3.076923 versicolor
## 73           4.9         1.5             3.266667 versicolor
## 74           4.7         1.2             3.916667 versicolor
## 75           4.3         1.3             3.307692 versicolor
## 76           4.4         1.4             3.142857 versicolor
## 77           4.8         1.4             3.428571 versicolor
## 78           5.0         1.7             2.941176 versicolor
## 79           4.5         1.5             3.000000 versicolor
## 80           3.5         1.0             3.500000 versicolor
## 81           3.8         1.1             3.454545 versicolor
## 82           3.7         1.0             3.700000 versicolor
## 83           3.9         1.2             3.250000 versicolor
## 84           5.1         1.6             3.187500 versicolor
## 85           4.5         1.5             3.000000 versicolor
## 86           4.5         1.6             2.812500 versicolor
## 87           4.7         1.5             3.133333 versicolor
## 88           4.4         1.3             3.384615 versicolor
## 89           4.1         1.3             3.153846 versicolor
## 90           4.0         1.3             3.076923 versicolor
## 91           4.4         1.2             3.666667 versicolor
## 92           4.6         1.4             3.285714 versicolor
## 93           4.0         1.2             3.333333 versicolor
## 94           3.3         1.0             3.300000 versicolor
## 95           4.2         1.3             3.230769 versicolor
## 96           4.2         1.2             3.500000 versicolor
## 97           4.2         1.3             3.230769 versicolor
## 98           4.3         1.3             3.307692 versicolor
## 99           3.0         1.1             2.727273 versicolor
## 100          4.1         1.3             3.153846 versicolor
## 101          6.0         2.5             2.400000  virginica
## 102          5.1         1.9             2.684211  virginica
## 103          5.9         2.1             2.809524  virginica
## 104          5.6         1.8             3.111111  virginica
## 105          5.8         2.2             2.636364  virginica
## 106          6.6         2.1             3.142857  virginica
## 107          4.5         1.7             2.647059  virginica
## 108          6.3         1.8             3.500000  virginica
## 109          5.8         1.8             3.222222  virginica
## 110          6.1         2.5             2.440000  virginica
## 111          5.1         2.0             2.550000  virginica
## 112          5.3         1.9             2.789474  virginica
## 113          5.5         2.1             2.619048  virginica
## 114          5.0         2.0             2.500000  virginica
## 115          5.1         2.4             2.125000  virginica
## 116          5.3         2.3             2.304348  virginica
## 117          5.5         1.8             3.055556  virginica
## 118          6.7         2.2             3.045455  virginica
## 119          6.9         2.3             3.000000  virginica
## 120          5.0         1.5             3.333333  virginica
## 121          5.7         2.3             2.478261  virginica
## 122          4.9         2.0             2.450000  virginica
## 123          6.7         2.0             3.350000  virginica
## 124          4.9         1.8             2.722222  virginica
## 125          5.7         2.1             2.714286  virginica
## 126          6.0         1.8             3.333333  virginica
## 127          4.8         1.8             2.666667  virginica
## 128          4.9         1.8             2.722222  virginica
## 129          5.6         2.1             2.666667  virginica
## 130          5.8         1.6             3.625000  virginica
## 131          6.1         1.9             3.210526  virginica
## 132          6.4         2.0             3.200000  virginica
## 133          5.6         2.2             2.545455  virginica
## 134          5.1         1.5             3.400000  virginica
## 135          5.6         1.4             4.000000  virginica
## 136          6.1         2.3             2.652174  virginica
## 137          5.6         2.4             2.333333  virginica
## 138          5.5         1.8             3.055556  virginica
## 139          4.8         1.8             2.666667  virginica
## 140          5.4         2.1             2.571429  virginica
## 141          5.6         2.4             2.333333  virginica
## 142          5.1         2.3             2.217391  virginica
## 143          5.1         1.9             2.684211  virginica
## 144          5.9         2.3             2.565217  virginica
## 145          5.7         2.5             2.280000  virginica
## 146          5.2         2.3             2.260870  virginica
## 147          5.0         1.9             2.631579  virginica
## 148          5.2         2.0             2.600000  virginica
## 149          5.4         2.3             2.347826  virginica
## 150          5.1         1.8             2.833333  virginica</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introducción-a-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="análisis-de-varianza-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
