<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 5 Inferencia de datos categóricos | Curso de R básico</title>
  <meta name="description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 5 Inferencia de datos categóricos | Curso de R básico" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 5 Inferencia de datos categóricos | Curso de R básico" />
  
  <meta name="twitter:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="estadística-inferencial.html"/>
<link rel="next" href="modelado-de-relaciones.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de R básico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Requisitos</a>
<ul>
<li><a href="index.html#descarga-de-r-y-rstudio">Descarga de <code>R</code> y RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introducción-a-r.html"><a href="introducción-a-r.html"><i class="fa fa-check"></i><b>1</b> Introducción a R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introducción-a-r.html"><a href="introducción-a-r.html#interfaz"><i class="fa fa-check"></i><b>1.1</b> Interfaz</a></li>
<li class="chapter" data-level="1.2" data-path="introducción-a-r.html"><a href="introducción-a-r.html#creando-nuestro-primer-proyecto"><i class="fa fa-check"></i><b>1.2</b> Creando nuestro primer proyecto</a></li>
<li class="chapter" data-level="1.3" data-path="introducción-a-r.html"><a href="introducción-a-r.html#objetos-y-variables"><i class="fa fa-check"></i><b>1.3</b> Objetos y variables</a></li>
<li class="chapter" data-level="1.4" data-path="introducción-a-r.html"><a href="introducción-a-r.html#instalar-paquetes"><i class="fa fa-check"></i><b>1.4</b> Instalar paquetes</a></li>
<li class="chapter" data-level="1.5" data-path="introducción-a-r.html"><a href="introducción-a-r.html#importar-datos-a-r"><i class="fa fa-check"></i><b>1.5</b> Importar datos a R</a></li>
<li class="chapter" data-level="1.6" data-path="introducción-a-r.html"><a href="introducción-a-r.html#comentarios"><i class="fa fa-check"></i><b>1.6</b> Comentarios</a></li>
<li class="chapter" data-level="1.7" data-path="introducción-a-r.html"><a href="introducción-a-r.html#exportar-datos"><i class="fa fa-check"></i><b>1.7</b> Exportar datos</a></li>
<li class="chapter" data-level="1.8" data-path="introducción-a-r.html"><a href="introducción-a-r.html#pedir-ayuda"><i class="fa fa-check"></i><b>1.8</b> Pedir ayuda</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html"><i class="fa fa-check"></i><b>2</b> Estadística descriptiva</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#datos"><i class="fa fa-check"></i><b>2.1</b> Datos y estudios</a></li>
<li class="chapter" data-level="2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>2.2</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#media"><i class="fa fa-check"></i><b>2.2.1</b> Media</a></li>
<li class="chapter" data-level="2.2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mediana"><i class="fa fa-check"></i><b>2.2.2</b> Mediana</a></li>
<li class="chapter" data-level="2.2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#moda"><i class="fa fa-check"></i><b>2.2.3</b> Moda</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>2.3</b> Medidas de dispersión</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#rango"><i class="fa fa-check"></i><b>2.3.1</b> Rango</a></li>
<li class="chapter" data-level="2.3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#desviación-estándar"><i class="fa fa-check"></i><b>2.3.2</b> Desviación estándar</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-posición-relativa"><i class="fa fa-check"></i><b>2.4</b> Medidas de posición relativa</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#valores-z"><i class="fa fa-check"></i><b>2.4.1</b> Valores <span class="math inline">\(Z\)</span></a></li>
<li class="chapter" data-level="2.4.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-absoluta"><i class="fa fa-check"></i><b>2.4.2</b> Frecuencia absoluta</a></li>
<li class="chapter" data-level="2.4.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-relativa"><i class="fa fa-check"></i><b>2.4.3</b> Frecuencia relativa</a></li>
<li class="chapter" data-level="2.4.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#cuartiles"><i class="fa fa-check"></i><b>2.4.4</b> Cuartiles</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#el-uso-de-la-librería-dplyr"><i class="fa fa-check"></i><b>2.5</b> El uso de la librería <code>dplyr</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probabilidad.html"><a href="probabilidad.html"><i class="fa fa-check"></i><b>3</b> Probabilidad</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probabilidad.html"><a href="probabilidad.html#probabilidad-frecuentista"><i class="fa fa-check"></i><b>3.1</b> Probabilidad frecuentista</a></li>
<li class="chapter" data-level="3.2" data-path="probabilidad.html"><a href="probabilidad.html#reglas-de-probabilidad"><i class="fa fa-check"></i><b>3.2</b> Reglas de probabilidad</a></li>
<li class="chapter" data-level="3.3" data-path="probabilidad.html"><a href="probabilidad.html#curvas-de-densidad"><i class="fa fa-check"></i><b>3.3</b> Curvas de densidad</a></li>
<li class="chapter" data-level="3.4" data-path="probabilidad.html"><a href="probabilidad.html#distribución-binomial"><i class="fa fa-check"></i><b>3.4</b> Distribución binomial</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="probabilidad.html"><a href="probabilidad.html#media-y-desviación-estándar-de-la-distribución-binomial"><i class="fa fa-check"></i><b>3.4.1</b> Media y desviación estándar de la distribución binomial</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="probabilidad.html"><a href="probabilidad.html#distribución-de-poisson"><i class="fa fa-check"></i><b>3.5</b> Distribución de Poisson</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="probabilidad.html"><a href="probabilidad.html#media-y-desviación-estándar-de-la-distribución-de-poisson"><i class="fa fa-check"></i><b>3.5.1</b> Media y desviación estándar de la distribución de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="probabilidad.html"><a href="probabilidad.html#distribución-normal"><i class="fa fa-check"></i><b>3.6</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="probabilidad.html"><a href="probabilidad.html#pruebas-de-normalidad"><i class="fa fa-check"></i><b>3.6.1</b> Pruebas de normalidad</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="probabilidad.html"><a href="probabilidad.html#distribución-muestral"><i class="fa fa-check"></i><b>3.7</b> Distribución muestral</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="probabilidad.html"><a href="probabilidad.html#poblaciones-muestras-y-distribuciones-muestrales"><i class="fa fa-check"></i><b>3.7.1</b> Poblaciones, muestras y distribuciones muestrales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html"><i class="fa fa-check"></i><b>4</b> Estadística inferencial</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#error-estándar-de-la-media"><i class="fa fa-check"></i><b>4.1</b> Error estándar de la media</a></li>
<li class="chapter" data-level="4.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>4.2</b> Intervalo de confianza para <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#distribución-t-de-student"><i class="fa fa-check"></i><b>4.2.1</b> Distribución <span class="math inline">\(t\)</span> de Student</a></li>
<li class="chapter" data-level="4.2.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#construcción-de-un-intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>4.2.2</b> Construcción de un intervalo de confianza para <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="4.2.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalos-de-confianza-unilaterales"><i class="fa fa-check"></i><b>4.2.3</b> Intervalos de confianza unilaterales</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-de-dos-medias"><i class="fa fa-check"></i><b>4.3</b> Comparación de dos medias</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalo-de-confianza-para-mu_1---mu_2"><i class="fa fa-check"></i><b>4.3.1</b> Intervalo de confianza para <span class="math inline">\(\mu_1 - \mu_2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#pruebas-de-hipótesis"><i class="fa fa-check"></i><b>4.4</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#t-test"><i class="fa fa-check"></i><b>4.4.1</b> <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="4.4.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#t-test-de-una-cola"><i class="fa fa-check"></i><b>4.4.2</b> <span class="math inline">\(t\)</span> test de una cola</a></li>
<li class="chapter" data-level="4.4.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#tamaño-de-efecto"><i class="fa fa-check"></i><b>4.4.3</b> Tamaño de efecto</a></li>
<li class="chapter" data-level="4.4.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-wilcoxon-mann-whitney"><i class="fa fa-check"></i><b>4.4.4</b> Prueba de Wilcoxon-Mann-Whitney</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-de-muestras-pareadas"><i class="fa fa-check"></i><b>4.5</b> Comparación de muestras pareadas</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-t-pareada"><i class="fa fa-check"></i><b>4.5.1</b> Prueba de <span class="math inline">\(t\)</span> pareada</a></li>
<li class="chapter" data-level="4.5.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-signos"><i class="fa fa-check"></i><b>4.5.2</b> Prueba de signos</a></li>
<li class="chapter" data-level="4.5.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-rangos-con-signos-de-wilcoxon"><i class="fa fa-check"></i><b>4.5.3</b> Prueba de rangos con signos de Wilcoxon</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html"><i class="fa fa-check"></i><b>5</b> Inferencia de datos categóricos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#distribuciones-de-una-muestra"><i class="fa fa-check"></i><b>5.1</b> Distribuciones de una muestra</a></li>
<li class="chapter" data-level="5.2" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-de-chi-cuadrada"><i class="fa fa-check"></i><b>5.2</b> Prueba de Chi-cuadrada</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#hipótesis-compuestas-y-direccionales"><i class="fa fa-check"></i><b>5.2.1</b> Hipótesis compuestas y direccionales</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-de-chi-cuadrada-para-tablas-de-contingencia"><i class="fa fa-check"></i><b>5.3</b> Prueba de Chi-cuadrada para tablas de contingencia</a></li>
<li class="chapter" data-level="5.4" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#interpretación-de-las-tablas-de-contingencia"><i class="fa fa-check"></i><b>5.4</b> Interpretación de las tablas de contingencia</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#cuestiones-acerca-de-las-columnas-y-filas"><i class="fa fa-check"></i><b>5.4.1</b> Cuestiones acerca de las columnas y filas</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-exacta-de-fisher"><i class="fa fa-check"></i><b>5.5</b> Prueba exacta de Fisher</a></li>
<li class="chapter" data-level="5.6" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#tablas-de-contingencia-r-times-k"><i class="fa fa-check"></i><b>5.6</b> Tablas de contingencia <span class="math inline">\(r \times k\)</span></a></li>
<li class="chapter" data-level="5.7" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#intervalos-de-confianza-para-la-diferencia-entre-probabilidades"><i class="fa fa-check"></i><b>5.7</b> Intervalos de confianza para la diferencia entre probabilidades</a></li>
<li class="chapter" data-level="5.8" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#datos-pareados-en-tablas-2x2"><i class="fa fa-check"></i><b>5.8</b> Datos pareados en tablas 2x2</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html"><i class="fa fa-check"></i><b>6</b> Modelado de relaciones</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#análisis-de-varianza-anova"><i class="fa fa-check"></i><b>6.1</b> Análisis de Varianza (ANOVA)</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#variación-dentro-de-los-grupos"><i class="fa fa-check"></i><b>6.1.1</b> Variación dentro de los grupos</a></li>
<li class="chapter" data-level="6.1.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#variación-entre-los-grupos"><i class="fa fa-check"></i><b>6.1.2</b> Variación entre los grupos</a></li>
<li class="chapter" data-level="6.1.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#una-relación-importante-en-el-anova"><i class="fa fa-check"></i><b>6.1.3</b> Una relación importante en el ANOVA</a></li>
<li class="chapter" data-level="6.1.4" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#tabla-de-anova"><i class="fa fa-check"></i><b>6.1.4</b> Tabla de ANOVA</a></li>
<li class="chapter" data-level="6.1.5" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#modelo-del-anova"><i class="fa fa-check"></i><b>6.1.5</b> Modelo del ANOVA</a></li>
<li class="chapter" data-level="6.1.6" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#distribución-de-f"><i class="fa fa-check"></i><b>6.1.6</b> Distribución de <span class="math inline">\(F\)</span></a></li>
<li class="chapter" data-level="6.1.7" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#prueba-de-f"><i class="fa fa-check"></i><b>6.1.7</b> Prueba de <span class="math inline">\(F\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diseño-por-bloques-aleatorizados"><i class="fa fa-check"></i><b>6.2</b> Diseño por bloques aleatorizados</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#creando-los-bloques"><i class="fa fa-check"></i><b>6.2.1</b> Creando los bloques</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#anova-de-dos-vías"><i class="fa fa-check"></i><b>6.3</b> ANOVA de dos vías</a></li>
<li class="chapter" data-level="6.4" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#combinaciones-lineales-de-las-medias"><i class="fa fa-check"></i><b>6.4</b> Combinaciones lineales de las medias</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#contrastes"><i class="fa fa-check"></i><b>6.4.1</b> Contrastes</a></li>
<li class="chapter" data-level="6.4.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>6.4.2</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="6.4.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#prueba-de-t"><i class="fa fa-check"></i><b>6.4.3</b> Prueba de <span class="math inline">\(t\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#pruebas-post-hoc"><i class="fa fa-check"></i><b>6.5</b> Pruebas post hoc</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diferencia-menos-significativa-de-fisher-lsd"><i class="fa fa-check"></i><b>6.5.1</b> Diferencia menos significativa de Fisher (LSD)</a></li>
<li class="chapter" data-level="6.5.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diferencia-significativa-honesta-de-tukey-hsd"><i class="fa fa-check"></i><b>6.5.2</b> Diferencia significativa honesta de Tukey (HSD)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html"><i class="fa fa-check"></i><b>7</b> Correlación y regresión lineal</a>
<ul>
<li class="chapter" data-level="7.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-coeficiente-de-correlación-r"><i class="fa fa-check"></i><b>7.1</b> El coeficiente de correlación <span class="math inline">\(r\)</span></a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#midiendo-la-fuerza-de-la-asociación"><i class="fa fa-check"></i><b>7.1.1</b> Midiendo la fuerza de la asociación</a></li>
<li class="chapter" data-level="7.1.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#inferencia-acerca-de-la-correlación"><i class="fa fa-check"></i><b>7.1.2</b> Inferencia acerca de la correlación</a></li>
<li class="chapter" data-level="7.1.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalo-de-confianza-para-rho"><i class="fa fa-check"></i><b>7.1.3</b> Intervalo de confianza para <span class="math inline">\(\rho\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#regresión-lineal"><i class="fa fa-check"></i><b>7.2</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#la-línea-sd"><i class="fa fa-check"></i><b>7.2.1</b> La línea SD</a></li>
<li class="chapter" data-level="7.2.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#ecuación-de-la-regresión-lineal"><i class="fa fa-check"></i><b>7.2.2</b> Ecuación de la regresión lineal</a></li>
<li class="chapter" data-level="7.2.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#gráfica-de-promedios"><i class="fa fa-check"></i><b>7.2.3</b> Gráfica de promedios</a></li>
<li class="chapter" data-level="7.2.4" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#la-suma-de-cuadrados-de-los-residuales"><i class="fa fa-check"></i><b>7.2.4</b> La suma de cuadrados de los residuales</a></li>
<li class="chapter" data-level="7.2.5" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#desviación-estándar-de-los-residuales"><i class="fa fa-check"></i><b>7.2.5</b> Desviación estándar de los residuales</a></li>
<li class="chapter" data-level="7.2.6" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-coeficiente-de-determinación"><i class="fa fa-check"></i><b>7.2.6</b> El coeficiente de determinación</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-model-lineal"><i class="fa fa-check"></i><b>7.3</b> El model lineal</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#estmiaciones-del-modelo-lineal"><i class="fa fa-check"></i><b>7.3.1</b> Estmiaciones del modelo lineal</a></li>
<li class="chapter" data-level="7.3.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#interpolación-en-el-modelo-lineal"><i class="fa fa-check"></i><b>7.3.2</b> Interpolación en el modelo lineal</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#inferencia-estadística-respecto-de-beta_1"><i class="fa fa-check"></i><b>7.4</b> Inferencia estadística respecto de <span class="math inline">\(\beta_1\)</span></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-error-estándar-de-b_1"><i class="fa fa-check"></i><b>7.4.1</b> El error estándar de <span class="math inline">\(b_1\)</span></a></li>
<li class="chapter" data-level="7.4.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalo-de-confianza-para-beta_1"><i class="fa fa-check"></i><b>7.4.2</b> Intervalo de confianza para <span class="math inline">\(\beta_1\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#prueba-de-hipótesis-para-h_0-beta_1-0"><i class="fa fa-check"></i><b>7.5</b> Prueba de hipótesis para <span class="math inline">\(H_0: \beta_1 = 0\)</span></a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#gráficos-de-residuales"><i class="fa fa-check"></i><b>7.5.1</b> Gráficos de residuales</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalos-de-confianza-y-de-predicción"><i class="fa fa-check"></i><b>7.6</b> Intervalos de confianza y de predicción</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#computando-los-intervalos"><i class="fa fa-check"></i><b>7.6.1</b> Computando los intervalos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografia</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso de R básico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inferencia-de-datos-categóricos" class="section level1" number="5">
<h1><span class="header-section-number">Lección 5</span> Inferencia de datos categóricos</h1>
<div id="distribuciones-de-una-muestra" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Distribuciones de una muestra</h2>
<p>En esta sección consideraremos <strong>variables categóricas</strong>, es decir, variables que solamente tienen dos posibles valores, y su distribución muestral de la proporción de la muestra.
Normalmente, al tomar muestras de una población dicotómica grande, un estimado de la proporción, <span class="math inline">\(p\)</span>, es la muestra de la proporción <span class="math inline">\(\hat{p} = \frac{x}{n}\)</span>, donde <span class="math inline">\(x\)</span> es el número de observaciones en la muestra que cumplen con el atributo de interés, y <span class="math inline">\(n\)</span> es el tamaño de muestra.</p>
<p>La proporción de Wilson ajustada a la muestra, <span class="math inline">\(\tilde{p}\)</span>, es otro estimado que utiliza la fórmula <a href="inferencia-de-datos-categóricos.html#eq:wilson">(5.1)</a>.
Esto equivale a sesgar la estimación hacia el valor 1/2.</p>
<p><span class="math display" id="eq:wilson">\[\begin{equation}
\tilde{p} = \frac{x + 2}{n + 4}
\tag{5.1}
\end{equation}\]</span></p>
<p>La distribución binomial determina la distribución muestral de <span class="math inline">\(\tilde{P}\)</span>.
Veamos cómo funciona esto con un ejemplo.</p>
<blockquote>
<p><strong>Ejemplo:</strong> En una región de Estados Unidos, el 17% de las máquinas dispensadoras de bebidas están contaminadas por la bacteria <em>Chryseobacterium meningosepticum</em>.
Imaginemos que examinamos una muestra de dos máquinas dispensadoras.
La probabilidad de tener dos máquinas contaminadas es <span class="math inline">\(0.17 * 0.17 = 0.0289\)</span>, la probabilidad de que ninguna este contaminada es de <span class="math inline">\(1-0.17 * 1-0.17\)</span> y la probabilidad de que una este contaminada y la otra no es <span class="math inline">\(0.17 * (1-0.17) + 0.17 * (1-0.17)\)</span>.</p>
</blockquote>
<p>Una muestra que contenga cero máquinas contaminadas, <span class="math inline">\(\tilde{p} = \frac{0+2}{2+4} = 0.33\)</span> ocurre con una probabilidad de 0.6889, una muestra con una máquina contaminada, <span class="math inline">\(\tilde{p} = \frac{1+2}{2+4} = 0.5\)</span> ocurre con una probabilidad de 0.2822 y una muestra con dos máquinas contaminadas, <span class="math inline">\(\tilde{p} = \frac{2+2}{2+4} = 0.67\)</span> ocurre con una probabilidad de 0.0289.
Por ende, hay un 68.89% de probabilidad de que <span class="math inline">\(\tilde{P}\)</span> sea igual a 0.33, un 28% de que <span class="math inline">\(\tilde{P}\)</span> sea igual a 0.5 y 3% de que <span class="math inline">\(\tilde{P}\)</span> sea igual a 0.67.</p>
<p>Imaginemos ahora que nuestra muestra pasa de <span class="math inline">\(n = 2\)</span> a <span class="math inline">\(n = 20\)</span>, para encontrar la probabilidad de cuántas máquinas podríamos esperar que estén contaminadas en nuestra muestra, acudimos a la distribución binomial.
Por ejemplo, para calcular que 5 de las 20 máquinas están contaminadas usamos <span class="math inline">\(p = 0.17\)</span> y <span class="math inline">\(n = 20\)</span>.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="inferencia-de-datos-categóricos.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">5</span>, <span class="dv">20</span>, <span class="fl">0.17</span>)</span></code></pre></div>
<pre><code>## [1] 0.1345426</code></pre>
<p>Como vemos, la probabilidad de obtener 5 máquinas contaminadas es 0.1345, ahora, usando <span class="math inline">\(\tilde{P}\)</span>, una muestra con 5 máquinas contaminadas sería <span class="math inline">\(\tilde{p} = \frac{5+2}{20+4} = 0.2917\)</span>, por lo que <span class="math inline">\(P(\tilde{P} = 0.2917) = 0.1345\)</span>.
Con la distribución binomial, podemos determinar toda la distribución muestral de <span class="math inline">\(\tilde{P}\)</span>.</p>
<p>Por ejemplo, podemos preguntar <em>¿Cuál es la probabilidad de que no más de 5 máquinas estén contaminadas?</em></p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="inferencia-de-datos-categóricos.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">5</span>, <span class="dv">20</span>, <span class="fl">0.17</span>)</span></code></pre></div>
<pre><code>## [1] 0.8902245</code></pre>
<p>Como vemos, la probabilidad de que no más de 5 máquinas estén contaminadas es de 0.8902245.
Y como <span class="math inline">\(\tilde{p} = \frac{5+2}{20+4} = 0.2917\)</span> entonces <span class="math inline">\(P(\tilde{P} \leq 0.2917) = 0.8902\)</span>.
La distribución muestral de <span class="math inline">\(\tilde{P}\)</span> se puede utilizar para predecir cuánto error de muestreo esperar en nuestro estimado.
De igual manera, entre mayor sea nuestro <span class="math inline">\(n\)</span> mayor posibilidades hay de que <span class="math inline">\(\tilde{P}\)</span> se encuentre cercano a <span class="math inline">\(p\)</span>.</p>
<p>Para la construcción de <strong>intervalos de confianza</strong> de la proporción de una población, necesitamos encontrar el error estándar de <span class="math inline">\(\tilde{P}\)</span>.
Para eso utilizamos la siguiente fórmula (para intervalos al 95%).</p>
<p><span class="math display" id="eq:pse">\[\begin{equation}
SE_\tilde{p} = \sqrt{\frac{\tilde{p}(1-\tilde{p})}{n + 4}}
\tag{5.2}
\end{equation}\]</span></p>
<p>Posteriormente, realizamos el intervalo de confianza correspondiente con la siguiente fórmula (esto para un intervalo de confianza al 95%).</p>
<p><span class="math display" id="eq:pic">\[\begin{equation}
\tilde{p} \pm 1.96 \times SE_{\tilde{p}}
\tag{5.3}
\end{equation}\]</span></p>
<p>Al igual que con otros métodos, podemos construir un intervalo de confianza unilateral si así lo deseamos.
Para eso podemos utilizar la función <code>qnorm()</code> en la cuál indicamos el valor de densidad (o probabilidad) que deseamos y así obtener un valor Z.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="inferencia-de-datos-categóricos.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 1.644854</code></pre>
<p>Como podemos ver, para casos de intervalos de confianza unilaterales al 95% utilizaríamos un multiplicador de 1.645.</p>
<p><span class="math display" id="eq:pic2">\[\begin{equation}
\tilde{p} \pm 1.645 \times SE_{\tilde{p}}
\tag{5.4}
\end{equation}\]</span></p>
<p>Las fórmulas para intervalos de confianza generales son las siguientes:</p>
<p><span class="math display" id="eq:pic2">\[\begin{equation}
\tilde{p} \pm z_{\alpha/2} \times SE_{\tilde{p}}
\tag{5.4}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:wilson2">\[\begin{equation}
\tilde{p} = \frac{x + 0.5(z^2_{\alpha/2})}{n + z^2_{\alpha/2}}
\tag{5.5}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:pse2">\[\begin{equation}
SE_\tilde{p} = \sqrt{\frac{\tilde{p}(1-\tilde{p})}{n + z^2_{\alpha/2}}}
\tag{5.6}
\end{equation}\]</span></p>
</div>
<div id="prueba-de-chi-cuadrada" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Prueba de Chi-cuadrada</h2>
<p>Una <strong>prueba de bondad de ajuste</strong> se utiliza para ver la compatibilidad de los datos con una distribución o <span class="math inline">\(H_0\)</span> específica.
Una de las más utilizadas es la <strong>prueba de</strong> <span class="math inline">\(\chi^2\)</span> (léase chi-cuadrada).
Para esto se utilizan frecuencias absolutas de nuestros datos.
Para cada nivel de categoría, <span class="math inline">\(i\)</span>, dejamos que <span class="math inline">\(o_i\)</span> represente la frecuencia observada y <span class="math inline">\(e_i\)</span> la frecuencia esperada, es decir, la frecuencia que esperaríamos obtener bajo la <span class="math inline">\(H_0\)</span>.
Las frecuencias esperadas <span class="math inline">\(e_i\)</span> se obtienen multiplicando las probabilidades dadas por la <span class="math inline">\(H_0\)</span> por <span class="math inline">\(n\)</span>.
Posteriormente utilizamos la fórmula <a href="inferencia-de-datos-categóricos.html#eq:chi">(5.7)</a> para calcular nuestro estadístico de prueba.</p>
<p><span class="math display" id="eq:chi">\[\begin{equation}
\chi^2 = \sum_{i = 1}^{k}\frac{(o_i - e_i)^2}{e_i}
\tag{5.7}
\end{equation}\]</span></p>
<p>Donde <span class="math inline">\(k\)</span> es el número total de categorías e <span class="math inline">\(i\)</span> es la <em>i</em>-ésima observación.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Después de seis meses de un incendio, los investigadores muestrearon una parcela de 3000 acres al rededor del área quemada.
La dividieron en cuatro regiones: (1) el área cercana al centro del incendio, (2) el área interior cercana al incendio, (3) el área exterior cercana al incendio y (4) área fuera de la zona quemada.
La <span class="math inline">\(H_0\)</span> es que los venados no muestran preferencia por alguna de las áreas.
La <span class="math inline">\(H_A\)</span> es que muestran cierta preferencia por alguna de las áreas.</p>
</blockquote>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="inferencia-de-datos-categóricos.html#cb214-1" aria-hidden="true" tabindex="-1"></a>Area <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">520</span>, <span class="dv">210</span>, <span class="dv">240</span>, <span class="dv">2030</span>)</span>
<span id="cb214-2"><a href="inferencia-de-datos-categóricos.html#cb214-2" aria-hidden="true" tabindex="-1"></a>Zona <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Área interior&quot;</span>, <span class="st">&quot;Área exterior&quot;</span>, <span class="st">&quot;Borde exterior&quot;</span>, <span class="st">&quot;No quemado&quot;</span>)</span>
<span id="cb214-3"><a href="inferencia-de-datos-categóricos.html#cb214-3" aria-hidden="true" tabindex="-1"></a>Proporcion <span class="ot">&lt;-</span> <span class="fu">round</span>(Area<span class="sc">/</span><span class="fu">sum</span>(Area), <span class="dv">3</span>)</span>
<span id="cb214-4"><a href="inferencia-de-datos-categóricos.html#cb214-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb214-5"><a href="inferencia-de-datos-categóricos.html#cb214-5" aria-hidden="true" tabindex="-1"></a>Datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Zona, Area, Proporcion)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:Ejemplo1">Tabla 5.1: </span>Áreas quemadas y no quemadas
</caption>
<thead>
<tr>
<th style="text-align:center;">
Zona
</th>
<th style="text-align:center;">
Área
</th>
<th style="text-align:center;">
Proporción
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 4cm; ">
Área interior
</td>
<td style="text-align:center;min-width: 4cm; ">
520
</td>
<td style="text-align:center;min-width: 4cm; ">
0.173
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
Área exterior
</td>
<td style="text-align:center;min-width: 4cm; ">
210
</td>
<td style="text-align:center;min-width: 4cm; ">
0.070
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
Borde exterior
</td>
<td style="text-align:center;min-width: 4cm; ">
240
</td>
<td style="text-align:center;min-width: 4cm; ">
0.080
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
No quemado
</td>
<td style="text-align:center;min-width: 4cm; ">
2030
</td>
<td style="text-align:center;min-width: 4cm; ">
0.677
</td>
</tr>
</tbody>
</table>
<p>Si la <span class="math inline">\(H_0\)</span> es verdadera, entonces</p>
<span class="math display">\[\begin{aligned}
H_0: P(Área \space interior) = \frac{520}{3000} = 0.173 \\
P(Área \space exterior) = \frac{210}{3000} = 0.070 \\
P(Borde \space  exterior) = \frac{240}{3000} = 0.080 \\
P(No \space quemado) = \frac{2030}{3000} = 0.677
\end{aligned}\]</span>
<p>Entonces la <span class="math inline">\(H_A\)</span> sería</p>
<span class="math display">\[\begin{aligned}
H_A: P(Área \space interior) \ne 0.173 \\
P(Área \space exterior) \ne 0.070 \\
P(Borde \space  exterior) \ne 0.080 \\
P(No \space quemado) \ne 0.677
\end{aligned}\]</span>
<p>Los investigadores encontraron 75 venados en el área, distribuidos en distintas zonas como se muestra a continuación.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="inferencia-de-datos-categóricos.html#cb215-1" aria-hidden="true" tabindex="-1"></a>Venados <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">43</span>)</span>
<span id="cb215-2"><a href="inferencia-de-datos-categóricos.html#cb215-2" aria-hidden="true" tabindex="-1"></a>Datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Datos, Venados)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-143"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-143-1.png" alt="Zonas de avistamientos de venados, $n = 75$." width="672" />
<p class="caption">
Figura 5.1: Zonas de avistamientos de venados, <span class="math inline">\(n = 75\)</span>.
</p>
</div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:Ejemplo1a">Tabla 5.2: </span>Áreas quemadas y no quemadas y el número de venados observados
</caption>
<thead>
<tr>
<th style="text-align:center;">
Zona
</th>
<th style="text-align:center;">
Área
</th>
<th style="text-align:center;">
Proporción
</th>
<th style="text-align:center;">
No. de venados
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 4cm; ">
Área interior
</td>
<td style="text-align:center;min-width: 4cm; ">
520
</td>
<td style="text-align:center;min-width: 4cm; ">
0.173
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
Área exterior
</td>
<td style="text-align:center;min-width: 4cm; ">
210
</td>
<td style="text-align:center;min-width: 4cm; ">
0.070
</td>
<td style="text-align:center;">
12
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
Borde exterior
</td>
<td style="text-align:center;min-width: 4cm; ">
240
</td>
<td style="text-align:center;min-width: 4cm; ">
0.080
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
No quemado
</td>
<td style="text-align:center;min-width: 4cm; ">
2030
</td>
<td style="text-align:center;min-width: 4cm; ">
0.677
</td>
<td style="text-align:center;">
43
</td>
</tr>
</tbody>
</table>
<p>Para este caso, las probabilidades estimadas (denotadas como <span class="math inline">\(\hat{p}\)</span>) son</p>
<p><span class="math display">\[\begin{align}
\hat{P}(Área \space interior) = \frac{2}{75} = 0.027 \\
\hat{P}(Área \space exterior) = \frac{12}{75} = 0.160 \\
\hat{P}(Borde \space  exterior) = \frac{18}{75} = 0.240 \\
\hat{P}(No \space quemado) = \frac{43}{75} = 0.573
\end{align}\]</span></p>
<p>Estas las podemos calcular fácilmente.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="inferencia-de-datos-categóricos.html#cb216-1" aria-hidden="true" tabindex="-1"></a>Prop_venados <span class="ot">&lt;-</span> <span class="fu">round</span>(Venados<span class="sc">/</span><span class="fu">sum</span>(Venados), <span class="dv">3</span>)</span>
<span id="cb216-2"><a href="inferencia-de-datos-categóricos.html#cb216-2" aria-hidden="true" tabindex="-1"></a>Datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Datos, Prop_venados)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:Ejemplo1b">Tabla 5.3: </span>Áreas quemadas y no quemadas y el número de venados observados con su proporción
</caption>
<thead>
<tr>
<th style="text-align:center;">
Zona
</th>
<th style="text-align:center;">
Área
</th>
<th style="text-align:center;">
Proporción esperada
</th>
<th style="text-align:center;">
No. de venados
</th>
<th style="text-align:center;">
Proporción observada
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 3.5cm; ">
Área interior
</td>
<td style="text-align:center;min-width: 3.5cm; ">
520
</td>
<td style="text-align:center;min-width: 3.5cm; ">
0.173
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0.027
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3.5cm; ">
Área exterior
</td>
<td style="text-align:center;min-width: 3.5cm; ">
210
</td>
<td style="text-align:center;min-width: 3.5cm; ">
0.070
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
0.160
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3.5cm; ">
Borde exterior
</td>
<td style="text-align:center;min-width: 3.5cm; ">
240
</td>
<td style="text-align:center;min-width: 3.5cm; ">
0.080
</td>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
0.240
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 3.5cm; ">
No quemado
</td>
<td style="text-align:center;min-width: 3.5cm; ">
2030
</td>
<td style="text-align:center;min-width: 3.5cm; ">
0.677
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
0.573
</td>
</tr>
</tbody>
</table>
<p>Como podemos ver, las proporciones observadas <span class="math inline">\(\hat{P}\)</span> difieren de las que esperaríamos en el modelo de la <span class="math inline">\(H_0\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:Ejemplo1c"></span>
<img src="Curso_R_basico_files/figure-html/Ejemplo1c-1.png" alt="Valores observados contra esperados en las proporciones de venados en zonas quemadas." width="672" />
<p class="caption">
Figura 5.2: Valores observados contra esperados en las proporciones de venados en zonas quemadas.
</p>
</div>
<p>Ahora, para aplicar la fórmula de <span class="math inline">\(\chi^2\)</span> necesitamos los valores absolutos de nuestros datos, para esto simplemente multiplicamos la probabilidad calculada por la <span class="math inline">\(H_0\)</span>, <span class="math inline">\(p * n\)</span>.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="inferencia-de-datos-categóricos.html#cb217-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Usamos la función sum() para sumar todos los valores de la variable &quot;Venados&quot;.</span></span>
<span id="cb217-2"><a href="inferencia-de-datos-categóricos.html#cb217-2" aria-hidden="true" tabindex="-1"></a>Venados_esperados <span class="ot">&lt;-</span> Proporcion <span class="sc">*</span> <span class="fu">sum</span>(Datos<span class="sc">$</span>Venados) </span>
<span id="cb217-3"><a href="inferencia-de-datos-categóricos.html#cb217-3" aria-hidden="true" tabindex="-1"></a>Venados_esperados</span></code></pre></div>
<pre><code>## [1] 12.975  5.250  6.000 50.775</code></pre>
<p>Como podemos ver, los valores son aproximadamente 13, 5.25, 6 y 50.78.
Ahora simplemente aplicamos la fórmula para nuestros datos.</p>
<p><span class="math display">\[\begin{align}
\chi_s^2 = \frac{(2-13)^2}{13} + \frac{(12-5.25)^2}{5.25} + \frac{(18-6)^2}{6} + \frac{(43-50.78)^2}{50.78} = 43.2
\end{align}\]</span></p>
<p>Ahora tenemos que considerar la distribución nula de <span class="math inline">\(\chi_s^2\)</span>, que es la distribución muestral que se sigue en caso de que nuestra <span class="math inline">\(H_0\)</span> sea verdadera.
Esta distribución muestral sigue la distribución de chi-cuadrada <span class="math inline">\(\chi^2\)</span> cuando el tamaño de muestra es suficientemente grande.
La forma de la distribución de <span class="math inline">\(\chi^2\)</span> depende de los grados de libertad.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-146"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-146-1.png" alt="Distribución de $\chi^2$ con $df = 5$ en azul, $df = 8$ en rojo y $df = 10$ en verde." width="672" />
<p class="caption">
Figura 5.3: Distribución de <span class="math inline">\(\chi^2\)</span> con <span class="math inline">\(df = 5\)</span> en azul, <span class="math inline">\(df = 8\)</span> en rojo y <span class="math inline">\(df = 10\)</span> en verde.
</p>
</div>
<p>Al igual que las demás distribuciones de probabilidad en <code>R</code>, tenemos una serie de comandos para encontrar los valores de una distribución de chi-cuadrada fácilmente.</p>
<p>-<code>dchisq()</code> nos da un valor de densidad en determinado punto de la distribución de <span class="math inline">\(\chi^2\)</span>.</p>
<p>-<code>pchisq()</code> nos da un valor de densidad acumulado hasta cierto punto en la distribución de <span class="math inline">\(\chi^2\)</span> (área debajo de la curva).</p>
<p>-<code>qchisq()</code> toma el valor de densidad que le ponemos como primer argumento y nos da como regreso un número cuya densidad acumulada empate con el valor de densidad ingresado.</p>
<p>-<code>rchisq()</code> genera cierta cantidad de número aleatorios de acuerdo al valor de densidad.</p>
<p>Sin embargo en este caso, en lugar de contar con el argumento <code>n</code> para el tamaño de muestra, contamos con otro argumento <code>df</code> para los grados de libertad.</p>
<p>Por ejemplo, supongamos que quisiéramos encontrar el valor crítico <span class="math inline">\(\chi_{5,0.05}^2\)</span> cuando <span class="math inline">\(df = 5\)</span>, para esto utilizamos la función <code>qchisq()</code>.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="inferencia-de-datos-categóricos.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 11.0705</code></pre>
<p>Como podemos ver, el valor crítico es 11.07.
Esto corresponde a un área de 0.05 por encima de la cola de la distribución de <span class="math inline">\(\chi^2\)</span>.</p>
<p><img src="Curso_R_basico_files/figure-html/unnamed-chunk-148-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>El cálculo de los grados de libertad <span class="math inline">\(df\)</span> para una distribución de <span class="math inline">\(\chi^2\)</span> depende del número de categorías, <span class="math inline">\(k\)</span>.</p>
<p><span class="math display" id="eq:chidf">\[\begin{align}
df = k - 1
\tag{5.8}
\end{align}\]</span></p>
<p>Siguiendo el ejemplo de los venados, en este caso tenemos <span class="math inline">\(k = 4\)</span> por lo que <span class="math inline">\(df = 4 - 1 = 3\)</span>.
Ya que el valor que habíamos obtenido de nuestra fórmula de <span class="math inline">\(\chi_s^2 = 43.2\)</span>, buscaremos el área debajo de la curva correspondiente a este valor.</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="inferencia-de-datos-categóricos.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">43.2</span>, <span class="dv">3</span>, <span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 2.231754e-09</code></pre>
<p>Como podemos ver el resultado es extremadamente pequeño y nuestro <span class="math inline">\(valor-p &lt; 0.0001\)</span> por lo que tenemos evidencia para rechazar la <span class="math inline">\(H_0\)</span> y aceptar la hipótesis de que los venados prefieren ciertas zonas sobre otras.
La prueba de <span class="math inline">\(\chi^2\)</span> se puede utilizar para cualquier número de categorías <span class="math inline">\(k\)</span>.</p>
<p>Ahora todo esto se facilita gracias a la función <code>chisq.test()</code> que viene incluida en <code>R</code>.</p>
<p>Para realizar la prueba de Chi-cuadrada con esta función, lo único que necesitamos es una variable con el valor absoluto de nuestras observaciones y otra con los valores relativos esperados como los de la tabla <a href="inferencia-de-datos-categóricos.html#tab:Ejemplo1d">5.4</a>.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="inferencia-de-datos-categóricos.html#cb223-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(Datos<span class="sc">$</span>Venados, Datos<span class="sc">$</span>Propocion)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  Datos$Venados
## X-squared = 48.787, df = 3, p-value = 1.448e-10</code></pre>
<p>Estos valores los podemos obtener de la matriz de datos que habíamos creado previamente, simplemente los seleccionamos con el símbolo <code>$</code> seguido del nombre de la variable (<code>$Venados</code> y <code>$Proporcion</code>, en mí caso).</p>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:Ejemplo1d">Tabla 5.4: </span>Datos utilizados por la función <code>chisq.test()</code> en R
</caption>
<thead>
<tr>
<th style="text-align:center;">
Proporción esperada
</th>
<th style="text-align:center;">
No. de venados
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 5.2cm; ">
0.173
</td>
<td style="text-align:center;min-width: 5.2cm; ">
2
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5.2cm; ">
0.070
</td>
<td style="text-align:center;min-width: 5.2cm; ">
12
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5.2cm; ">
0.080
</td>
<td style="text-align:center;min-width: 5.2cm; ">
18
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 5.2cm; ">
0.677
</td>
<td style="text-align:center;min-width: 5.2cm; ">
43
</td>
</tr>
</tbody>
</table>
<div id="hipótesis-compuestas-y-direccionales" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Hipótesis compuestas y direccionales</h3>
<p>Hay que darnos cuenta que en el ejemplo de los venados, nuestras hipótesis son <strong>hipótesis compuestas</strong>, es decir, hacen múltiples afirmaciones, a diferencia de las hipótesis que hacíamos en las pruebas de <span class="math inline">\(t\)</span> (<span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>).
Las primeras tres afirmaciones de nuestra hipótesis nula <span class="math inline">\(H_0\)</span> son independientes, <span class="math inline">\(P(Área \space interior) = 0.173\)</span>, <span class="math inline">\(P(Área \space exterior) = 0.070\)</span>, <span class="math inline">\(P(Borde \space exterior) = 0.080\)</span> pero nuestra última afirmación, <span class="math inline">\(P(No \space quemado) = 0.677\)</span>, es <strong>dependiente</strong> de las demás afirmaciones realizadas.
Cuando esto ocurre, la hipótesis alternativa es necesariamente no direccional.
Otra cosa interesante es que cuando se rechaza la <span class="math inline">\(H_0\)</span>, la prueba no nos dice la dirección de la conclusión.</p>
<p>En cambio, cuando una variable es dicotómica, la <span class="math inline">\(H_0\)</span> no es compuesta y por lo tanto, alternativas direccionales o conclusiones direccionales no suponen un problema.
Para una variable dicotómica, una prueba de hipótesis direccional de Chi-cuadrada se realizaría de la misma manera que en pruebas pasadas.</p>
<ol style="list-style-type: decimal">
<li><p>Primero elegimos la direccionalidad y corroboramos que los datos se desvían de la <span class="math inline">\(H_0\)</span> en la dirección especificada por la <span class="math inline">\(H_A\)</span>.
Si es así realizamos el siguiente paso.</p></li>
<li><p>Encontramos el valor-<em>p</em>, el cuál será la mitad de lo que sería si nuestra <span class="math inline">\(H_A\)</span> fuese no direccional.</p></li>
</ol>
</div>
</div>
<div id="prueba-de-chi-cuadrada-para-tablas-de-contingencia" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Prueba de Chi-cuadrada para tablas de contingencia</h2>
<p>Una <strong>tabla de contingencia</strong> muestra los datos de tal manera que existe una asociación entre las variables de las filas y columnas.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Un grupo de 75 pacientes fueron asignados de manera aleatoria para recibir una cirugía para tratar dolores de migraña.
La cirugía podía ser real (<span class="math inline">\(n = 49\)</span>) o no (<span class="math inline">\(n = 26\)</span>).
Los cirujanos esperan una reducción en los dolores de migraña (éxito).
En la tabla <a href="#tab:Ej2a"><strong>??</strong></a> se pueden observar los datos.</p>
</blockquote>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="inferencia-de-datos-categóricos.html#cb225-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creamos nuestra matriz de datos.</span></span>
<span id="cb225-2"><a href="inferencia-de-datos-categóricos.html#cb225-2" aria-hidden="true" tabindex="-1"></a>cirugia <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">41</span>, <span class="dv">15</span>, <span class="dv">8</span>, <span class="dv">11</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> T)</span>
<span id="cb225-3"><a href="inferencia-de-datos-categóricos.html#cb225-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(cirugia) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">&quot;Éxito&quot;</span>, <span class="st">&quot;Fracaso&quot;</span>), <span class="fu">c</span>(<span class="st">&quot;Real&quot;</span>, <span class="st">&quot;Falsa&quot;</span>))</span></code></pre></div>
<p>Como podemos ver, tenemos nuestra tabla de contingencia lista.</p>
<table>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Real</strong></td>
<td><strong>Falsa</strong></td>
</tr>
<tr class="even">
<td><strong>Éxito</strong></td>
<td>41</td>
<td>15</td>
</tr>
<tr class="odd">
<td><strong>Fracaso</strong></td>
<td>8</td>
<td>11</td>
</tr>
</tbody>
</table>
<p>Posteriormente podríamos agregar los casos totales para cada lado de nuestra tabla de contingencia.</p>
<table style="width:97%;">
<colgroup>
<col width="23%" />
<col width="23%" />
<col width="25%" />
<col width="25%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Real</strong></td>
<td><strong>Falsa</strong></td>
<td><strong>Total</strong></td>
</tr>
<tr class="even">
<td><strong>Éxito</strong></td>
<td>41</td>
<td>15</td>
<td>56</td>
</tr>
<tr class="odd">
<td><strong>Fracaso</strong></td>
<td>8</td>
<td>11</td>
<td>19</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>49</td>
<td>26</td>
<td>75</td>
</tr>
</tbody>
</table>
<p>Cuando hacemos una prueba de Chi-cuadrado para este tipo de tablas, nuestra hipótesis nula es que la probabilidad de éxito dado que la cirugía fue real es la misma que la probabilidad de éxito dado que la cirugía fue falsa, <span class="math inline">\(H_0: P(Éxito|Real) = P(Éxito|Falsa)\)</span>. Como vimos en la lección de probabilidad, este tipo de probabilidad se conoce como <strong>condicional</strong> y predice qué tan seguido un evento ocurre bajo condiciones específicas.</p>
<p><span class="math display">\[\begin{equation}
P(A|B)
\end{equation}\]</span></p>
<p>Esta fórmula nos dice cuál es la probabilidad de que A ocurra, dado que B ha ocurrido. Cuando una probabilidad condicional se estima de los datos, normalmente se denota con el símbolo ^.</p>
<p><span class="math display">\[\begin{equation}
\hat{P}(A|B)
\end{equation}\]</span></p>
<p>Por ejemplo, para nuestros datos:</p>
<p><span class="math display">\[\begin{align}
\hat{P}(Éxito|Real) = \frac{41}{49} = 0.837 \\
\hat{P}(Éxito|Falsa) = \frac{15}{26} = 0.577
\end{align}\]</span></p>
<p>Como podemos ver, estas probabilidades las obtenemos utilizando las columnas <strong>Real</strong> y <strong>Falsa</strong> de nuestra tabla de contingencia y sus respectivos totales. Pero, ¿es esta diferencia significativa? Para esto realizaremos la prueba de Chi-cuadrada.</p>
<p><strong>IMPORTANTE:</strong> No es lo mismo <span class="math inline">\(P(Éxito|Real)\)</span> que <span class="math inline">\(P(Real|Éxito)\)</span>. Puedes comprobarlo tú mismo.</p>
<p><span class="math display">\[\begin{align}
\hat{P}(Éxito|Real) = \frac{41}{49} = 0.837 \\
\hat{P}(Real|Éxito) = \frac{41}{56} = 0.7321 \\
\hat{P}(Éxito|Real) \ne \hat{P}(Real|Éxito)
\end{align}\]</span></p>
<p>Ahora, el primer paso para aplicar la prueba de Chi-cuadrada a nuestra tabla de contingencia es calcular las <strong>frecuencias marginales</strong>, es decir, las frecuencias de los totales de nuestra tabla de contingencia. Si nuestra <span class="math inline">\(H_0\)</span> es verdadera, entonces las columnas <strong>Real</strong> y <strong>Falsa</strong> son equivalentes, así que podemos agruparlas (<span class="math inline">\(41 + 15\)</span>) y dividirlas sobre el total de observaciones (<span class="math inline">\(\frac{56}{75} = 0.747\)</span>). Bien, ahora aplicamos esta probabilidad a nuestros valores observados para el grupo Real y Falso (<span class="math inline">\(\frac{56}{75} \times 49 = 36.59\)</span> éxitos esperados y <span class="math inline">\(\frac{56}{75} \times 26 = 36.59\)</span> éxitos esperados). De igual manera, aplicamos lo mismo para los fracasos esperados (<span class="math inline">\(\frac{19}{75} = 0.253\)</span>). Para obtener nuestros fracasos esperados obtenemos, multiplicamos este valor por los de los grupos Real y Falso (<span class="math inline">\(\frac{19}{75} \times 49\)</span> fracasos esperados y <span class="math inline">\(\frac{19}{75} \times 26\)</span> fracasos esperados).</p>
<table style="width:97%;">
<colgroup>
<col width="23%" />
<col width="23%" />
<col width="25%" />
<col width="25%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Real</strong></td>
<td><strong>Falsa</strong></td>
<td><strong>Total</strong></td>
</tr>
<tr class="even">
<td><strong>Éxito</strong></td>
<td>41 (36.59)</td>
<td>15 (19.41)</td>
<td>56</td>
</tr>
<tr class="odd">
<td><strong>Fracaso</strong></td>
<td>8 (12.41)</td>
<td>11 (6.59)</td>
<td>19</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>49</td>
<td>26</td>
<td>75</td>
</tr>
</tbody>
</table>
<p>Ya que estos cálculos se realizan exclusivamente con los valores marginales, los valores esperados <span class="math inline">\(e\)</span> se pueden obtener de la siguiente manera.</p>
<p><span class="math display" id="eq:e">\[\begin{align}
e = \frac{(Total \space columna) \times (Total \space fila)}{Gran \space total}
\tag{5.9}
\end{align}\]</span></p>
<p>Los grados de libertad para nuestra tabla de contingencia de 2x2 es de 1. ¿Por qué? Bueno, porque de las 4 celdas disponibles, solamente una de ellas es libre de variar. Ya que, por ejemplo, al determinar el valor esperado de la celda superior izquierda (36.59), el valor de la celda superior derecha tiene que ser 19.41, ya que la suma de ambas debe de ser 56. Lo mismo para la celda inferior izquierda (12.41) que al sumarse a la celda superior izquierda dan como resultado 49. Y la misma lógica aplica a la celda inferior derecha. Ya que la celda superior derecha es 19.41, la celda inferior tiene que ser 6.59 para sumar 26 en total. En este sentido, <strong>solo una celda es libre de variar</strong> y por ende <span class="math inline">\(df = 1\)</span> para una tabla de contingencia de 2x2.</p>
<p>Para este tipo de tablas, la hipótesis puede ser direccional o no direccional. En el caso de nuestro ejemplo, nos interesa saber si el efecto de la cirugía reduce el dolor de migraña (hipótesis direccional), así que al calcular el valor-<em>p</em> simplemente hay que dividirlo entre 2 y obtendremos el valor direccional.</p>
<p>Ahora sí, podemos aplicar la fórmula de <span class="math inline">\(\chi^2\)</span>.</p>
<p><span class="math display">\[\begin{align}
\chi_s^2 = \frac{(41-36.59)^2}{36.59} + \frac{(15-19.41)^2}{19.41} + \frac{(8-12.41)^2}{12.41} + \frac{(11-6.59)^2}{6.59} = 6.06
\end{align}\]</span></p>
<p>Todo este proceso se puede hacer de manera rapidísima con la función <code>chisq.test()</code>. Lo único que tenemos que hacer es poner nuestra matriz de datos y el argumento <code>correct = F</code> para evitar aplicar correcciones.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="inferencia-de-datos-categóricos.html#cb226-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(cirugia, <span class="at">correct =</span> F)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  cirugia
## X-squared = 6.0619, df = 1, p-value = 0.01381</code></pre>
<p>Como vemos el valor-<em>p</em> es igual a 0.01381, pero como nuestra hipótesis es direccional debemos de dividirlo en 2.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="inferencia-de-datos-categóricos.html#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(cirugia, <span class="at">correct =</span> F)<span class="sc">$</span>p.value <span class="sc">/</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.00690659</code></pre>
<p>Por lo que obtenemos un <span class="math inline">\(valor-p = 0.0069\)</span>. En este caso, si nuestro <span class="math inline">\(\alpha = 0.01\)</span> rechazaríamos la <span class="math inline">\(H_0\)</span> y diríamos que hay evidencias suficientes que apoyan que la cirugía real es mejor que la falsa para reducir los dolores de migraña.</p>
</div>
<div id="interpretación-de-las-tablas-de-contingencia" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Interpretación de las tablas de contingencia</h2>
<p>Una tabla de contingencia 2x2 se puede interpretar de dos maneras:</p>
<ol style="list-style-type: decimal">
<li><p>Dos muestras independientes con una variable dicotómica.</p></li>
<li><p>Una muestra con dos variable dicotómicas.</p></li>
</ol>
<p>Afortunadamente, la aritmética de la prueba de Chi-cuadrada es la misma para ambos contextos, pero la interpretación de la hipótesis y las conclusiones son distintas.</p>
<p>En algunas tablas de contingencia las filas y columnas juegan un papel muy distinto. Por ejemplo, puede que las columnas sean un tratamiento y las filas una respuesta. En otros casos, las columnas y las filas pueden jugar papeles intercambiables.</p>
<p>Cuando un conjunto de datos es visto como una sola muestra con dos variable dicotómicas, la relación expresada por <span class="math inline">\(H_0\)</span> se conoce como <strong>dependencia estadística</strong> de las variables de columna y fila. Variables que no son independientes son llamadas <strong>dependientes</strong> o <strong>asociadas</strong>. Por eso a veces la prueba de Chi-cuadrada puede ser conocida como prueba de asociación o prueba de independencia.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Un antropólogo alemán que estidaba la relación entre el color de ojos y cabello observó una muestra de <span class="math inline">\(n = 6800\)</span> hombres con los resultados siguientes.</p>
</blockquote>
<table>
<colgroup>
<col width="24%" />
<col width="28%" />
<col width="27%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Cabello oscuro (CO)</strong></th>
<th><strong>Cabello claro (CC)</strong></th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Ojo oscuro (OO)</strong></td>
<td>726</td>
<td>131</td>
<td>857</td>
</tr>
<tr class="even">
<td><strong>Ojo claro (OC)</strong></td>
<td>3129</td>
<td>2814</td>
<td>5943</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>3855</td>
<td>2945</td>
<td>6800</td>
</tr>
</tbody>
</table>
<p>En este caso, podemos calcular las probabilidades condicional de la siguiente manera:</p>
<p><span class="math display">\[\begin{align}
\hat{P} = (OO|CO) = \frac{726}{3855} = 0.19 \\
\hat{P} = (OO|CC) = \frac{131}{2945} = 0.04
\end{align}\]</span></p>
<p>Pero la siguiente manera también es valida:</p>
<p><span class="math display">\[\begin{align}
\hat{P} = (CO|OO) = \frac{726}{857} = 0.85 \\
\hat{P} = (CO|OC) = \frac{3129}{5943} = 0.53
\end{align}\]</span></p>
<p>Por lo tanto nuestra hipótesis nula se vería de las siguientes dos maneras, ambas válidas:</p>
<p><span class="math display">\[\begin{align}
H_0: P(OO|CO) = P(OO|CC) \\
H_0: P(CO|OO) = P(CO|OC)
\end{align}\]</span></p>
<p>Esto es lo mismo que decir que <span class="math inline">\(H_0: El \space color \space de \space ojos \space es \space independiente \space del \space color \space de \space cabello\)</span> o <span class="math inline">\(H_0: El \space color \space del \space cabello \space es \space independiente \space del \space color \space de \space ojos\)</span>. Que es lo mismo que decir <span class="math inline">\(H_0: El \space color \space de \space ojos \space y \space el \space color \space del \space cabello \space son \space independientes\)</span>.</p>
<p>La hipótesis nula de independencia puede decirse de la siguiente manera. Dos grupos, <span class="math inline">\(G_1\)</span> y <span class="math inline">\(G_2\)</span> son comparados con respecto de la probabilidad de la característica <span class="math inline">\(C\)</span>. La hipótesis nula es entonces:</p>
<p><span class="math display">\[\begin{align}
H_0: P(C|G_1) = P(C|G_2)
\end{align}\]</span></p>
<blockquote>
<p><strong>Ejemplo:</strong> Considere una especie ficticia de plantas, que se puede categorizar en pequeñas (S), y altas (T), así como resistentes (R) y no resistentes (NR) a una enfermedad.</p>
</blockquote>
<p>Consideremos las siguientes <span class="math inline">\(H_0\)</span>:</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(H_0: P(R|S) = P(R|T)\)</span></p></li>
<li><p><span class="math inline">\(H_0: P(NR|S) = P(NR|T)\)</span></p></li>
<li><p><span class="math inline">\(H_0: P(S|R) = P(S|NR)\)</span></p></li>
<li><p><span class="math inline">\(H_0: P(T|R) = P(T|NR)\)</span></p></li>
</ol>
<p>Todas ellas son igual de válidas. Sin embargo la siguiente hipótesis no es valida.</p>
<ol start="5" style="list-style-type: decimal">
<li><span class="math inline">\(H_0: P(R|S) = P(NR|S)\)</span></li>
</ol>
<p>La primer hipótesis compara dos grupos (plantas pequeñas con altas) respecto a la resistencia a la enfermedad. mientras que la hipótesis 5 es una afirmación acerca de la distribución de la resistencia a la enfermedad en solo un grupo (plantas bajas).</p>
<p>Supongamos ahora que hacemos un muestreo aleatorio de 100 plantas de esta población.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="inferencia-de-datos-categóricos.html#cb230-1" aria-hidden="true" tabindex="-1"></a>plantas <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">28</span>, <span class="dv">42</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> T)</span>
<span id="cb230-2"><a href="inferencia-de-datos-categóricos.html#cb230-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(plantas) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">&quot;R&quot;</span>, <span class="st">&quot;NR&quot;</span>), <span class="fu">c</span>(<span class="st">&quot;S&quot;</span>, <span class="st">&quot;T&quot;</span>))</span>
<span id="cb230-3"><a href="inferencia-de-datos-categóricos.html#cb230-3" aria-hidden="true" tabindex="-1"></a>plantas</span></code></pre></div>
<pre><code>##     S  T
## R  12 18
## NR 28 42</code></pre>
<table style="width:97%;">
<colgroup>
<col width="23%" />
<col width="27%" />
<col width="26%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>S</th>
<th>T</th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>R</strong></td>
<td>12</td>
<td>18</td>
<td>30</td>
</tr>
<tr class="even">
<td><strong>NR</strong></td>
<td>28</td>
<td>42</td>
<td>70</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>40</td>
<td>60</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>Vamos a corroborar las hipótesis antes generadas:</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(H_0: P(R|S) = P(R|T) = \frac{12}{40} = \frac{18}{60} = 0.30\)</span></p></li>
<li><p><span class="math inline">\(H_0: P(NR|S) = P(NR|T) = \frac{28}{40} = \frac{42}{60} = 0.70\)</span></p></li>
<li><p><span class="math inline">\(H_0: P(S|R) = P(S|NR) = \frac{12}{30} = \frac{28}{70} = 0.40\)</span></p></li>
<li><p><span class="math inline">\(H_0: P(T|R) = P(T|NR) = \frac{18}{30} = \frac{42}{70} = 0.30\)</span></p></li>
</ol>
<p>Sin embargo, con la hipótesis 5.</p>
<ol start="5" style="list-style-type: decimal">
<li><span class="math inline">\(H_0: P(R|S) = \frac{12}{40} = 0.40\)</span> y <span class="math inline">\(H_0: P(NR|S) = \frac{28}{40} = 0.70\)</span>.</li>
</ol>
<div id="cuestiones-acerca-de-las-columnas-y-filas" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Cuestiones acerca de las columnas y filas</h3>
<p>El hecho de que la tabla anterior muestre la independencia vista tanto por medio de las filas o columnas no es casualidad, como se demuestra en la siguiente tabla.</p>
<table style="width:97%;">
<colgroup>
<col width="23%" />
<col width="27%" />
<col width="26%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th></th>
<th></th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>a</td>
<td>b</td>
<td>a + b</td>
</tr>
<tr class="even">
<td></td>
<td>c</td>
<td>d</td>
<td>c + d</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>a + c</td>
<td>b + d</td>
<td></td>
</tr>
</tbody>
</table>
<p>Entonces,</p>
<p><span class="math display">\[\begin{align}
\frac{a}{c} = \frac{b}{d}
\end{align}\]</span></p>
<p>si y solo si</p>
<p><span class="math display">\[\begin{align}
\frac{a}{b} = \frac{c}{d}
\end{align}\]</span></p>
<p>Otra forma en la que esto se puede expresar es</p>
<p><span class="math display">\[\begin{align}
\frac{a}{a+c} = \frac{b}{b+d}
\end{align}\]</span></p>
<p>si y solo si</p>
<p><span class="math display">\[\begin{align}
\frac{a}{a+b} = \frac{c}{c+d}
\end{align}\]</span></p>
<p>Otra cuestión es que si <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span>, <span class="math inline">\(c\)</span> y <span class="math inline">\(d\)</span> son números positivos, entonces</p>
<p><span class="math display">\[\begin{align}
\frac{a}{a+c} &gt; \frac{b}{b+d}
\end{align}\]</span></p>
<p>si y solo si</p>
<p><span class="math display">\[\begin{align}
\frac{a}{a+b} &gt; \frac{c}{c+d}
\end{align}\]</span></p>
</div>
</div>
<div id="prueba-exacta-de-fisher" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Prueba exacta de Fisher</h2>
<p>Con esta prueba se encuentra la probabilidad de que la tabla de contingencia que tengamos, haya surgido por mero azar, dado que las probabilidades marginales de la tabla son fijas. Se utiliza especialmente con muestras pequeñas. La fórmula para calcular nuestro valor es la siguiente:</p>
<p><span class="math display" id="eq:fisher">\[\begin{align}
p = \frac{\binom{a+b}{a}\binom{c+d}{c}}{\binom{n}{a+c}} = \frac{(a+b)!(c+d)!(a+c)!(b+d)!}{a! \space b! \space c! \space d!  \space n!}
\tag{5.10}
\end{align}\]</span></p>
<p>Donde <span class="math inline">\(\binom{n}{k}\)</span> es el coeficiente binomial (<span class="math inline">\(_{n}C_{k}\)</span>). Para recordar este coeficiente aquí tenemos la fórmula.</p>
<p><span class="math display" id="eq:binc2">\[\begin{equation}
_{n}C_{k} = \frac{n!}{k!(n-k)!}
\tag{5.11}
\end{equation}\]</span></p>
<p>Por ejemplo, para el primer y segundo coeficiente binomial obtendríamos lo siguiente:</p>
<p><span class="math display">\[\begin{align}
_{a+b}C_{a} = \frac{a+b!}{a!(a+b-a)!} \\
_{a+b}C_{a} = \frac{c+d!}{c!(c+d-c)!} 
\end{align}\]</span></p>
<p>Y para el último coeficiente, sería algo así:</p>
<p><span class="math display">\[\begin{align}
_{n}C_{a+c} = \frac{n!}{a+c!(n-a+c)!} 
\end{align}\]</span></p>
<p>Cuando hacemos una prueba exacta de Fisher para probar una hipótesis nula contra una hipótesis alternativa direccional, necesitamos encontrar la probabilidad de todas las tablas de datos (teniendo los mismos margenes que la tabla observada) que provean evidencia al menos tan fuerte en contra de <span class="math inline">\(H_0\)</span>, en la dirección predicha por la <span class="math inline">\(H_A\)</span>, como la tabla observada.</p>
<p>Posteriormente calculamos el valor-<em>p</em> como la suma de las probabilidades de obtener tablas tan extremas como las obtenidas, si la <span class="math inline">\(H_0\)</span> es verdad.</p>
<p>Afortunadamente no tenemos que buscar los valores de todas las tablas posibles una por una y en su lugar podemos utilizar el comando <code>fisher.test()</code> que viene incluido en <code>R</code>.</p>
<blockquote>
<p><strong>Ejemplo:</strong> La oxigenación extracorpórea por membrana (ECMO) es un procedimiento con el potencial de salvar vidas de bebés recién nacidos que sufren de una falla respiratoria severa. En un experimento se trataron a 29 bebés recién nacidos con ECMO y a 10 bebés recién nacidos con terapia médica convencional (CMT).</p>
</blockquote>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="inferencia-de-datos-categóricos.html#cb232-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creamos nuestra matriz de datos.</span></span>
<span id="cb232-2"><a href="inferencia-de-datos-categóricos.html#cb232-2" aria-hidden="true" tabindex="-1"></a>Tratamientos <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">28</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> T)</span>
<span id="cb232-3"><a href="inferencia-de-datos-categóricos.html#cb232-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(Tratamientos) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">&quot;Muerto&quot;</span>, <span class="st">&quot;Vivo&quot;</span>), <span class="fu">c</span>(<span class="st">&quot;CMT&quot;</span>, <span class="st">&quot;ECMO&quot;</span>))</span>
<span id="cb232-4"><a href="inferencia-de-datos-categóricos.html#cb232-4" aria-hidden="true" tabindex="-1"></a>Tratamientos</span></code></pre></div>
<pre><code>##        CMT ECMO
## Muerto   4    1
## Vivo     6   28</code></pre>
<table style="width:99%;">
<colgroup>
<col width="23%" />
<col width="27%" />
<col width="26%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>CMT</th>
<th>ECMO</th>
<th><strong>Total</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Muerto</strong></td>
<td>4</td>
<td>1</td>
<td>5</td>
</tr>
<tr class="even">
<td><strong>Vivo</strong></td>
<td>6</td>
<td>28</td>
<td>34</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>10</td>
<td>29</td>
<td>39</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="inferencia-de-datos-categóricos.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(Tratamientos)</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  Tratamientos
## p-value = 0.01102
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##    1.366318 944.080411
## sample estimates:
## odds ratio 
##   16.78571</code></pre>
<p>Como podemos ver, el <span class="math inline">\(valor-p = 0.01102\)</span> lo que quiere decir que rechazamos la <span class="math inline">\(H_0\)</span> y aceptamos la <span class="math inline">\(H_A: P(Muerto|ECMO) &lt; P(Muerto|CMT)\)</span>.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="inferencia-de-datos-categóricos.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(Tratamientos)</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  Tratamientos
## p-value = 0.01102
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##    1.366318 944.080411
## sample estimates:
## odds ratio 
##   16.78571</code></pre>
<p>Para cambiar la direccionalidad de nuestra hipótesis basta con que agreguemos el argumento <code>alternative = "two.sided"</code> para una <span class="math inline">\(H_A\)</span> no direccional y <code>alternative = "less"</code> o <code>alternative = "greater"</code> para una <span class="math inline">\(H_A\)</span> direccional.</p>
</div>
<div id="tablas-de-contingencia-r-times-k" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Tablas de contingencia <span class="math inline">\(r \times k\)</span></h2>
<p>En esta sección consideraremos tablas de contingencia más grandes, con <span class="math inline">\(r\)</span> filas y <span class="math inline">\(k\)</span> columnas. Veamos el siguiente ejemplo.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Ecólogos que estudiaron los hábitats reproductivos del Chorlo Llanero (<em>Charadrius montanus</em>) durante 3 años y anotaron en dónde es que anidan. Encontraron 66 nidos en zonas agricolas (ZA), 67 en pastizales con perritos de las praderas (PP) y otros 20 en praderas (P). La siguiente tabla muestra las elecciones a través de los años.</p>
</blockquote>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="inferencia-de-datos-categóricos.html#cb238-1" aria-hidden="true" tabindex="-1"></a>chorlos <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">19</span>, <span class="dv">26</span>, <span class="dv">17</span>, <span class="dv">38</span>, <span class="dv">12</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">9</span>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> T)</span>
<span id="cb238-2"><a href="inferencia-de-datos-categóricos.html#cb238-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(chorlos) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">&quot;Zona Agricola (ZA)&quot;</span>, <span class="st">&quot;Pastizal con Perritos (PP)&quot;</span>, <span class="st">&quot;Praderas (P)&quot;</span>), <span class="fu">c</span>(<span class="st">&quot;2004&quot;</span>, <span class="st">&quot;2005&quot;</span>, <span class="st">&quot;2006&quot;</span>))</span>
<span id="cb238-3"><a href="inferencia-de-datos-categóricos.html#cb238-3" aria-hidden="true" tabindex="-1"></a>chorlos</span></code></pre></div>
<pre><code>##                            2004 2005 2006
## Zona Agricola (ZA)           21   19   26
## Pastizal con Perritos (PP)   17   38   12
## Praderas (P)                  5    6    9</code></pre>
<table style="width:100%;">
<colgroup>
<col width="42%" />
<col width="14%" />
<col width="14%" />
<col width="14%" />
<col width="15%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>2004</strong></td>
<td><strong>2005</strong></td>
<td><strong>2006</strong></td>
<td><strong>Total</strong></td>
</tr>
<tr class="even">
<td><strong>Zona Agrícola (ZA)</strong></td>
<td>21</td>
<td>19</td>
<td>26</td>
<td>66</td>
</tr>
<tr class="odd">
<td><strong>Pastizal con Perritos (PP)</strong></td>
<td>17</td>
<td>38</td>
<td>12</td>
<td>67</td>
</tr>
<tr class="even">
<td><strong>Praderas (P)</strong></td>
<td>5</td>
<td>6</td>
<td>9</td>
<td>20</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>43</td>
<td>63</td>
<td>47</td>
<td>153</td>
</tr>
</tbody>
</table>
<p>En este caso, podemos transformar los valores absolutos en relativos haciendo uso del total que se encuentra en las columnas. Por ejemplo, en el caso de <em>2004</em> y la <em>ZA</em> tendríamos algo como <span class="math inline">\(\frac{21}{43} = 0.488\)</span> y así sucesivamente.</p>
<table style="width:92%;">
<colgroup>
<col width="45%" />
<col width="15%" />
<col width="15%" />
<col width="15%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>2004</strong></td>
<td><strong>2005</strong></td>
<td><strong>2006</strong></td>
</tr>
<tr class="even">
<td><strong>Zona Agrícola (ZA)</strong></td>
<td>48.8</td>
<td>30.2</td>
<td>55.3</td>
</tr>
<tr class="odd">
<td><strong>Pastizal con Perritos (PP)</strong></td>
<td>39.5</td>
<td>60.3</td>
<td>25.5</td>
</tr>
<tr class="even">
<td><strong>Praderas (P)</strong></td>
<td>11.6</td>
<td>9.5</td>
<td>19.1</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>99.9</td>
<td>100</td>
<td>99.9</td>
</tr>
</tbody>
</table>
<p>Algunos totales no dan el 100 debido al redondeo. Podemos ver en la figura <a href="inferencia-de-datos-categóricos.html#fig:Ej2a">5.4</a> las proporciones de cada una de las áreas de anidamiento correspondientes con cada año. Estos porcentajes que tenemos en la tabla son nuestras probabilidades condicionales, es decir <span class="math inline">\(P(ZA|2004) = 0.488\)</span>, <span class="math inline">\(P(PP|2004) = 0.395\)</span>, <span class="math inline">\(P(P|2004) = 0.116\)</span> y así sucesivamente…</p>
<div class="figure" style="text-align: center"><span id="fig:Ej2a"></span>
<img src="Curso_R_basico_files/figure-html/Ej2a-1.png" alt="Gráfica con las proporciones de las zonas de anidamiento del Chorlo Llanero." width="672" />
<p class="caption">
Figura 5.4: Gráfica con las proporciones de las zonas de anidamiento del Chorlo Llanero.
</p>
</div>
<p>Para esto simplemente aplicamos la fórmula de Chi-cuadrada.</p>
<p><span class="math display" id="eq:chirk">\[\begin{align}
\sum_{r \times k} = \frac{(o_i - e_i)^2}{e_i}
\tag{5.12}
\end{align}\]</span></p>
<p>Donde <span class="math inline">\(r \times k\)</span> son todas las celdas de nuestra tabla de contingencia. Los valores <span class="math inline">\(e\)</span> se calculan con la fórmula vista anteriormente <a href="inferencia-de-datos-categóricos.html#eq:e">(5.9)</a>. Para los grados de libertad <span class="math inline">\(df\)</span> utilizaríamos la siguiente fórmula:</p>
<p><span class="math display" id="eq:dfrk">\[\begin{align}
df = (r-1)(k-1)
\tag{5.13}
\end{align}\]</span></p>
<p>Nuestra <span class="math inline">\(H_0\)</span> para los Chorlos sería que la preferencia de anidamiento es igual en todos los años y la <span class="math inline">\(H_A\)</span> sería que son distintas.</p>
<p><span class="math display">\[\begin{equation*}
H_0:
\begin{Bmatrix}
P(ZA|2004) = P(ZA|2005) = P(ZA|2006) \\
P(PP|2004) = P(PP|2005) = P(PP|2006) \\
P(P|2004) = P(P|2005) = P(P|2006)
\end{Bmatrix}
\end{equation*}\]</span></p>
<p>Igual que con la tabla de contingencia de 2x2, multiplicamos la probabilidad marginal por el total para obtener el valor esperado. Es decir, del total chorlos en la Zona Agrícola (ZA) <span class="math inline">\(\frac{66}{153} \times 43 = 18.55\)</span> y así sucesivamente.</p>
<table>
<colgroup>
<col width="38%" />
<col width="15%" />
<col width="15%" />
<col width="15%" />
<col width="15%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>2004</strong></td>
<td><strong>2005</strong></td>
<td><strong>2006</strong></td>
<td><strong>Total</strong></td>
</tr>
<tr class="even">
<td><strong>Zona Agrícola (ZA)</strong></td>
<td>21 (18.55)</td>
<td>19 (21.18)</td>
<td>26 (20.27)</td>
<td>66</td>
</tr>
<tr class="odd">
<td><strong>Pastizal con Perritos (PP)</strong></td>
<td>17 (18.83)</td>
<td>38 (27.59)</td>
<td>12 (20.58)</td>
<td>67</td>
</tr>
<tr class="even">
<td><strong>Praderas (P)</strong></td>
<td>5 (5.62)</td>
<td>6 (8.24)</td>
<td>9 (6.14)</td>
<td>20</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>43</td>
<td>63</td>
<td>47</td>
<td>153</td>
</tr>
</tbody>
</table>
<p>Ahora simplemente aplicamos la fórmula de Chi-cuadrada para obtener nuestro estadístico <span class="math inline">\(\chi_s^2\)</span>.</p>
<p><span class="math display">\[\begin{equation}
\chi_s^2 = \frac{(21-18.55)^2}{18.55} + \frac{(19-21.18)^2}{21.18} + \cdots + \frac{(9-6.14)^2}{6.14} = 14.09
\end{equation}\]</span></p>
<p>Nuestros <span class="math inline">\(df\)</span> son los siguientes, dado que <span class="math inline">\(r = 3\)</span> y <span class="math inline">\(k = 3\)</span>:</p>
<p><span class="math display">\[\begin{equation}
df = (3-1)(3-1) = 4
\end{equation}\]</span></p>
<p>Si buscamos el valor de tablas, vemos que el valor-<em>p</em> se encuentra entre 0.01 y 0.001. Pero para facilitarnos la vida, simplemente ingresamos nuestra variable <code>chorlos</code> que creamos previamente a la función <code>chisq.test()</code> y obtenemos nuestro resultado. Podemos corroborar que el valor de <span class="math inline">\(\chi^2\)</span> calculado coincide al igual que los <span class="math inline">\(df\)</span>. Nuestro <span class="math inline">\(valor-p = 0.007\)</span> por lo tanto, <span class="math inline">\(valor-p &lt; 0.01\)</span>, tenemos evidencias significativas con un <span class="math inline">\(\alpha = 0.01\)</span> de de que los Chorlos Llaneros cambiaron de sitio de anidación. Para estos casos, nuestra <span class="math inline">\(H_A\)</span> siempre será no direccional.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="inferencia-de-datos-categóricos.html#cb240-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(chorlos)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  chorlos
## X-squared = 14.089, df = 4, p-value = 0.007015</code></pre>
<p>Al igual que con las tablas de contingencia 2x2, las tabla <span class="math inline">\(r \times k\)</span> pueden ser vistas bajo dos contextos.</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(k\)</span> muestras independientes; una variable categórica observada con <span class="math inline">\(r\)</span> categorías</p></li>
<li><p>Una muestra; dos variables categóricas observadas — una con <span class="math inline">\(k\)</span> categorías y otra con <span class="math inline">\(r\)</span> categorías.</p></li>
</ol>
<p>Y al igual que las tablas 2x2, el cálculo del valor <span class="math inline">\(\chi^2\)</span> es el mismo para ambos contexto pero la interpretación de las hipótesis cambia.</p>
</div>
<div id="intervalos-de-confianza-para-la-diferencia-entre-probabilidades" class="section level2" number="5.7">
<h2><span class="header-section-number">5.7</span> Intervalos de confianza para la diferencia entre probabilidades</h2>
<p>Un modo de análisis complementario para la prueba de Chi-cuadrada es la construcción de intervalos de confianza para la magnitud de diferencia (<span class="math inline">\(p_1 - p_2\)</span>). Para esto vamos a definir nuevas estimaciones que están basadas en la idea de añadir 1 observación a cada celda de nuestra tabla.</p>
<p>Consideremos una tabla de contingencia 2x2.</p>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-160">Tabla 5.5: </span>Dos muestra hipotéticas
</caption>
<thead>
<tr>
<th style="text-align:center;">
Muestra 1
</th>
<th style="text-align:center;">
Muestra 2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 4cm; ">
<span class="math inline">\(x_1\)</span>
</td>
<td style="text-align:center;min-width: 4cm; ">
<span class="math inline">\(x_2\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
<span class="math inline">\(n_1 - x_1\)</span>
</td>
<td style="text-align:center;min-width: 4cm; ">
<span class="math inline">\(n_2 - x_2\)</span>
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
<span class="math inline">\(n_1\)</span>
</td>
<td style="text-align:center;min-width: 4cm; ">
<span class="math inline">\(n_2\)</span>
</td>
</tr>
</tbody>
</table>
<p>Definimos entonces</p>
<p><span class="math display">\[\begin{equation}
\tilde{p_1} = \frac{x_1 + 1}{n_1 + 2} \\
\tilde{p_2} = \frac{x_2 + 1}{n_2 + 2}
\end{equation}\]</span></p>
<p>Y usaremos la diferencia entre <span class="math inline">\(\tilde{p_1} - \tilde{p_2}\)</span> para construir el intervalo de confianza para (<span class="math inline">\(p_1 - p_2\)</span>). De igual manera, <span class="math inline">\(\tilde{P_1} - \tilde{P_2}\)</span> esta sujeta a error de muestreo. Para calcular este error usamos la fórmula de error estándar para <span class="math inline">\(\tilde{P_1} - \tilde{P_2}\)</span>.</p>
<p><span class="math display" id="eq:stderrorp">\[\begin{equation}
SE_{\tilde{P_1} - \tilde{P_2}} = \sqrt{\frac{\tilde{p_1}(1-\tilde{p_1})}{n_1 + 2} + \frac{\tilde{p_2}(1-\tilde{p_2})}{n_2 + 2}}
\tag{5.14}
\end{equation}\]</span></p>
<p>Un intervalo de confianza al 95% sería de la siguiente manera.</p>
<p><span class="math display">\[\begin{equation}
(\tilde{p_1} - \tilde{p_2}) \pm (1.96)SE_{\tilde{P_1} - \tilde{P_2}}
\end{equation}\]</span></p>
<p>Para calcular un intervalo de confianza de las proporciones o probabilidades en <code>R</code> utilizamos la función <code>prop.test()</code>. Para este comando es necesario que la matriz de datos sea 2x2. Por ejemplo.</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="inferencia-de-datos-categóricos.html#cb242-1" aria-hidden="true" tabindex="-1"></a>prop.datos <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">23</span>, <span class="dv">6</span>, <span class="dv">16</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> T)</span>
<span id="cb242-2"><a href="inferencia-de-datos-categóricos.html#cb242-2" aria-hidden="true" tabindex="-1"></a>prop.datos</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   18   23
## [2,]    6   16</code></pre>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="inferencia-de-datos-categóricos.html#cb244-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(prop.datos, <span class="at">correct =</span> F)</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity
##  correction
## 
## data:  prop.datos
## X-squared = 1.679, df = 1, p-value = 0.1951
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.07392967  0.40652391
## sample estimates:
##    prop 1    prop 2 
## 0.4390244 0.2727273</code></pre>
</div>
<div id="datos-pareados-en-tablas-2x2" class="section level2" number="5.8">
<h2><span class="header-section-number">5.8</span> Datos pareados en tablas 2x2</h2>
<p>Para datos pareados en tablas de 2x2 necesitamos reconstruir nuestra tabla de cierta manera. Veamos esto con un ejemplo.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Se conduce un estudio para determinar el riesgo de que una mujer transmita el VIH a sus hijos no nacidos. De una muestra de 114 mujeres infectadas con VIH que dieron a luz a dos hijos, se encontró que la infección por VIH ocurrió en 19 de los 114 hijos mayores y en 20 de los 114 hijos menores.</p>
</blockquote>
<table style="width:64%;">
<colgroup>
<col width="16%" />
<col width="23%" />
<col width="23%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Hijo mayor</strong></td>
<td><strong>Hijo menor</strong></td>
</tr>
<tr class="even">
<td><strong>VIH +</strong></td>
<td>19</td>
<td>20</td>
</tr>
<tr class="odd">
<td><strong>VIH -</strong></td>
<td>95</td>
<td>94</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>114</td>
<td>114</td>
</tr>
</tbody>
</table>
<p>Como se puede ver, estos datos claramente están pareados ya que tanto los hijos menores como mayores provienen de la misma madre. Una forma de representar esta tabla es de la siguiente manera.</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Hijo menor con VIH +</strong></td>
<td><strong>Hijo menor con VIH -</strong></td>
</tr>
<tr class="even">
<td><strong>Hijo mayor con VIH +</strong></td>
<td>2</td>
<td>17</td>
</tr>
<tr class="odd">
<td><strong>Hijo mayor con VIH -</strong></td>
<td>18</td>
<td>77</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>114</td>
<td>114</td>
</tr>
</tbody>
</table>
<p>Como podemos ver, hay dos casos que corresponden a una respuesta <em>sí/sí</em> y 77 casos que corresponden a una respuesta <em>no/no.</em> Estos no nos ayudan a determinar si el VIH ocurre con mayor frecuencia en hijos menores que en mayores, y se les conoce como <strong>pares concordantes.</strong> Tenemos a su vez 17 casos <em>sí/no</em> y 18 <em>no/sí.</em> Estos se conocen como <strong>pares discordantes</strong> y nos ayudan a determinar si la infección por VIH ocurre con mayor frecuencia en uno de los dos casos (hijos mayores vs menores).</p>
<p>Por lo tanto, nuestra <em><span class="math inline">\(H_0:\)</span> la probabilidad de infección por VIH es la misma para hijos mayores y menores.</em></p>
<p><span class="math display">\[\begin{equation}
H_0: entre \space pares \space discordantes, \space P(sí/no) = P(no/sí) = \frac{1}{2}
\end{equation}\]</span></p>
<p>Para este tipo de pruebas se utiliza la <strong>prueba de Chi-cuadrada de McNemar.</strong> Tiene una forma sumamente sencilla de aplicarse. Imaginemos que <span class="math inline">\(n_{11}\)</span> corresponde al número de pares <em>sí/sí</em>, <span class="math inline">\(n_{12}\)</span> corresponde al número de pares <em>sí/no</em>, <span class="math inline">\(n_{21}\)</span> al número de pares <em>no/sí</em> y <span class="math inline">\(n_{22}\)</span> al número de pares <em>no/no.</em></p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>+</strong></td>
<td><strong>-</strong></td>
</tr>
<tr class="even">
<td><strong>+</strong></td>
<td><em>n<sub>11</sub></em></td>
<td><em>n<sub>12</sub></em></td>
</tr>
<tr class="odd">
<td><strong>-</strong></td>
<td><em>n<sub>21</sub></em></td>
<td><em>n<sub>22</sub></em></td>
</tr>
</tbody>
</table>
<p>La fórmula para encontrar nuestro estadístico <span class="math inline">\(X_{s}^2\)</span> sería:</p>
<p><span class="math display" id="eq:mcnemar">\[\begin{equation}
X_{s}^2 = \frac{(n_{12} - \frac{(n_{12} + n_{21})}{2})^2}{\frac{(n_{12} - n_{21})}{2}} + \frac{(n_{21} - \frac{(n_{12} + n_{21})^2}{2})^2}{\frac{(n_{12} - n_{21})^2}{2}} \\
\tag{5.15}
\end{equation}\]</span></p>
<p>Esto se simplifica de la siguiente manera:</p>
<p><span class="math display" id="eq:mcnemar2">\[\begin{equation}
X_{s}^2 = \frac{(n_{12} - n_{21})^2}{n_{12} + n_{21}}
\tag{5.16}
\end{equation}\]</span></p>
<p>Para realizar esta prueba en <code>R</code>, simplemente utilizamos el comando <code>mcnemar.test()</code> con el argumento con nuestra matriz de datos y el argumento <code>correct = F</code>, para evitar que<code>R</code> realice correcciones.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="inferencia-de-datos-categóricos.html#cb246-1" aria-hidden="true" tabindex="-1"></a>VIH <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">17</span>, <span class="dv">18</span>, <span class="dv">77</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> T)</span>
<span id="cb246-2"><a href="inferencia-de-datos-categóricos.html#cb246-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(VIH) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">&quot;Hijo mayor&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;VIH +&quot;</span>, <span class="st">&quot;VIH -&quot;</span>), <span class="st">&quot;Hijo menor&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;VIH +&quot;</span>, <span class="st">&quot;VIH -&quot;</span>))</span>
<span id="cb246-3"><a href="inferencia-de-datos-categóricos.html#cb246-3" aria-hidden="true" tabindex="-1"></a>VIH</span></code></pre></div>
<pre><code>##           Hijo menor
## Hijo mayor VIH + VIH -
##      VIH +     2    17
##      VIH -    18    77</code></pre>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="inferencia-de-datos-categóricos.html#cb248-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mcnemar.test</span>(VIH, <span class="at">correct =</span> F)</span></code></pre></div>
<pre><code>## 
##  McNemar&#39;s Chi-squared test
## 
## data:  VIH
## McNemar&#39;s chi-squared = 0.028571, df = 1, p-value = 0.8658</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estadística-inferencial.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelado-de-relaciones.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
