<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 7 Modelado de relaciones | Curso de R básico</title>
  <meta name="description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 7 Modelado de relaciones | Curso de R básico" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 7 Modelado de relaciones | Curso de R básico" />
  
  <meta name="twitter:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

<meta name="author" content="Alejandro Ruiz-García" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inferencia-de-datos-categóricos.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de R básico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Requisitos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#descarga-de-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Descarga de R y RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introducción-a-r.html"><a href="introducción-a-r.html"><i class="fa fa-check"></i><b>2</b> Introducción a R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introducción-a-r.html"><a href="introducción-a-r.html#interfaz"><i class="fa fa-check"></i><b>2.1</b> Interfaz</a></li>
<li class="chapter" data-level="2.2" data-path="introducción-a-r.html"><a href="introducción-a-r.html#creando-nuestro-primer-proyecto"><i class="fa fa-check"></i><b>2.2</b> Creando nuestro primer proyecto</a></li>
<li class="chapter" data-level="2.3" data-path="introducción-a-r.html"><a href="introducción-a-r.html#objetos-y-variables"><i class="fa fa-check"></i><b>2.3</b> Objetos y variables</a></li>
<li class="chapter" data-level="2.4" data-path="introducción-a-r.html"><a href="introducción-a-r.html#instalar-paquetes"><i class="fa fa-check"></i><b>2.4</b> Instalar paquetes</a></li>
<li class="chapter" data-level="2.5" data-path="introducción-a-r.html"><a href="introducción-a-r.html#importar-datos-a-r"><i class="fa fa-check"></i><b>2.5</b> Importar datos a R</a></li>
<li class="chapter" data-level="2.6" data-path="introducción-a-r.html"><a href="introducción-a-r.html#comentarios"><i class="fa fa-check"></i><b>2.6</b> Comentarios</a></li>
<li class="chapter" data-level="2.7" data-path="introducción-a-r.html"><a href="introducción-a-r.html#exportar-datos"><i class="fa fa-check"></i><b>2.7</b> Exportar datos</a></li>
<li class="chapter" data-level="2.8" data-path="introducción-a-r.html"><a href="introducción-a-r.html#pedir-ayuda"><i class="fa fa-check"></i><b>2.8</b> Pedir ayuda</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html"><i class="fa fa-check"></i><b>3</b> Estadística descriptiva</a>
<ul>
<li class="chapter" data-level="3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>3.1</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#media"><i class="fa fa-check"></i><b>3.1.1</b> Media</a></li>
<li class="chapter" data-level="3.1.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mediana"><i class="fa fa-check"></i><b>3.1.2</b> Mediana</a></li>
<li class="chapter" data-level="3.1.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#moda"><i class="fa fa-check"></i><b>3.1.3</b> Moda</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>3.2</b> Medidas de dispersión</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#rango"><i class="fa fa-check"></i><b>3.2.1</b> Rango</a></li>
<li class="chapter" data-level="3.2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#desviación-estándar"><i class="fa fa-check"></i><b>3.2.2</b> Desviación estándar</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-posición-relativa"><i class="fa fa-check"></i><b>3.3</b> Medidas de posición relativa</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#valores-z"><i class="fa fa-check"></i><b>3.3.1</b> Valores Z</a></li>
<li class="chapter" data-level="3.3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-absoluta"><i class="fa fa-check"></i><b>3.3.2</b> Frecuencia absoluta</a></li>
<li class="chapter" data-level="3.3.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-relativa"><i class="fa fa-check"></i><b>3.3.3</b> Frecuencia relativa</a></li>
<li class="chapter" data-level="3.3.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#cuartiles"><i class="fa fa-check"></i><b>3.3.4</b> Cuartiles</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#el-uso-de-la-librería-dplyr"><i class="fa fa-check"></i><b>3.4</b> El uso de la librería <code>dplyr</code></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="probabilidad.html"><a href="probabilidad.html"><i class="fa fa-check"></i><b>4</b> Probabilidad</a>
<ul>
<li class="chapter" data-level="4.1" data-path="probabilidad.html"><a href="probabilidad.html#probabilidad-frecuentista"><i class="fa fa-check"></i><b>4.1</b> Probabilidad frecuentista</a></li>
<li class="chapter" data-level="4.2" data-path="probabilidad.html"><a href="probabilidad.html#reglas-de-probabilidad"><i class="fa fa-check"></i><b>4.2</b> Reglas de probabilidad</a></li>
<li class="chapter" data-level="4.3" data-path="probabilidad.html"><a href="probabilidad.html#curvas-de-densidad"><i class="fa fa-check"></i><b>4.3</b> Curvas de densidad</a></li>
<li class="chapter" data-level="4.4" data-path="probabilidad.html"><a href="probabilidad.html#distribución-binomial"><i class="fa fa-check"></i><b>4.4</b> Distribución binomial</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="probabilidad.html"><a href="probabilidad.html#media-y-desviación-estándar-de-la-distribución-binomial"><i class="fa fa-check"></i><b>4.4.1</b> Media y desviación estándar de la distribución binomial</a></li>
<li class="chapter" data-level="4.4.2" data-path="probabilidad.html"><a href="probabilidad.html#distribución-binomial-en-r"><i class="fa fa-check"></i><b>4.4.2</b> Distribución binomial en R</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="probabilidad.html"><a href="probabilidad.html#distribución-normal"><i class="fa fa-check"></i><b>4.5</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="probabilidad.html"><a href="probabilidad.html#distribución-normal-en-r"><i class="fa fa-check"></i><b>4.5.1</b> Distribución normal en R</a></li>
<li class="chapter" data-level="4.5.2" data-path="probabilidad.html"><a href="probabilidad.html#pruebas-de-normalidad-en-r"><i class="fa fa-check"></i><b>4.5.2</b> Pruebas de normalidad en R</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="probabilidad.html"><a href="probabilidad.html#distribución-muestral"><i class="fa fa-check"></i><b>4.6</b> Distribución muestral</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="probabilidad.html"><a href="probabilidad.html#poblaciones-muestras-y-distribuciones-muestrales"><i class="fa fa-check"></i><b>4.6.1</b> Poblaciones, muestras y distribuciones muestrales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html"><i class="fa fa-check"></i><b>5</b> Estadística inferencial</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#error-estándar-de-la-media"><i class="fa fa-check"></i><b>5.1</b> Error estándar de la media</a></li>
<li class="chapter" data-level="5.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>5.2</b> Intervalo de confianza para <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#distribución-t-de-student"><i class="fa fa-check"></i><b>5.2.1</b> Distribución <span class="math inline">\(t\)</span> de Student</a></li>
<li class="chapter" data-level="5.2.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#construcción-de-un-intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>5.2.2</b> Construcción de un intervalo de confianza para <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="5.2.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalos-de-confianza-unilaterales"><i class="fa fa-check"></i><b>5.2.3</b> Intervalos de confianza unilaterales</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-de-dos-medias"><i class="fa fa-check"></i><b>5.3</b> Comparación de dos medias</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalo-de-confianza-para-mu_1---mu_2"><i class="fa fa-check"></i><b>5.3.1</b> Intervalo de confianza para <span class="math inline">\(\mu_1 - \mu_2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#pruebas-de-hipótesis"><i class="fa fa-check"></i><b>5.4</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#t-test"><i class="fa fa-check"></i><b>5.4.1</b> <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="5.4.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#t-test-de-una-cola"><i class="fa fa-check"></i><b>5.4.2</b> <span class="math inline">\(t\)</span> test de una cola</a></li>
<li class="chapter" data-level="5.4.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#tamaño-de-efecto"><i class="fa fa-check"></i><b>5.4.3</b> Tamaño de efecto</a></li>
<li class="chapter" data-level="5.4.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-wilcoxon-mann-whitney"><i class="fa fa-check"></i><b>5.4.4</b> Prueba de Wilcoxon-Mann-Whitney</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-de-muestras-pareadas"><i class="fa fa-check"></i><b>5.5</b> Comparación de muestras pareadas</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-t-pareada"><i class="fa fa-check"></i><b>5.5.1</b> Prueba de <span class="math inline">\(t\)</span> pareada</a></li>
<li class="chapter" data-level="5.5.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-signos"><i class="fa fa-check"></i><b>5.5.2</b> Prueba de signos</a></li>
<li class="chapter" data-level="5.5.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-rangos-con-signos-de-wilcoxon"><i class="fa fa-check"></i><b>5.5.3</b> Prueba de rangos con signos de Wilcoxon</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html"><i class="fa fa-check"></i><b>6</b> Inferencia de datos categóricos</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#distribuciones-de-una-muestra"><i class="fa fa-check"></i><b>6.1</b> Distribuciones de una muestra</a></li>
<li class="chapter" data-level="6.2" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-de-chi-cuadrada"><i class="fa fa-check"></i><b>6.2</b> Prueba de Chi-cuadrada</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#hipótesis-compuestas-y-direccionales"><i class="fa fa-check"></i><b>6.2.1</b> Hipótesis compuestas y direccionales</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-de-chi-cuadrada-para-tablas-de-contingencia"><i class="fa fa-check"></i><b>6.3</b> Prueba de Chi-cuadrada para tablas de contingencia</a></li>
<li class="chapter" data-level="6.4" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#interpretación-de-las-tablas-de-contingencia"><i class="fa fa-check"></i><b>6.4</b> Interpretación de las tablas de contingencia</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#cuestiones-acerca-de-las-columnas-y-filas"><i class="fa fa-check"></i><b>6.4.1</b> Cuestiones acerca de las columnas y filas</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-exacta-de-fisher"><i class="fa fa-check"></i><b>6.5</b> Prueba exacta de Fisher</a></li>
<li class="chapter" data-level="6.6" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#tablas-de-contingencia-r-times-k"><i class="fa fa-check"></i><b>6.6</b> Tablas de contingencia <span class="math inline">\(r \times k\)</span></a></li>
<li class="chapter" data-level="6.7" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#intervalos-de-confianza-para-la-diferencia-entre-probabilidades"><i class="fa fa-check"></i><b>6.7</b> Intervalos de confianza para la diferencia entre probabilidades</a></li>
<li class="chapter" data-level="6.8" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#datos-pareados-en-tablas-2x2"><i class="fa fa-check"></i><b>6.8</b> Datos pareados en tablas 2x2</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html"><i class="fa fa-check"></i><b>7</b> Modelado de relaciones</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#análisis-de-varianza-anova"><i class="fa fa-check"></i><b>7.1</b> Análisis de Varianza (ANOVA)</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#variación-dentro-de-los-grupos"><i class="fa fa-check"></i><b>7.1.1</b> Variación dentro de los grupos</a></li>
<li class="chapter" data-level="7.1.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#variación-entre-los-grupos"><i class="fa fa-check"></i><b>7.1.2</b> Variación entre los grupos</a></li>
<li class="chapter" data-level="7.1.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#una-relación-importante-en-el-anova"><i class="fa fa-check"></i><b>7.1.3</b> Una relación importante en el ANOVA</a></li>
<li class="chapter" data-level="7.1.4" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#tabla-de-anova"><i class="fa fa-check"></i><b>7.1.4</b> Tabla de ANOVA</a></li>
<li class="chapter" data-level="7.1.5" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#modelo-del-anova"><i class="fa fa-check"></i><b>7.1.5</b> Modelo del ANOVA</a></li>
<li class="chapter" data-level="7.1.6" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#distribución-de-f"><i class="fa fa-check"></i><b>7.1.6</b> Distribución de <span class="math inline">\(F\)</span></a></li>
<li class="chapter" data-level="7.1.7" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#prueba-de-f"><i class="fa fa-check"></i><b>7.1.7</b> Prueba de <span class="math inline">\(F\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso de R básico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelado-de-relaciones" class="section level1" number="7">
<h1><span class="header-section-number">Lección 7</span> Modelado de relaciones</h1>
<p>En esta lección vamos a considerar la comparación de más de dos muestras y los diversos métodos que podemos emplear para esto.</p>
<div id="análisis-de-varianza-anova" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Análisis de Varianza (ANOVA)</h2>
<p>El análisis clásico para realizar observaciones de múltiples muestras es el <strong>análisis de varianza</strong> o <strong>ANOVA.</strong> Para llevar a cabo este análisis existen ciertos supuestos que nuestros datos deben de cumplir.</p>
<ul>
<li>Distribución normal de los datos.</li>
<li>Homocedasticidad (varianzas iguales).</li>
<li>Datos independientes.</li>
</ul>
<p>La distribución normal y la homocedasticidad son hasta cierto punto flexibles. Sin embargo, el ANOVA es sumamente sentitivo a muestras no independientes. Pese a su nombre, el análisis de varianza en realidad busca <strong>diferencias en las medias</strong> (<span class="math inline">\(\mu\)</span>) de las muestras.</p>
<p>Empezaremos con el ANOVA de una vía, es decir, un ANOVA en el cuál una sola variable define los grupos o tratamientos. El ANOVA de <span class="math inline">\(I\)</span> muestras o grupos inicia con el cálculo de las cantidades que describen la variabilidad de los datos <em>entre</em> los grupos y <em>dentro</em> de los grupos. Antes de empezar con esto, veamos un poco de notación utilizada en un ANOVA.</p>
<ul>
<li><p><span class="math inline">\(x_{ij}\)</span>: observación <span class="math inline">\(j\)</span> en el <span class="math inline">\(i\)</span>-ésimo grupo. Por ejemplo la primer observación del primer grupo o muestra sería <span class="math inline">\(x_{11}\)</span>, la segunda <span class="math inline">\(x_{12}\)</span> y así sucesivamente.</p></li>
<li><p><span class="math inline">\(k\)</span>: Número total de grupos, muestras o tratamientos.</p></li>
<li><p><span class="math inline">\(n_i\)</span>: número de observaciones en el <span class="math inline">\(i\)</span>-ésimo grupo.</p></li>
<li><p><span class="math inline">\(\overline{x}_i\)</span>: la media del <span class="math inline">\(i\)</span>-ésimo grupo.</p></li>
<li><p><span class="math inline">\(s_i\)</span>: la desviación estándar del <span class="math inline">\(i\)</span>-ésimo grupo.</p></li>
<li><p><span class="math inline">\(n\)</span>: el número total de observaciones, dado por la fórmula:</p></li>
</ul>
<p><span class="math display">\[\begin{equation}
n = \sum_{i = 1}^k n_i
\end{equation}\]</span></p>
<ul>
<li><span class="math inline">\(\overline{x}\)</span>: la gran media o promedio de todas las observaciones, dado por la fórmula:</li>
</ul>
<p><span class="math display">\[\begin{equation}
\overline{x} = \frac{\sum_{i = 1}^k \sum_{j = 1}^{n_i}n_{ij}}{n} = \frac{\sum_{i = 1}^k n_{i} \overline{x}_i}{\sum_{i}^k n_i} = \frac{\sum_{i = 1}^k n_{i} \overline{x}_i}{n}
\end{equation}\]</span></p>
<div id="variación-dentro-de-los-grupos" class="section level3" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Variación dentro de los grupos</h3>
<p>Una medida de variación dentro de los grupos es la <strong>varianza agrupada,</strong> denotada como <span class="math inline">\(s_{p}^2\)</span>. Su cálculo se obtiene de la siguiente manera:</p>
<p><span class="math display" id="eq:varpooled">\[\begin{equation}
s_{p}^2 = \frac{\sum_{i=1}^k (n_i - 1)s_i^2}{\sum_{i=1}^k(n_i - 1)} = \frac{\sum_{i=1}^k (n_i - 1)s_i^2}{n - k}
\tag{7.1}
\end{equation}\]</span></p>
<p>Mientras que para obtener la desviación estándar agrupadas simplemente obtenemos la raíz cuadrada.</p>
<p><span class="math display" id="eq:sdpooled">\[\begin{equation}
s_{p} = \sqrt{\frac{\sum_{i=1}^k (n_i - 1)s_i^2}{\sum_{i=1}^k(n_i - 1)}} = \sqrt{\frac{\sum_{i=1}^k (n_i - 1)s_i^2}{n - k}}
\tag{7.2}
\end{equation}\]</span></p>
<p>El valor de la desviación estándar agrupada solamente depende de la variabilidad dentro de los datos y no de sus medias. Por ahora, vamos a asignar términos correspondientes al ANOVA a nuestra fórmula.</p>
<p>El númerador de la varianza agrupada se conoce como <strong>suma de cuadrados dentro de los grupos,</strong> <span class="math inline">\(SS(dentro)\)</span> mientras que el denominador son los <strong>grados de libertad dentro de los grupos,</strong> <span class="math inline">\(df(dentro)\)</span>.</p>
<p>Así, entoces:</p>
<p><span class="math display" id="eq:sswithin">\[\begin{equation}
SS(dentro) = \sum_{i = 1}^k (n_i - 1)^2
\tag{7.3}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:dfwithin">\[\begin{equation}
df(dentro) = n - k
\tag{7.4}
\end{equation}\]</span></p>
<p>La razón entre estos dos valores se conoce como <strong>cuadrados medios dentro de los grupos,</strong> <span class="math inline">\(MS(dentro)\)</span>.</p>
<p><span class="math display" id="eq:mswithin">\[\begin{equation}
MS(dentro) = \frac{SS(dentro)}{df(dentro)}
\tag{7.5}
\end{equation}\]</span></p>
<p>Por lo tanto <span class="math inline">\(MS(dentro)\)</span> mide la variabilidad dentro de los grupos.</p>
</div>
<div id="variación-entre-los-grupos" class="section level3" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Variación entre los grupos</h3>
<p>En los casos en los que solamente tenemos dos grupos, la diferencia es simplemente <span class="math inline">\((\overline{x}_1 - \overline{x}_2)\)</span>. Sin embargo, en este caso tenemos más dos grupos que queremos comparar. Para este caso utilizamos los <strong>cuadrados medios entre los grupos,</strong> <span class="math inline">\(MS(entre)\)</span>. Su cálculo se obtiene de la siguiente manera:</p>
<p><span class="math display" id="eq:msbetween">\[\begin{equation}
MS(entre) = \frac{\sum_{i=1}^k n_i(\overline{x}_i - \overline{x})^2}{k - 1}
\tag{7.6}
\end{equation}\]</span></p>
<p>De igual manera, el numerador y denominador tienen sus nombres respectivos. Al numerador se le conoce coo <strong>suma de cuadrados entre los grupos,</strong> <span class="math inline">\(SS(entre)\)</span> y al denominador como <strong>grados de libertad entre los grupos,</strong> <span class="math inline">\(df(entre)\)</span>.</p>
<p><span class="math display" id="eq:ssbetween">\[\begin{equation}
SS(entre) = \sum_{i=1}^k n_i(\overline{x}_i - \overline{x})^2
\tag{7.7}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:dfbetween">\[\begin{equation}
df(dentro) = k - 1
\tag{7.8}
\end{equation}\]</span></p>
</div>
<div id="una-relación-importante-en-el-anova" class="section level3" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Una relación importante en el ANOVA</h3>
<p>El nombre <em>análisis de varianza</em> viene de la comparación entre <span class="math inline">\(SS(entre)\)</span> y <span class="math inline">\(SS(dentro)\)</span>. Consideremos un valor, <span class="math inline">\(x_{ij}\)</span>.</p>
<p><span class="math display">\[\begin{equation}
x_{ij} - \overline{x} = (x_{ij} - \overline{x}_i) + (x_{ij} - \overline{x})
\end{equation}\]</span></p>
<p>Esta ecuación expresa la desviación que hay en una observación <span class="math inline">\((x_{ij})\)</span> de la gran media <span class="math inline">\((\overline{x})\)</span> como la suma de dos partes: una desviación dentro del grupo <span class="math inline">\((x_{ij} - \overline{x}_i)\)</span> y una desviación entre grupos <span class="math inline">\((\overline{x}_i - \overline{x})\)</span>.</p>
<p>Esta relación se mantiene para la suma de cuadrados correspondiente:</p>
<p><span class="math display" id="eq:sstotal1">\[\begin{equation}
\sum_{i=1}^k\sum_{j=1}^{n_i}(x_{ij} - \overline{x})^2 = \sum_{i=1}^k \sum_{j=1}^{n_i}(x_{ij} - \overline{x}_i)^2 + \sum_{i=1}^k\sum_{j=1}^{n_i}(x_{ij} - \overline{x})^2
\tag{7.9}
\end{equation}\]</span></p>
<p>Que, al reescribirse se puede expresar como:</p>
<p><span class="math display" id="eq:sstotal2">\[\begin{equation}
\sum_{i=1}^k\sum_{j=1}^{n_i}(x_{ij} - \overline{x})^2 = \sum_{i=1}^k (n_i - 1)s_{i}^2 + \sum_{i=1}^k n_i (\overline{x}_i - \overline{x})^2
\tag{7.10}
\end{equation}\]</span></p>
<p>Esta cantidad se conoce como <strong>suma de cuadrados totales,</strong> <span class="math inline">\(SS(total)\)</span>.</p>
<p><span class="math display" id="eq:sstotal3">\[\begin{equation}
SS(total) = \sum_{i=1}^k\sum_{j=1}^{n_i}(x_{ij} - \overline{x})^2
\tag{7.11}
\end{equation}\]</span></p>
<p>Este valor mide la cantidad de variabilidad entre todas las <span class="math inline">\(n\)</span> observaciones en los grupos <span class="math inline">\(k\)</span>.</p>
<p><span class="math display" id="eq:sstotal4">\[\begin{equation}
SS(total) = SS(entre) + SS(dentro)
\tag{7.12}
\end{equation}\]</span></p>
<p>Esta relación anterior muestra cómo la variación total de nuestros datos puede dividirse o partirse en dos componentes: la variación entre grupos y la variación dentro de los grupos (de ahí el nombre, <strong>análisis de varianza</strong>).</p>
<p>Para los grados de libertad totales <span class="math inline">\(df(total)\)</span> se utiliza la siguiente fórmula:</p>
<p><span class="math display" id="eq:dftotal1">\[\begin{equation}
df(total) = n - 1
\tag{7.13}
\end{equation}\]</span></p>
<p>Y al igual que la suma de cuadrados, se pueden calcular sumando los grados de libertad entre y dentro de los grupos:</p>
<p><span class="math display" id="eq:dftotal2">\[\begin{equation}
df(total) = df(dentro) + df(entre) \\
df(total) = (n - k) + (k - 1)
\tag{7.14}
\end{equation}\]</span></p>
</div>
<div id="tabla-de-anova" class="section level3" number="7.1.4">
<h3><span class="header-section-number">7.1.4</span> Tabla de ANOVA</h3>
<p>Cuando se realzia un ANOVA, es una práctica muy común realizar una <strong>tabla de ANOVA</strong>. En estas tablas vamos anotando los resultados de nuestras sumas de cuadrados, nuestros grados de libertad y nuestros cuadrados medios, de la siguiente manera.</p>
<table>
<caption>
<span id="tab:anovatab">Tabla 7.1: </span>Tabla de ANOVA
</caption>
<thead>
<tr>
<th style="text-align:left;">
Valores
</th>
<th style="text-align:left;">
df
</th>
<th style="text-align:left;">
SS
</th>
<th style="text-align:left;">
MS
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Entre los grupos (Tratamientos)
</td>
<td style="text-align:left;">
<span class="math inline">\(k - 1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\sum_{i = 1}^{k}n_{i}(\overline{x}_{i} - \overline{x})^2\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{SS(entre)}{df(entre)}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Dentro de los grupos (Residuales)
</td>
<td style="text-align:left;">
<span class="math inline">\(n - k\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\sum_{i = 1}^{k}\sum_{j = 1}^{n_i}(x_{ij} - \overline{x}_{i})^2\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{SS(dentro)}{df(dentro)}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Total
</td>
<td style="text-align:left;">
<span class="math inline">\(n - 1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\sum_{i = 1}^{k}\sum_{j = 1}^{n_i}(x_{ij}-\overline{x})^2\)</span>
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>
<p>Una tabla de ANOVA nos ayuda a organizar los datos y los valores de nuestro conjunto de datos. En la tabla <a href="modelado-de-relaciones.html#tab:anovatab">7.1</a> podemos ver las fórmulas que necesitamos utilizar para obtener los valores correspondientes. Por ejemplo, para obtener los grados de libertad entre tratamientos,<span class="math inline">\(df(entre)\)</span>, utilizaría la fórmula <span class="math inline">\(k - 1\)</span> y así sucesivamente. La suma de cuadrados y los cuadrados medios entre grupos son los que corresponden a los tratamientos y los que se dan dentro de los grupos son típicamente conocidos como <strong>residuales.</strong></p>
</div>
<div id="modelo-del-anova" class="section level3" number="7.1.5">
<h3><span class="header-section-number">7.1.5</span> Modelo del ANOVA</h3>
<p>Pensamos acerca de <span class="math inline">\(x_{ij}\)</span> como una observación aleatoria del grupo <span class="math inline">\(i\)</span>, donde la media poblacional del grupo <span class="math inline">\(i\)</span> es <span class="math inline">\(\mu_i\)</span>. Utilizamos el ANOVA para investigar la hipótesis nula, <span class="math inline">\(H_0: \mu_1 = \mu_2 = \cdots = \mu_i\)</span>. El siguiente modelo describe al ANOVA:</p>
<p><span class="math display" id="eq:anovamodel">\[\begin{equation}
x_{ij} = \mu + \tau_i + \epsilon_{ij}
\tag{7.15}
\end{equation}\]</span></p>
<p>En este modelo, <span class="math inline">\(\mu\)</span> representa la gran media poblacional, es decir la media de todos los grupos combinados. Si la <span class="math inline">\(H_0\)</span> entonces <span class="math inline">\(\mu\)</span> es la media en común para todos los grupos. Si es falsa, entonces al menos una de las <span class="math inline">\(\mu_i\)</span> difiere de la gran media pbolacional <span class="math inline">\(\mu\)</span>. El término <span class="math inline">\(\tau_i\)</span> (tau) representa el efecto que tiene el grupo <span class="math inline">\(i\)</span>, es decir, la diferencia entre la media poblacional para el grupo <span class="math inline">\(i\)</span>, <span class="math inline">\(\mu_i\)</span> y la gran media poblacional, <span class="math inline">\(\mu\)</span>. Por ende:</p>
<p><span class="math display" id="eq:anovatau">\[\begin{equation}
\tau_i = \mu_i - \mu
\tag{7.16}
\end{equation}\]</span></p>
<p>Esto es equivalente a decir que <span class="math inline">\(H_0: \tau_1 = \tau_2 = \cdots = \tau_n = 0\)</span>. Si la <span class="math inline">\(H_0\)</span> es falsa, entonces al menos alguno de los grupos o tratamientos difiere de los demás. Si <span class="math inline">\(\tau_i\)</span> es positivo, entonces, las observaciones del grupo <span class="math inline">\(i\)</span> tienden a ser mayores que el promedio, en cambio, si es negativo, las observaciones tienden a ser menores que el promedio.</p>
<p>El término <span class="math inline">\(\epsilon_{ij}\)</span> (epsilon) representa el error aleatorio asociado con la observación <span class="math inline">\(j\)</span> en el grupo <span class="math inline">\(i\)</span>. Por lo que nuestro modelo puede ser intepretado como:</p>
<p><span class="math display" id="eq:anovamodel2">\[\begin{equation}
observación = gran \space media + effecto \space de \space grupo + error \space aleatorio
\tag{7.17}
\end{equation}\]</span></p>
<p>Estimamos la media general, <span class="math inline">\(\mu\)</span>, con la gran media de los datos <span class="math inline">\(\overline{x}\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\hat{\mu} = \overline{x}
\end{equation}\]</span></p>
<p>De igual manera, estimamos la media poblacional del grupo <span class="math inline">\(i\)</span> con la media muestral del grupo <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\hat{\mu}_i = \overline{x}_i
\end{equation}\]</span></p>
<p>Entonces, efecto de grupo es:</p>
<p><span class="math display">\[\begin{equation}
\hat{\tau}_i = \overline{x}_i - \overline{x}
\end{equation}\]</span></p>
<p>Finalmente, para el error aleatorio de la observación <span class="math inline">\(j\)</span> en el grupo <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\hat{\epsilon}_{ij} = x_{ij} - \overline{x}_i
\end{equation}\]</span></p>
<p>Poniendo todos estos valores juntos obtenemos:</p>
<p><span class="math display">\[\begin{equation}
x_{ij} = \overline{x} + (\overline{x}_i - \overline{x}) + (x_{ij} + \overline{x}_i) = \hat{\mu} + \hat{\tau_i} + \hat{\epsilon}_{ij}
\end{equation}\]</span></p>
<p>En algunos libros e incluso algunos software, se utiliza la terminología <span class="math inline">\(SS(error)\)</span> en lugar de <span class="math inline">\(SS(dentro)\)</span> ya que este componente, <span class="math inline">\(x_{ij} - \overline{x}_i\)</span>, es la parte del error aleatorio en el modelo del ANOVA. También se le conoce como residuales y de está manera la encontramos en <code>R</code>.</p>
<p>Cuando hacemos un análisis de varianza, ANOVA, comparamos el tamaño del efecto de grupo de la muestra, <span class="math inline">\(\hat{\tau}_i\)</span>, al tamaño del error aleatorio de los datos, <span class="math inline">\(\hat{\epsilon}_{ij}\)</span>.</p>
<p>Esto se puede observar en las fórmulas para <span class="math inline">\(SS(entre)\)</span> y <span class="math inline">\(SS(dentro)\)</span>.</p>
<p><span class="math display">\[\begin{equation}
SS(entre) = \sum_{i=1}^k n_i \hat{\tau}_i^2
\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}
SS(dentro) = \sum_{i=1}^k \sum_{j=1}^{n_i} \hat{\epsilon}_{ij}^2
\end{equation}\]</span></p>
</div>
<div id="distribución-de-f" class="section level3" number="7.1.6">
<h3><span class="header-section-number">7.1.6</span> Distribución de <span class="math inline">\(F\)</span></h3>
<p>Consideremos la hipótesis nula <span class="math inline">\(H_0: \mu_1 = \mu_2 = \cdots = \mu_i\)</span> y una hipótesis alternativa no direccional, <span class="math inline">\(H_A: Al \space menos \space una \space \mu_i \space no \space es \space igual\)</span>. El rechazo de la <span class="math inline">\(H_0\)</span> no nos dice cuál grupo es el que es diferente.</p>
<p>La <strong>distribución de <span class="math inline">\(F\)</span></strong> fue nombrada así en honor del estadista y genetista R.A. Fisher y es utilizada en muchísimos análisis estadísticos. Su forma depende de dos parámetros: el <strong>numerador de los grados de libertad</strong> (<span class="math inline">\(df(entre)\)</span>) y el <strong>denominador de los grados de libertad</strong> (<span class="math inline">\(df(dentro)\)</span>). La siguiente figura muestra una distribución de <span class="math inline">\(F\)</span> con <span class="math inline">\(df(entre) = 4\)</span> y <span class="math inline">\(df(dentro) = 20\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-2"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-2-1.png" alt="Distribución de $F$ con $df(entre) = 4$ y $df(dentro) = 20$." width="672" />
<p class="caption">
Figura 7.1: Distribución de <span class="math inline">\(F\)</span> con <span class="math inline">\(df(entre) = 4\)</span> y <span class="math inline">\(df(dentro) = 20\)</span>.
</p>
</div>
<p>Como con el resto de distribuciones, tenemos una serie de comandos en <code>R</code> para trabajar con la distribución de <span class="math inline">\(F\)</span>.</p>
<p>-<code>df()</code> nos da un valor de densidad en determinado punto de la distribución de <span class="math inline">\(F\)</span>.</p>
<p>-<code>pf()</code> nos da un valor de densidad acumulado hasta cierto punto en la distribución de <span class="math inline">\(F\)</span> (área debajo de la curva).</p>
<p>-<code>qf()</code> toma el valor de densidad que le ponemos como primer argumento y nos da como regreso un número cuya densidad acumulada empate con el valor de densidad ingresado.</p>
<p>-<code>rf()</code> genera cierta cantidad de número aleatorios de acuerdo al valor de densidad.</p>
<p>Para encontrar los valores críticos de nuestra distribución de <span class="math inline">\(F\)</span> simplemente utilizamos la función <code>qf()</code>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="modelado-de-relaciones.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.05</span>, <span class="at">df1 =</span> <span class="dv">4</span>, <span class="at">df =</span> <span class="dv">20</span>, <span class="at">lower.tail =</span> F)</span></code></pre></div>
<pre><code>## [1] 2.866081</code></pre>
<p>Y listo, nuestro valor crítico de <span class="math inline">\(F\)</span> para un <span class="math inline">\(F(4, 20)_{0.05}\)</span> es 2.87. Estos comandos se utilizan como el resto que hemos visto con las demás distribuciones.</p>
</div>
<div id="prueba-de-f" class="section level3" number="7.1.7">
<h3><span class="header-section-number">7.1.7</span> Prueba de <span class="math inline">\(F\)</span></h3>
<p>Para obtener nuestro <strong>estadístico de <span class="math inline">\(F\)</span></strong> utilizamos la siguiente fómrula:</p>
<p><span class="math display" id="eq:fratio">\[\begin{equation}
F_s = \frac{MS(entre)}{MS(dentro)}
\tag{7.18}
\end{equation}\]</span></p>
<p>Esta claro que el valor de nuestra <span class="math inline">\(F_s\)</span> será mayor si las discrepancias entre las medias de los grupos (<span class="math inline">\(\overline{X}_i\)</span>) son grandes en relación a variabiliadad dentro de los grupos. Valores grandes de <span class="math inline">\(F_s\)</span> tienden a proveer evidencia en contra de la <span class="math inline">\(H_0\)</span>.</p>
<p>Veamos todo lo que hemos visto con un ejemplo.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Se realizó un experimento sobre la alimentación de corderos con tres dietas distintas. Las ganancias de peso se muestran en la tabla @tab:ex1.</p>
</blockquote>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="modelado-de-relaciones.html#cb3-1" aria-hidden="true" tabindex="-1"></a>Dieta1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">16</span>, <span class="dv">9</span>, <span class="cn">NA</span>, <span class="cn">NA</span>)</span>
<span id="cb3-2"><a href="modelado-de-relaciones.html#cb3-2" aria-hidden="true" tabindex="-1"></a>Dieta2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">16</span>, <span class="dv">21</span>, <span class="dv">11</span>, <span class="dv">18</span>)</span>
<span id="cb3-3"><a href="modelado-de-relaciones.html#cb3-3" aria-hidden="true" tabindex="-1"></a>Dieta3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">10</span>, <span class="dv">17</span>, <span class="dv">6</span>, <span class="cn">NA</span>)</span>
<span id="cb3-4"><a href="modelado-de-relaciones.html#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="modelado-de-relaciones.html#cb3-5" aria-hidden="true" tabindex="-1"></a>Corderos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Dieta1, Dieta2, Dieta3)</span>
<span id="cb3-6"><a href="modelado-de-relaciones.html#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">knitr.kable.NA =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb3-7"><a href="modelado-de-relaciones.html#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="modelado-de-relaciones.html#cb3-8" aria-hidden="true" tabindex="-1"></a>Corderos <span class="sc">%&gt;%</span> </span>
<span id="cb3-9"><a href="modelado-de-relaciones.html#cb3-9" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="st">&quot;html&quot;</span>, <span class="at">align =</span> <span class="fu">c</span>(<span class="st">&quot;c&quot;</span>, <span class="st">&quot;c&quot;</span>), <span class="at">caption =</span> <span class="st">&quot;Ganancia de peso (lb) de los corderos&quot;</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;Dieta 1&quot;</span>, <span class="st">&quot;Dieta 2&quot;</span>, <span class="st">&quot;Dieta 3&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="modelado-de-relaciones.html#cb3-10" aria-hidden="true" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_classic</span>(<span class="at">lightable_options =</span> <span class="st">&quot;striped&quot;</span>, <span class="at">full_width =</span> F) <span class="sc">%&gt;%</span> </span>
<span id="cb3-11"><a href="modelado-de-relaciones.html#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">width_min =</span> <span class="st">&quot;4cm&quot;</span>)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-4">Tabla 7.2: </span>Ganancia de peso (lb) de los corderos
</caption>
<thead>
<tr>
<th style="text-align:center;">
Dieta 1
</th>
<th style="text-align:center;">
Dieta 2
</th>
<th style="text-align:center;">
Dieta 3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 4cm; ">
8
</td>
<td style="text-align:center;min-width: 4cm; ">
9
</td>
<td style="text-align:center;min-width: 4cm; ">
15
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
16
</td>
<td style="text-align:center;min-width: 4cm; ">
16
</td>
<td style="text-align:center;min-width: 4cm; ">
10
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
9
</td>
<td style="text-align:center;min-width: 4cm; ">
21
</td>
<td style="text-align:center;min-width: 4cm; ">
17
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
</td>
<td style="text-align:center;min-width: 4cm; ">
11
</td>
<td style="text-align:center;min-width: 4cm; ">
6
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 4cm; ">
</td>
<td style="text-align:center;min-width: 4cm; ">
18
</td>
<td style="text-align:center;min-width: 4cm; ">
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="modelado-de-relaciones.html#cb4-1" aria-hidden="true" tabindex="-1"></a>Corderos <span class="ot">&lt;-</span> <span class="fu">gather</span>(Corderos, Dieta1, Dieta2, Dieta3) <span class="sc">%&gt;%</span> na.omit</span></code></pre></div>
<p>En lugar de realizar todo el proceso manual (el cuál puede tomar cierto tiempo) vamos a utilizar la función <code>aov()</code> para analizar estos datos y ver si realmente existe alguna diferencia entre los datos. Para esto necesitamos generar nuestra variable con nuestros datos.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="modelado-de-relaciones.html#cb5-1" aria-hidden="true" tabindex="-1"></a>Tratamiento <span class="ot">&lt;-</span> <span class="fu">c</span>((<span class="fu">rep</span>(<span class="st">&quot;Dieta 1&quot;</span>, <span class="dv">3</span>)), <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Dieta 2&quot;</span>, <span class="dv">5</span>)), <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Dieta 3&quot;</span>, <span class="dv">4</span>)))</span>
<span id="cb5-2"><a href="modelado-de-relaciones.html#cb5-2" aria-hidden="true" tabindex="-1"></a>Peso <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">16</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">16</span>, <span class="dv">21</span>, <span class="dv">11</span>, <span class="dv">18</span>, <span class="dv">15</span>, <span class="dv">10</span>, <span class="dv">17</span>, <span class="dv">6</span>)</span>
<span id="cb5-3"><a href="modelado-de-relaciones.html#cb5-3" aria-hidden="true" tabindex="-1"></a>Corderos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Tratamiento, Peso)</span>
<span id="cb5-4"><a href="modelado-de-relaciones.html#cb5-4" aria-hidden="true" tabindex="-1"></a>Corderos</span></code></pre></div>
<pre><code>##    Tratamiento Peso
## 1      Dieta 1    8
## 2      Dieta 1   16
## 3      Dieta 1    9
## 4      Dieta 2    9
## 5      Dieta 2   16
## 6      Dieta 2   21
## 7      Dieta 2   11
## 8      Dieta 2   18
## 9      Dieta 3   15
## 10     Dieta 3   10
## 11     Dieta 3   17
## 12     Dieta 3    6</code></pre>
<p>Ahora que tenemos nuestra variable simplente ingresamos el siguiente comando.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="modelado-de-relaciones.html#cb7-1" aria-hidden="true" tabindex="-1"></a>ANOVA <span class="ot">&lt;-</span> <span class="fu">aov</span>(Peso <span class="sc">~</span> Tratamiento, Corderos)</span></code></pre></div>
<p>Si queremos observar nuestros valores-<em>p</em> calculados, y ver si existen diferencias significativas, tenemos que guardar el análisis en una variable, en este caso yo la nombre <em>ANOVA</em>. Posteriormente utilizamos la función <code>summary()</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="modelado-de-relaciones.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ANOVA)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Tratamiento  2     36   18.00   0.771  0.491
## Residuals    9    210   23.33</code></pre>
<p>Donde obtenemos una tabla de ANOVA con nuestros valores F esperados y F estimados. El apartado Pr(&gt;F) es nuestro valor-<em>p</em>. Si quisiéramos guardar nuestra tabla de ANOVA para algún reporte, podemos hacerlo a través de la librería <code>broom</code>.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="modelado-de-relaciones.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb10-2"><a href="modelado-de-relaciones.html#cb10-2" aria-hidden="true" tabindex="-1"></a>ANOVA.tabla <span class="ot">&lt;-</span> <span class="fu">tidy</span>(ANOVA)</span></code></pre></div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="modelado-de-relaciones.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">knitr.kable.NA =</span> <span class="st">&#39;&#39;</span>)</span>
<span id="cb11-2"><a href="modelado-de-relaciones.html#cb11-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ANOVA.tabla, <span class="st">&quot;html&quot;</span>, <span class="at">align =</span> <span class="fu">c</span>(<span class="st">&quot;c&quot;</span>, <span class="st">&quot;c&quot;</span>), <span class="at">caption =</span> <span class="st">&quot;Ganancia de peso (lb) de los corderos&quot;</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;Término&quot;</span>, <span class="st">&quot;df&quot;</span>, <span class="st">&quot;SS&quot;</span>, <span class="st">&quot;MS&quot;</span>, <span class="st">&quot;Estadístico de F&quot;</span>, <span class="st">&quot;Valor p&quot;</span>)) <span class="sc">%&gt;%</span> kableExtra<span class="sc">::</span><span class="fu">kable_classic</span>(<span class="at">lightable_options =</span> <span class="st">&quot;striped&quot;</span>, <span class="at">full_width =</span> F) <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="modelado-de-relaciones.html#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">width_min =</span> <span class="st">&quot;2cm&quot;</span>)</span></code></pre></div>
<table class=" lightable-classic lightable-striped" style="font-family: &quot;Arial Narrow&quot;, &quot;Source Sans Pro&quot;, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-9">Tabla 7.3: </span>Ganancia de peso (lb) de los corderos
</caption>
<thead>
<tr>
<th style="text-align:center;">
Término
</th>
<th style="text-align:center;">
df
</th>
<th style="text-align:center;">
SS
</th>
<th style="text-align:center;">
MS
</th>
<th style="text-align:center;">
Estadístico de F
</th>
<th style="text-align:center;">
Valor p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;min-width: 2cm; ">
Tratamiento
</td>
<td style="text-align:center;min-width: 2cm; ">
2
</td>
<td style="text-align:center;min-width: 2cm; ">
36
</td>
<td style="text-align:center;min-width: 2cm; ">
18.00000
</td>
<td style="text-align:center;min-width: 2cm; ">
0.7714286
</td>
<td style="text-align:center;min-width: 2cm; ">
0.490658
</td>
</tr>
<tr>
<td style="text-align:center;min-width: 2cm; ">
Residuals
</td>
<td style="text-align:center;min-width: 2cm; ">
9
</td>
<td style="text-align:center;min-width: 2cm; ">
210
</td>
<td style="text-align:center;min-width: 2cm; ">
23.33333
</td>
<td style="text-align:center;min-width: 2cm; ">
</td>
<td style="text-align:center;min-width: 2cm; ">
</td>
</tr>
</tbody>
</table>
<p>Por lo tanto nuestro estadístico <span class="math inline">\(F\)</span> calculado nos da un valor de 0.77, el área correspondiente a esta densidad valor <span class="math inline">\(F\)</span> es 0.4907, por lo que nuestro valor-<em>p</em> &gt; 0.05 y aceptamos la <span class="math inline">\(H_0\)</span>.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inferencia-de-datos-categóricos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
