<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lección 3 Probabilidad | Curso de R básico</title>
  <meta name="description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Lección 3 Probabilidad | Curso de R básico" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lección 3 Probabilidad | Curso de R básico" />
  
  <meta name="twitter:description" content="Curso de R cubriendo los aspectos básicos para el análisis de datos biológicos." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="estadística-descriptiva.html"/>
<link rel="next" href="estadística-inferencial.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Curso de R básico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Requisitos</a>
<ul>
<li><a href="index.html#descarga-de-r-y-rstudio">Descarga de <code>R</code> y RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introducción-a-r.html"><a href="introducción-a-r.html"><i class="fa fa-check"></i><b>1</b> Introducción a R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introducción-a-r.html"><a href="introducción-a-r.html#interfaz"><i class="fa fa-check"></i><b>1.1</b> Interfaz</a></li>
<li class="chapter" data-level="1.2" data-path="introducción-a-r.html"><a href="introducción-a-r.html#creando-nuestro-primer-proyecto"><i class="fa fa-check"></i><b>1.2</b> Creando nuestro primer proyecto</a></li>
<li class="chapter" data-level="1.3" data-path="introducción-a-r.html"><a href="introducción-a-r.html#objetos-y-variables"><i class="fa fa-check"></i><b>1.3</b> Objetos y variables</a></li>
<li class="chapter" data-level="1.4" data-path="introducción-a-r.html"><a href="introducción-a-r.html#instalar-paquetes"><i class="fa fa-check"></i><b>1.4</b> Instalar paquetes</a></li>
<li class="chapter" data-level="1.5" data-path="introducción-a-r.html"><a href="introducción-a-r.html#importar-datos-a-r"><i class="fa fa-check"></i><b>1.5</b> Importar datos a R</a></li>
<li class="chapter" data-level="1.6" data-path="introducción-a-r.html"><a href="introducción-a-r.html#comentarios"><i class="fa fa-check"></i><b>1.6</b> Comentarios</a></li>
<li class="chapter" data-level="1.7" data-path="introducción-a-r.html"><a href="introducción-a-r.html#exportar-datos"><i class="fa fa-check"></i><b>1.7</b> Exportar datos</a></li>
<li class="chapter" data-level="1.8" data-path="introducción-a-r.html"><a href="introducción-a-r.html#pedir-ayuda"><i class="fa fa-check"></i><b>1.8</b> Pedir ayuda</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html"><i class="fa fa-check"></i><b>2</b> Estadística descriptiva</a>
<ul>
<li class="chapter" data-level="2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#datos"><i class="fa fa-check"></i><b>2.1</b> Datos y estudios</a></li>
<li class="chapter" data-level="2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-tendencia-central"><i class="fa fa-check"></i><b>2.2</b> Medidas de tendencia central</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#media"><i class="fa fa-check"></i><b>2.2.1</b> Media</a></li>
<li class="chapter" data-level="2.2.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#mediana"><i class="fa fa-check"></i><b>2.2.2</b> Mediana</a></li>
<li class="chapter" data-level="2.2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#moda"><i class="fa fa-check"></i><b>2.2.3</b> Moda</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-dispersión"><i class="fa fa-check"></i><b>2.3</b> Medidas de dispersión</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#rango"><i class="fa fa-check"></i><b>2.3.1</b> Rango</a></li>
<li class="chapter" data-level="2.3.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#desviación-estándar"><i class="fa fa-check"></i><b>2.3.2</b> Desviación estándar</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#medidas-de-posición-relativa"><i class="fa fa-check"></i><b>2.4</b> Medidas de posición relativa</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#valores-z"><i class="fa fa-check"></i><b>2.4.1</b> Valores <span class="math inline">\(Z\)</span></a></li>
<li class="chapter" data-level="2.4.2" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-absoluta"><i class="fa fa-check"></i><b>2.4.2</b> Frecuencia absoluta</a></li>
<li class="chapter" data-level="2.4.3" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#frecuencia-relativa"><i class="fa fa-check"></i><b>2.4.3</b> Frecuencia relativa</a></li>
<li class="chapter" data-level="2.4.4" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#cuartiles"><i class="fa fa-check"></i><b>2.4.4</b> Cuartiles</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="estadística-descriptiva.html"><a href="estadística-descriptiva.html#el-uso-de-la-librería-dplyr"><i class="fa fa-check"></i><b>2.5</b> El uso de la librería <code>dplyr</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="probabilidad.html"><a href="probabilidad.html"><i class="fa fa-check"></i><b>3</b> Probabilidad</a>
<ul>
<li class="chapter" data-level="3.1" data-path="probabilidad.html"><a href="probabilidad.html#probabilidad-frecuentista"><i class="fa fa-check"></i><b>3.1</b> Probabilidad frecuentista</a></li>
<li class="chapter" data-level="3.2" data-path="probabilidad.html"><a href="probabilidad.html#reglas-de-probabilidad"><i class="fa fa-check"></i><b>3.2</b> Reglas de probabilidad</a></li>
<li class="chapter" data-level="3.3" data-path="probabilidad.html"><a href="probabilidad.html#curvas-de-densidad"><i class="fa fa-check"></i><b>3.3</b> Curvas de densidad</a></li>
<li class="chapter" data-level="3.4" data-path="probabilidad.html"><a href="probabilidad.html#distribución-binomial"><i class="fa fa-check"></i><b>3.4</b> Distribución binomial</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="probabilidad.html"><a href="probabilidad.html#media-y-desviación-estándar-de-la-distribución-binomial"><i class="fa fa-check"></i><b>3.4.1</b> Media y desviación estándar de la distribución binomial</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="probabilidad.html"><a href="probabilidad.html#distribución-de-poisson"><i class="fa fa-check"></i><b>3.5</b> Distribución de Poisson</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="probabilidad.html"><a href="probabilidad.html#media-y-desviación-estándar-de-la-distribución-de-poisson"><i class="fa fa-check"></i><b>3.5.1</b> Media y desviación estándar de la distribución de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="probabilidad.html"><a href="probabilidad.html#distribución-normal"><i class="fa fa-check"></i><b>3.6</b> Distribución normal</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="probabilidad.html"><a href="probabilidad.html#pruebas-de-normalidad"><i class="fa fa-check"></i><b>3.6.1</b> Pruebas de normalidad</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="probabilidad.html"><a href="probabilidad.html#distribución-muestral"><i class="fa fa-check"></i><b>3.7</b> Distribución muestral</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="probabilidad.html"><a href="probabilidad.html#poblaciones-muestras-y-distribuciones-muestrales"><i class="fa fa-check"></i><b>3.7.1</b> Poblaciones, muestras y distribuciones muestrales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html"><i class="fa fa-check"></i><b>4</b> Estadística inferencial</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#error-estándar-de-la-media"><i class="fa fa-check"></i><b>4.1</b> Error estándar de la media</a></li>
<li class="chapter" data-level="4.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>4.2</b> Intervalo de confianza para <span class="math inline">\(\mu\)</span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#distribución-t-de-student"><i class="fa fa-check"></i><b>4.2.1</b> Distribución <span class="math inline">\(t\)</span> de Student</a></li>
<li class="chapter" data-level="4.2.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#construcción-de-un-intervalo-de-confianza-para-mu"><i class="fa fa-check"></i><b>4.2.2</b> Construcción de un intervalo de confianza para <span class="math inline">\(\mu\)</span></a></li>
<li class="chapter" data-level="4.2.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalos-de-confianza-unilaterales"><i class="fa fa-check"></i><b>4.2.3</b> Intervalos de confianza unilaterales</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-de-dos-medias"><i class="fa fa-check"></i><b>4.3</b> Comparación de dos medias</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#intervalo-de-confianza-para-mu_1---mu_2"><i class="fa fa-check"></i><b>4.3.1</b> Intervalo de confianza para <span class="math inline">\(\mu_1 - \mu_2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#pruebas-de-hipótesis"><i class="fa fa-check"></i><b>4.4</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#t-test"><i class="fa fa-check"></i><b>4.4.1</b> <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="4.4.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#t-test-de-una-cola"><i class="fa fa-check"></i><b>4.4.2</b> <span class="math inline">\(t\)</span> test de una cola</a></li>
<li class="chapter" data-level="4.4.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#tamaño-de-efecto"><i class="fa fa-check"></i><b>4.4.3</b> Tamaño de efecto</a></li>
<li class="chapter" data-level="4.4.4" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-wilcoxon-mann-whitney"><i class="fa fa-check"></i><b>4.4.4</b> Prueba de Wilcoxon-Mann-Whitney</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#comparación-de-muestras-pareadas"><i class="fa fa-check"></i><b>4.5</b> Comparación de muestras pareadas</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-t-pareada"><i class="fa fa-check"></i><b>4.5.1</b> Prueba de <span class="math inline">\(t\)</span> pareada</a></li>
<li class="chapter" data-level="4.5.2" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-signos"><i class="fa fa-check"></i><b>4.5.2</b> Prueba de signos</a></li>
<li class="chapter" data-level="4.5.3" data-path="estadística-inferencial.html"><a href="estadística-inferencial.html#prueba-de-rangos-con-signos-de-wilcoxon"><i class="fa fa-check"></i><b>4.5.3</b> Prueba de rangos con signos de Wilcoxon</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html"><i class="fa fa-check"></i><b>5</b> Inferencia de datos categóricos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#distribuciones-de-una-muestra"><i class="fa fa-check"></i><b>5.1</b> Distribuciones de una muestra</a></li>
<li class="chapter" data-level="5.2" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-de-chi-cuadrada"><i class="fa fa-check"></i><b>5.2</b> Prueba de Chi-cuadrada</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#hipótesis-compuestas-y-direccionales"><i class="fa fa-check"></i><b>5.2.1</b> Hipótesis compuestas y direccionales</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-de-chi-cuadrada-para-tablas-de-contingencia"><i class="fa fa-check"></i><b>5.3</b> Prueba de Chi-cuadrada para tablas de contingencia</a></li>
<li class="chapter" data-level="5.4" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#interpretación-de-las-tablas-de-contingencia"><i class="fa fa-check"></i><b>5.4</b> Interpretación de las tablas de contingencia</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#cuestiones-acerca-de-las-columnas-y-filas"><i class="fa fa-check"></i><b>5.4.1</b> Cuestiones acerca de las columnas y filas</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#prueba-exacta-de-fisher"><i class="fa fa-check"></i><b>5.5</b> Prueba exacta de Fisher</a></li>
<li class="chapter" data-level="5.6" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#tablas-de-contingencia-r-times-k"><i class="fa fa-check"></i><b>5.6</b> Tablas de contingencia <span class="math inline">\(r \times k\)</span></a></li>
<li class="chapter" data-level="5.7" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#intervalos-de-confianza-para-la-diferencia-entre-probabilidades"><i class="fa fa-check"></i><b>5.7</b> Intervalos de confianza para la diferencia entre probabilidades</a></li>
<li class="chapter" data-level="5.8" data-path="inferencia-de-datos-categóricos.html"><a href="inferencia-de-datos-categóricos.html#datos-pareados-en-tablas-2x2"><i class="fa fa-check"></i><b>5.8</b> Datos pareados en tablas 2x2</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html"><i class="fa fa-check"></i><b>6</b> Modelado de relaciones</a>
<ul>
<li class="chapter" data-level="6.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#análisis-de-varianza-anova"><i class="fa fa-check"></i><b>6.1</b> Análisis de Varianza (ANOVA)</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#variación-dentro-de-los-grupos"><i class="fa fa-check"></i><b>6.1.1</b> Variación dentro de los grupos</a></li>
<li class="chapter" data-level="6.1.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#variación-entre-los-grupos"><i class="fa fa-check"></i><b>6.1.2</b> Variación entre los grupos</a></li>
<li class="chapter" data-level="6.1.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#una-relación-importante-en-el-anova"><i class="fa fa-check"></i><b>6.1.3</b> Una relación importante en el ANOVA</a></li>
<li class="chapter" data-level="6.1.4" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#tabla-de-anova"><i class="fa fa-check"></i><b>6.1.4</b> Tabla de ANOVA</a></li>
<li class="chapter" data-level="6.1.5" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#modelo-del-anova"><i class="fa fa-check"></i><b>6.1.5</b> Modelo del ANOVA</a></li>
<li class="chapter" data-level="6.1.6" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#distribución-de-f"><i class="fa fa-check"></i><b>6.1.6</b> Distribución de <span class="math inline">\(F\)</span></a></li>
<li class="chapter" data-level="6.1.7" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#prueba-de-f"><i class="fa fa-check"></i><b>6.1.7</b> Prueba de <span class="math inline">\(F\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diseño-por-bloques-aleatorizados"><i class="fa fa-check"></i><b>6.2</b> Diseño por bloques aleatorizados</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#creando-los-bloques"><i class="fa fa-check"></i><b>6.2.1</b> Creando los bloques</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#anova-de-dos-vías"><i class="fa fa-check"></i><b>6.3</b> ANOVA de dos vías</a></li>
<li class="chapter" data-level="6.4" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#combinaciones-lineales-de-las-medias"><i class="fa fa-check"></i><b>6.4</b> Combinaciones lineales de las medias</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#contrastes"><i class="fa fa-check"></i><b>6.4.1</b> Contrastes</a></li>
<li class="chapter" data-level="6.4.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>6.4.2</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="6.4.3" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#prueba-de-t"><i class="fa fa-check"></i><b>6.4.3</b> Prueba de <span class="math inline">\(t\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#pruebas-post-hoc"><i class="fa fa-check"></i><b>6.5</b> Pruebas post hoc</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diferencia-menos-significativa-de-fisher-lsd"><i class="fa fa-check"></i><b>6.5.1</b> Diferencia menos significativa de Fisher (LSD)</a></li>
<li class="chapter" data-level="6.5.2" data-path="modelado-de-relaciones.html"><a href="modelado-de-relaciones.html#diferencia-significativa-honesta-de-tukey-hsd"><i class="fa fa-check"></i><b>6.5.2</b> Diferencia significativa honesta de Tukey (HSD)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html"><i class="fa fa-check"></i><b>7</b> Correlación y regresión lineal</a>
<ul>
<li class="chapter" data-level="7.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-coeficiente-de-correlación-r"><i class="fa fa-check"></i><b>7.1</b> El coeficiente de correlación <span class="math inline">\(r\)</span></a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#midiendo-la-fuerza-de-la-asociación"><i class="fa fa-check"></i><b>7.1.1</b> Midiendo la fuerza de la asociación</a></li>
<li class="chapter" data-level="7.1.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#inferencia-acerca-de-la-correlación"><i class="fa fa-check"></i><b>7.1.2</b> Inferencia acerca de la correlación</a></li>
<li class="chapter" data-level="7.1.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalo-de-confianza-para-rho"><i class="fa fa-check"></i><b>7.1.3</b> Intervalo de confianza para <span class="math inline">\(\rho\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#regresión-lineal"><i class="fa fa-check"></i><b>7.2</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#la-línea-sd"><i class="fa fa-check"></i><b>7.2.1</b> La línea SD</a></li>
<li class="chapter" data-level="7.2.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#ecuación-de-la-regresión-lineal"><i class="fa fa-check"></i><b>7.2.2</b> Ecuación de la regresión lineal</a></li>
<li class="chapter" data-level="7.2.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#gráfica-de-promedios"><i class="fa fa-check"></i><b>7.2.3</b> Gráfica de promedios</a></li>
<li class="chapter" data-level="7.2.4" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#la-suma-de-cuadrados-de-los-residuales"><i class="fa fa-check"></i><b>7.2.4</b> La suma de cuadrados de los residuales</a></li>
<li class="chapter" data-level="7.2.5" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#desviación-estándar-de-los-residuales"><i class="fa fa-check"></i><b>7.2.5</b> Desviación estándar de los residuales</a></li>
<li class="chapter" data-level="7.2.6" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-coeficiente-de-determinación"><i class="fa fa-check"></i><b>7.2.6</b> El coeficiente de determinación</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-model-lineal"><i class="fa fa-check"></i><b>7.3</b> El model lineal</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#estmiaciones-del-modelo-lineal"><i class="fa fa-check"></i><b>7.3.1</b> Estmiaciones del modelo lineal</a></li>
<li class="chapter" data-level="7.3.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#interpolación-en-el-modelo-lineal"><i class="fa fa-check"></i><b>7.3.2</b> Interpolación en el modelo lineal</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#inferencia-estadística-respecto-de-beta_1"><i class="fa fa-check"></i><b>7.4</b> Inferencia estadística respecto de <span class="math inline">\(\beta_1\)</span></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#el-error-estándar-de-b_1"><i class="fa fa-check"></i><b>7.4.1</b> El error estándar de <span class="math inline">\(b_1\)</span></a></li>
<li class="chapter" data-level="7.4.2" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalo-de-confianza-para-beta_1"><i class="fa fa-check"></i><b>7.4.2</b> Intervalo de confianza para <span class="math inline">\(\beta_1\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#prueba-de-hipótesis-para-h_0-beta_1-0"><i class="fa fa-check"></i><b>7.5</b> Prueba de hipótesis para <span class="math inline">\(H_0: \beta_1 = 0\)</span></a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#gráficos-de-residuales"><i class="fa fa-check"></i><b>7.5.1</b> Gráficos de residuales</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#intervalos-de-confianza-y-de-predicción"><i class="fa fa-check"></i><b>7.6</b> Intervalos de confianza y de predicción</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="correlación-y-regresión-lineal.html"><a href="correlación-y-regresión-lineal.html#computando-los-intervalos"><i class="fa fa-check"></i><b>7.6.1</b> Computando los intervalos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliografia.html"><a href="bibliografia.html"><i class="fa fa-check"></i>Bibliografia</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Curso de R básico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="probabilidad" class="section level1" number="3">
<h1><span class="header-section-number">Lección 3</span> Probabilidad</h1>
<p>La <strong>probabilidad</strong> es una cantidad numérica que expresa qué tan factible es que ocurra un evento. Normalmente es expresada como <span class="math inline">\(P(A)\)</span>, donde <span class="math inline">\(A\)</span> es un evento aleatorio. Siempre se encuentra entre un rango de 0 y 1, o expresado en porcentaje, entre 0% y 100%. Existen distintos acercamientos a la probabilidad como el acercamiento <strong>frecuentista</strong> o el acercamiento <strong>bayesiano.</strong></p>
<p>En este caso, aprenderemos el enfoque frecuentista como una forma de asignar una probabilidad mensurable a un evento, es decir, la ocurrencia de el evento a la larga (qué tan <em>frecuentemente</em> ocurre).</p>
<div id="probabilidad-frecuentista" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Probabilidad frecuentista</h2>
<p>En este enfoque, la probabilidad de un evento se determina a través por el número de veces que el evento <span class="math inline">\(A\)</span> ocurre en una serie de repeticiones indefinidamente largas.</p>
<p><span class="math display" id="eq:prob">\[\begin{equation}
P(A) = \frac{num_{A}}{num_{T}}
\tag{3.1}
\end{equation}\]</span></p>
<p>Donde <span class="math inline">\(num_{A}\)</span> es el número de veces que se repite el evento <span class="math inline">\(A\)</span> y <span class="math inline">\(num_{T}\)</span> es el número total de repeticiones.</p>
</div>
<div id="reglas-de-probabilidad" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Reglas de probabilidad</h2>
<p>Estas son algunas reglas que nos pueden servir para determinar la probabilidad de algunos eventos.</p>
<ol style="list-style-type: decimal">
<li><p>La probabilidad de un evento <span class="math inline">\(A\)</span> siempre se encuentra entre 0 y 1.</p></li>
<li><p>La suma de probabilidades de los eventos tiene que ser igual a 1 (en caso de que sean complementarios).</p></li>
<li><p>La probabilidad de que el evento <span class="math inline">\(A\)</span> no ocurra es <span class="math inline">\(1 - P(A)\)</span> y se denota con el símbolo <span class="math inline">\(\overline{A}_1\)</span>, indicando que es el complemento de <span class="math inline">\(A_1\)</span>. A este tipo de eventos se les conoce como <strong>eventos complementarios.</strong></p></li>
<li><p>Si dos eventos <span class="math inline">\(A_1\)</span> y <span class="math inline">\(A_2\)</span> son eventos que no ocurren en conjunto, entonces:</p></li>
</ol>
<p><span class="math display">\[
P(A_1 \cup A_2) = P(A_1) + P(A_2)
\]</span></p>
<p>Donde <span class="math inline">\(\cup\)</span> nos sirve para indicar que ocurre el evento <span class="math inline">\(A_1\)</span> o el evento <span class="math inline">\(A_2\)</span>. En cambio, <span class="math inline">\(\cap\)</span> indica que ocurre el evento <span class="math inline">\(A_1\)</span> y el evento <span class="math inline">\(A_2\)</span> al mismo tiempo.</p>
<ol start="5" style="list-style-type: decimal">
<li>Para dos eventos que ocurren en conjunto:
<span class="math display">\[
P(A_1 \cup A_2) = P(A_1) + P(A_2) - P(A_1 \cap A_2)
\]</span></li>
</ol>
<table>
<colgroup>
<col width="22%" />
<col width="18%" />
<col width="20%" />
<col width="18%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Cabello Café</th>
<th>Cabello Negro</th>
<th>Cabello Rojo</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Ojos Cafés</strong></td>
<td>400</td>
<td>300</td>
<td>20</td>
<td>720</td>
</tr>
<tr class="even">
<td><strong>Ojos Azules</strong></td>
<td>800</td>
<td>200</td>
<td>50</td>
<td>1050</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>1200</td>
<td>500</td>
<td>70</td>
<td>1770</td>
</tr>
</tbody>
</table>
<p>En este caso, la probabilidad de que alguien tenga el cabello café (CC) o rojo (CR):</p>
<p><span class="math display">\[
P(CC \cup CR) = P(CC) + P(CR) = 500/1770 + 70 / 1770
\]</span></p>
<p>La probabilidad de que alguien tenga el cabello café:</p>
<p><span class="math display">\[
P(CC) = 1200/1770
\]</span></p>
<p>La probabilidad de tener ojos azules:</p>
<p><span class="math display">\[
P(OA) = 1050/1770
\]</span></p>
<p>La probabilidad de tener cabello negro y ojos azules <span class="math inline">\(P(CN \cap OA)\)</span> pueden ocurrir en conjunto ya que hay 200 personas con ojos azules y cabello negro.
Entonces si queremos saber la probabilidad de que alguien tenga cabello negro u ojos azules:</p>
<p><span class="math display">\[
P(CN \cup OA) = P(CN) + P(OA) - P(CN \cap OA) = 500/1770 + 1050/1770 - 200/1770 = 1350/1770
\]</span></p>
<p>La fórmula de <strong>probabilidad condicional</strong> es la siguiente:</p>
<p><span class="math display">\[
P(A_1 | A_2) = \frac{P(A_1 \cap A_2)}{P(A_2)}
\]</span></p>
<ol start="6" style="list-style-type: decimal">
<li>Si dos eventos, <span class="math inline">\(A_1\)</span> y <span class="math inline">\(A_2\)</span> son <strong>independientes,</strong> entonces:</li>
</ol>
<p><span class="math display">\[
P(A_1 \cap A_2) = P(A_1) \times P(A_2)
\]</span></p>
<ol start="7" style="list-style-type: decimal">
<li>Para cualquier evento <span class="math inline">\(A_1\)</span> y <span class="math inline">\(A_2\)</span>:</li>
</ol>
<p><span class="math display">\[
P(A_1 \cap A_2) = P(A_1) \times P(A_2 | A_1)
\]</span></p>
<p>Por ejemplo, de la tabla anterior, ¿Cuál es la probabilidad de que una persona tenga cabello rojo y ojos cafés?
En este caso:</p>
<p><span class="math display">\[
P(CR \cap OC) = P(CR) \times P(OC | CR) = 70/1770 \times 20/70 = 20/1770
\]</span></p>
<ol start="8" style="list-style-type: decimal">
<li>Para dos eventos cualesquiera, <span class="math inline">\(A_1\)</span> y <span class="math inline">\(A_2\)</span>:</li>
</ol>
<p><span class="math display">\[
P(A_1) = P(A_2) \times P(A_1 | A_2) + P(\overline{A}_2) \times P(A_1 | \overline{A}_2 )
\]</span>
Donde <span class="math inline">\(\overline{A}_2\)</span> es el complemento de <span class="math inline">\(A_2\)</span>, es decir <span class="math inline">\(1 - A_2\)</span>.</p>
</div>
<div id="curvas-de-densidad" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Curvas de densidad</h2>
<p>Una <strong>distribución de probabilidad</strong> corresponde a una descripción que da la probabilidad para cada valor de una variable aleatoria. La variable aleatoria puede ser <strong>discreta</strong> o puede ser <strong>continua,</strong> tal como vimos con los tipos de datos en la sección <a href="estadística-descriptiva.html#datos">2.1</a>.</p>
<p>Un <strong>histogramas de frecuencias relativas</strong> representa las proporciones de las observaciones en cada categoría, en lugar del total de observaciones. Sin embargo, para variables continuas normalmente se utilizan clases muy estrechas para representar al histograma como una <strong>curva de densidad.</strong> La coordenada <span class="math inline">\(y\)</span> de una curva de densidad representa la escala de densidad y a menudo las frecuencias relativas se representan como áreas debajo de la curva.</p>
<p>Algunos de los requisitos de una distribución de probabilidad son:</p>
<ul>
<li><p>Que exista una variable aleatoria numérica <span class="math inline">\(x\)</span> y que sus valores estén asociados a una probabilidad.</p></li>
<li><p>Que <span class="math inline">\(\sum P(x) = 1\)</span>, donde <span class="math inline">\(x\)</span> asume todos los los valores posibles. El área total bajo la curva de densidad debe ser igual a 1.</p></li>
<li><p>Que la probabilidad de ver a <span class="math inline">\(x_i\)</span> se encuentre entre 0 y 1. Es decir, <span class="math inline">\(0 \le P(x_i) \le 1\)</span>.</p></li>
</ul>
<p>Algunos ejemplos de distribuciones de probabilidad para variables discretas son: <strong>distribución binomial</strong> y <strong>distribución de Poisson.</strong> En el caso de variables continuas encontramos: <strong>distribución normal,</strong> <strong>distribución <span class="math inline">\(t\)</span> de Student,</strong> <strong>distribución de F,</strong> <strong>distribución de Chi,</strong> etc.</p>
<p>En la figura <a href="probabilidad.html#fig:histden">3.1</a> podemos ver un histograma de frecuencias relativas junto a una curva de densidad.</p>
<div class="figure" style="text-align: center"><span id="fig:histden"></span>
<img src="Curso_R_basico_files/figure-html/histden-1.png" alt="Curva de densidad junto con un histograma de frecuencias relativas." width="672" />
<p class="caption">
Figura 3.1: Curva de densidad junto con un histograma de frecuencias relativas.
</p>
</div>
<p>La probabilidad para una variable continua equivale al área debajo de la curva de densidad entre dos puntos. Si quisiéramos saber el valor de un punto exacto, obtendríamos de manera un tanto paradójica 0, ya que lo que equivale a la probabilidad es el área bajo la curva.</p>
<p>Algunos de los parámetros de una distribución de probabilidad son:</p>
<ul>
<li><p><strong>Media:</strong> <span class="math inline">\(\mu\)</span></p></li>
<li><p><strong>Varianza:</strong> <span class="math inline">\(\sigma^2\)</span></p></li>
<li><p><strong>Desviación estándar:</strong> <span class="math inline">\(\sigma\)</span></p></li>
<li><p><strong>Tamaño de muestra:</strong> <span class="math inline">\(n\)</span></p></li>
</ul>
</div>
<div id="distribución-binomial" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Distribución binomial</h2>
<p>La <strong>distribución binomial</strong> de una variable aleatoria es una distribución de probabilidad para una variable discreta, que cuenta el número de éxitos tras realizar <span class="math inline">\(n\)</span> veces un experimento, cada <em>intento</em> debe ser independiente entre sí. Además, la probabilidad de éxito es fija entre cada intento y se denota con la letra <span class="math inline">\(p\)</span>.</p>
<p>Lo primero que se nos viene a la mente con este tipo de distribuciones son <em>lanzamientos de moneda</em>, sin embargo, el comportamiento de muchos genes también sigue una distribución binomial.</p>
<p>Normalmente, para que una variable aleatoria sea una <strong>variable aleatoria binomial</strong> se tienen que cumplir los siguientes requisitos:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Resultados binarios:</strong> Solamente existen dos posibilidades para cada intento (éxito o fracaso, cara o cruz, dominante o recesivo, muerto o vivo, niño o niña, etc.).</p></li>
<li><p><strong>Intentos independientes:</strong> Cada prueba o intento deben ser independientes del anterior.</p></li>
<li><p><strong>El valor de</strong> <span class="math inline">\(n\)</span> es fijo: Se sabe con antelación el número de pruebas <span class="math inline">\(n\)</span>.</p></li>
<li><p><strong>Mismo valor</strong> <span class="math inline">\(p\)</span>: En todos los casos, la probabilidad de éxito o fracaso no debe cambiar, es decir <span class="math inline">\(p\)</span> debe permanecer constante.</p></li>
<li><p><strong>Resultados mutuamente excluyentes:</strong> Es decir, no se puede tener éxito y fracaso al mismo tiempo.</p></li>
<li><p><strong>Resultados colectivamente exhaustivos:</strong> Al menos uno de los dos resultados debe de ocurrir.</p></li>
</ol>
<p>La <strong>función de masa de probabilidad (PMF)</strong> o fórmula de la distribución binomial se indica en la fórmula <a href="probabilidad.html#eq:binom">(3.2)</a>.</p>
<p><span class="math display" id="eq:binom">\[\begin{equation}
P(X = k) = {\binom{n}{k}}{p^{k}}{q^{n-k}}
\tag{3.2}
\end{equation}\]</span></p>
<p>Donde:</p>
<ul>
<li><p><span class="math inline">\(P(X = k)\)</span> = probabilidad de obtener <span class="math inline">\(k\)</span> éxitos.</p></li>
<li><p><span class="math inline">\(\binom{n}{k}\)</span> = coeficiente binomial, que se calcula con la fórmula <a href="probabilidad.html#eq:binc">(3.3)</a>.</p></li>
<li><p><span class="math inline">\(k\)</span> = número de éxitos.</p></li>
<li><p><span class="math inline">\(p\)</span> = probabilidad de éxito.</p></li>
<li><p><span class="math inline">\(q\)</span> = probabilidad de fracaso.</p></li>
<li><p><span class="math inline">\(n\)</span> = número de pruebas.</p></li>
</ul>
<p><span class="math display" id="eq:binc">\[\begin{equation}
_{n}C_{k} = \binom{n}{k} = \frac{n!}{k!(n-k)!}
\tag{3.3}
\end{equation}\]</span></p>
<div id="media-y-desviación-estándar-de-la-distribución-binomial" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Media y desviación estándar de la distribución binomial</h3>
<p>Se pueden calcular tanto la <strong>media</strong> como la <strong>desviación estándar</strong> de una distribución binomial. En este caso la media es el número promedio de éxitos (<span class="math inline">\(k\)</span>) y la desviación estándar es qué tan lejos de esta media caen el resto de los valores de la distribución.</p>
<p>La media de una distribución binomial se calcula con la fórmula <a href="probabilidad.html#eq:meanbinom">(3.4)</a>.</p>
<p><span class="math display" id="eq:meanbinom">\[\begin{equation}
\mu = {n}{p}
\tag{3.4}
\end{equation}\]</span></p>
<p>En cuanto a la desviación estándar se calcula con la siguiente fórmula <a href="probabilidad.html#eq:sdbinom">(3.5)</a>.</p>
<p><span class="math display" id="eq:sdbinom">\[\begin{equation}
\sigma = \sqrt{{n}{p}{(1-p)}} = \sqrt{{n}{p}{q}}
\tag{3.5}
\end{equation}\]</span></p>
<p>En caso de querer obtener la <strong>varianza</strong>, simplemente tomamos la fórmula <a href="probabilidad.html#eq:sdbinom">(3.5)</a> sin aplicar la raíz cuadrada.</p>
<p><span class="math display" id="eq:varbinom">\[\begin{equation}
\sigma^2 = {n}{p}{(1-p)} = {n}{p}{q}
\tag{3.6}
\end{equation}\]</span></p>
<p>Para utilizar la distribución binomial en <code>R</code> es bastante sencillo.
Veamos el siguiente ejemplo.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Supongamos que analizamos a 5 individuos de una población en la que el 37% de las personas presentan un alelo mutante.
Las probabilidades de las distintas configuraciones están dadas por la distribución binomial, en donde <span class="math inline">\(n\)</span> = 5 y <span class="math inline">\(p\)</span> = 0.37.
¿Cuál es la probabilidad de que exactamente 2 personas sean mutantes?</p>
</blockquote>
<p>Antes de continuar, hay que saber que existen 4 distintos comandos (o funciones) para la función binomial:</p>
<ul>
<li><p><code>dbinom()</code> nos da un valor exacto de la distribución binomial en el punto indicado.</p></li>
<li><p><code>pbinom()</code> nos da la probabilidad acumulada de un evento.</p></li>
<li><p><code>qbinom()</code> toma el valor de probabilidad que le ponemos como primer argumento y nos da como regreso un número cuya probabilidad acumulada empate con el valor de la probabilidad (también conocida como función cuantil).</p></li>
<li><p><code>rbinom()</code> genera cierta cantidad de número aleatorios de acuerdo con la probabilidad y el número de pruebas realizadas.</p></li>
</ul>
<p>En este caso, queremos conocer la probabilidad exacta de que 2 personas sean mutantes.
Para esto necesitamos la función <code>dbinom(x, size, prob)</code>, donde el argumento <code>x</code> equivale al número de éxitos, <code>size</code> al número de ensayos y <code>prob</code> a la probabilidad de éxito.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="probabilidad.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="fl">0.37</span>)</span></code></pre></div>
<pre><code>## [1] 0.3423143</code></pre>
<div class="figure" style="text-align: center"><span id="fig:muts"></span>
<img src="Curso_R_basico_files/figure-html/muts-1.png" alt="Distribución de probabilidad binomial para el ejercicio de alelos mutantes." width="672" />
<p class="caption">
Figura 3.2: Distribución de probabilidad binomial para el ejercicio de alelos mutantes.
</p>
</div>
<blockquote>
<p><strong>Ejemplo</strong>: En Estados Unidos, 85% de la población tiene sangre Rh positivo.
Supongamos que tomamos 6 personas y contamos cuántos tiene Rh positivo.
En este caso <span class="math inline">\(Y\)</span> representará cuántas personas tienen Rh positivo dentro del grupo de 6.
¿Cuál es la probabilidad de <span class="math inline">\(Y\)</span> = 4?
¿Y la probabilidad de que <em>al menos</em> 4 personas sean Rh positivo?
¿Y la probabilidad de que haya <em>al menos</em> 1 persona con Rh negativo?</p>
</blockquote>
<p>En este caso debemos utilizar dos comandos, <code>dbinom()</code> y <code>pbinom()</code>, con uno calcularemos <span class="math inline">\(Y = 4\)</span> y con el otro <span class="math inline">\(Y \ge 4\)</span> (4 o más).
Como queremos obtener <span class="math inline">\(P(Y \ge 4)\)</span>, entonces:</p>
<p><span class="math display">\[
P(Y \ge 4) = P(Y = 4) + P(Y=5) + P(Y=6)
\]</span></p>
<p>Utilizamos el argumento <code>lower.tail</code> y lo ponemos en <code>FALSE</code> para indicar que vamos a trabajar con un valor mínimo de 4, para arriba.
Para el caso de <em>al menos</em> una persona con Rh negativo <span class="math inline">\(P(Y &lt; 6)\)</span>, tenemos dos opciones.
Usar <code>dbinom()</code> cinco veces para calcular el valor individual de:</p>
<p><span class="math display">\[
P(Y = 0) + P(Y = 1) + P(Y = 2) \cdots + P(Y = 5)
\]</span></p>
<p>O calcular <span class="math inline">\(P(Y = 6)\)</span> y restarle a 1 este valor.
Como vemos ambas operaciones dan los mismos resultados, pero es más sencilla la segunda.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="probabilidad.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Probabilidad de que 4 personas tengan Rh positivo.</span></span>
<span id="cb107-2"><a href="probabilidad.html#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="fl">0.85</span>)</span></code></pre></div>
<pre><code>## [1] 0.1761771</code></pre>
<div class="figure" style="text-align: center"><span id="fig:rh3"></span>
<img src="Curso_R_basico_files/figure-html/rh3-1.png" alt="Distribución binomial para los datos de Rh. En azul encontramos $P(X = 4)$." width="672" />
<p class="caption">
Figura 3.3: Distribución binomial para los datos de Rh. En azul encontramos <span class="math inline">\(P(X = 4)\)</span>.
</p>
</div>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="probabilidad.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Probabilidad de que al menos 4 personas (pueden ser 4, 5 o 6) tengan Rh positivo.</span></span>
<span id="cb109-2"><a href="probabilidad.html#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">3</span>, <span class="dv">6</span>, <span class="fl">0.85</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.9526614</code></pre>
<div class="figure" style="text-align: center"><span id="fig:rh4"></span>
<img src="Curso_R_basico_files/figure-html/rh4-1.png" alt="Distribución binomial para los datos de Rh. En azul encontramos la probabilidad al menos 4 personas sean Rh +." width="672" />
<p class="caption">
Figura 3.4: Distribución binomial para los datos de Rh. En azul encontramos la probabilidad al menos 4 personas sean Rh +.
</p>
</div>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="probabilidad.html#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Probabilidad de que al menos 1 persona tenga Rh negativo.</span></span>
<span id="cb111-2"><a href="probabilidad.html#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">0</span>, <span class="dv">6</span>, <span class="fl">0.85</span>) <span class="sc">+</span> <span class="fu">dbinom</span>(<span class="dv">1</span>, <span class="dv">6</span>, <span class="fl">0.85</span>) <span class="sc">+</span> <span class="fu">dbinom</span>(<span class="dv">2</span>, <span class="dv">6</span>, <span class="fl">0.85</span>) <span class="sc">+</span> <span class="fu">dbinom</span>(<span class="dv">3</span>, <span class="dv">6</span>, <span class="fl">0.85</span>) <span class="sc">+</span> <span class="fu">dbinom</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="fl">0.85</span>) <span class="sc">+</span> <span class="fu">dbinom</span>(<span class="dv">5</span>, <span class="dv">6</span>, <span class="fl">0.85</span>)</span></code></pre></div>
<pre><code>## [1] 0.6228505</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="probabilidad.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">dbinom</span>(<span class="dv">6</span>, <span class="dv">6</span>, <span class="fl">0.85</span>)</span></code></pre></div>
<pre><code>## [1] 0.6228505</code></pre>
<div class="figure" style="text-align: center"><span id="fig:rh1"></span>
<img src="Curso_R_basico_files/figure-html/rh1-1.png" alt="Distribución binomial para los datos de Rh. En azul se ve la probabilidad de que al menos una persona tenga Rh -." width="672" />
<p class="caption">
Figura 3.5: Distribución binomial para los datos de Rh. En azul se ve la probabilidad de que al menos una persona tenga Rh -.
</p>
</div>
<p>Como vemos en la distribución binomial, nuestra distribución de probabilidades está siempre representada por un histograma de probabilidades, a diferencia de las distribuciones de probabilidad de variables continuas que están representados por una curva de densidad.</p>
</div>
</div>
<div id="distribución-de-poisson" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Distribución de Poisson</h2>
<p>La <strong>distribución de Poisson</strong> es llamada así en honor al matemático francés Simeón Denis Poisson. Se utiliza para describir la probabilidad de variables discretas, al igual que la distribución binomial. Se utiliza para eventos aleatorios representados en un intervalo de tiempo determinado, aunque también es utilizada cuando el evento de interés se distribuye en un espacio plano o tridimensional. Nuestro suceso de interés (<span class="math inline">\(X\)</span>) tiene valores discretos, mientras que nuestro intervalo tiene valores continuos. La fórmula de la distribución de Poisson (PMF) es:</p>
<p><span class="math display" id="eq:poisson">\[\begin{equation}
P(X = k | \lambda) = \frac{e^{-\lambda}\lambda^k}{k!}
\tag{3.7}
\end{equation}\]</span></p>
<p>Donde:</p>
<ul>
<li><p><span class="math inline">\(P(X=k|\lambda)\)</span> = número de observaciones <span class="math inline">\(k\)</span> dado la media <span class="math inline">\(\lambda\)</span>.</p></li>
<li><p><span class="math inline">\(e\)</span> = número de Euler (aproximadamente 2.7183).</p></li>
<li><p><span class="math inline">\(\lambda\)</span> = parámetro de la distribución de Poisson, corresponde al promedio de veces que ocurre el evento aleatorio.</p></li>
</ul>
<p>Para que una variable sea considerada una <strong>variable aleatoria de Poisson</strong> se deben de cumplir los siguientes requisitos:</p>
<ol style="list-style-type: decimal">
<li><p>Cada evento tiene que ser independiente.</p></li>
<li><p>Las ocurrencias del evento tienen que ser aleatorias.</p></li>
<li><p>El número de eventos en un intervalo de tiempo o espacio es infinito (<span class="math inline">\(k = 0, 1, 2, \cdots, \infty\)</span>).</p></li>
<li><p>La probabilidad de que un evento se presente en un intervalo de tiempo es proporcional al intervalo de tiempo o espacio.</p></li>
<li><p>Se considera que la probabilidad de que dos eventos se presenten en la misma fracción de tiempo es tan pequeña que se puede considerar inexistente.</p></li>
</ol>
<div id="media-y-desviación-estándar-de-la-distribución-de-poisson" class="section level3" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Media y desviación estándar de la distribución de Poisson</h3>
<p>Algo interesante de la distribución de Poisson es que la varianza y la media corresponden al mismo valor (<span class="math inline">\(\lambda\)</span>) por lo que la desviación estándar sería:</p>
<p><span class="math display">\[
\sigma = \sqrt{\lambda}
\]</span></p>
<p>Uno de los usos que tiene la distribución de Poisson es su aproximación a la distribución binomial cuando se cumplen las siguientes condiciones:</p>
<ol style="list-style-type: decimal">
<li><p>Cuando <span class="math inline">\(p &lt; 0.1\)</span> o <span class="math inline">\(p &gt; 0.9\)</span>.</p></li>
<li><p>Cuando <span class="math inline">\(n \ge 20\)</span>. Es todavía mejor si <span class="math inline">\(n \ge 100\)</span>.</p></li>
<li><p>Cuando <span class="math inline">\(np \le 10\)</span>.</p></li>
</ol>
<p>Si tenemos estas condiciones, la distribución de Poisson es un muy buen aproximado a la distribución binomial. En estos casos, la media se obtendría de la misma manera que obtenemos la media de la distribución binomial. Debido a esta dependencia de probabilidades muy bajas o muy elevadas, frecuentemente se utiliza la distribución de Poisson para la evaluación de eventos <em>raros.</em></p>
<p><span class="math display" id="eq:poimean">\[\begin{equation}
\mu =  \lambda = np
\tag{3.8}
\end{equation}\]</span></p>
<blockquote>
<p><strong>Ejemplo:</strong> En <em>Escherichia coli</em>, una célula de cada <span class="math inline">\(10^9\)</span> muta para desarrollar resistencia a la estreptomicina. Si observamos <span class="math inline">\(2 \times 10^9\)</span> células, ¿Cuál es la probabilidad de que ninguna mute? ¿Cuál es la probabilidad de que al menos una mute?</p>
</blockquote>
<p>Como con la distribución binomial, <code>R</code> cuenta con funciones específicas para calcular los valores de una distribución de Poisson.</p>
<ul>
<li><p><code>dpois()</code> nos da un valor exacto de la distribución de Poisson en el punto indicado.</p></li>
<li><p><code>ppois()</code> nos da la probabilidad acumulada de un evento.</p></li>
<li><p><code>qpois()</code> toma el valor de probabilidad que le ponemos como primer argumento y nos da como regreso un número cuya probabilidad acumulada empate con el valor de la probabilidad (también conocida como función cuantil).</p></li>
<li><p><code>rpois()</code> genera cierta cantidad de número aleatorios de acuerdo con la probabilidad y el número de pruebas realizadas.</p></li>
</ul>
<p>Como estamos hablando de probabilidades demasiado pequeñas, ya que tenemos que encontrar 1 mutante entre <span class="math inline">\(10^9\)</span> células:</p>
<p><span class="math display">\[
p = \frac{1}{10^9} = 0.000000001
\]</span></p>
<p>Para este caso, podemos utilizar la aproximación a la probabilidad binomial:</p>
<p><span class="math display">\[
\mu = \lambda = np = (2\times10^9) \times \frac{1}{10^9} = 2
\]</span></p>
<p>Por lo tanto, <span class="math inline">\(\lambda = 2\)</span>. Observemos que teníamos un valor de <span class="math inline">\(n\)</span> enorme (<span class="math inline">\(2 \times 10^9\)</span>) y una <span class="math inline">\(p\)</span> extremadamente pequeña (<span class="math inline">\(\frac{1}{10^9}\)</span>) y a pesar de eso, obtuvimos un valor de <span class="math inline">\(\lambda\)</span> relativamente pequeño, además de cumplir los supuestos para utilizar la distribución de Poisson como aproximación a la distribución binomial.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="probabilidad.html#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Probabilidad de que 1 célula mute.</span></span>
<span id="cb115-2"><a href="probabilidad.html#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dpois</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="at">log =</span> F)</span></code></pre></div>
<pre><code>## [1] 0.2706706</code></pre>
<div class="figure" style="text-align: center"><span id="fig:pois3"></span>
<img src="Curso_R_basico_files/figure-html/pois3-1.png" alt="Distribución de Poisson para datos de *E. coli.* En azul podemos ver la probabilidad de que 1 célula haya mutado." width="672" />
<p class="caption">
Figura 3.6: Distribución de Poisson para datos de <em>E. coli.</em> En azul podemos ver la probabilidad de que 1 célula haya mutado.
</p>
</div>
<p>Por lo que la probabilidad de que al menos una célula mute dentro de <span class="math inline">\(2 \times 10^9\)</span> células de <em>E. coli</em> es de <span class="math inline">\(P(X = 1) = 0.2707\)</span>. Para el caso de que ninguna célula mute:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="probabilidad.html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Probabilidad de que ninguna célula mute.</span></span>
<span id="cb117-2"><a href="probabilidad.html#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dpois</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="at">log =</span> F)</span></code></pre></div>
<pre><code>## [1] 0.1353353</code></pre>
<div class="figure" style="text-align: center"><span id="fig:pois2"></span>
<img src="Curso_R_basico_files/figure-html/pois2-1.png" alt="Distribución de Poisson para datos de *E. coli.* En azul podemos ver la probabilidad de que ninguna célula haya mutado." width="672" />
<p class="caption">
Figura 3.7: Distribución de Poisson para datos de <em>E. coli.</em> En azul podemos ver la probabilidad de que ninguna célula haya mutado.
</p>
</div>
<p>Por lo que <span class="math inline">\(P(X = 0) = 0.1353\)</span>. Si por el contrario, quisiéramos encontrar la probabilidad de que al menos una célula mute:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="probabilidad.html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Probabilidad de que al menos una célula mute.</span></span>
<span id="cb119-2"><a href="probabilidad.html#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">dpois</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="at">log =</span> F)</span></code></pre></div>
<pre><code>## [1] 0.8646647</code></pre>
<p>Por lo que <span class="math inline">\(P(X \ge 1) = 0.865\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:pois"></span>
<img src="Curso_R_basico_files/figure-html/pois-1.png" alt="Distribución de Poisson para datos de *E. coli.* En azul podemos ver la probabilidad de que al menos 1 célula haya mutado (que corresponde a los valores mayores a 0." width="672" />
<p class="caption">
Figura 3.8: Distribución de Poisson para datos de <em>E. coli.</em> En azul podemos ver la probabilidad de que al menos 1 célula haya mutado (que corresponde a los valores mayores a 0.
</p>
</div>
<p>Como podemos ver en la figura <a href="probabilidad.html#fig:pois">3.8</a>, la probabilidad de obtener 7 o más células mutantes se vuelve prácticamente 0.</p>
</div>
</div>
<div id="distribución-normal" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> Distribución normal</h2>
<p>Una <strong>distribución normal</strong> corresponde a una curva <em>en forma de campana</em> o <em>gaussiana</em>, con ciertas características específicas.
Se utiliza para representar la distribución de los valores de una variable <span class="math inline">\(X\)</span>, de dos maneras distintas: (1) como una aproximación a un histograma basado en los valores muestreados de la variable <span class="math inline">\(X\)</span> o; (2) como una representación idealizada de la distribución poblacional de <span class="math inline">\(X\)</span>.</p>
<p>Las curvas con distribución normal toman su forma por dos elementos muy importantes: la <strong>media</strong>, <span class="math inline">\(\mu\)</span> y su <strong>desviación estándar</strong>, <span class="math inline">\(\sigma\)</span>.
Cuando se tiene una curva con distribución normal, se expresa de la siguiente manera <span class="math inline">\(X \sim N(\mu, \sigma)\)</span>.
La fórmula de la distribución normal se encuentra en la fórmula <a href="probabilidad.html#eq:norm">(3.9)</a>.
No se trata de cualquier curva simétrica, si no de una curva simétrica <em>específica</em>.</p>
<p><span class="math display" id="eq:norm">\[\begin{equation}
f(x) = \frac{1}{{\sigma}{\sqrt{2 \pi}}}e^{-\frac{1}{2}(\frac{x-\mu}{\sigma})^2}
\tag{3.9}
\end{equation}\]</span></p>
<p>La función <span class="math inline">\(f(x)\)</span> se conoce como <strong>función de densidad de probabilidad (PDF)</strong> y expresa la altura de la curva como una función de la posición en el eje horizontal. El área bajo la curva acumulada se conoce como <strong>función de densidad acumulada (CDF).</strong>
El centro de una curva normal es <span class="math inline">\(x = \mu\)</span>, los puntos de inflexión están en <span class="math inline">\(x = \mu + \sigma\)</span> y <span class="math inline">\(x = \mu - \sigma\)</span>.
En principio la curva se extiende hasta el infinito, pero tres desviaciones estándar de la media hacia el valor negativo o positivo da como resultado valores demasiado pequeños. El ancho y alto de una curva normal están determinados por la desviación estándar <span class="math inline">\(\sigma\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-81"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-81-1.png" alt="Forma de la distribución normal." width="672" />
<p class="caption">
Figura 3.9: Forma de la distribución normal.
</p>
</div>
<p>Normalmente lo que nos interesa de una curva con distribución normal es el <strong>área debajo de la curva</strong>.
Para esto utilizamos la <strong>escala estandarizada</strong>, en el cual el valor del eje horizontal se denomina <strong>valor <span class="math inline">\(Z\)</span></strong>.
La escala de <span class="math inline">\(Z\)</span> mide las desviaciones estándar a partir de la media, por ejemplo, <span class="math inline">\(z = 1\)</span> corresponde a una desviación estándar de la media.
Para transformar nuestros datos a la escala <span class="math inline">\(Z\)</span> simplemente aplicamos la fórmula <a href="probabilidad.html#eq:Z">(3.10)</a> y a la variable <span class="math inline">\(Z\)</span> se le conoce como una variable de <strong>distribución normal estándar</strong>, ya que se encuentra estandarizada y no importa en que valor se encuentren los datos originales (kg, °C, cm, mmHg, etc.), la variable <span class="math inline">\(Z\)</span> es <em>adimensional</em>.</p>
<p><span class="math display" id="eq:Z">\[\begin{equation}
Z = \frac{X - \mu}{\sigma}
\tag{3.10}
\end{equation}\]</span></p>
<p>Una vez que nuestras variables se encuentran estandarizadas en el valor <span class="math inline">\(Z\)</span>, podemos utilizar <strong>tablas de <span class="math inline">\(Z\)</span></strong> para realizar el cálculo debajo del área que corresponde al valor <span class="math inline">\(Z\)</span> obtenido, aunque claro, también podemos hacer estos cálculos en <code>R</code>.
Hay que tener en cuenta que para una curva de distribución normal estándar:</p>
<ul>
<li><p>68% del área se encuentra entre <span class="math inline">\(\pm\)</span> 1 distribución estándar.</p></li>
<li><p>95% del área se encuentra entre <span class="math inline">\(\pm\)</span> 2 distribuciones estándar.</p></li>
<li><p>99.7% del área se encuentra entre <span class="math inline">\(\pm\)</span> 3 distribuciones estándar.</p></li>
</ul>
<p>De manera similar a la distribución binomial, en <code>R</code> encontramos comandos similares para la distribución normal, donde tenemos:</p>
<ul>
<li><p><code>dnorm()</code> nos da un valor de densidad normal (PDF).</p></li>
<li><p><code>pnorm()</code> nos da un valor de densidad normal acumulado hasta cierto punto (área debajo de la curva, CDF).</p></li>
<li><p><code>qnorm()</code> toma el valor de densidad normal que le ponemos como primer argumento y nos da como regreso un número cuya densidad normal acumulada empate con el valor de densidad normal ingresado.</p></li>
<li><p><code>rnorm()</code> genera cierta cantidad de número aleatorios de acuerdo al valor de densidad normal.</p></li>
</ul>
<p>Intentemos resolver algunos ejercicios.</p>
<blockquote>
<p><strong>Ejemplo:</strong> En una población de peces de la especie <em>Pomolobus aestivalis</em>, la longitud de los individuos sigue una distribución normal. La media de la longitud es de 54.0 mm, y la desviación estándar es de 4.5 mm<sup>2</sup>. ¿Qué porcentaje de los peces mide menos de 60 mm? ¿Qué porcentaje de los peces mide más de 51 mm? ¿Qué porcentaje de los peces miden entre 51 mm y 60 mm?</p>
</blockquote>
<p>Para responder la primer pregunta, debemos transformar nuestros datos a valores Z, ya que se encuentran en mm. Para esto aplicamos la fórmula <a href="probabilidad.html#eq:Z">(3.10)</a>. En <code>R</code> es una operación relativamente sencilla de hacer.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="probabilidad.html#cb121-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">60</span> <span class="sc">-</span> <span class="dv">54</span>)<span class="sc">/</span>(<span class="fl">4.5</span>)</span></code></pre></div>
<pre><code>## [1] 1.333333</code></pre>
<p>Como podemos ver, el valor <span class="math inline">\(Z\)</span> de 60 mm es igual a 1.33. Lo siguiente sería encontrar <em>el área bajo la curva</em> que corresponda a este valor Z. Para esto utilizamos la función <code>pnorm()</code>.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="probabilidad.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.33</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.9082409</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-84"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-84-1.png" alt="Curva de distribución normal con el área sombreada correspondiente a un valor Z = 1.33" width="672" />
<p class="caption">
Figura 3.10: Curva de distribución normal con el área sombreada correspondiente a un valor Z = 1.33
</p>
</div>
<p>De nuevo, el argumento <code>lower.tail = TRUE</code> significa que encontrará la probabilidad acumulada de valores <span class="math inline">\(Z\)</span> menores a 1.33 hasta 1.33. Como podemos ver la probabilidad de que un pez mida menos de 60 mm es de 90.82%.</p>
<p>Para la segunda pregunta, primero debemos encontrar el valor de <span class="math inline">\(Z\)</span> correspondiente a 51 mm y después basta con cambiar el argumento <code>lower.tail</code> a <code>FALSE</code>.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="probabilidad.html#cb125-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">51</span> <span class="sc">-</span> <span class="dv">54</span>)<span class="sc">/</span>(<span class="fl">4.5</span>)</span></code></pre></div>
<pre><code>## [1] -0.6666667</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="probabilidad.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.67</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.7485711</code></pre>
<p>Como podemos ver el resultado indica que 75.86% de los peces miden más de 51 mm. Bastante sencillo, ¿no?</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-86"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-86-1.png" alt="Curva de distribución normal con el área sombreada correspondiente a un valor Z = -0.67, pero partiendo desde el lado positivo de la curva." width="672" />
<p class="caption">
Figura 3.11: Curva de distribución normal con el área sombreada correspondiente a un valor Z = -0.67, pero partiendo desde el lado positivo de la curva.
</p>
</div>
<p>Ahora para la última pregunta, simplemente calculamos la probabilidad acumulada hasta nuestro valor <span class="math inline">\(Z\)</span> más grande, que en este caso corresponde a 1.33 y le restamos la probabilidad acumulada del valor <span class="math inline">\(Z\)</span> más pequeño, que corresponde -0.67.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="probabilidad.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.33</span>, <span class="dv">0</span>, <span class="dv">1</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.67</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.656812</code></pre>
<p>Como resultado obtenemos que el 65.68% de los peces se encuentran en longitudes de entre 51 mm y 60 mm. Si nos damos cuenta, la distribución normal puede, de cierta manera, interpretarse como una distribución de probabilidad continua.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-88"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-88-1.png" alt="Curva de distribución normal con el área sombreada correspondiente a un intervalo entre Z = -0.67 y Z = 1.33." width="672" />
<p class="caption">
Figura 3.12: Curva de distribución normal con el área sombreada correspondiente a un intervalo entre Z = -0.67 y Z = 1.33.
</p>
</div>
<p>En algunas ocasiones, queremos encontrar el valor <span class="math inline">\(Z\)</span> correspondiente a un área bajo la curva determinada, para este tipo de ocasiones, utilizamos la función <code>qnorm()</code>.</p>
<p>Del ejemplo anterior, supongamos que queremos encontrar el percentil 70 de la distribución de la longitud de los peces. Supongamos que este valor está representado por la variable <span class="math inline">\(y\)</span>. En otras palabras, queremos encontrar el valor tal que el 70% de las longitudes de los peces son menores que <span class="math inline">\(y\)</span> y el 30% son mayores.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="probabilidad.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.7</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.5244005</code></pre>
<p>Como podemos ver, el valor <span class="math inline">\(Z\)</span> correspondiente es 0.5244. Ahora, utilizando la fórmula <a href="probabilidad.html#eq:Z">(3.10)</a> podemos realizar un despeje muy sencillo y obtener la fórmula <span class="math inline">\(y = Z* \sigma + \mu = 0.5244 * 4.5 + 54 = 56.3\)</span>. Esto quiere decir que 56.3 mm es el percentil 70 de la distribución de nuestros datos.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-90"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-90-1.png" alt="Curva de distribución normal con el área sombreada correspondiente a un valor Z = -0.67, pero partiendo desde el lado positivo de la curva." width="672" />
<p class="caption">
Figura 3.13: Curva de distribución normal con el área sombreada correspondiente a un valor Z = -0.67, pero partiendo desde el lado positivo de la curva.
</p>
</div>
<div id="pruebas-de-normalidad" class="section level3" number="3.6.1">
<h3><span class="header-section-number">3.6.1</span> Pruebas de normalidad</h3>
<p>Ya que muchos procedimientos estadísticos se basan en datos provenientes de una población con distribución normal, es importante saber si nuestros datos siguen está distribución.</p>
<p>Uno de los métodos más utilizados son los <strong>gráficos cuantil-cuantil</strong>, <strong>gráficos Q-Q</strong> o <strong>Q-Q plot</strong>. Veamos un ejemplo con datos de plantas que vienen incluidas en <code>ggplot2</code>.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="probabilidad.html#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;PlantGrowth&quot;</span>)</span>
<span id="cb133-2"><a href="probabilidad.html#cb133-2" aria-hidden="true" tabindex="-1"></a>PlantGrowth</span></code></pre></div>
<pre><code>##    weight group
## 1    4.17  ctrl
## 2    5.58  ctrl
## 3    5.18  ctrl
## 4    6.11  ctrl
## 5    4.50  ctrl
## 6    4.61  ctrl
## 7    5.17  ctrl
## 8    4.53  ctrl
## 9    5.33  ctrl
## 10   5.14  ctrl
## 11   4.81  trt1
## 12   4.17  trt1
## 13   4.41  trt1
## 14   3.59  trt1
## 15   5.87  trt1
## 16   3.83  trt1
## 17   6.03  trt1
## 18   4.89  trt1
## 19   4.32  trt1
## 20   4.69  trt1
## 21   6.31  trt2
## 22   5.12  trt2
## 23   5.54  trt2
## 24   5.50  trt2
## 25   5.37  trt2
## 26   5.29  trt2
## 27   4.92  trt2
## 28   6.15  trt2
## 29   5.80  trt2
## 30   5.26  trt2</code></pre>
<p>Como podemos ver, tenemos tres grupos, el control, tratamiento 1 y tratamiento 2. Vamos a enfocarnos solamente en los datos del grupo del tratamiento 1.</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="probabilidad.html#cb135-1" aria-hidden="true" tabindex="-1"></a>Datos <span class="ot">&lt;-</span> PlantGrowth <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;trt1&quot;</span>), weight)</span>
<span id="cb135-2"><a href="probabilidad.html#cb135-2" aria-hidden="true" tabindex="-1"></a>Datos</span></code></pre></div>
<pre><code>##    weight
## 1    4.17
## 2    5.58
## 3    5.18
## 4    6.11
## 5    4.50
## 6    4.61
## 7    5.17
## 8    4.53
## 9    5.33
## 10   5.14
## 11   4.81
## 12   4.17
## 13   4.41
## 14   3.59
## 15   5.87
## 16   3.83
## 17   6.03
## 18   4.89
## 19   4.32
## 20   4.69
## 21   6.31
## 22   5.12
## 23   5.54
## 24   5.50
## 25   5.37
## 26   5.29
## 27   4.92
## 28   6.15
## 29   5.80
## 30   5.26</code></pre>
<p>Recordemos que podemos utilizar la librería <code>dplyr</code> para extraer ciertos datos de nuestras matrices de datos. Lo que haremos ahora es utilizar el gráfico Q-Q para comprar los datos de nuestra muestra con unos datos teóricos que siguen una distribución normal. En caso de que nuestros datos se comporten de manera normal, deberíamos de tener casi una línea recta. Para esto necesitaremos la librería <code>ggpubr</code>.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="probabilidad.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb137-2"><a href="probabilidad.html#cb137-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-3"><a href="probabilidad.html#cb137-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggqqplot</span>(Datos<span class="sc">$</span>weight) <span class="sc">+</span></span>
<span id="cb137-4"><a href="probabilidad.html#cb137-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Teórico&quot;</span>) <span class="sc">+</span></span>
<span id="cb137-5"><a href="probabilidad.html#cb137-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Muestra&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-93"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-93-1.png" alt="Gráfico Q-Q comparando una muestra de datos contra una muestra teórica con distribución normal." width="672" />
<p class="caption">
Figura 3.14: Gráfico Q-Q comparando una muestra de datos contra una muestra teórica con distribución normal.
</p>
</div>
<p>Otra opción sería realizar el gráfico de densidad, pero muchas veces es difícil identificar la forma de campana en cierto conjunto de datos, así que los gráficos Q-Q son de gran ayuda.</p>
<p>Otra opción para realizar una prueba de normalidad conocida como <strong>prueba de Shapiro-Wilks</strong> (aunque no se recomienda que para <span class="math inline">\(n &gt; 50\)</span>), pero es muy sensible a ligeras desviaciones de la normalidad, sobre todo con un tamaño de muestra grande. Es muy sencillo de realizar en <code>R</code>, simplemente utilizamos el comando <code>shapiro_test()</code> del paquete <code>rstatix</code>. En este caso, vamos a analizar si nuestros dos tratamientos y el control siguen una distribución normal. Para esto, vamos a hacer uso de la librería <code>dplyr</code>.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="probabilidad.html#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;rstatix&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="probabilidad.html#cb141-1" aria-hidden="true" tabindex="-1"></a>PlantGrowth <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> <span class="fu">shapiro_test</span>(weight) <span class="co">#Agrupamos los datos por tipo de tratamiento y hacemos la prueba a la variable &quot;weight&quot;.</span></span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   group variable statistic     p
##   &lt;fct&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1 ctrl  weight       0.957 0.747
## 2 trt1  weight       0.930 0.452
## 3 trt2  weight       0.941 0.564</code></pre>
<p>¿Cómo interpretamos los resultados y qué significa el valor-<em>p</em>? Bueno, ya que el control y los dos tratamientos tienen un valor-<em>p</em> &gt; 0.05 decimos que se distribuyen de manera normal. Valores-<em>p</em> menores a 0.05 son indicativos fuertes de no-normalidad. Después de obtener un valor menor a 0.05, podríamos corroborar esto con un gráfico Q-Q o con un histograma para ver la forma de la distribución de nuestros datos.</p>
</div>
</div>
<div id="distribución-muestral" class="section level2" number="3.7">
<h2><span class="header-section-number">3.7</span> Distribución muestral</h2>
<p>La variabilidad entre muestras aleatorias que provienen de una misma población se conoce como <strong>variabilidad de muestreo</strong>. Una distribución de probabilidad que caracteriza algún aspecto de la variabilidad de muestreo se conoce como <strong>distribución muestral</strong>. Usualmente los valores de una muestra se parecen a los de la población de la cuál provienen. Una distribución muestral nos indica qué tan cerca la resemblanza entre entre la muestra y la población es probable que sea.</p>
<p>Normalmente tomamos solamente una muestra aleatoria de una población. Pero para visualizar la distribución muestral, necesitamos realizar un <strong>meta-estudio</strong>, que consiste en repetir de manera indefinida, réplicas del mismo estudio. Por ejemplo, si un estudio consiste en extraer una muestra aleatoria de tamaño <span class="math inline">\(n\)</span> de una población, un meta-estudio consiste en repetir varias veces la extracción de una muestra de tamaño <span class="math inline">\(n\)</span> de una población. Por lo tanto, las probabilidades relativas de una muestra aleatoria se pueden interpretar como frecuencias relativas en un meta-estudio. Conocer la distribución muestral nos permite hacer afirmaciones de probabilidad de otras posibles muestras.</p>
<p>Una pregunta natural a realizar es, ¿Qué tan parecida es la media de la muestra <span class="math inline">\(\overline{x}\)</span> a la media de la población <span class="math inline">\(\mu\)</span>? Aunque con una sola muestra no podemos responder esta pregunta, si pensamos en un modelo de muestreo aleatorio y tomamos la media muestral como una variable <span class="math inline">\(\overline{X}\)</span>, podemos hacer ciertas inferencias. Reformulamos nuestra pregunta a ¿Qué tan cerca de <span class="math inline">\(\mu\)</span> es probable que este <span class="math inline">\(\overline{X}\)</span>? Nuestra respuesta la encontramos en la <strong>distribución muestral de <span class="math inline">\(\overline{X}\)</span></strong>.</p>
<p>Tenemos que tener en cuenta que, en promedio, la <strong>media de la distribución muestral</strong> <span class="math inline">\(\overline{X}\)</span> equivale a la media de la población <span class="math inline">\(\mu\)</span>. Esto se ve mejor en la fórmula <a href="probabilidad.html#eq:samplemean">(3.11)</a>.</p>
<p><span class="math display" id="eq:samplemean">\[\begin{equation}
\mu_{\overline{X}} = \mu
\tag{3.11}
\end{equation}\]</span></p>
<p>La fórmula de la <strong>desviación estándar de la muestra</strong> es un poco menos intuitiva, aunque si se analiza de manera detallada tiene sentido.</p>
<p><span class="math display" id="eq:samplesd">\[\begin{equation}
\sigma_{\overline{X}} = \frac{\sigma}{\sqrt{n}}
\tag{3.12}
\end{equation}\]</span></p>
<p>Mientras el tamaño de muestra incrementa, la desviación estándar de <span class="math inline">\(\overline{X}\)</span> disminuye. Es decir para muestras más grandes existe menos variación.</p>
<p>La <strong>forma</strong> está determinada por el tamaño de muestra y la naturaleza de la población. Si la población <span class="math inline">\(X\)</span> se distribuye de manera normal, entonces la distribución muestral de <span class="math inline">\(\overline{X}\)</span> será también normal, sin importar el tamaño de nuestra <span class="math inline">\(n\)</span>. Además el <strong>teorema del límite central</strong> indica que si obtenemos una <span class="math inline">\(n\)</span> suficientemente grande, la distribución muestral de <span class="math inline">\(\overline{X}\)</span> será aproximadamente normal incluso para muestras cuya población <span class="math inline">\(X\)</span> no se distribuye de manera normal.</p>
<blockquote>
<p><strong>Ejemplo:</strong> Supongamos que tenemos una población del Carbonerito Mexicano (<em>Poecile sclateri</em>) en la cuál el peso medio es de <span class="math inline">\(\mu = 11 g\)</span> y la desviación estándar <span class="math inline">\(\sigma = 1.2 g\)</span>. Supongamos que tomamos una muestra aleatoria de seis aves. Dejemos que <span class="math inline">\(\overline{x}\)</span> represente la media del peso de las seis aves. Ya que sabemos que el peso de esta ave sigue una distribución normal en la población, también nuestras muestras seguirán una distribución normal.</p>
</blockquote>
<p>Para este caso, la media y la desviación estándar de nuestra muestra serán las siguientes:</p>
<p><span class="math display">\[\begin{equation}
\mu_{\overline{X}} = \mu = 11 g\\
\sigma_{\overline{X}} = \frac{\sigma}{\sqrt{n}} = \frac{1.2}{\sqrt{6}} = 0.49 g
\end{equation}\]</span></p>
<p>En este caso <span class="math inline">\(\mu_{\overline{X}} = 11 g\)</span> y <span class="math inline">\(\sigma_{\overline{X}} = 0.49 g\)</span>. De tal manera que, en promedio la media de la muestra será 11 g, sin embargo, el 68% de las veces <span class="math inline">\(\overline{X}\)</span> se encontrará entre <span class="math inline">\(11g \pm 0.49g\)</span> y el 95% de las veces se encontrará entre <span class="math inline">\(11g \pm 0.98g\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-95"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-95-1.png" alt="Distribución muestral proveniente de una población de *Sclateri poecile*." width="672" />
<p class="caption">
Figura 3.15: Distribución muestral proveniente de una población de <em>Sclateri poecile</em>.
</p>
</div>
<p>Esta distribución muestral expresa distintas posibilidades para los valores de <span class="math inline">\(\overline{X}\)</span>. Supongamos que quisiéramos saber la probabilidad de que la media de una muestra de seis aves sea mayor a 11.5 g. Ya que nuestros datos son normales, podemos usar la transformación a valores <span class="math inline">\(Z\)</span> para obtener nuestro resultado.</p>
<p><span class="math display">\[\begin{equation}
Z = \frac{\overline{x}-\mu_\overline{X}}{\sigma_{\overline{X}}} = \frac{11.5 - 11}{0.49} = 1.0204
\end{equation}\]</span></p>
<p>Ya que nuestro valor <span class="math inline">\(Z = 1.0204\)</span>, usamos la función <code>pnorm()</code> para encontrar nuestra área bajo la curva.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="probabilidad.html#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.0204</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.1537694</code></pre>
<p>De hecho, ni siquiera es necesario realizar la transformación a valores <span class="math inline">\(Z\)</span> en <code>R</code> ya que podemos modificar los parámetros de la función <code>pnorm()</code>.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="probabilidad.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">11.5</span>, <span class="at">mean =</span> <span class="dv">11</span>, <span class="at">sd =</span> <span class="fl">0.49</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.1537675</code></pre>
<p>Debido a que hemos redondeado la desviación estándar el resultado es ligeramente distinto (cuestión de decimales). Entonces podemos concluir que:</p>
<p><span class="math display">\[\begin{equation}
P(\overline{X} &gt; 11.5) = P(Z &gt; 1.0204) = 0.1538 \approx 0.15
\end{equation}\]</span></p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-98"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-98-1.png" alt="Probabilidad de que la media de una muestra de seis aves de la especie *Poecile sclateri* sea mayor a 11.5." width="672" />
<p class="caption">
Figura 3.16: Probabilidad de que la media de una muestra de seis aves de la especie <em>Poecile sclateri</em> sea mayor a 11.5.
</p>
</div>
<p>Si eligiéramos muchas muestras aleatorias provenientes de esta población cerca del 15% de las muestras tendrían una media mayor a 11.5 g.</p>
<p>El <strong>tamaño de la muestra</strong> tiene un efecto directo sobre la forma de nuestra curva. Básicamente, muestras más grandes dan un <span class="math inline">\(\sigma_\overline{X}\)</span> menor, y por ende dan un menor error de muestreo. En seguida se muestran distintas gráficas con distintas <span class="math inline">\(\mu_\overline{X}\)</span>. Para este caso hipotético, <span class="math inline">\(\mu = 100, \sigma = 40\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-99-1"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-99-1.png" alt="Cambios en la forma de la curva dependientes de la desviación estándar muestral." width="672" />
<p class="caption">
Figura 3.17: Cambios en la forma de la curva dependientes de la desviación estándar muestral.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-99-2"></span>
<img src="Curso_R_basico_files/figure-html/unnamed-chunk-99-2.png" alt="Cambios en la forma de la curva dependientes de la desviación estándar muestral." width="672" />
<p class="caption">
Figura 3.18: Cambios en la forma de la curva dependientes de la desviación estándar muestral.
</p>
</div>
<p>Qué tan cerca esta <span class="math inline">\(\overline{X}\)</span> de <span class="math inline">\(\mu\)</span> depende del tamaño de la muestra <span class="math inline">\(n\)</span>. La media de una muestra grande no necesariamente está más cerca a la media poblacional que la media de una muestra pequeña, pero existe mayor probabilidad de que lo este.</p>
<div id="poblaciones-muestras-y-distribuciones-muestrales" class="section level3" number="3.7.1">
<h3><span class="header-section-number">3.7.1</span> Poblaciones, muestras y distribuciones muestrales</h3>
<p>Una vez llegado a este punto puede que exista confusión entre los valores de una población, de una muestra y de una distribución muestral. Para esto aclaremos los siguientes puntos, en torno a una variable <span class="math inline">\(X\)</span>.</p>
<p>En una <strong>población</strong>, los estadísticos descriptivos como la media y la desviación estándar se representan por los siguientes símbolos:</p>
<ul>
<li><p><span class="math inline">\(\mu\)</span>: media poblacional.</p></li>
<li><p><span class="math inline">\(\sigma\)</span>: desviación estándar poblacional.</p></li>
</ul>
<p>En una <strong>muestra</strong>, los mismos estadísticos se representan por los siguientes símbolos:</p>
<ul>
<li><p><span class="math inline">\(\overline{x}\)</span>: media muestral.</p></li>
<li><p><span class="math inline">\(s\)</span>: desviación estándar poblacional.</p></li>
</ul>
<p>En una <strong>distribución muestral</strong> lo que nosotros hacemos es repetir un muestreo indefinidas veces (meta-estudio) y de cada muestreo extraer la media muestral <span class="math inline">\(\overline{x}\)</span>. Lo que representa la distribución muestral es una distribución de medias, en lugar de observaciones individuales.</p>
<ul>
<li><p><span class="math inline">\(\mu_\overline{X}\)</span>: media de una distribución muestral.</p></li>
<li><p><span class="math inline">\(\sigma_\overline{X}\)</span>: desviación estándar de una distribución muestral.</p></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estadística-descriptiva.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estadística-inferencial.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
